### ISSUE TITLE
Variables are not expanded in action menu (_THRUK_ACTION_MENU)

### ISSUE THREAD

**Issue by eduault** [sni/Thruk#1000]
**Describe the bug**
I put some variables in _THRUK_ACTION_MENU, for example $HOSTNAME$, but they are not expanded.

**Thruk Version**
Version of Thruk : 2.12-13

**To Reproduce**
1. Add the code below code to a host in Shinken
2. Reload Shinken configuration
2. Open Thruk service list, and search for the host
3. Open the drop-down menu : "$HOSTNAME$ server in CMDB" is displayed. cf. screenshot
4. Put the mouse on the link : "http://cmdb.exemple.com/servers?servername=$HOSTNAME$" is displayed in the botton of the web browser. cf. screenshot
5. Click on the link : nothing happens

Here is the host definition:

```
define host {
	host_name               server1234
	address                 localhost

	_THRUK_ACTION_MENU	{ \
							"icon":"../themes/{{theme}}/images/dropdown.png", \
							"title": "sample menu", \
							"menu": [ \
							  { \
							    "label":  "$HOSTNAME$ server in CMDB", \
							    "action": "http://cmdb.exemple.com/servers?servername=$HOSTNAME$", \
							    "target": "_blank" \
							  } \
							] \
						}
}
```

**Expected behavior**
3. Open the drop-down menu : "server1234 server in CMDB" is displayed
4. Put the mouse on the link : "http://cmdb.exemple.com/servers?servername=server1234" is displayed in the botton of the web browser
5. Click on the link : "http://cmdb.exemple.com/servers?servername=server1234" page is opened in a new tab

**Screenshots**
![2020-02-20 17_37_19-Thruk server1234](https://user-images.githubusercontent.com/29234693/74957390-c08a1300-5407-11ea-9daf-39d5d32c80c3.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version : 76.0.3809.132 (64 bits)

**Comment by eduault** [comment]
This issue #1000 !

![1036477920](https://user-images.githubusercontent.com/29234693/74958186-d9df8f00-5408-11ea-9543-24edb581fe13.jpg)

**Comment by sni** [comment]
It is not possible to use variables in the label. Those variables are only supported in the `action` attribute, and only if its a http(s) link or a server action.
I updated the docs in c5fc2c0fe55c90a557d2bec094564266e501eba6 to make this more clear.

However, this should be possible with dynamic javascript menus.

**Comment by eduault** [comment]
Thank you.
But it is a shame that variable replacements are only possible when the action is executed.
And worst, I discovered that it is not possible to use custom variables in "action" of _THRUK_ACTION_MENU.

**Comment by eduault** [comment]
@sni Can you develop how variables, and if possible custom variables, can be used in javascript as you tell ?

**Comment by sni** [comment]
thats probably not easily possible, because variables are replaced on server side while javascript runs on the client side and is not bound to a specific host or service.
Then with custom variables it gets more tricky, because they might contain passwords and secrets, so they are not exposed to the client.
