### ISSUE TITLE
Business Process Report "no result found'

### ISSUE THREAD

**Issue by loicfgc** [sni/Thruk#1007]
**Describe the bug**
When i try to generate "SLA Business Process" report with thruk in the Business Process form it show no result found even with some BP working

**Thruk Version**
Thruk 2.32-3

**To Reproduce**
1. Go to Reporing
2. Create new reportting
3. Select type "SLA Business Process"
4. Fiels to specify which business process shows " no result found"

**Expected behavior**
Should show list of available BP like it does with SLA hosts or SLA services

**Screenshots**
![Capture](https://user-images.githubusercontent.com/33361074/77516347-871b4c00-6e7a-11ea-8fe9-72e842a2a619.PNG)

**Desktop (please complete the following information):**
Same bug on all browsers (safari, chrome, Firefox, opera and multiple instance of thruk

**Comment by sni** [comment]
should be fixed with the recent 2.34 release.Please reopen if this issue still occurs with the latest release.
