### ISSUE TITLE
Graphs in Nagios/Thruk with Histou

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1014]
We are looking into too replace PNP4Nagios with Nagios+Nagflux+InfluxDB+Grafana+Histou+Thruk.
Everything is looking good so far, the DB is getting updated with performancedata and we can see the data when we click on the Graph symbol in Nagios/Thruk (redirected to Grafana).
What we are missing and can not get to work is the Performance-Graph on the Host-/Service-detail page as well as the PopUp's when we hover with the mousepointer over the Graph symbol (with PNP4Nagios both works).

Do you have a suggestion what I have could have missed/done wrong in our config and how to get this to work?

**Thruk Version**
2.34

*To Reproduce**
1. Go to "Hosts" and select "View Service details for this host" for one host
2. Hover with the mouse over the "action-icon" ==> No PopUp graph visible
3. Click on the host
4. Scroll down to "Performance Graph"
5. No graph is displayed. Only the text "Could not retrieve graph data" is visible.

**Expected behavior**
In both cases should a graph be visible.

**Desktop :**
 - Firefox / Chrome
 
--
Dan

**Comment by sni** [comment]
In OMD we use the following naemon template to set the histou url:
https://github.com/ConSol/omd/blob/labs/packages/grafana/skel/etc/naemon/conf.d/histou.cfg
together with this ssi file
https://github.com/sni/Thruk/blob/master/ssi/status-header.ssi-pnp

If you use Grafana, Naemon, Thruk, Nagflux, Histour and Influxdb, then you might want to have a look at OMD-Labs, which is pretty much what you have already. Read more at
https://labs.consol.de/omd/

**Comment by dan-m-joh** [comment]
Hello Sven,

This is interesting, the two configurations are in place, but still no joy (:-(

Any suggestion on how to increase some logging to see whats (not) happening?

-- 
Dan

**Comment by slas23** [comment]
Hello,
[status-header.txt](https://github.com/sni/Thruk/files/8006226/status-header.txt)

I updated the status header for work with nagios
I attach my status-header.ssi
[status-header.txt](https://github.com/sni/Thruk/files/8006226/status-header.txt)

and this is my action-url
define host {
	name host-pnp
	action_url	URL/dashboard/script/histou.js?host=$HOSTNAME$' class='tips' rel='/grafana/dashboard/script/histou.js?host=$HOSTNAME$'&kiosk&viewPanel=1
	register 0
	}
define service {
	name srv-pnp
	action_url	URL/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$' class='tips' rel='/grafana/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$&kiosk&viewPanel=1
	register 0
	}
