### ISSUE TITLE
"Hostgroup-Nodes" in Business Process get "Scheduled- and Acknowledged-Status"

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1016]
**Describe the bug**
After updating Thruk to v2.34 (from 2.32-2) we have started to see some strange behavior with our business processes. This problem exists for existing and newly created BPs.

If we create a node like this:
- Type : Any Filter
- Details:
  - Aggregation : Worst
  - Type: Hosts
  - Host Status Type:All
  - Host Properties: Any
  - Hostgroup = switches 

The resulting node shows with "In scheduled downtime" and "Acknowledged" and the Parent Node gets into status "Unknown" - like this:

![Screenshot_20200514_091651](https://user-images.githubusercontent.com/26163222/81905199-aefa7680-95c4-11ea-9bac-99d6d1078662.png)

None of the host in the hostgroup are in scheduled downtime or are "Acknowledged".

**Thruk Version**
2.34
**Nagios Version**
4.4.5
**Livestatus Version**
1.2.8p18

**Expected behavior**
The Child-node should be "Green" and without and "Status" (as long as there actually is no issue) and the Parent-node should also be "Green".

**Desktop (please complete the following information):**
 - Linux, Firefox, 68.8.0esr
 - Linux, Chromium, 81.0.4044.138

//Dan

**Comment by sni** [comment]
I am working on that right now, there should be a fix soon.

**Comment by dan-m-joh** [comment]
OK, thanks for the quick feedback.

//Dan

**Comment by sni** [comment]
fixed with 83eafa4d1da67a8bedca79b3676391a4e1ba8d15
