### ISSUE TITLE
showlog.cgi sends invalid GET log query to to livestatus

### ISSUE THREAD

**Issue by Niemeijer** [sni/Thruk#1019]
**Describe the bug**
After upgrading to 2.34-2, thruk appears to send an invalid GET log command to livestatus when opening the "Event Log" page, specifically:
```selectall_arrayref("GET log\nFilter: time >= 1591567200\nFilter: time <= 1591653600\nAnd: 2\nStats: time != as total", {'addpeer' => 0,'slice' => {}}, 0)```

Whereas the old version sent:
```selectall_arrayref("GET log\nColumns: class time type state host_name service_description plugin_output message options state_type contact_name\nFilter: time >= 1591567200\nFilter: time <= 1591653600\nAnd: 2", {'addpeer' => 0,'slice' => {}}, 0)```

This results in livestatus returning an error because of the unexpected and empty time value:
```[1591612220] ERROR: [broker-master] [Livestatus] Unexpected error during process of request 'GET log\nFilter: time >= 1591567200\nFilter: time <= 1591653600\nAnd: 2\nStats: time !=\nOutputFormat: json\nResponseHeader: fixed16\n\n' : invalid literal for int() with base 10: ''```

While troubleshooting i noticed changing the following line back to how it was set in 2.32-3 seems to be a workaround for the issue for my setup:
```
diff ./lib/Thruk/Backend/Provider/Livestatus.pm ./lib/Thruk/Backend/Provider/Livestatus.pm.original 
<         ($size, $limit) = $self->_get_query_size('log', \%options, 'time', 'time');
---
>         ($size, $limit) = $self->_get_query_size('log', \%options, 'time', 'DESC', 'time');
```

**Thruk Version**
2.34-2
Previously working in 2.32-3

**To Reproduce**
1. Configure thruk to connect to livestatus (in my case mod-livestatus on shinken)
2. Upgrade to Thruk 2.34-2
3. Open Event Log, this will result in a blank page and error messages in the logs 

**Expected behavior**
Correctly show the Event Log as it did in version 2.32-3

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 76.0.1

**Additional context**
The aforementioned workaround only seems to work with no_external_job_forks=0, when setting no_external_job_forks=1 with the workaround active the Event Log seems to trigger an infinite loop on GET status instead 
```selectall_arrayref("GET status\nColumns: accept_passive_host_checks accept_passive_service_checks check_external_commands check_host_freshness check_service_freshness enable_event_handlers enable_flap_detection enable_notifications execute_host_checks execute_service_checks last_command_check last_log_rotation livestatus_version nagios_pid obsess_over_hosts obsess_over_services process_performance_data program_start program_version interval_length", {'addpeer' => 1,'rename' => {'livestatus_version' => 'data_source_version'},'slice' => {},'wrapped_json' => 0}, 0)``` 

If you require any more information please let me know.

**Comment by sni** [comment]
Should be better with the next release. The reason to do so was to reduce the amount of logs being fetched on the showlog page. Seems like shinken cannot handle queries with a "time != " filter. I changed it to "time != -1" which should result in the same result but is a valid query for shinken.
