### ISSUE TITLE
Text of the Grafana graphs in the panorama view is missing

### ISSUE THREAD

**Issue by stku** [sni/Thruk#1020]
Hello,

the text of the Grafana graphs in my panorama view is missing. I get the lines but no text, No labeling of the axes and no text in the legend. I integrate the Grafana graphs directly without Histu. I don't get any error message. Any idea what could be wrong in my installation or where to look for what is going wrong. 

Thruk 2.34-3, Grafana v7.03 on Debian 9.12

Thanks in advance

![thruk_grafana](https://user-images.githubusercontent.com/748716/84739162-7119b500-afab-11ea-9081-1b9651abf9ec.png)

**Comment by sni** [comment]
Interesting. Maybe thats an issue with Grafana 7. So far i only tested Grafana 6 and older.

**Comment by stku** [comment]
I have downgraded Grafana to version 6.7.4 but still the same problem. 

If I see that correctly, phantomjs is used to generate the image in the panorama view. In other projects I found the hint that such problems can occur if the appropriate font is not installed or found. But I have no idea how to check this.

**Comment by sni** [comment]
Thats right, Thruk uses phantomjs to generate the image. There is a simple wrapper included in Thruk `grafana_export.sh` which starts the export and creates the png.

**Comment by stku** [comment]
I solved the problem for myself by replacing the script grafana_export.sh. My script now calls the Grafana Image Renderer plugin instead of phantom.js. Which works well for me.

**Comment by sni** [comment]
Great. Do you want to share your script? Could be helpful for others as well. Maybe Thruk could switch to the renderer plugin as well.

**Comment by stku** [comment]
Here is my script, written in perl.

#!/usr/bin/perl 
use warnings;
use strict;
use LWP::UserAgent;
use URI::Escape;

my $width=$ARGV[0];
my $height=$ARGV[1];
my $start=$ARGV[2] * 1000;
my $end=$ARGV[3] * 1000;
my $input=$ARGV[4];
my $tempfile=$ARGV[5];
my $timezone = uri_escape($ENV{'TZ'});
my $cookie = $ENV{'PHANTOMJSSCRIPTOPTIONS'};
$cookie =~ s/.*(thruk_auth),([^\s]+) .*/$1=$2/;

(my $url = $input) =~ s/(\/grafana)\/(d-solo\/)/$1\/render\/$2/;
$url .= "&from=$start";
$url .= "&to=$end";
$url .= "&width=$width";
$url .= "&height=$height";
$url .= "&tz=$timezone";

my $ua = LWP::UserAgent->new();
$ua->default_header('Cookie' => $cookie,);
$ua->ssl_opts(
    SSL_verify_mode => 0x00,
    verify_hostname => 0
);

my $response = $ua->get("$url");
print "status grafana export ".$response->status_line."\n";
my $img = $response->decoded_content;

open (FH,">$tempfile");
print FH $img;
close (FH);
