### ISSUE TITLE
Problem using Rest API with sort and limit context

### ISSUE THREAD

**Issue by kileou78** [sni/Thruk#1021]
Hello everybody

My goal is to use an API query to extract the status of a service group on thruk. {OK or Critical}
I'm using the following query
http://{{username}}:{{password}}@{{server}}/thruk/r/service?columns=state,host_name,last_check&groups[gte]=GroupName&state[regex]=0|2&sort=-state

- The first part of the query respond with the list of services member of the servicegroup
- I'm extracting status 0 for OK and status 2 for Critical
- Sorting by state to have all critical services on top of the list

My goal is the take the first status of the list to know if my servicegroup status is OK or KO
So i have added to my request &limit=1 to return only the first item of my list

So seems that limit=1 has not the expected effect.
Sometimes, there is i no items back from my query
Sometimes, i do have an item with a status 0 even if i have a status 2 in my list

My opinion is that this might be a bug.
You can share if you have any similar experience on this point
If you have any idea to obtain my result by another method ... thanks in advance.

**Thruk Version**
Tested on thruk version 2.32-3 and 2.33-20191105
Centos6

Please let me know if you need some more details
Best Regards

**Comment by sni** [comment]
I just tried to reproduce, but it works as intended (with latest git head). So i assume its already fixed.
Besides that, i added more columns to the `/servicegroups` endpoint with 253572819509390e2003cef6699656bcda6d06c8
so you could simply request `/thruk/r/servicegroups?columns=worst_service_state`. If you need more details, there is already
a `/servicegroup/<name>/stats`.
