### ISSUE TITLE
Thruk: Searching for Hostgroups doesnt display all services.

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#1022]
Hi Sven,

**Describe the bug**
I have 2 server under a specific hostgroup. they have the same number of service checks, but when i search for that hostgroup, and click on View Service Status Detail For All Host Groups. I dont get the same number of service checks, please see attached for details.

**Thruk Version**
Version of Thruk (Thruk 2.30-3)

**To Reproduce**
1. Go to 'Hostgroups'
2. Click on 'Display Filters' icon
3. Scroll down to 'Host Properties.'
4. Select Hostgroup = "name of hostgroup"
5. Click on Search
6.  Click View Service Status Detail For All Host Groups
7. Then on Service Status Details For Host Group '<hostgroup-name>
8. Screenshot

![image](https://user-images.githubusercontent.com/12998432/85017350-ec42bd00-b19d-11ea-8aa8-9bef76e9b90c.png)

**Expected behavior**
I was expecting that all the service checks on both server will be the same, since they have identical numbers of service checks, but on one server it only displays partial list of service checks while the other server display all the available service checks, 

*

**Comment by sni** [comment]
thruk simply sends a livestatus query to the backend and displays the result. Which backend are you using?

**Comment by jgbuenaventura** [comment]
thanks! Sven! For that screenshot its Nagios but, we both have icinga and nagios on production
