### ISSUE TITLE
Add data to report

### ISSUE THREAD

**Issue by marcom29** [sni/Thruk#1023]
How can I get the data from the "Status Information" column .. 

example to table:
_  ______________________________
**Status Information**                  
_______________________________|
**OK: Percent was 15.63 %**   
_______________________________|

so I can put it in the thruk report? I am customizing a little the report that is generated.

**Comment by sni** [comment]
nice, just make sure you put the changed file with the same path into you user template folder. `/etc/thruk/templates` usually. So the changes won't be overwritten on the next update.
