### ISSUE TITLE
Filter by custom variable with tilde shows nothing

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1025]
**Describe the bug**
Filter some hosts by customvariable using tilde shows nothing. Using equal/not equal seems to work.

**Thruk Version**
2.34-3 OMD 3.31 2020-06-13

**To Reproduce**
1. Choose a Hostgroup with custom variables
2. add additional filter with "and" and choose "custom variable"
3. choose available customvariable and search with tilde
4. nothing should appear - with "=" should appear something

**Desktop (please complete the following information):**
 - Chrome 83

**Comment by kafos** [comment]
It seems not to work, if the string has umlaute.
**works**:
Custom Variable - STANDORT - = - München Feldmoching Bf
**does not work**:
Custom Variable - STANDORT - ~ - München Feldmoching B

**works**:
Custom Variable - STANDORT - ~ - Hamburg Altona Bf
Custom Variable - STANDORT - = - Hamburg Altona Bf
Custom Variable - STANDORT - ~ - Hamburg Altona B

**Comment by sni** [comment]
Those queries are basically just passed on to the core. Which core is this? Do you use LMD?

**Comment by ntokos** [comment]
Hello,
my problem when using the tilde in filtering custom variable values in the hostdetail view is even worse, it causes livestatus to crash.
Here are some screenshots:
- Selection:
![thruk_filter_tilde_screenshot](https://user-images.githubusercontent.com/18023303/92093741-5aca0b00-eddc-11ea-9479-7c6732d4b031.jpg)
- Result (livestatus crash):
![thruk_filter_tilde_crash_screenshot](https://user-images.githubusercontent.com/18023303/92093851-7a613380-eddc-11ea-90b3-c12ad1dcbe38.jpg)

Also using the equal sign produces no results (now rows in hostdetail). Here is the filter I tried to apply:
![thruk_filter_equal_screenshot](https://user-images.githubusercontent.com/18023303/92094014-a4b2f100-eddc-11ea-81de-b190bbfa5a25.jpg)
This is what I reported in issue #1036 where column sorting problem for custom variables is reported, maybe all are related.
As can be seen in the screenshots, I'm using Thruk 2.34-2 as part of OMD labs 3.30. My core is Icinga2 (ver 2.11.3).

Note that with the exact same config in OMD labs 2.90 (Thruk 2.26-2, Icinga2 2.9.2) everything was working fine.

**Comment by sni** [comment]
Are you using LMD between Icinga2 and Thruk or plain Icinga2?

**Comment by ntokos** [comment]
Hello, not using LMD, plain Icinga2.

**Comment by ntokos** [comment]
Here are the error messages inside the thruk.log file:
[error_messages_in_log.txt](https://github.com/sni/Thruk/files/5167625/error_messages_in_log.txt)

**Comment by sni** [comment]
Thats an internal crash/stacktrace from icinga2, there is nothing thruk can do about it. Except you could try enabling LMD which handles most of the complicated livestatus things then.

**Comment by ntokos** [comment]
Thank you for the reply.
I enabled LMD and now no crash is happening.
So now I see the same problem as @kafos reported, that is, no rows are displayed. The same happens when using the equal sign, so filtering doesn't seem to work at all for me (same when not using LMD).
