### ISSUE TITLE
I can not get Thruk RestAPI to work

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1027]
I probably have some miss-configuration which prevent me from using the RestAPI.

When I call
`curl -g 'https://thrukadmin:xxxxxxx@nagioshost/thruk/r/'`
I only get the following
```
{
   "code" : 403,
   "description" : "It seems like you are not authorized.",
   "details" : "",
   "failed" : true,
   "message" : "You are not authorized."
}
```
Using the same user/password calling the cgi-bin like this 
`curl -g 'https://thrukadmin:xxxxxxx@nagioshost/thruk/cgi-bin/status.cgi?servicegroup=SLA&style=detail&view_mode=json'`
everything is working and I am getting data back.

So the username/password combination is OK.

The only thing regarding "api" in the config is the following:
```
# grep -i api *.conf
thruk.conf:#plugin_registry_url = https://api.thruk.org/v1/plugin/list.json
thruk.conf:# API settings
thruk.conf:# Using api keys can be disabled by setting this to 0.
thruk.conf:#api_keys_enabled = 1
thruk.conf:#max_api_keys_per_user = 10
thruk_local.conf:rest_api_enabled = 1
```

Thruk Version : 2.34-2

Any suggestion on what I have miss-configured?

-- 
Dan

**Comment by sni** [comment]
How did you install Thruk? Maybe its an issue from a not updated Apache configuration.

**Comment by dan-m-joh** [comment]
Thruk is installed from the RPMs @ ConSol Labs.
I have compared your default "apache_fcgid.conf" with my "thruk.conf" and the only differences are related to authentication:
```
$ diff apache_fcgid.conf /etc/httpd/conf.d/thruk.conf
73c74,79
<     AuthUserFile /etc/thruk/htpasswd
---
>     #AuthUserFile /etc/thruk/htpasswd
>      AuthBasicProvider file ldap
>      AuthUserFile /etc/nagios/passwd
>      AuthLDAPURL "ldaps://ldapauth.org.ch/ou=people,ou=pass,dc=org,dc=ch"
>      AuthLDAPBindDN "cn=sys_auth_nagios,ou=admins,dc=org,dc=ch"
>      AuthLDAPBindPassword "xxxxxxx"
```

But, as I wrote, calling cgi-bin works with both "local" users (in /etc/nagios/passwd) an ldap users  - the RestAPI interface, sadly,  works with none.

**Comment by sni** [comment]
are you using the cookie auth? (the login form)

**Comment by dan-m-joh** [comment]
No, we are using "Basic Auth".

**Comment by sni** [comment]
i see, i can reproduce it when using basic auth.

**Comment by sni** [comment]
alright, so the thing is a bit tricky. The apache config contains an extra block for the rest api to bypass authentication:
```
  <Location /thruk/r/>
    Order Deny,Allow
    Allow from all
    Satisfy any
  </Location>
```
This is required in order to make API keys work. It seems like you cannot have both. Either api keys work or basic authentication for the rest api. It would prefer api keys, they are way more flexible. In case you want basic auth only for rest api, simply remove that block from the apache config.

**Comment by sni** [comment]
i updated the docs accordingly: 9054ddcd8b79da7597311de1174822d94d1fce22

**Comment by dan-m-joh** [comment]
Hi Sven,

Thanks for the Feedback!

Using API-keys indeed works.

(I have created a Pull Request for three small typos (missing "'") in the doc)

Regards,
Dan

**Comment by sni** [comment]
thanks for fixing the docs :-) much appreciated
