### ISSUE TITLE
Problem with "spaces" on display name

### ISSUE THREAD

**Issue by malcombecerra** [sni/Thruk#1031]
In the screenshot the character "space" isn't show like normal, its like html doesnt decode correctly that character.

**Thruk Version**
it happen only on 2.32-3

**To Reproduce**
when the status information has 2 or more lines

**Expected behavior**
decode correclty that character

**Screenshots**
![image](https://user-images.githubusercontent.com/20689770/88063045-987a1980-cb37-11ea-9219-0676faafbec3.png)

**Desktop (please complete the following information):**
 - Browser chrome, firefox

**Comment by sni** [comment]
thanks for reporting, should be fine with the next release.

**Comment by sni** [comment]
i mentioned the commit which fixes the issue, you can try to apply that manually to your current version.

**Comment by malcombecerra** [comment]
Thanks sni, thats works very good.
