### ISSUE TITLE
Thruk Oauth challenges

### ISSUE THREAD

**Issue by harishjadhav26** [sni/Thruk#1032]
**Describe the bug**
Oauth is not happening after set following details in thruk.conf

<auth_oauth>
  <provider>
    login         = "GitHub"
    client_id     = b8d08dbcfb99fxxxxxxxx
    client_secret = c91216f5f130f68xxxxxxxxxxxxxxxxxxx
    scopes        = openid profile email
    auth_url      = https://github.com/login/oauth/authorize
    token_url     = https://github.com/login/oauth/access_token
    api_url       = https://api.github.com/user
    login_field   = login
  </provider>
</auth_oauth>

**Thruk Version**
Thruk 2.36

**To Reproduce**
1. Create oauth apps on github
2. add oauth entry in thruk.conf
<auth_oauth>
  <provider>
    login         = "GitHub"
    client_id     = b8d08dbcxxxxxxxxxxxxxxx
    client_secret = c91216f5f13xxxxxxxxxxxxxxxxxxxx
    scopes        = openid profile email
    auth_url      = https://github.com/login/oauth/authorize
    token_url     = https://github.com/login/oauth/access_token
    api_url       = https://api.github.com/user
    login_field   = login
  </provider>
</auth_oauth>

restart service httpd

**Screenshots**
![image](https://user-images.githubusercontent.com/57670076/89173352-c0d72e80-d5a1-11ea-9a4d-85384091ebdd.png)

**Desktop (please complete the following information):**
 - Browser Mozilla Firefox
 - Version 78.0.1

Refer Apache error log

Use of uninitialized value $basic_auth in concatenation (.) or string at /usr/share/thruk/lib/Thruk/Utils/CookieAuth.pm line 140.
[Mon Aug 03 14:14:19.351464 2020] [auth_basic:error] [pid 8623] [client 127.0.0.1:51934] AH01618: user  not found: /thruk/cgi-bin/restricted.cgi

**Comment by harishjadhav26** [comment]
also iam getting error after add keycloak oauth details in thruk.conf

<auth_oauth>
  <provider>
    login         = "Keycloak"
    client_id     = oauthsaccess
    client_secret = 104b71a0-d976-408d-bd43-fb8ab1523961
    scopes        = email profile openid roles
    auth_url      = http://192.168.1.10:8080/auth/realms/oauth_relm/protocol/openid-connect/auth
    token_url     = http://192.168.1.10:8080/auth/realms/oauth_relm/protocol/openid-connect/token
    api_url       = http://192.168.1.10:8080/auth/realms/oauth_relm/protocol/openid-connect/userinfo
    login_field   = login
  </provider>
</auth_oauth>

getting this error in thruk.log

[2020/08/03 21:30:36][thruk236x][ERROR] ***************************
[2020/08/03 21:30:36][thruk236x][ERROR] page:    http://192.168.1.81/thruk/cgi-bin/login.cgi?state=c0bb4dc708dde2612b50c1d5bc78cfa1cea8e9db85ad588775962bf419f2d4d2_1&session_state=25f973e9-dae0-4454-ae7f-5dc35dfd1874&code=ee703aa0-daa2-4429-8f1a-87325a449b5a.25f973e9-dae0-4454-ae7f-5dc35dfd1874.4c17db05-ac99-456e-9a84-b9669cd67e6f
[2020/08/03 21:30:36][thruk236x][ERROR] params:  {'code' => 'ee703aa0-daa2-4429-8f1a-87325a449b5a.25f973e9-dae0-4454-ae7f-5dc35dfd1874.4c17db05-ac99-456e-9a84-b9669cd67e6f','session_state' => '25f973e9-dae0-4454-ae7f-5dc35dfd1874','state' => 'c0bb4dc708dde2612b50c1d5bc78cfa1cea8e9db85ad588775962...
[2020/08/03 21:30:36][thruk236x][ERROR] user:    ?
[2020/08/03 21:30:36][thruk236x][ERROR] address: 192.168.1.10
[2020/08/03 21:30:36][thruk236x][ERROR] time:    0.2s
[2020/08/03 21:30:36][thruk236x][ERROR] cannot find oauth user name
[2020/08/03 21:30:36][thruk236x][ERROR] $VAR1 = {
[2020/08/03 21:30:36][thruk236x][ERROR]           'userinfo' => {
[2020/08/03 21:30:36][thruk236x][ERROR]                           'Group' => [],
[2020/08/03 21:30:36][thruk236x][ERROR]                           'email_verified' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
[2020/08/03 21:30:36][thruk236x][ERROR]                           'preferred_username' => 'gmetricsadmin',
[2020/08/03 21:30:36][thruk236x][ERROR]                           'sub' => '71675a55-8ae4-4f36-ac3f-fda0a512aeb8'
[2020/08/03 21:30:36][thruk236x][ERROR]                         }
[2020/08/03 21:30:36][thruk236x][ERROR]         };
[2020/08/03 21:30:36][thruk236x][ERROR] ***************************

**Comment by sni** [comment]
You specified `login_field = login` but there is no `login` field in the response. Seems like `login_field =  preferred_username` would fit better.

**Comment by harishjadhav26** [comment]
Thanks, i have same updated and got following error.
Please find screen shot

![image](https://user-images.githubusercontent.com/57670076/89270262-ba57be00-d658-11ea-87aa-fe7bf53ef610.png)


and in apache error.log

Use of uninitialized value $basic_auth in concatenation (.) or string at /usr/share/thruk/lib/Thruk/Utils/CookieAuth.pm line 140.
[Tue Aug 04 13:38:38.243534 2020] [auth_basic:error] [pid 12121] [client 127.0.0.1:38220] AH01618: user  not found: /thruk/cgi-bin/restricted.cgi

**Comment by lpopil** [comment]
I observing exactly the same issue.
Use of uninitialized value $basic_auth in concatenation (.) or string at /usr/share/thruk/lib/Thruk/Utils/CookieAuth.pm line 140.
[Wed Aug 05 06:34:37.337920 2020] [auth_basic:error] [pid 30593] [client ::1:45204] AH01618: user  not found: /thruk/cgi-bin/restricted.cgi
thruk_auth: basic auth verify failed for usesrname

Let me know if additional information is required.

**Comment by harishjadhav26** [comment]
Thanks, could you please refer /usr/share/thruk/lib/Thruk/Utils/OAuth.pm file at line no. 79. following function.
In this function i observed username not fetching from 'login_field' so its showing user not found


# get username from response hash
        my $login = $auth->{'login_field'} ? $userinfo->{$auth->{'login_field'}} : ($userinfo->{'login'} || $userinfo->{'email'});
        if(!defined $login) {
            return $c->detach_error({msg => "cannot find oauth user name", code => 500, debug_information => { userinfo => $userinfo }});
        }

also any method to find is user name is properly fetching in oauth function

**Comment by lpopil** [comment]
Thanks @harishjadhav26, I have checked my case after providing correct login_field for user login, problem still exists.
But I have found something interesting:
```perl 
/usr/share/thruk/lib/Thruk/Utils/CookieAuth.pm
                  my $hash = $res->request->header('authorization');
                     $hash =~ s/^Basic\ //mx;
                     $hash = 'none' if $config->{'cookie_auth_session_cache_timeout'} == 0;
                      my($sessionid) = store_session($config, undef, {
                          hash       => $hash,
                          address    => $address,
                          username   => $login,
                     });
```

When  I set cookie_auth_session_cache_timeout=0 auth is successful.
`thruk_auth: session ok (not revalidated)thruk_auth: basic auth ok for testuser`

**Comment by harishjadhav26** [comment]
Thanks @lpopil same thing i have tested its working thanks.
# Is it Bug???? or configuration

**Comment by harishjadhav26** [comment]
@lpopil google oauth challenges, i had configured google oauth its success but that user is not allocated any hosts and services still that user is able to view hosts

![image](https://user-images.githubusercontent.com/57670076/89776189-04441680-db27-11ea-9d6f-ae23d50e972b.png)

**Comment by harishjadhav26** [comment]
@lpopil, Sorry my mistake use_authentication=1 did not checked in cgi.cfg.
now working fine

**Comment by sni** [comment]
I will add a warning or something like that if `use_authentication` is disabled completely.

**Comment by harishjadhav26** [comment]
@sni Thanks
