### ISSUE TITLE
Business Process does not work correctly.

### ISSUE THREAD

**Issue by iv0001** [sni/Thruk#1033]
The BP is defined to only accept HARD states and when SOFT events arrive, the BP state calculation works fine in visual mode.
It shows everything OK, but in the nagios log it adds a critical event.
This logically affects the bp sla reports.
In the attached images, you will find the evidence.

**Thruk Version** 2.34-3
**Nagios Core 4.3.4

**Screenshots**

[Issue_Thruk.docx](https://github.com/sni/Thruk/files/5029852/Issue_Thruk.docx)

**Comment by sni** [comment]
What type is that BP using. I cannot find the string "Group state is" nor "Child Problems" in the current code base. Can you please attach the BP configuration (stripping all confidential details).
