### ISSUE TITLE
"Grafana-Backend" does not honor "Maximum Graph Sources" when generating Report in Thruk

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1034]
**Describe the bug**
I have set "Maximum Graph Sources" to "2" but when the report is generated it tries to create four graphs when using Grafana as "graphing backend" (using pnp4nagios the correct number of graphs are generated).

**Thruk Version**
2.34-2

**To Reproduce**
1) Create report with "Maximum Graph Sources" set to 2
2) Run the report
3) In the report the first two graphs are displayed OK but then there are also two messages saying "Panel with id [3|4] not found.

**Expected behavior**
Only two graphs should be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/26163222/89873677-1a9bb200-dbbb-11ea-9e48-a0bd5b1e124a.png)

![Screenshot_20200811_100909](https://user-images.githubusercontent.com/26163222/89873698-212a2980-dbbb-11ea-8690-31e7b1fba31d.png)

**Desktop (please complete the following information):**
 - Browser Firefox/Chrome

**Comment by dan-m-joh** [comment]
I have created Pull request #1035

// D/\N

**Comment by sni** [comment]
thanks for taking care of it yourself :)
