### ISSUE TITLE
new dependency for thruk-base

### ISSUE THREAD

**Issue by haraldj** [sni/Thruk#1037]
Hello,

could you please add nginx-light as a dependency to the thruk-base package so it will also install with the minimal nginx package? The uWSGI module is part of nginx-light in Debian since stretch (9.0, nginx version 1.10.3) and I already run this configuration.

Kind regards
Harald Jenny

**Comment by sni** [comment]
i updated the dependencies. thanks for reporting this

**Comment by haraldj** [comment]
Thank you too.
