### ISSUE TITLE
Availability Report time Period

### ISSUE THREAD

**Issue by rverchere** [sni/Thruk#1039]
**Describe the bug**
When using availability report with different time periods, result is always de same

**Thruk Version**
2.36

**To Reproduce**
1. Go to 'Reports' > 'Availability'
2. Select a host,hostgroup or whatever
3. Select a "Report time Period"
4. Generate the availability report

5. Redo the same, with another "Report time Period" 
6. Generate the availability report

**Expected behavior**
If errors are not in the Report time Period, they should not be taken in account.

**Screenshots**

- Nagios Timeperiod Configuration:
![thruk-3](https://user-images.githubusercontent.com/232433/92241957-5cb8ca80-eebf-11ea-8a4c-5b366f6424f2.png)

- Thruk Timeperiod Configuration:
![thruk-4](https://user-images.githubusercontent.com/232433/92241978-67735f80-eebf-11ea-9fba-d4067a6c5cd6.png)

- Thruk Report options:
![thruk-1](https://user-images.githubusercontent.com/232433/92242005-735f2180-eebf-11ea-8520-1501fcc82536.png)

- Thruk incorrect result:
![thruk-2](https://user-images.githubusercontent.com/232433/92242035-7eb24d00-eebf-11ea-98e0-817bbd91b2da.png)

**Desktop (please complete the following information):**
 - Firefox
 - Version 80.0.1 

**Additional context**
Thank you !

**Comment by sni** [comment]
Is this an old or a new timeperiod? Thruk can only use the "TIMEPERIOD TRANSITION" entries from the logfile. So a timeperiod can only be used after it has been created for future reports.
