### ISSUE TITLE
logcache import for icinga (SQL Privileges needed)

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#1041]
Hi Sven,

am setting up the logcacheupdate for icinga based on https://www.thruk.org/documentation/logfile-cache.html#_icinga-2 and your instruction provided in https://github.com/sni/Thruk/issues/1018

Just want to know what MYSQL privileges should it get in order for a user fetch log from icinga? (GRANT ALL) really necessary?

**Comment by sni** [comment]
thruk needs to create and alter tables in the database. So all privileges for the given database would be the easiest setup.

**Comment by jgbuenaventura** [comment]
thanks you!
