### ISSUE TITLE
Not possibile to connect to encrypted livestatus tcp port

### ISSUE THREAD

**Issue by pindara** [sni/Thruk#1046]
Since release  1.6.0b1 livestatus via TCP can now be encrypted by the CheckMK slave.

Attempting to connect to an encrypted port from  Thruk  generates an error message   of the type:

99: not a valid header (no content-length) got: Error reading from 3: Connection reset by peer Monitoring::Livestatus::_send_socket(Monitoring::Livestatus=HASH(0x55b07a733718), "GET status\x{a}Columns: accept_passive_host_checks accept_passive_service_checks  .........

Obviously the ideal solution would be for Thruk to connect to the encrypted port by importing the CheckMK certificates in some way.

In the meantime whilst waiting for the ideal solution, may be the error message could be adjusted to something which could help direct the user to more quickly determine the source of the problem; something like:

'The data seems to be encrypted; try switching-off  encryption on the remote CheckMk slave tcp port'

Thanks

**Comment by sni** [comment]
From Thruks perspective there is no good way to detect an error on the remote side if the connection is simply closed.
Have you tried to enable encryption in Thruk? I don't have access to any cmk, but Thruk supports encrypted livestatus for quite a while now. There is an example here: http://thruk.org/documentation/configuration.html#_component-thruk-backend
