### ISSUE TITLE
Icinga2 and livestatus support

### ISSUE THREAD

**Issue by handfreezer** [sni/Thruk#1047]
Hello to every one,

  Sorry for this question if already answered (I didn't find), but I just discovered that Icinga2 project is deprecating livestatus interface ([here](https://icinga.com/docs/icinga2/latest/doc/14-features/#livestatus)).
  Do you know if there is a plan to support Icinga2 without livestatus through there own API ? or through LMD ?

Best regards

**Comment by sni** [comment]
So far Thruk only speaks livestatus. LMD also only speaks livestatus, so lmd will stop working with icinga2 as well. I have little interest in implementing and supporting a icinga2 api which likely changes every now and then.
If required, it would maybe possible to use LMD as translator which offers livestatus to Thruk but somehow fetches data with from a different api. But this would require major changes to LMD and a lot of things are unclear since i haven't looked into alternative icinga apis yet. But according to icinga developer, they are slower than livestatus and no idea if they cover everything livestatus has.
Afaik the compat log will also be dropped. I estimate this at least 2 weeks of work to get this to work
Also no idea if this is a political move to force people more into the icinga products. So its probably wasted time to try to keep up with deprecations in icinga2 and focus on other long term stable backends like Naemon or modern solutions like Grafana / Prometheus.
But if somebody wants to dig into this and implement something for LMD i am happy to discuss this and accept pull requests.

**Comment by Ashark** [comment]
It is confusing though that in thruk documentation [here](https://www.thruk.org/documentation/lmd.html) it is said that
> It is recommended for Icinga 2 users to use LMD.

Probably, it should instead be edited to prewarn people from migrating to icinga2 because it is going to stop supporting thruk.

**Comment by sni** [comment]
i hopefully never suggested using Icinga2. However, I made the hint more clear now.

**Comment by hugleo** [comment]
> So far Thruk only speaks livestatus. LMD also only speaks livestatus, so lmd will stop working with icinga2 as well. I have little interest in implementing and supporting a icinga2 api which likely changes every now and then.
> If required, it would maybe possible to use LMD as translator which offers livestatus to Thruk but somehow fetches data with from a different api. But this would require major changes to LMD and a lot of things are unclear since i haven't looked into alternative icinga apis yet. But according to icinga developer, they are slower than livestatus and no idea if they cover everything livestatus has.
> Afaik the compat log will also be dropped. I estimate this at least 2 weeks of work to get this to work
> Also no idea if this is a political move to force people more into the icinga products. So its probably wasted time to try to keep up with deprecations in icinga2 and focus on other long term stable backends like Naemon or modern solutions like Grafana / Prometheus.
> But if somebody wants to dig into this and implement something for LMD i am happy to discuss this and accept pull requests.

Same thing happened to centreon: https://github.com/centreon/centreon/issues/8246

**Comment by handfreezer** [comment]
Hello,
Yes , it seems that Icinga2 as Centreon is changing there API.
The main explication I got is the fact that LiveStatus protocol is not enough extended to support the edge functionnality coded in each project, and that's why each project doesn't plan to maintain LiveStatus protocol by defining thereo wn one.
To limit the change and maintaining portability, it was suggested to implement new protocols into LMD, and use LMD as a gateway for thruk by still speaking LiveStatus to LMD , and LMD converting to a specific protocol if needed:

Thruk <=> "LiveStatus" <=> LMD <=> "specific protocol" <=> monitoring system (Icinga, Centreon, ...)

But I fail to get time for this (for my part I was interested in the Icinga protocol).

**Comment by rainer-tammer** [comment]
Hello,
Any recommendation for an user of icinga2 with thruk and pnp4nagios?
To which stack can we migrate and re-use most of our configuration and preserve our historical data?

Bye
  Rainer

**Comment by rainer-tammer** [comment]
Thanks, then I should have a look.

**Comment by handfreezer** [comment]
Hello,

But Icinga2 implemented a DSL language which allows a lot of more flexible conf. Also, it comes with a great concept on HA and clustering for monitoring natively.
The fact is that Thruk is more advanced with it's Panorama view for end-user.
I feel that Thruk should be able to connect to other backend protocol than just Naemon (even if I know that historically, it is link to netsaint, nagios, then naemon) to get more visiblity and perspective.

I take in consideration to maintain Livestatus module in Icinga2 but, using LMD to implement and support other protocol for Thruk is a point to consider because Thruk deserve to get more visibility. Where this debat can take place?

Best regards.

**Comment by rainer-tammer** [comment]
Hello,
I would highly appreciate that!

Bye
  Rainer Tammer

**Comment by sni** [comment]
i am not aware of any place to discuss things yet. Still would prefer to keep livestatus in icinga 2, that's where it belongs in first place.

**Comment by handfreezer** [comment]
OK, so, to sump'up : there's no way to change Thruk to integrate natively the Icinga2 API. I'm feeling even it should not be a good point, and we have not enough interest to implement Icinga2 API into LMD for now.
Maintaining Livestatus on my side into Icinga2 will depend on my futur needs.
So we are falling in a "Wait and see" situation.

Thanks for your answers, and your time!

Best regads.
