### ISSUE TITLE
Oauth logout not working

### ISSUE THREAD

**Issue by harishjadhav26** [sni/Thruk#1053]
**Describe the bug**
Keycloak oauth and github oauth is applied its working fine but, when i click on logout button its logout but if i open same url in new tab same browser and click on oauth login its logged in instead of ask username and password.
Also updated following config in thruk.conf
cookie_auth_session_timeout     = 60
cookie_auth_session_cache_timeout = 0
but still generated hash filesystem in /var/lib/thruk/session/
and not cleaned auto after logout
Or may be not working with oauth

**Thruk Version**
2.38-1

**To Reproduce**
1. Configure oauth
2. Login through oauth
3. logout 
4. open same url in new tab same browser without clean cookies and cache.

**Expected behavior**
logout from all oauth and thruk.

**Desktop (please complete the following information):**
 - Browser (chrome, firefox)
 - Version [86.0.4240.111, 82]

**Comment by sni** [comment]
Thats outside the scope of Thruk and probably a setting of your OAuth provider. Thruk simply redirect to the oauth server. So if you logout, you log out of Thruk, not out of your oauth provider.

**Comment by harishjadhav26** [comment]
@sni i have replaced logout url in menu.conf and _header.tt

<form action="[% url_prefix %]cgi-bin/login.cgi?logout" method='POST' target='_top'>
#TO
 <a href='https://auth.example.com/auth/realms/thruk/protocol/openid-connect/logout?redirect_uri=https://thruk.example.com/thruk/cgi-bin/login.cgi?logout' target='_parent'>

and in thruk.conf 
set value 30 to 0
cookie_auth_session_cache_timeout = 0

and restarted service its worked for both thruk and oauth
Shall we update in thruk.conf logout url in oauth section

**Comment by sni** [comment]
so it would be nice to have a configurable logout url as well for each oauth configuration.

**Comment by harishjadhav26** [comment]
@sni oauth logout configuration will planing to add in thruk!!!

**Comment by gabortakacs78** [comment]
Hi Sven,
Yes, we realized the same.
Our WASI/SSO Colleagues suggested the same, to have an option to define logout link also ;-)
Br,
Taki

**Comment by sni** [comment]
There is now a `logout_url` config option. If you need more specific links, the menu_local.conf is using perl and not static.
