### ISSUE TITLE
Panorama View: Fetching Details Failed

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#1054]
**Describe the bug**
We are running several nagios backend at our environment, and there seems to be a problem with the panorama view, It doesnt refresh and doesnt display the figures as it should be.

**Thruk Version**

thruk-base-2.30-3.x86_64
thruk-2.30-3.x86_64
libthruk-2.32-0.x86_64
thruk-plugin-reporting-2.30-3.x86_64
lmd - version 1.8.2
rhel-6

**To Reproduce**
1. Go to 'Thruk'
2. Click on 'Panorama View'
3. Load the desired dashboard

**Expected behavior**
Panorama view should display figures 

**Screenshots**
![image](https://user-images.githubusercontent.com/12998432/98218486-c704ee80-1f86-11eb-9f71-ac1db89f6ddb.png)

Here's the another view after right clicking each items and clicking the refresh button.

![image](https://user-images.githubusercontent.com/12998432/98231851-f07a4600-1f97-11eb-8cba-396b636534f0.png)

**Desktop (please complete the following information):**
 - Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Additional context**

**Comment by sni** [comment]
is there anything in the thruk.log or apache error log?

**Comment by jgbuenaventura** [comment]
[thruk.log](https://github.com/sni/Thruk/files/5494179/thruk.log)
 hi sven,
here's the log it produces after we got the error

**Comment by sni** [comment]
i assume this has been fixed meanwhile. From the logfile, it might be a permission issue. Panorama checks the execute flag of the .tab file to determine whether it's a dynamic dashboard or a normal static one.
