### ISSUE TITLE
"Empty" graphs in Reports and graphs generated using the CLI

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1055]
Hello Sven,

I have a issue with generating graphs in Reports using Grafana.
I also see this issue when generating graphs from Grafana using the Thruk CLI.

The problem is that Thruk only generates an "empty" graph, only the background is created.
I can see that it is the background because if I delete "theme=light" in the action_url, the generated image changes from all white to all black.

This is the CLI command I use to create the graph:
`/usr/bin/thruk graph --host='localhost' --service='ssh' --format=base64`

and this is what I have in the nagios configuration:
`action_url  /grafana/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$&theme=light&annotations=true&kiosk=tv`

Have also tried without theme, annotations and kiosk --> same result.

**Thruk Version**
2.34-2 and 2.38-2

**To Reproduce**
1. Generate any Report that has "Grafana" as "graphing" engine  (Services/Hosts with rrd4nagios as graphing engine works OK) or use the CLI to create a graph.
2. A report with "empty" graphs get generated or an empty graph is created.

**Expected behavior**
A report with "embedded" graphs.

**Desktop (please complete the following information):**
 - Browser Firefox/Chrome/Opera

**Additional context**
Running the CLI takes about 20seconds every time, which made me believe the we are running into some timeout.
Looking at the code used for generating the graph i found the following in html2pdf.js:
```
                    retries++;
                    // wait up to 20 seconds
                    if(checkGrafanaLoaded() || retries > 400) {

```
I changed the `retries>400` to `retries>800` and sure enough it no took ~40 seconds to generate the empty image.
So something somewhere is causing a timeout.

Looking at the graphs in the GUI works without problem (and the delay of displaying the graph in the GUI is <2s).

Regards,
Dan

**Comment by dan-m-joh** [comment]
Hello Sven,

I found the culprit of this issue.
The system got an update of Grafana to version 7.x.x and in the 7.x.x version PhantomJS is no longer supported and has been removed: [breaking-change---phantomjs-removed](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v7-0/#breaking-change---phantomjs-removed).
Downgrading to latest available 6.x.x version solved this issue and the graphs are generated as they should once again.

Do you have any plans for Thruk to be able to use Grafana with version >= 7.x.x?

Regards,
Dan

**Comment by sni** [comment]
Thruk does not use the phantomjs from grafana but ships its own, but it seems like phantomjs is unable to render grafana graphs starting with grafana 7.
Thruk will definitly support grafana 7 somehow, either by replacing phantomjs or by getting phantomjs to work with grafana 7. And since phantomjs is unmaintained i am evaluating other solutions.

**Comment by dan-m-joh** [comment]
Thanks for the Feedback.
Great to hear that you are aware of a problem with Grafana >= 7.

Dan

**Comment by sni** [comment]
I gave up on getting phantomjs to work with grafana 7. The only alternative right now seems to be headless chrome. This works quite well except you need nodejs and tons of javascript, well and chrome :-)
The updated `grafana_export.sh` now checks if there is a NODE_PATH set and will use headless chrome then. In order
to get it running, you need to install nodejs and the puppeteer node module (which installs chromium as dependency).
The downloaded chrome will fail to start with lots of missing library dependencies, so i found it convenient to simply install chromium as system package which brings in all required dependencies for the price of having chromium twice.
