### ISSUE TITLE
thruk rest api regex service not force fully checked

### ISSUE THREAD

**Issue by harishjadhav26** [sni/Thruk#1057]
Hi @sni ,

I am forcefully checking service whose name is disk_/boot its throwing error unknown.
Also used esc. char "\" but same error. How i should avoid this thing

sudo thruk r -d "start_time=now" /services/Myserver/disk_/boot/cmd/schedule_forced_svc_check
{
   "code" : 404,
   "failed" : true,
   "message" : "unknown rest path: /services/Myserver/disk_/boot/cmd/schedule_forced_svc_check"
}

# Using esc. char.

sudo thruk r -d "start_time=now" /services/Myserver/disk_\/boot/cmd/schedule_forced_svc_check
{
   "code" : 404,
   "failed" : true,
   "message" : "unknown rest path: /services/Myserver/disk_/boot/cmd/schedule_forced_svc_check"
}

**Comment by sni** [comment]
You have to url encode special characters. Or use the generic command endpoint and set host/services as post parameter:
https://thruk.org/documentation/rest.html#_post-cmd
