### ISSUE TITLE
SNMPWALK & SNMPGET with thruk

### ISSUE THREAD

**Issue by johnnync13** [sni/Thruk#1059]
I'm always frustrated when I have to monitoring with SNMP circuit that they have specific MIB’s, OID’s like juniper.

I would like to add snmpwalk and snmp get to thruk but I don’t find any plugin.

I don’t know if exists alternative.

**Comment by sni** [comment]
What exactly do you want to do? Thruk simply display information from Naemon, Icinga or Nagios.

**Comment by johnnync13** [comment]
So, installing plugin for Naemon, Icinga or Nagios...would the problem be solved?
I can't find a smpwalk.pl or something like that http://nagios.manubulon.com/index_snmp.html
for example:
<img width="702" alt="Captura de pantalla 2020-11-18 a las 12 52 08" src="https://user-images.githubusercontent.com/22727137/99527352-f2330900-299c-11eb-97fe-b8968617321e.png">
<img width="389" alt="Captura de pantalla 2020-11-18 a las 12 52 16" src="https://user-images.githubusercontent.com/22727137/99527356-f3643600-299c-11eb-9f9b-4f9ac836c4a2.png">

**Comment by sni** [comment]
right, Thruk just lists the available commands here. If you install more check plugins, they will automatically show up.

**Comment by johnnync13** [comment]
sabes donde puedo encontrar snmpwalk plugin? @sni

**Comment by sni** [comment]
no idea, sry.

**Comment by johnnync13** [comment]
Thank you for your help!
