### ISSUE TITLE
thruk 2.38-2 rebuild for Debian bullseye

### ISSUE THREAD

**Issue by haraldj** [sni/Thruk#1060]
Dear Sven,

could you please rebuild the thruk bullseye package for Debian's switch to perl 5.32?

Kind regards
Harald Jenny

**Comment by sni** [comment]
which repository are you using, labs.consol.de or the suse open build server?

**Comment by haraldj** [comment]
labs.consol.de - is this your repository or whom should I contact?

**Comment by sni** [comment]
i operate both, just wanted to know which one you use

**Comment by haraldj** [comment]
Ok :-) well I like to use your apt repository, it's very comfortable for updating.

**Comment by sni** [comment]
the testing repository should contain a package build against perl 5.32 meanwhile. The stable repository will be updated on the next release.

**Comment by haraldj** [comment]
Ok thanks upgrade works without problems.
