### ISSUE TITLE
Data truncated for column 'state_type'

### ISSUE THREAD

**Issue by exodus1984** [sni/Thruk#1062]
hi,
I get a lot of errors when running /usr/bin/thruk -a logcacheupdate

> /usr/bin/thruk -a logcacheupdate 2>&1|sort |uniq -c
>       4 DBD::mysql::db do failed: Data truncated for column 'state_type' at row 1 at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 2226.
>    1145 DBD::mysql::db do failed: Data truncated for column 'state_type' at row 1 at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 2234.
>       1 OK - imported 1145 log items from 4 sites successfully in 0.62s (1861/s)

I refresh the status every minute - and every minute over 1000 entries land in the log ...

Thruk Version 2.38~2
lmd - version 1.9.1 (Build: , go1.13.8)
mk_livestatus in several versions 1.2.8p24, 1.2.6p16, 1.2.8p24, 1.2.8p16 depends on the backend
ubuntu server 20.04
mysq 8.0.22-0ubuntu0.20.04.3

**Comment by sni** [comment]
this has been fixed already:
https://github.com/sni/Thruk/commit/c99451e31f9a5987dd1e364fe0dc4dcb5fc06019
the relevant part is only the last line of that change. You could manually apply that if you don't want to wait for the next release.
