### ISSUE TITLE
Contradictionary information in the API documentation.

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1063]
I am in the process of implementing a some functions using thruk's API.

In [https://www.thruk.org/documentation/rest.html](url) it says "_Basic authentication is not possible with the rest API._"
but on the example page you say `%> curl -g 'http://user:password@localhost/thruk/r/csv/hosts?columns=name'` which is using Basic Authentication.

Is the example on the example page wrong?

Regards,
Dan

**Comment by sni** [comment]
Thanks for pointing that out. Getting basic auth to work was a bit tricky in first place, so that's why there was this relic in the documentation. Fixed it, basic auth should just work.
