### ISSUE TITLE
Legend "color-coding" missing in Grafana output

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1064]
Hello Sven,

I am having a small problem creating a image using the thruk CLI.
I can not tell which of the following components that is the culprit:
1. Grafana (v. 6.7.4, not yet updated to a v. 7 release)
2. Histou (v. 0.4.3)
3. Thruk (v. 2.38-2, not yet updated to 2.40)
4. Phantom.js (bundled with Thruk)

When I create an image using thruk CLI like this:
`/usr/bin/thruk graph --host='<host>' --service='<service>' --width=600 --height=300 --start=1605255836 --source=1 --format=base64 | base64 -d >month.png`
In the image the legend is missing the "color-coding" and only the labels are displayed like this:
![month](https://user-images.githubusercontent.com/26163222/102066668-61fcae00-3dfa-11eb-9b93-7ac1e5ffb34a.png)

If I on the other hand generate the same image for a year instead of just a month (only the parameter `--start=` has changed) like this everything looks good:
`/usr/bin/thruk graph --host='<host>' --service='<service>' --width=600 --height=300 --start=1576398339 --source=1 --format=base64 | base64 -d >year.png`
![year](https://user-images.githubusercontent.com/26163222/102066901-b2740b80-3dfa-11eb-810e-bec933ebc51e.png)

Do you have any idea/suggestion where the issue could be?
(Sadly, at the moment I have no possibility to test this with Thruk 2.40 and Grafana v. 7).

Regards,
Daan

**Comment by dan-m-joh** [comment]
After upgrading to 2.42.2 this problem went away.

Once again: Thanks for your great work with Thruk!!!

**Comment by sni** [comment]
great, thanks for your feedback.
