### ISSUE TITLE
Unable to add/view public Bookmarks in Thruk 2.40-2

### ISSUE THREAD

**Issue by Shorty110** [sni/Thruk#1065]
Hi,

there seems to be a problem with public bookmarks in thruk 2.40-2.
A user with roles "authorized_for_public_bookmarks" or "authorized_for_admin" does not get the "public available" option when trying to add a public bookmark:
![image](https://user-images.githubusercontent.com/3840650/102346769-aecdb980-3f9f-11eb-89fe-2139528c167c.png)
When I add a small debug statement to /usr/share/thruk/templates/_add_bookmark.tt I can see that this IF does not evaluate to true although the user has the permission:
```
 32       [% IF c.check_user_roles('public_bookmarks') %]
 33       public available <input type="checkbox" name="public" value=1> /
 34       [% ELSE %]
 35       not authorized
 36       [% END %]

```
![image](https://user-images.githubusercontent.com/3840650/102347096-34516980-3fa0-11eb-96a7-14b6b76368e2.png)

I tried setting authorized_for_public_bookmarks for that user, setting it to "*" and setting authorized_for_admin for that user but nothing works.

I could not find a hint in thruk.log or the apaches.log

Environment:
CentOS Linux release 7.9.2009
Apache/2.4.6 (CentOS)
libthruk.x86_64                       2.40-0                     @consol_labs_stable
thruk.x86_64                          2.40-2                     @consol_labs_stable
thruk-base.x86_64                     2.40-2                     @consol_labs_stable
thruk-plugin-reporting.x86_64         2.40-2                     @consol_labs_stable

Any advise?

**Comment by sni** [comment]
thanks, should be better now. The role name was wrong.

**Comment by Shorty110** [comment]
Your patch works, thank you!
