### ISSUE TITLE
Panorama: Upgrade from v1 to v2 config files

### ISSUE THREAD

**Issue by Shorty110** [sni/Thruk#1066]
Hi,

I have to migrate many dashboards from an old thruk 1.88 instance to the latest version. The GUI export/import works partially (not for "Hosts" tabs) but is quite cumbersome for many dashboards and the owner information is lost.

I came across convert_old_datafile.pl as mentioned in #817 but when I try it with an old dashboard file I get this error:
```
[nagios@host support]$ ./convert_old_datafile.pl ./137.tab
json_store options have been changed to hash. at ../lib/Thruk/Utils/IO.pm line 339.
        Thruk::Utils::IO::json_store('./137.tab', 'HASH(0x2698a60)', 1) called at ../lib/Thruk/Utils/IO.pm line 392
        Thruk::Utils::IO::json_lock_store('./137.tab', 'HASH(0x2698a60)', 1) called at ./convert_old_datafile.pl line 67

```

Is there any other possibility to do this more efficiently then the GUI-way?
Thank you.

**Comment by sni** [comment]
oh, that version is now over 5 years old. It might be possible to install a version in the middle, open panorama so the dashboards will get migrated and then install the last version and do that again.
You could also do this in a test installation somewhere on a test box. Then just copy the dashboard files when finished migrating.

**Comment by sni** [comment]
however, i fixed the converter if you want to give it another shot, use the one from the master tree: https://github.com/sni/Thruk/blob/master/support/convert_old_datafile.pl

**Comment by Shorty110** [comment]
Hi sni,
the new script did not produce any error but for some reason some dashboards with a "Service" panlet where still empty after the import. Anyway, you helped me a lot, thank you!
