### ISSUE TITLE
optional save open panorama tabs to user profile

### ISSUE THREAD

**Issue by afernique** [sni/Thruk#1070]
Hi,

I'm working at a school in france. Using omd distrib. (debian 8/thruk prior, very nice work !)
I was using a dummy user for the monitoring screen in our hall. was reading half a dozen panoramas every 10s to keep students waiting while we were working.

Since 2.20 panorama views are saved to cookie instead of userprofile, but cookie are erased on our hall computer and me must reconfigure tabs every start. Would it be possible to have an option to save open tab views back to user profile instead? or to read user profile tabs when cookie is not present?

tried filling dummy userprofile but it's not working :-/

{
   "panorama" : {
         "tabpan" : {
            "activeTab" : "tabpan-tab_82",
            "open_tabs" : [
               "tabpan-tab_82",
               "tabpan-tab_33",
               "tabpan-tab_37",
               "tabpan-tab_34",
               "tabpan-tab_35",
               "tabpan-tab_36",
               "tabpan-tab_83",
               "tabpan-tab_32"
            ],
      "rotate_tabs" : 10,
      "server_time" : true,
      "sounds_enabled" : false
   }
}

**Comment by sni** [comment]
If Cookies are removed every time the wallscreen starts up, you might want to set default dashboards like here:
https://thruk.org/documentation/configuration.html#_component-thruk-plugin-panorama

It is also possible to set this on a user or group basis:

```
<User wallscreen>
  <Component Thruk::Plugin::Panorama>
    default_dashboard        = 1,3,7,4
    readonly                 = 1
  </Component>
</User>
```

**Comment by afernique** [comment]
Thx for the update, user parameter is definitely SUUUUUUUper usefull in config.
Specially since i use another default dashboard for standard users.

Still default_dashnoard parameter was'nt working, I bypassed with a forged url of the form:
https://login:pass@websiteurl/OMD_site/thruk/cgi-bin/panorama.cgi?maps=33&maps=34&...&maps=last
using the "maps" parameter i stumble across while reading panorama.pm file. ^_^
