### ISSUE TITLE
Filter panel is always hidden, despite the hidesearch parameter value in url

### ISSUE THREAD

**Issue by Ashark** [sni/Thruk#1074]
On the status pages the panel with filters is always hidden. I cannot control it via parameter in url.

Thruk 2.34-2 - OMD 3.30-labs-edition

**To Reproduce**
1. Go to any page with host status, for example 'https://mon.yourdomain.com/thruk/cgi-bin/status.cgi?host=yourhost1'
2. You see that filter panel is collapsed.
3. Add "&hidesearch=0" to url and reload page.
4. You see that filter panel is still collapsed.
5. You can show filter panel with a small button, but after page reloading, it will again be collapsed.

**Expected behavior**
I want to be able to see uncollapsed filter panel, so I can easily see which filters are on the displayed page (i.e. service name, host name, etc...).

**Desktop:**
 - Browser chromium
 - Version 88.0.4324.96

**Additional context**
According to [this](https://www.thruk.org/documentation/cgi-parameters.html#_hidesearch) page, the hidesearch parameter is what I am looking for. But when I add it to url and set it to 0, the page still renders with filter panel collapsed.

As a temporary workaround, I have created a user script for ViolentMonkey with this line of code:
`toggleFilterPane('dfl_');`
this is a function that is called when click on that collapse/uncollapse button.

**Comment by Ashark** [comment]
I have read in that page that hidesearch values may be 1 or 2. I have tried 0, 1 and 2, but nothing works (pane is always hidden).

**Comment by sni** [comment]
As far as i remember, this feature is not supported by the Thruk2 theme (which is the default) because it overlaps the data table.
This parameter is a relic from older days when the filter did not overlap. I see two options here, either set a descriptive `title` parameter, so you can read what the filter is about, or try to adjust the template to make some space for the filter to be permanently visible.

**Comment by Ashark** [comment]
Thanks for the answer
> either set a descriptive title parameter, so you can read what the filter is about

The problem is that I also want to edit filters, so when tinkering with regular expressions, I do not need to reopen the panel every time.

> or try to adjust the template to make some space for the filter to be permanently visible

Can you explain in more detail what you mean?

**Comment by sni** [comment]
what i meant is adjust the `templates/_status_filter.tt` file to do different things on the `hidesearch` variable. Like not add the display:none for the filter table.
