### ISSUE TITLE
Thruk's mobile UI does not show performance graphs (using Histou/Grafana)

### ISSUE THREAD

**Issue by dagobertdocker** [sni/Thruk#1076]
In Thruk 2.40-2's mobile UI, the performance graphs seemingly work only with pnp4nagios, not with the more recent Histou/Grafana/InfluxDB/Nagflux. It would be great to be able to see graphs as context to a service notification however...
If you find the time to look into this, it would be very much appreciated!

**Comment by sni** [comment]
The mobile plugin is deprecated and has been removed. Closing this one.
