### ISSUE TITLE
[Feature request] Zabbix integration as backends

### ISSUE THREAD

**Issue by iam333** [sni/Thruk#1082]
HI! Thanks in advance!

We have been Thruk users for a few years and we are very happy with this tool.

The case that leads me is that we work with multiple backends such as Nagios / Icinga, Zabbix and we would like to be able to integrate this tool (Zabbix) into Thruk's backends, since it is one of the most used monitoring systems, would it be possible?

I have seen a tool that has done it through the Zabbix API with XMLRPC, but we would like to continue using Thruk, as it fits our needs perfectly.

Congratulations on this great job!

**Comment by sni** [comment]
This probably requires some days or weeks of work, so its quite unlikely going to happen. I personally do not use Zabbix anywhere nor have i ever used Zabbix. Does Zabbix use a similar data structure like Naemon/Nagios with Hosts, Services, Contacts etc...?
Basically, Thruk talks Livestatus with all its Backends, so if there would be a Tool that provides a Livestatus API for zabbix, you
could simply add it as another Backend.

**Comment by iam333** [comment]
Thank you very much for your quick response!

Yes, I am aware that this type of thing takes a long time to analyze and develop ... but I think it would be interesting to be able to integrate as many backends as possible into Thruk, since it is a monitoring system integration tool that could be unique .

Although, Zabbix also uses services, hosts, groups of hosts, etc., it does not do so at the configuration file level, nor does it dump the information to a status file such as nagios (status.dat) in order to be used by livestatus.
For this, an API Endpoint URL is used which can be invoked to obtain the information as livestatus (https://www.zabbix.com/documentation/current/manual/api).

**Comment by sni** [comment]
Closing this one. If anybody want to work on it, feel free to contact me or open a new issue.

**Comment by SanderDelden** [comment]
Hi @sni ,

I see this issue was closed as completed but can't find any info on support for Zabbix in the project files. Was this ever actually implemented?

**Comment by sni** [comment]
i simply closed the issue. There is no zabbix integration. Thruk is a naemon/nagios project. The "completed" is related to the issue itself i guess. I am not aware if issues can be closed as "won't fix" or something like that.
