### ISSUE TITLE
Thruk v2.40-2 not able to delete comments

### ISSUE THREAD

**Issue by glomertorino** [sni/Thruk#1084]
**Describe the bug**
not able to delete comments made on either Host or Service Check

**Thruk Version**
Thruk v2.40-2 / Checkmk EE 1.6p22 (and OMD if applicable)

**To Reproduce**
1. Browse to services in Thruk
2. Select a specific service and then enter a comment
3. Then try removing the comment
4. Check the /var/log/thruk/thruk.log and you'll see 2 - 4 entries with "...DEL_ALL_SVC_COMMENTS..." and nothing happens to the change

**Expected behavior**
It should have remove the Comments

**Desktop (please complete the following information):**
 - Browser : Chrome
 - Version 89.0.4389.82

**Comment by sni** [comment]
You could check the livestatus.log of your monitoring core. External Commands are "fire & forget" from Thruks perspective (except when using naemon core which is capable of sending a result". I'd say this issue is not on Thruks side. Does cmk enterprise support the DEL_ALL_SVC_COMMENTS command?

**Comment by sylekta** [comment]
Ignoring non-implemented command 'DEL_ALL_SVC_COMMENTS'
Yeah looks like cmc does not support delete all comments.
