### ISSUE TITLE
Thruk 2.40-2 - upgraded from 2.34-2: Report2 not working as expected

### ISSUE THREAD

**Issue by rainer-tammer** [sni/Thruk#1085]
**Describe the bug**

The SLA host reports reports from 2.34-2 do no longer work as expected., there is no data displayed in the report.
Deleting and creating a SLA report brings back some data, but the outages from the 2.34-2 system are missing.

**Thruk Version**

2.40-2

**To Reproduce**
Define a new SLA report:
- last 12 month
- daily break down
- 

**Expected behavior**

Display a SLA report with all recorded outages.

**Screenshots**

N/A

**Desktop (please complete the following information):**

FireFox ESR 78.8 -> Acrobat to view the PDF

**Additional context**

The system was upgraded from 2.34-2 to 2.40-2.
The database was updated: thruk logcache update

**Comment by sni** [comment]
There had been some issues with the logcache (which are already resolved). Besides that i am reworking the sla reports right now to support any filter for sla reports and not just simple host/service/group selection. If you want, you are welcome to test the nightly builds.
