### ISSUE TITLE
_GRAPH_SOURCE does not work in Service Status Details list

### ISSUE THREAD

**Issue by dagobertdocker** [sni/Thruk#1086]
In Thruk 2.40-2 with integrated performance graphs via Grafana/histou, there is an issue using `_GRAPH_SOURCE` to get n-th graph.

For some checks (e.g. memory usage) the 1st performance data key is shown as default (e.g.: cache) instead of e.g. the 2nd that I am more interested in. Using setting `_GRAPH_SOURCE` in a naemon's `service` definition, we see the correct graph by default on the service details page (under heading "Performance Graph")

However, when hovering over the gear icon on "Service Status Details" page, there is no change (Cache is shown).

E.g. the sample check is defined as

```
define service{
	use                   vip-service
	hostgroup_name        workers
	service_description   Memory Usage
	check_command         check_nrpe_ssl!check_memory
	notification_options  n
	notifications_enabled 0
	_GRAPH_SOURCE         2
}
```

and

```
command[check_memory]=/opt/username/nagios/libexec/check_mem -f -w 3 -c 1 -C
```

Any ideas?

**Comment by dan-m-joh** [comment]
As far as I can see, the function `get_action_url(...)` in `Utils.pm` completely ignores the _GRAPH_SOURCE variable and uses the `grafana_default_panelId` (line 1793) value instead when creating the `popup_url`.

In comparison, you are doing a lot more "processing" regarding _GRAPH_SOURCE in the `get_perf_image(...)` function. 

(I am not confident enough in Perl to try to fix your code).

Regards,
Dan
