### ISSUE TITLE
Problem with thruk graph generation

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1090]
We are having a small problem with the CLI to generate graphs (Grafana/InfluxDB/histou).

The problem that we have is that the URL generated from thruk to create the graph is created with HTTP and "localhost"  - which I can not get to work.
If I patch the grafana_export.sh script with the following two lines (yes I know I could do it in one)
`INPUT="${INPUT/http/https}"`
`INPUT="${INPUT/localhost/<real_hostname>}"`
everything works as expected.

My question is: Can we change this URL (http://localhost/) in some configuration file to some other value or is it fixed in the code?

**Thruk Version**
2.40-2

Regards,
D/\N

**Comment by sni** [comment]
The url is taken directly from the action url itself, so you should be able to set it there.

**Comment by dan-m-joh** [comment]
OK, that was it.

Until today we have only had `action_url     /grafana/dashboard/scri...` (without protocol and hostname), which have
worked fine (except for `thruk graph`). 

I have now changed it and the "normal" graphing-functions ("popup", the graph on the "details" page and the "full-blown" Grafana graph) works as they should and so do `thruk graph`.

Thanks,
D/\N

**Comment by sni** [comment]
great :-)
