### ISSUE TITLE
SLA Service Group Report is empty

### ISSUE THREAD

**Issue by heinowalther** [sni/Thruk#1092]
SLA Report based on Service Group is empty.

Thruk version 2.40-2, OMD 4.0

Fairly new installation
Have put some services into a service group, and is trying to generate a SLA Report which is based on the service group.
But no matter which options I use, it only generates a report which is empty.
I am able to generate a report if I use a SLA based on host or on a specific service... that works OK.. just not Service Group.

I have other installation (on older versions on Thruk) where the report is generated as expected.

I am thinking that this could be a know issue?

**Comment by sni** [comment]
Could you, by chance, try a recent nightly build? SLA reporting has changed and uses generic filter instead of fixed service/host/group reports.

**Comment by heinowalther** [comment]
Nightly version of OMD?
Is it possible to get "back" to the stable release later on?

**Comment by sni** [comment]
yes, update work in both directions. But you should never test in production anyway :)
