### ISSUE TITLE
Primary key violation when running logcache authupdate

### ISSUE THREAD

**Issue by lamaral** [sni/Thruk#1097]
**Describe the bug**

**Thruk Version**
2.40+2 on Debian Buster

**To Reproduce**
1. Have two different contact groups that contain the same user assigned to the same host.
2. Check the Thruk web interface, and verify that the responsible_admin field shows the user twice. 
3. Run `/usr/bin/thruk logcache authupdate` and receive the primary key violation error when trying to insert the same set of data a second time on the `contact_host_rel` table. 

```
[13:09:14,415][E][.../lib/Thruk/Utils/CLI.pm:365] DBD::mysql::db do failed: Duplicate entry '30-103' for key 'PRIMARY' at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1588.
```

**Expected behavior**
Thruk doesn't create a duplicated contact definition and succeeds with the import. 

**Additional context**
Is this configuration having the user assigned to two different contact groups and both on the same host unsupported?
Feel free to ask for more details if needed.

**Comment by sni** [comment]
What do you mean by `responsible_admin field`? What type of backend is this. The contact should only be listed once, no matter from how many contactgroups this contact is assigned to a host or service.

**Comment by lamaral** [comment]
Hi Sven,

It's a Livestatus backend with Naemon. 
What I meant with responsible_admin is actually the Contacts field on the web interface. If you would like, I can share a screenshot with more details shown with you by email. 
![image](https://user-images.githubusercontent.com/1342887/116882647-fa1df700-ac24-11eb-90b2-9d3dfc9e22d2.png)

Forgive me the confusion, I didn't have a lot of sleep this night.

**Comment by sni** [comment]
no problem. is this the latest naemon (and livestatus) release? If so, i'd move the issue there.

**Comment by lamaral** [comment]
Yes, I just queried livestatus directly and the data is duplicated there. 
I'm running Naemon 1.2.4 and Livestatus 1.2.4.1, latest on the Consol repos. 

I'll open an issue over there.
