### ISSUE TITLE
SLA-Report only shows "n/a" for availability

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1103]
Hello Sven,

Since updating to Thruk-2.42-2 (ConSol Labs) our SLA-Reports only shows "n/a" for the availability (see screenshot):

![2021-05-25_12-52](https://user-images.githubusercontent.com/26163222/119487596-e2381f80-bd59-11eb-8273-b80df0ffc849.png)

This is happening for existing and new Reports.

**To Reproduce**
1. Create a new Report
![image](https://user-images.githubusercontent.com/26163222/119488326-b1a4b580-bd5a-11eb-87df-83703680ecb8.png)

**Expected behavior**
A Report containing real values (like before).

Any suggestion on how to fix/debug this?

And, could this be something related to #1098 ?

-- 
Dan

**Comment by dan-m-joh** [comment]
Hallo Sven,

I will send you the .rpt files in a private mail (as the .rpt file contains host-information).

3.rpt is an "old" report that is not using the new "Flexible Reporting" feature and 4.rpt is a newly created report (using the new "Flexible Reporting").

Regards,
Dan

**Comment by sni** [comment]
got them, thanks.

**Comment by dan-m-joh** [comment]
Sorry for the late answer, I had already left for the weekend when you answered.

Yes, report 3 is an old (pre 2.42) report that was/is generating a report for a Hostgroup.
(The Host in the Hostgroup are still "listed" in the output although neither the Hosts or the Hostgroup is visible in the GUI).

I have run the report 4 again with debugging enabled and have sent you the files in a PM.

-- 
Dan
