### ISSUE TITLE
_GRAPH_SOURCE does not "apply" to the action_url "popup"

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1104]
Hello Sven,

Is the "_GRAPH_SOURCE" variable supposed to work for the "hover over action_url" graph?
I have set _GRAPH_SOURCE to 2 for some of my hosts and when I hover over the action_url it still shows "graph # 1".
When looking at the "details page" for the host, the correct graph (# 2) is shown.

Regards,
Dan

**Comment by sni** [comment]
it should work, but it seems like it doesn't. There is an issue for this already: #1086

**Comment by sni** [comment]
no problem :-)
