### ISSUE TITLE
BUG: Thruk is Switching User after "Regenarate Report"

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1105]
**Describe the bug**
Reportings: If I push the button to regenarate a report, the user is switching to the owner of the report.

**Thruk Version**
2.43.20210523 - OMD 4.01~2021-05-23-labs-edition

**To Reproduce**
1. Go as User XX to Reportings and list all Reportings "All"
2. Click on Button "Regenerate Report" of Owner YY.
3. See on "Logged in as YY"

**Desktop (please complete the following information):**
 - Google Chrome 90

**Comment by sni** [comment]
oh, that should not happen. Fixed in tomorrows nightly.
