### ISSUE TITLE
Thruk's cli does not show performance graphs (using Histou/Grafana)

### ISSUE THREAD

**Issue by ibr** [sni/Thruk#1114]
**Describe the bug**
Thruk's cli does not show performance graphs (using Histou/Grafana)

**Thruk Version**
2.44.3
OMD 4.20-labs-edition

**To Reproduce**
1. $ thruk graph --host='abc' --service='CEPH_DF_SSD'
2. [ERROR] Call /omd/sites/monitor/share/thruk/script/grafana_export.sh "800" "300" "1624357970" "1624444370" "https://127.0.0.1:5000/monitor/grafana/dashboard-solo/script/histou.js?host=abc&service=CEPH_DF_SSD&theme=light&annotations=true&panelId=1" "/tmp/DmmmHHsvyp"
[WARN] Unable to load the input file!

Debugging grafana_export.sh shows that phantomjs is calling html2pdf.js and that throws 'Unable to load the input file!'

**Comment by ibr** [comment]
Installation nodejs and puppeteer: problem fixed

**Comment by sni** [comment]
glad its working now, thanks for the update.
