### ISSUE TITLE
400: The request contains an invalid header. - Filter: Unexpected escape character. at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1645.

### ISSUE THREAD

**Issue by tomaszdubiel18** [sni/Thruk#1116]
**Describe the bug**
I can't neither get alert status history for a host (logs), nor alert status history for a service (logs). I get an error:
"400: The request contains an invalid header. - Filter: Unexpected escape character. at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1645."

**Thruk Version**
Thruk 2.42.2
Nagios 4.4.6

**To Reproduce**
Click alert status history for a host (logs) and alert status history for a service (logs)

**Expected behavior**
I should see logs concerning given host or service

**Desktop (please complete the following information):**
I test on Firefox, but I dont think its browser dependent bug.
![obraz](https://user-images.githubusercontent.com/85760200/125177062-321f5880-e1d9-11eb-92fb-7cf6b9ba302e.png)
![obraz](https://user-images.githubusercontent.com/85760200/125177070-43686500-e1d9-11eb-8c7d-44860166dbd4.png)

**Comment by sni** [comment]
Is there anything special in the name of the service or host?

**Comment by tomaszdubiel18** [comment]
I switched to Naemon and here this problem doesn't occur.
