### ISSUE TITLE
select backends by their section

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1121]
**Is your feature request related to a problem? Please describe.**
running multiple two-node nagios clusters for high availability means I have each monitored server twice.
In order to "hide" this from the users I can set `hidden=true` on the secondary cluster side's backends

Now in order to run a few external integration I often need to specify either of the sides, to query data for example only from the primary side, or in a bit rarer cases to get only data from the secondary side.

Doing so via the API means that I need to remember the sides by their combined set of backend IDs, which is pretty cumbersome.

Furthermore the IDs are somewhat random and never known before setting up Thruk and reading the IDs from the API.

**Describe the solution you'd like**
It would be nice to be able to query for `?backend=site1`, which expands on the backend to all backends which have their section be `site1`.

**Describe alternatives you've considered**
- reading the API to query for the backends available, which is really cumbersome in clients like Excel Powerquery and would require more roundtrips
- manually inserting the IDs by either remembering them, writing them down or looking them up manually each time.

**Additional context**
nothing valuable to add

**Comment by sni** [comment]
There will be some changes in the near future and i will consider this feature request as well when implementing the changes.

**Comment by sni** [comment]
next release should fully support this, current version does it in some ways already.
