### ISSUE TITLE
searchnavbar: ERROR: Not Found

### ISSUE THREAD

**Issue by garadar** [sni/Thruk#1122]
**Describe the bug**
When i Use the searchnavbar it's displaying an erro message : ERROR: Not Found

**Thruk Version**
Version of Thruk (and OMD if applicable): thruk-2.44.3-11112.1.x86_64

**To Reproduce**
1. Click on search nav bar (click/double click/input)
2. See the error message

**Expected behavior**
I want to understand  and resolve the search nav bar issue :)

**Screenshots**
![Screenshot from 2021-08-10 20-58-19](https://user-images.githubusercontent.com/11789709/128938863-0914805c-8035-4f4f-939b-93ce78519160.png)

**Desktop (please complete the following information):**
 - Browser: firefox
 - Version: firefox-78.12.0-1.el7.centos.x86_64

Thank you !

**Comment by sni** [comment]
Cannot reproduce that. Could you open the browsers dev console and get some details about the failed request?

**Comment by exodus1984** [comment]
hi - I noticed the same.

![problem](https://user-images.githubusercontent.com/17269638/148764504-0c52b072-e20e-4524-b674-89478c9fa038.png)

![query](https://user-images.githubusercontent.com/17269638/148764684-cd235ece-3e13-4e33-aff6-c692caaded85.png)
and respons is huge
![resp](https://user-images.githubusercontent.com/17269638/148764905-a47e3e15-7596-4c2f-86a3-8389924912aa.png)


and F5

![problem2](https://user-images.githubusercontent.com/17269638/148764601-0ff29a2f-a4ac-4f4b-8835-99ea83f8cdd3.png)

![query2](https://user-images.githubusercontent.com/17269638/148764742-29833e1e-6d27-43e5-86ca-e1e6c158c674.png)
and resp is small
![resp2](https://user-images.githubusercontent.com/17269638/148764979-7c1b3511-07f3-48c5-ae76-2ad7ef61d224.png)

**Comment by dan-m-joh** [comment]
I have also noticed the same issue.
I mostly notice it after restarting the backend due to some configuration change (not done through Thruk).
I say "mostly" because I am not 100% that it is just after a backend restart.

If it does matter, we are using a Nagios 4.4.6 backend with Livestatus 1.2.8p18  "Data source".

**Comment by exodus1984** [comment]
> Cannot reproduce that. Could you open the browsers dev console and get some details about the failed request?

what you need?

**Comment by exodus1984** [comment]
as I can see in version 2.48.2 there is a fix "fix sidebar search not showing all service names" - what I reported now works fine.

imo now it's ok :)

**Comment by sni** [comment]
great, thanks for the feedback
