### ISSUE TITLE
crontab / cluster : heartbeat hangs if host unreachable 

### ISSUE THREAD

**Issue by ronansalmon** [sni/Thruk#1124]
Whenever a host is unreachable, a heartbeat cron jobs is fired every minutes and hangs. It ends up eating all resources available on the server.

Our setup: 3 nodes
thruk : thruk-2.44.3-11112.1.x86_64
CentOS: 7.9.2009
/etc/thruk/thruk_local.conf : 
cluster_enabled = 1
cluster_nodes = http://$hostname$/$url_prefix$/
etc_path and var_path are NFS shared

How to reproduce : 
setup 3 nodes with cluster enabled. once the status is OK for all 3 of them, run the following command on only one of the nodes.

[root@node1 ~]$ iptables -A INPUT -s node2 -p tcp --dport 80 -j DROP

After a few minutes, on node2 you should see a lot of this : 
```
59912 ?        S      0:00  \_ /usr/sbin/CROND -n
59922 ?        Ss     0:00  |   \_ /bin/sh -c cd /usr/share/thruk && /bin/bash -l -c '/usr/bin/thruk r -q -m POST /thruk/cluster/heartbeat ' >/dev/null 2>>/var/lib/thruk/cron.log
59931 ?        S      0:00  |       \_ perl -x /usr/bin/thruk r -q -m POST /thruk/cluster/heartbeat
60301 ?        S      0:00  \_ /usr/sbin/CROND -n
60313 ?        Ss     0:00  |   \_ /bin/sh -c cd /usr/share/thruk && /bin/bash -l -c '/usr/bin/thruk r -q -m POST /thruk/cluster/heartbeat ' >/dev/null 2>>/var/lib/thruk/cron.log
60318 ?        S      0:00  |       \_ perl -x /usr/bin/thruk r -q -m POST /thruk/cluster/heartbeat
60702 ?        S      0:00  \_ /usr/sbin/CROND -n
60709 ?        Ss     0:00  |   \_ /bin/sh -c cd /usr/share/thruk && /bin/bash -l -c '/usr/bin/thruk r -q -m POST /thruk/cluster/heartbeat ' >/dev/null 2>>/var/lib/thruk/cron.log
.....
```

So, can /thruk/cluster/heartbeat timeout at some stage  ?
Thanks,
Ronan

**Comment by sni** [comment]
There is a 100sec timeout on heartbeat pings. So if they are run every minute, you should not see more than 2 of those hanging around. I tried, but was unable to reproduce the issue. The timeout worked as expected.
There had been issues with the timeout not working on ssl connections with older version of the underlaying IO::Socket::SSL library but i never heard of issues with plain http connections.

**Comment by ronansalmon** [comment]
as soon as I remove the iptables DROP and killall the perl cron job, everything works fine.
we will do ssl offload and load balancing, so this is plain http connections indeed.

I don't now how to debug :(
This behavior seams to only happen when /thruk/cluster/heartbeat is called from the crontab. 
I don't have this issue from a shell.

**Comment by sni** [comment]
so if you run `thruk cluster ping` from the command line it just works fine, even when packages are dropped?

**Comment by sni** [comment]
There should never be more than 2 processes running doing heartbeats with the 100 sec timeout. I fixed a potential
issue with:
 - c0401fdfbc0ada69612ce8c0656bc5d403887c8e
 - b3d3e98a2e2f1d5dcf1d338eebe535a286c1c612
So this should work better with the current nightly and the upcoming release.

**Comment by ronansalmon** [comment]
I've locally patched thruk. The patch fixes the issue.
Great ! thanks.
