### ISSUE TITLE
wrong version?

### ISSUE THREAD

**Issue by ItfB4L** [sni/Thruk#1125]
See this directory:
https://download.thruk.org/pkg/v2.44-3/ubuntu20.04/amd64/

For libthruk, there is no file version 2.44-3, however it still has 2.44-2.
Please update?

**Comment by sni** [comment]
that's fine, there is no 2.44-3 for libthruk. Libthruk will only be rebuild if there have been changes to the libraries.

**Comment by ItfB4L** [comment]
Ok so that means I have to keep different file versions in the dockerfile, because they can all have different versions?

**Comment by ItfB4L** [comment]
Also your download dir is 2.44-3 but your filename is 2.44.3, that is also not that helpful. Again extra scripting work.

**Comment by ItfB4L** [comment]
Also libthruk_2.44.2.ubuntu20.04.amd64.deb has .amd64 while the rest has _amd64, that is also not very helpful. Again extra scripting work..
