### ISSUE TITLE
Show host action menu near service action menu in the extinfo page

### ISSUE THREAD

**Issue by Ashark** [sni/Thruk#1138]
I started using [action menus](https://www.thruk.org/documentation/action-menu.html) for hosts and services. For host I specified some common things like open ipmi interface, connect to ssh url, url to warehouse web page with hardware components list, etc. For each service the menus are specific of course. For example, I have a service called "sel" indicating if there are some records present in sel (system event log). And I set a menu entries to elist and clear the sel.

When I go to some service page (I mean that page with address like this: cgi-bin/extinfo.cgi?type=2&host=server1.mail&service=sel), I very often need to access the menu for host itself. For example, from that page with sel service, I want to connect to ssh. For this I need get to host page instead, i.e. click to "View Information For This Host".

It would be more convenient to have both service menu and host menu at service pages. This way you are able to reach the wanted menu entry quicker and avoid cluttering your tabs in browser.

**Comment by sni** [comment]
Where would you put that menu? Or would you simply show it only if there is no service menu already and then use the same place as the service menu?

**Comment by Ashark** [comment]
I want it to be available _in addition_ to service menu. Always, despite the availability of service menu/menus.
Actually, I want to be able to also see a host notes url link and host groups.
This is how my host page looks:
![my_host](https://user-images.githubusercontent.com/22634975/141960730-ce20ba0c-a72b-4609-897a-45e4fb732cde.png)


This is how my service page looks:
![my_service](https://user-images.githubusercontent.com/22634975/141960771-a952c0fc-e6f3-4e3a-8cfd-2d0065d304da.png)


This is (for example) how I want to combine them:
![my_combo](https://user-images.githubusercontent.com/22634975/141960878-0da4c2f1-e98a-4149-af3b-18ed87590b25.png)

**Comment by sni** [comment]
We rearranged a lot of things with Thruk 3, please reopen the issue if it is still relevant.
