### ISSUE TITLE
Thruk hangs when SSH-Forwarded livestatus connection is broken

### ISSUE THREAD

**Issue by heinowalther** [sni/Thruk#1140]
**Describe the bug**
We have 7-8 decentral Thruk servers running OMD and livestatus configured.
We use an SSH tunnel on each host to tunnel the livestatus port to that it is reachable on a local port on the central Thruk server.
We then add each decentral server to the site manager, which gives us a nice overview of all out servers.
Each server is of cause forwarded to a separate local port.
This all works great... we of cause do it like this because it is more secure than just opening up the port in a firewall..

But if one of the remove Thruk servers loose its connection, the central setup will typically hang so hard that the web server is not even reachable...  Which is kind of annoying :-)

We are unsure if this is because we are using SSH forwarding...

**Thruk Version**
Thruk 2.44.3 with OMD 4.20-labs-ed.

**To Reproduce**
1. Setup SSH tunnel to another Thruk setup forwarding the livestatus port to 9999
2. Configure connection in the site manager with type livestatus, connection localhost:9999
3. Confirm that it works..
4. Disconnect the other Thruk server
5. ... the GUI and possible the whole server will now hang..

**Expected behavior**
It would be great if the unreachable Thruk server was just shown as disconnected

**Screenshots**
No screenshots, sorry...

**Additional context**
If there is another way to "bind" several server together in a secure way, we are all ears ;-)

**Comment by sni** [comment]
Is this with or without LMD? When enabled, LMD handles connections for Thruk. The LMD daemon is the prefered way when having multiple connections in Thruk because of this exact issue. It does not block if remote connections are not available and it also makes Thruk way faster because it removes network delays.
When using OMD you can simply enable it by uncommenting it in `etc/thruk/thruk_local.d/lmd.conf`. Give it a try
and let me know if that solves the issue.

**Comment by heinowalther** [comment]
The file looks default...
Is this the one that should be uncommented? #use_lmd_core=1
And should I do this on all servers or just the central server that links to all the other?

**Comment by sni** [comment]
yes, uncomment that line and only on the central site.

**Comment by heinowalther** [comment]
I have just tested this and rebooted a few hosts, and it seems to work much better now :-)

Thanks for the quick help!
