### ISSUE TITLE
REST API. Error for empty csv output with headers=0 

### ISSUE THREAD

**Issue by zhiltsov-dtln** [sni/Thruk#1142]
**Describe the bug**
Request to this URL:
/r/csv/hosts?name=fakehost&columns=name&headers=0
returns:
ERROR: failed to generate output, rerun with -v to get more details.
instead of empty output

**Thruk Version**
2.46

**To Reproduce**
In browser:
http://<thrukhost>/thruk/r/csv/hosts?name=fakehost&columns=name&headers=0

Retrurns:
ERROR: failed to generate output, rerun with -v to get more details.

**Expected behavior**
Simply empty output as in previous versions of Thruk.

**Screenshots**
NA

**Desktop (please complete the following information):**
All browsers and cli

**Additional context**
NA

**Comment by sni** [comment]
thanks for reporting this issue, should be fine again with the next release.
