### ISSUE TITLE
REST API. csv comments output format

### ISSUE THREAD

**Issue by zhiltsov-dtln** [sni/Thruk#1143]
**Describe the bug**
Incorrect csv output format for comments column

**Thruk Version**
2.46

**To Reproduce**
In browser:
http://<thrukhost/thruk/r/csv/hosts?name=localhost&columns=name,comments

Output:
#name;comments
localhost;[]\n

Unexpected '[' and ']' and '\n' symbols.

**Expected behavior**
comments column data has format like in previous versions of Thruk - list of comma separated comment_id.  

**Screenshots**
NA

**Desktop (please complete the following information):**
Browser and cli

**Additional context**
NA

**Comment by sni** [comment]
thanks for reporting this issue, should be fine again with the next release.

Beside that, please note the the csv is still pretty limited. If possible, use the json format.
