### ISSUE TITLE
"Servicename Format" in Reporting does not work correctly in Thruk 2.46

### ISSUE THREAD

**Issue by Mac-Dui** [sni/Thruk#1151]
**Describe the bug**
In Reporting: Type: SLA Report 

- Setting "Servicename Format" to "Customvariable" has no effect - the service_description is still used. The specified custom variable is ignored.
- Setting "Servicename Format" to "Displayname" leads to a report with empty service names.

 
For Thruk 2.44.3 - OMD 4.20-labs-edition everything still worked fine.

**Thruk Version**
Thruk 2.46 - OMD 4.40-labs-edition

**To Reproduce**
Example config:

```
define service{
	use				generic-service
	host_name			testhost1
	service_description		service_1
	display_name			Display 1
	check_command			check_custom!0!OK: One and only one
	_NAME_IN_REPORT			ONE
	}

define service{
	use				generic-service
	host_name			testhost2
	service_description		service_2
	display_name			Display 2
	check_command			check_custom!0!OK: Two, too
	_NAME_IN_REPORT			TWO
	}
```

Added this line to etc/thruk/thruk_local.conf:

`show_custom_vars = _NAME_IN_REPORT`

**Expected behavior**
Using the example config above one would expect:
Setting "Servicename Format" to "Customvariable" with value "NAME_IN_REPORT" should yield a report with service names "ONE" and "TWO".
Setting "Servicename Format" to "Displayname" should yield a report with service names "Display 1" and "Display 2"

Example report definition:
![test-report](https://user-images.githubusercontent.com/95912103/145565687-d8c9e25c-b9b5-442a-8b89-6af3bcca4211.png)

Obtained report with Thruk 2 46 using Servicename Format "Customvariable" shows service_description as service name not the custom variable:
<img width="541" alt="Thruk_2 46_using-customvariable" src="https://user-images.githubusercontent.com/95912103/145565852-ac32edf8-c662-4210-81ae-8cda63f96506.png">

Obtained report with Thruk 2 46 using Servicename Format "Displayname" shows no service name at all:
<img width="539" alt="Thruk_2 46_using-displayname" src="https://user-images.githubusercontent.com/95912103/145565948-5db242e3-e05a-4bc1-ab07-0862bcb3d284.png">

That is how it should be and is with Thruk_2 44 3 using customvariable:
<img width="542" alt="Thruk_2 44 3_using-customvariable" src="https://user-images.githubusercontent.com/95912103/145566182-4bccd14e-05df-4d77-8f3c-b0b3e5172bdb.png">
 
That is how it should be and is with Thruk_2 44 3 using displayname:
<img width="547" alt="Thruk_2 44 3_using-displayname" src="https://user-images.githubusercontent.com/95912103/145566259-168dc8f0-a4dc-46dc-90cc-399368addcfc.png">

**Comment by sni** [comment]
thanks for reporting this, should be fine again with the next update.

**Comment by Mac-Dui** [comment]
Thanks, but it still doesn't work with the servicename format "Customvariable".
For servicename format "Displayname" it seems fine now.
