### ISSUE TITLE
site name change does not update bookmarks

### ISSUE THREAD

**Issue by systemdlete** [sni/Thruk#1161]
### Description
When changing the name of the site, the bookmarks file does not get updated.

### Thruk Version
Thruk 2.46
OMD 4.40 

### To Reproduce
```omd mv oldsitename newsitename```

The bookmarks entries in the file var/thruk/users/omdadmin does not get updated for the new resulting URL

### Expected behavior
When site name changes, the URL to the bookmarks entries also must change.  So an entry before the site name change such as
```
         [
            "router interfaces",
            "https://host.domain/oldsitename/thruk/cgi-bin/status.cgi?servicegroup
=Interfaces&style=detail"
         ],
```
should end up looking like
```
         [
            "router interfaces",
            "https://host.domain/newsitename/thruk/cgi-bin/status.cgi?servicegroup
=Interfaces&style=detail"
         ],
```

### Environment
OS Devuan Chimaera (Debian 11 sans systemd)
Desktop XFCE4
Firefox 91.6.0esr

### Priority / Severity
Low / Low
(the bookmarks file can be manually modified)

**Comment by sni** [comment]
i don't think this can be easily fixed and it's a really rare corner case. If someone wants to implement this, i am happy to merge it, but i don't think this will ever make it into reachable regions of my todo list. If anyone wants to work on this, i'd happily reopen this issue again.
