### ISSUE TITLE
html error appears at top of page

### ISSUE THREAD

**Issue by systemdlete** [sni/Thruk#1162]
**Describe the bug**
`/omd/sites/sitename/etc/thruk/ssi/status-header.ssi: 2: Syntax error: newline unexpected `
appears at the top of many pages, including hosts, services, and bookmarked pages

**Thruk Version**
Thruk 2.46
OMD 4.40

**To Reproduce**
Click on some of the navigation bar items, such as services
The message appears at the top of the page

**Expected behavior**
Message should not appear.

**Screenshots**
![thrukhtmlbug](https://user-images.githubusercontent.com/79785832/154797570-5f75f73a-faf2-4d1a-9817-81fd75feb7b7.png)

**Environment**
- Devuan Chimaera 
- apache 2.4.52
- XFCE4
 - Firefox 91.6esr

**Comment by sni** [comment]
What's in that file? I assume its not the default one

**Comment by systemdlete** [comment]
Nvm.  More collateral damage from the file system mishap.   I have taken your advice and started with a fresh site and rebuilding it from backed-up configuration files.  A bit tedious, but it seems to be coming back to life now.
