### ISSUE TITLE
Switching page size on the last page returns empty page

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1163]
**Describe the bug**
Increasing the page size from the dropdown to a page size where the current page number does not exist results in an empty result.

**Thruk Version**
Thruk 2.44.3

**To Reproduce**
1. open a search result with 400 items
2. select 100 items per page
3. navigate to page 4
4. select 200 items per page
5. observe the empty result page, without a way to switch the page size again (only the browser back button works)

**Expected behavior**
Thruk recognizes, that with a pagesize of 200 no pages 3 and 4 will exist, so it will switch the user to the last page with the new pagesize

**Screenshots**
Demonstration with 109 results and pagesize switch 100->250:
after step 3:
![image](https://user-images.githubusercontent.com/5636383/155972940-3ddbff1c-175d-4b23-ba1c-b9118fa12a40.png)
step 5:
![image](https://user-images.githubusercontent.com/5636383/155972887-718eaca2-6bc7-4c4d-9c55-0d892685e016.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**

**Comment by sni** [comment]
Thanks for your report. This should be fixed in the upcoming Thruk 3. Beta/preview is available already in the testing repository if you want to have a look.

**Comment by sni** [comment]
this should be fine now.
