### ISSUE TITLE
http_backend_reverse_proxy returns 404 with grafana 8.0

### ISSUE THREAD

**Issue by supfors** [sni/Thruk#1167]
**Describe the bug**
I'm using `http_backend_reverse_proxy` to proxy grafana graphs which works great in the latest 7 version. After I upgrade Grafana to 8.0.0 (also tried 8.4.4) all requests return a "Page not found" 404 error. Grafana without the thruk proxy still works fine.

**Thruk Version**
2.44.3

**Additional context**
Grafana access/debug logs give me no clue whats wrong. Any idea what might be the issue?

**Comment by sni** [comment]
I think this is related to the issue here: https://github.com/grafana/grafana/issues/41736
Does it work meanwhile?

**Comment by supfors** [comment]
I've seen that issue as well but I think its slightly different as in our case the embedding of graphs works fine in Thruk 2.4.8. I just tested this with Grafana 9.0.4 and it still works. As soon as we start using `http_backend_reverse_proxy` it breaks and returns 404's.

So our setup is:

ThrukA > Grafana > OK
ThrukB with `http_backend_reverse_proxy` connected to ThrukB > ThrukB  > Grafana > 404

Can I supply any logs or configuration samples that would help debugging?

**Comment by sni** [comment]
We haven't upgraded grafana yet to 8/9 and still stay on 7 due to various issues. But the plan
is to do this within this year.

**Comment by sni** [comment]
The issue should be fixed with 1d8c1bbf37a2a5b3a0206ca34a593011e33ff04c
