### ISSUE TITLE
Can't open embedded Grafana inside Thruk

### ISSUE THREAD

**Issue by it-native** [sni/Thruk#1168]
**Describe the bug**
It's not possible to open Grafana Graphs directly from Thruk (Bookmark, Pop-up, etc). The website doesn't allow to open an embedded site. Here's the example from Firefox (https://support.mozilla.org/de/kb/website-erlaubt-firefox-nicht-die-seite-anzuzeigen?as=u&utm_source=inproduct).
Opening in a new tab works fine

**Thruk Version**
Thruk: 2.44-3
OMD: 4.20

**To Reproduce**
1. Hover over action icon in host or service view
2. open service/ host  and scroll down to Performance Graph

**Expected behavior**
Show the  performance graph

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5801642/160106860-11a2b906-33b5-4a7e-8d29-67c3f47c2a52.png)

**Desktop (please complete the following information):**
 - Browser Firefox/Chrome

BR Oliver

**Comment by it-native** [comment]
we got a little closer:
`Refused to display 'https://monitoring.host.tld/site/grafana in a frame because it set 'X-Frame-Options' to 'deny'.`

any hit where to alter this setting for a site?

BR Oliver

**Comment by it-native** [comment]
We could not find where the X-Frame-Options is set in the httpd conf, but what helped was to add the following line to the root apache config file located unter 
_/opt/omd/sites/\<sitename>/etc/apache/apache.conf_

```
Header unset X-Frame-Options    
Header always set X-Frame-Options "SAMEORIGIN"
```

**Comment by sni** [comment]
Sounds good, i added this to omd upstream.
