### ISSUE TITLE
Problem for change Thruk URL

### ISSUE THREAD

**Issue by samna88** [sni/Thruk#1169]
following the official documentation, they report that to modify the thruk url, you have to change the url_prefix, I have added the following information in the path /etc/thruk/thruk_local.conf

![image](https://user-images.githubusercontent.com/102529906/160407105-6d493888-e32f-4bc8-ad30-58f8e39e6067.png)

and I have configured the corresponding aliases

![image](https://user-images.githubusercontent.com/102529906/160407210-9555e943-7bdb-4186-bbd0-e24218d01d95.png)

however, when I restart the apache it gives me the following error

![image](https://user-images.githubusercontent.com/102529906/160407268-1f377757-20a1-4428-ae44-b4b96720ca4b.png)

in the thruk and apache logs it does not show any relevant error

It recognizes all the static content, but what I have to load from the cgi, it seems that it is not able to find it

![image](https://user-images.githubusercontent.com/102529906/160407547-d8270d82-97aa-4d24-a459-4a2c72489c2b.png)

**Comment by klaernie** [comment]
I think you're missing the replacement part of this line:
`  AliasMatch ^/thruk/(.*\.cgi|.*\.html|r/).* /usr/share/thruk/fcgid_env.sh/thruk/$1`
It has `/thruk` once in the match part, that you replaced, but also one more time at the end.

If I'm not mistaken, thruk expects the path set as `url_prefix` there. My guess would be that you'll have to replace the `fcgid_env.sh/thruk/$1` part with `fcgid_env.sh/aplicaciones/monitorizadelegada/$1`.

**Comment by sni** [comment]
There was an issue in the path tranlation which has been fixed in d4158f9287373cf17706c548b259226229b85584.
