### ISSUE TITLE
Change (increase) frequency of BP status refresh

### ISSUE THREAD

**Issue by dt770pro** [sni/Thruk#1170]
**Is your feature request related to a problem? Please describe.**
I need more timely updates for business process status changes

**Describe the solution you'd like**
I would like all Business Process status refreshes to happen more frequently - every second (or 2 or 5?) would be ideal!

**Describe alternatives you've considered**
I have considered writing an external script to achieve this

**Additional context**
The faster they can realistically update, the better.

**Comment by sni** [comment]
The lowest interval Thruk supports is one minute, but you can force a calculation manually by running `thruk bp all`. You can do this in an endless loop to get the fastest refresh possible.

**Comment by dt770pro** [comment]
Thank you - really helpful.

Regards,
James

From: Sven Nierlein ***@***.***>
Sent: 31 March 2022 18:48
To: sni/Thruk ***@***.***>
Cc: Martin, James ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [sni/Thruk] Change (increase) frequency of BP status refresh (Issue #1170)

You don't often get email from ***@***.*** Learn why this is important<http://aka.ms/LearnAboutSenderIdentification>

The lowest interval Thruk supports is one minute, but you can force a calculation manually by running thruk bp all. You can do this in an endless loop to get the fastest refresh possible.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsni%2FThruk%2Fissues%2F1170%23issuecomment-1084920127&data=04%7C01%7Cjames.martin%40bauermedia.co.uk%7Cfb2283f87585403cc84708da133e8c2d%7C0e79f3f34eeb48ed815e2876c379e863%7C0%7C0%7C637843456642432244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OAVGDyfuaxBNv%2B5SjEF%2FXADgpbW%2F9F9GDL8rVIZJs10%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWD7J7ODOUUOAMZQCQIVEILVCXQLTANCNFSM5SGCTS3Q&data=04%7C01%7Cjames.martin%40bauermedia.co.uk%7Cfb2283f87585403cc84708da133e8c2d%7C0e79f3f34eeb48ed815e2876c379e863%7C0%7C0%7C637843456642432244%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HmUx2cqCz90FLIzyuyHb97AxgbVdzxNfoXtAR%2BGrtCI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Bauer Media UK reaches over 25 million UK consumers through a portfolio of world-class, multi-platform media and entertainment brands including heat, Kiss, Grazia, Empire, TV Choice, Take a Break, Bella, Magic and Absolute Radio. It creates and curates entertaining media content that audiences love whenever, wherever and however they want through a multi-channel strategy and a focus on product excellence and audience insight. The result is an exciting array of influential brands, content and talent that provide compelling and engaging advertising opportunities with valuable audiences for UK commercial partners. Bauer Media UK is part of the Bauer Media Group, one of the world's largest privately owned media businesses with media assets all over the globe. www.bauermedia.co.uk

For subscriptions and gift offers, please visit www.greatmagazines.co.uk<http://www.greatmagazines.co.uk>.

The information in this email is intended only for the addressee(s) named above. Access to this email by anyone else is unauthorised. If you are not the intended recipient of this message any disclosure, copying, distribution or any action taken in reliance on it is prohibited and may be unlawful. Bauer Media and/or its subsidiaries do not warrant that any attachments are free from viruses or other defects and accept no liability for any losses resulting from infected email transmissions.

To view our privacy policy please go to https://www.bauerlegal.co.uk/privacy-policy-20210728

Please note that any views expressed in this email may be those of the originator and do not necessarily reflect those of this organisation.

Bauer Consumer Media Ltd, Company number: 01176085 (England and Wales), Registered Office: Media House, Peterborough Business Park, Lynch Wood, Peterborough, PE2 6EA
H Bauer Publishing, Company number: LP003328 (England and Wales), Registered Office: Academic House, 24-28 Oval Road, London, NW1 7DT
Bauer Radio Ltd, Company number: 1394141 (England and Wales), Registered Office: Media House, Peterborough Business Park, Lynch Wood, Peterborough, PE2 6EA
Bauer Media Audio LP, Company number LP02004 (England and Wales), Registered Office: Castle Quay, Castlefield, Manchester, M15 4PR
