### ISSUE TITLE
NagiosGraph on report SLA

### ISSUE THREAD

**Issue by marcom29** [sni/Thruk#1175]
Is it possible to integrate NagiosGraph into SLA reports?

**Comment by sni** [comment]
Have a look at http://thruk.org/documentation/graphing.html#_other-3rd-party-grapher to see if that helps.

**Comment by marcom29** [comment]
I mean, if it is possible to place them in the SLA reports, I already manage to integrate NagiosGraph to Thruk, but I would like the graph to be visualized in the reports.

![image](https://user-images.githubusercontent.com/55645181/165317984-5c08014e-ba6a-4836-8875-4d1aca3cfecd.png)

**Comment by sni** [comment]
no, i don't think that's possible.
The report plugin calls the `Thruk::Utils::get_perf_image` helper and this only supports PNP4nagios and Grafana/Histou.

**Comment by sni** [comment]
Thruk decides whether to show a graph or not based on the action_url. Usually you still want to see a graph, even if something is unavailable right now. Probably to get a hint on the situation before the outage.
