### ISSUE TITLE
RFE - Send selected data via WebHook

### ISSUE THREAD

**Issue by MattCrum1** [sni/Thruk#1176]
**Is your feature request related to a problem? Please describe.**
Trying to find a way to automatically raise tickets in our ITSM system for alerts which are acknowledged or commented upon. e.g. a group of services at a customer site have gone down because of a network issue, I acknowledge them but need a ticket to track updates. This is to assign accountability for alerts and to avoid having lots of acknowledged alerts sitting doing nothing.

**Describe the solution you'd like**
Addition of an action in the GUI which triggers a customisable script based on selected Hosts and Services. In my case, script would be used to call out to the ITSM system and create a ticket with a few fields from the host/service payload - but it could be extendable to a number of other use cases.

**Describe alternatives you've considered**
External script to grab the data and send it up to a ticket - but this would not be accessible via the GUI. Best option for my Ops team would be to have a GUI element.

**Comment by sni** [comment]
Should be doable with action menus, see https://thruk.org/documentation/action-menu.html#_custom-form-elements for an example.

**Comment by MattCrum1** [comment]
Ah great - thanks Sven
