### ISSUE TITLE
Dots in host name make host and service status pages inaccessible

### ISSUE THREAD

**Issue by mantasg** [sni/Thruk#1179]
**Describe the bug**

Nagios configuration that contains dots in host names make host and service pages inaccessible on Thruk resulting in message "This service does not exist"

**Thruk Version**
2.46

**To Reproduce**
1. Use a Nagios backend via livestatus
2. Define a host with host_name value containing dot (.)
3. Define a service for said host
4. Try viewing host and service pages in Thruk
5. Get error message: "This service does not exist..."

**Expected behavior**
Host and service pages are accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/1678730/170969284-afc627fd-8615-4840-aaca-e849f47d98b0.png)

**Additional context**

Those host and service pages are visible in Nagios web interface (Nagios Core 4.4.6). 

Here is the Nagios configuration I used resulting in inaccessible pages on Thruk:

```
define command {
  command_name check_test
  command_line echo $ARG1$
}

define host {
  host_name          example.com
  max_check_attempts 10
}

define service {
  host_name           example.com
  max_check_attempts  10
  service_description WHOIS
  check_command       check_test!$HOSTNAME$
  check_interval      300
}
```

**Comment by sni** [comment]
Cannot reproduce that. Having dots in hostnames is also pretty common and i never saw any issues. What's the url of the 404 page?

**Comment by mantasg** [comment]
Hi. Thank you for having a look. I think I have tracked the cause of my problem which does not involve Thruk. I've been using mk-livestatus Nagios plugin (mk-livestatus-1.5.0p25) to serve livestatus socket. I've picked up setup instructions from here: https://listed.to/@kodiak/21850/check_mk-livestatus-api-for-nagios

Having listened to the conversations I think I can see that the socket returns zero results if `service_name` contains dot (both `example.com` and `examplecom` certainly exist):

```
GET services
Columns: accept_passive_checks acknowledged ...
Filter: host_name = example.com
Filter: description = WHOIS
OutputFormat: json
ResponseHeader: fixed16

200           3
[]
```

```
GET services
Columns: accept_passive_checks acknowledged  ...
Filter: host_name = examplecom
Filter: description = WHOIS
OutputFormat: json
ResponseHeader: fixed16

200         581
[[1,0,"/pnp4nagios/index.php/graph?host=$HOSTNAME$&srv=$SERVICEDESC$","/pnp4nagios/index.php/graph?host=examplecom&srv=WHOIS",1,"check_whois!$HOSTNAME$"...
```

I suppose I need to look for another (version of) livestatus Nagios plugin.

**Comment by mantasg** [comment]
I can confirm that `mk-livestatus-1.2.4p5` does not have this problem.

**Comment by sni** [comment]
Thanks for the update.
