### ISSUE TITLE
comment column in host and service details is filled with comments from wrong backend

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1182]
**Describe the bug**
A comment associated with a single host or service on a single backend is shown on all backends of this host or service. If a comment is set on more than one backend the same comment is shown multiple times.
The comment.gif icon is doing the correct lookup (using the backend), but the column disregards the backend to which the comment belongs.

Best was to describe is probably as "full outer join of host/service against the comments, not using the backend as part of the join condition".

**Thruk Version**
2.48

**To Reproduce**
1. find a host or service that is present on more than one backend
2. add a comment only on one backend
3. return to the host or service overview (refreshing if needed)
4. observe the comment that was just made being listed in all rows of the host or services

**Expected behavior**
The comment is only shown on the rows that also have the comment.gif icon.

**Screenshots**
starting state: 
![image](https://user-images.githubusercontent.com/5636383/172693741-86056669-6ce6-43e2-95ad-9c9438afbd93.png)
comment being set:
![image](https://user-images.githubusercontent.com/5636383/172693796-78af2232-5ffb-4ff9-82b9-40afb34ba6aa.png)
comment being "incorrectly distributed":
![image](https://user-images.githubusercontent.com/5636383/172693871-1c922381-985c-4e56-837e-eaa97bf9c13b.png)
same problem demonstrated for hosts:
![image](https://user-images.githubusercontent.com/5636383/172694055-de5a2599-4313-49e6-889e-ac99d6f4ff17.png)

**Desktop (please complete the following information):**
- Google Chrome 102.0.5005.63 (Official Build) (64-bit)
- nagios 4.4.7 backends
- lmd - version 2.0.7 (Build: fb663ec, go1.18.2)~2.0.4 (Build: 5115f84, go1.17.6)~

**Additional context**

**Comment by sni** [comment]
Thruk had initially been designed to use a `host;service` combination as a unique item. And when having the 'same' service on multiple backends, they would mostly be merged into a single item. You will see such effects probably all over Thruk.
Advice for now would be to avoid having the same host/services on multiple backends if they are not the same thing. But i agree, this is a bug and it should not behave like that.

**Comment by klaernie** [comment]
After taking the time to write the issues I've spend quite some time more looking for exactly this underlying design. But I haven't been able to show it anywhere else, or haven't noticed in running one thruk on both halves of my HA over the last year. So I'd say most places are good already and use the backend as part of the unique key.

**Comment by klaernie** [comment]
Cool! Time to install updates for me!
