### ISSUE TITLE
Thruk 3 still thinks it is 2.48.2

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1188]
I think this slipped through the cracks, or you're waiting to actually release v3.0 before updating that.
https://github.com/sni/Thruk/blob/master/lib/Thruk/Config.pm#L30

**Comment by sni** [comment]
This will be changed on the release and points to the last release till then. So yes, the development server still thinks it is a 2.x version.
The daily packages run `make dailyversion` which basically sets the version to the output of `./get_version`
