### ISSUE TITLE
Thruk 3: double scrolling status table

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1189]
The new UI looks really nice, but I noticed one problem that certain customers of my installation will definitely be annoyed by:
![image](https://user-images.githubusercontent.com/5636383/184916713-4a9c2201-a718-4de7-91a8-fae0fcee91be.png)

Notice the double scrollbar, so there is one part where you can scroll the main window, so you can see the footer of the status table, and there is a scrollbar for the status table itself.

Hiding the top row brings the entire table in view, removing the outer scrollbar, but of cause hides valuable statistics.

My personal preference would be to not set the height of the status table in stone, but rather let it be as big as it likes to be.
A quick test with https://github.com/sni/Thruk/blob/master/themes/base.css#L1136 disabled behaves as I'd expect it to.

Of cause there is always the option to reduce the pagesize, which would make the status table always fit on screen, but I quite often find myself scrolling across longer result lists in order to gauge what a particular check has in failure modes. Doing this with a 25 entry page size would probably not be very enjoyable.

Could you help me understand the design decisions for the new table?

**Comment by sni** [comment]
tbh, i am not so happy with that either. The main reason for the change is to avoid the double pager (top/bottom). This change is something we will reconsider before the 3.x release. If you have some ideas who to improve the usability of that page, i am all ears.

**Comment by klaernie** [comment]
The thoughts that pop into my mind are (in no particular order, totally unfiltered):
- rework the top row to take up less space, so the table always fits on screen entirely
- just force users to scroll back up for pagination, letting the table overhang and just skipping the lower pagination
- load subsequent pages onto the bottom of the table as the user scrolls to it
- turn the entire pagination into a dynamically loading table

Now, I'd judge these as:
- reworking the top row could make quite some room. My first mental image would fold the totals into a vim-airline/powerline alike row: 
![image](https://user-images.githubusercontent.com/5636383/185338938-44bc76ef-db03-479a-9225-894d0dc2ece5.png)
(quick devtools mockup). One might even put this into the table header and put the pagination at the bottom. (the links in the totals work as quick filter changers anyway, so why not put them right next to the filters)
The user/version/data could be neatly folded into the header row:
  - show loading time centered in the header, just wall time unless `now-time>24h` 
  - don't know how valuable you see having the version listed on every page (I could imagine helps debugging if every screenshot shows the version)
  - put username right next to the logout button
 
   I also don't use the actionbox actions often enough that I'd give them this much screen real estate. Plus it buggers me that they don't work with the current filters, but simply default to "all hosts" or "all hostgroups".
   In general keeping too close to the old nagios cgi output is maybe a detriment - after all things like servicegroups loose a lot of their value when one can quickly filter and perform actions with Thruk's quick commands. For the old nagios cgi this was an essential feature, now I'm quicker at filtering and save time building a config that has servicegroups for every kind of check.

- forcing the users to scroll back up is a bit invasive, but I personally wouldn't mind too much. I tend to reach for the page size dropdown after the second pagination, since scrolling is superior to paging, but I'd never set pagesizes >250 as default, since that will pull too much in most cases, making the Chrome choke a little.
For most of my daily users they will get results for one host (direct links from the cross-tool aggregating alert inbox). They'd be fine no matter what. The more analytical/reporting focused set of users are on the "pare down using filters, then if #pages < 3 flick through pages, else increase pagesize to reduce paging to tolerable amount" side of things.

- both dynamic table loading options are things I wouldn't touch with a 10 foot pole. I've done such once, and I'd never do that again, unless there is a library that does 99% of the work. So implementing something like this could be done with [Datatables](https://datatables.net/), that does lazy-load data from the API, but that would be a way too big architectural change I'd think (plus, as I've never used datatables myself, I cannot begin to judge how well the custom cell contents would work for things like notes, host/service menus and long status information).

I hope this wall of text sparks an idea, but I'd say I spent the last hour wisely ;)

**Comment by sni** [comment]
thanks for your input.
We thought about dynamic tables as well, but it wouldn't work anyway because of the filtering and the dynamic hosts/services.

Right now, the header statistics will automatically hide at a certain screen size, but the mini status bar looks interesting.

The reason for the "infobox" is mainly to have a version in screenshots when i get error reports. But it will be hidden already on a couple of pages.

**Comment by klaernie** [comment]
Cool! Thanks! I like that solution, with the preset I can make that a seamless transition for my users.
