### ISSUE TITLE
Support expiring acknowledgements for Naemon

### ISSUE THREAD

**Issue by roelvanmeer** [sni/Thruk#1199]
Now that Naemon has support for expiring acks (https://github.com/naemon/naemon-core/issues/302), it would be nice if Thruk would support this.

I can write up a change, but I'd like to know how you'd prefer this. Currently the `enable_icinga_features` and `enable_shinken_features` variables are used to enable this, but `enable_naemon_features` doesn't exist. Do you want to create that, or can we just allow this feature to be enabled regardless of the backend? I didn't check but I can't imagine Nagios doesn't have this feature as well.

**Comment by sni** [comment]
I have prepared a patch already, no worries. Will push it as soon as the change it merged.

**Comment by sni** [comment]
expire acks are now enabled by default with bf9afefe0400be179f52459170772621be5c33f2
But they can be disabled from the config if necessary.
