### ISSUE TITLE
Thruk 3: pressing Enter in a filter value field

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1200]
Using Thruk 2 the filter value fields responded to pressing enter as if you'd clicked the OK button of the form and started reloading the page with your changed filters applied.

Using Thruk 3 this doesn't work anymore, the filter box is closed, but the page does not reload.

![image](https://user-images.githubusercontent.com/5636383/191572609-26240139-aa93-4687-b960-444f359a90c0.png)

Is this an intentional (potentially incomplete) behaviour change, or just a bug?

**Comment by sni** [comment]
Sounds like a bug. Forms with text input should submit/reload on enter. Also there seems to be an issue with the z-index here.

**Comment by klaernie** [comment]
Good to know. I didn't want to bring the z-index issue up, as I wasn't sure yet if that's a problem in the code or an artifact of how I build the stylesheet (I'm also not sure still, but meaning to find out).

**Comment by klaernie** [comment]
Thanks for fixing both the submit and the z-index!
