### ISSUE TITLE
Problem in installation of thruk in OEL 7.9 nodes

### ISSUE THREAD

**Issue by legendary-acp** [sni/Thruk#1207]
While following integration steps for apache and thruk, I am getting following error while running the script mentioned in documentation. 
```
no user id! at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 230.
Thruk::Utils::IO::ensure_permissions('dir', '/tmp/thruk_0') called at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 65
Thruk::Utils::IO::mkdir('/tmp/thruk_0') called at /usr/share/thruk/lib/Thruk.pm line 516
Thruk::_init_cache() called at /usr/share/thruk/lib/Thruk.pm line 132
Thruk::_build_app('Thruk', 'Thruk::Backend::Pool=HASH(0x2312278)') called at /usr/share/thruk/lib/Thruk.pm line 79
Thruk::startup('Thruk', 'Thruk::Backend::Pool=HASH(0x2312278)') called at ./script/thruk_fastcgi.pl line 28
```
**Documentation Link**
https://www.thruk.org/documentation/install-webserver.html

**Comment by sni** [comment]
Is there a reason why you did not use the rpm (rhel7) packages?

**Comment by legendary-acp** [comment]
I tried installing through rpm package but due to some config error thruk was not visible on desired address. Corrected the config and now thruk is working fine.
