### ISSUE TITLE
docs: REST API perf_data expansion and hoisting

### ISSUE THREAD

**Issue by klaernie** [sni/Thruk#1208]
For a quick demo I today fired a query against the REST API without specifying the set of columns.
I interestingly found a feature that was hidden in plain view: Thruk hoists the the performance data fields into their own columns, besides just expanding them with `(host_)?perf_data_expanded`.

Could this feature please be documented?

The same also holds true for the custom_variables, which just appear as columns following their internal nagios macro naming (although that could be a livestatus feature, haven't looked into it too deeply).

**Comment by sni** [comment]
That's a Thruk feature and has nothing to do with Livestatus. I added a small chapter about it.

**Comment by klaernie** [comment]
Cool! Thanks a lot!
