### ISSUE TITLE
Bookmarks on 3.00

### ISSUE THREAD

**Issue by welj** [sni/Thruk#1213]
**Describe the bug**
When open Bookmarks navigation bar close

**Thruk Version**
3.00

**To Reproduce**
1. Click on any Bookmarks  
2. See no bar navigation

**Screenshots**

<img width="57" alt="Снимок экрана 2022-11-17 101447" src="https://user-images.githubusercontent.com/5948085/202380607-6ee64fcb-53dd-4a2e-95bb-98e29dc82e2e.png">

**Desktop (please complete the following information):**
 - Browser chrome, opera
 - Version latest
 
P.S. Thx for best update :) awesome disign and functions

**Comment by welj** [comment]
Oh.. if link start thruk/cgi-bin/status.cgi?nav=&hidesearch=0&hidetop=&dfl_columns= then navi hide, bug?

<img width="563" alt="Снимок экрана 2022-11-17 140633" src="https://user-images.githubusercontent.com/5948085/202430383-219741fd-226d-4a2d-98f1-0d0dc1efe3f4.png">

**Comment by sni** [comment]
the bookmark cannot be edited directly right now. You could always edit the json file /var/lib/thruk/users/...

With the nav= parameter navigation can be controlled. I'll have a look how this parameter slipped in here

**Comment by sni** [comment]
did this bookmark exist already from previous versions or is it a new one?
