### ISSUE TITLE
Display problem (warning vs critical) in thruk 3.0 services list page

### ISSUE THREAD

**Issue by alexcernat** [sni/Thruk#1215]
**Describe the bug**
On service status detail the "progress bar" (better said "performance bar") should be yellow/amber for warnings. Actually it's red (looks as critical)

**Thruk Version**
3.0

**To Reproduce**
1. Go to /thruk/cgi-bin/status.cgi?style=detail&page=5

**Expected behavior**
"Progress bar" should be yellow/amber

**Desktop (please complete the following information):**
Latest Chrome

**Additional context**
<span class="perf-bar-container not-clickable" style="width:75px;" title="%TITLE%"><span class="bg"></span><span class="bar red" style="width:23px;" title="%TITLE%"></span></span>
^span class should be "bar yellow"

**Comment by sni** [comment]
thanks, you are right. Should be fixed now.
