### ISSUE TITLE
Thruk 3.0 missing CSS after upgrade

### ISSUE THREAD

**Issue by jboisdequin** [sni/Thruk#1216]
**Describe the bug**
Thruk is displaying without CSS after the upgrade to 3.0

I have the following conf:
in /etc/thruk/thruk.cfg: themes_path = /etc/thruk/themes/themes-enabled

themes Light and Dark are installed:
/usr/share/thruk/themes/themes-available/

symlinks are present in
/etc/thruk/themes/themes-enabled
and
/etc/thruk/themes/themes-available

in apache access logs:
81.244.237.11 - - [18/Nov/2022:10:53:25 +0000] "GET /thruk/themes/Light/stylesheets/Light.css HTTP/1.1" 404 523 "https://<HIDDEN>/thruk/cgi-bin/status.cgi?style=detail" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"

**Thruk Version**
thruk v3.00

**To Reproduce**
After the upgrade from latest 2.5 to 3.0 I got this
Running on Debian 10.13

**Expected behavior**
I'm expecting CSS 

**Screenshots**
![Selection_016](https://user-images.githubusercontent.com/791037/202692068-dc7d8751-8d8b-4f84-b497-00022edb8633.png)

**Desktop (please complete the following information):**
 - Browser All browsers

**Comment by sni** [comment]
how did you install Thruk? Which repository did you use?

**Comment by jboisdequin** [comment]
I did use this repo along with naemon:
http://download.opensuse.org/repositories/home:/naemon/Debian_10/

**Comment by guigeek208** [comment]
I have the same issue with the repo http://download.opensuse.org/repositories/home:/naemon/Debian_11/

**Comment by sni** [comment]
Seems like all OBS builds have this issue, you can use this repo for now as workaround:
https://labs.consol.de/repo/stable/

**Comment by guigeek208** [comment]
Yes ! It works perfectly ! Thanks

**Comment by jboisdequin** [comment]
Same here, Thank you :)

**Comment by sni** [comment]
i switched the release obs builds to a static tarball instead of a dynamic git clone. This should fix this issue.
