### ISSUE TITLE
Thruk CLI : bug with request

### ISSUE THREAD

**Issue by jbeaujour** [sni/Thruk#1221]
Hello

**Describe the bug**
When asking thruk cli some error appears 

**Thruk Version**
3.0

**To Reproduce**
Steps to reproduce the behavior this is example
1. thruk r /sites
2. thruk r /comments

**Expected behavior**
1. thruk r /sites

#addr;connected;federation_addr;federation_key;federation_name;federation_type;id;last_error;localtime;name;section;status;type
x.x.x.x:6557;1;x.x.x.x:6557;0cbef;nagios-dev;livestatus;0cbef;;1669397743;nagios-dev;Default;0;livestatus

**Screenshots**
Odd number of elements in hash assignment at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 64.
Odd number of elements in hash assignment at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 64.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Odd number of elements in hash assignment at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 64.
Odd number of elements in hash assignment at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 64.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Menu.pm line 574.
#addr;connected;federation_addr;federation_key;federation_name;federation_type;id;last_error;localtime;name;section;status;type
x.x.x.x:6557;1;x.x.x.x:6557;0cbef;nagios-dev;livestatus;0cbef;;1669397743;nagios-dev;Default;0;livestatus

**Desktop (please complete the following information):**
Linux RH7.9

**Comment by sni** [comment]
I'd say this is something in you local installation. Probably from a menu_local.conf. Could you check and move such file away to see if the issue persists?

**Comment by jbeaujour** [comment]
with curl it's OK :
curl 'http://xxxxxxxxxxxxxxxxxx@x.x.x.x/thruk/r/sites'
[
   {
      "addr" : "x.x.x.x:6557",
      "connected" : 1,
      "federation_addr" : [
         "x.x.x.x:6557"
      ],
      "federation_key" : [
         "0cbef"
      ],
      "federation_name" : [
         "nagios-dev"
      ],
      "federation_type" : [
         "livestatus"
      ],
      "id" : "0cbef",
      "last_error" : "",
      "localtime" : 1669399252,
      "name" : "nagios-dev",
      "section" : "Default",
      "status" : 0,
      "type" : "livestatus"
   }
]

**Comment by jbeaujour** [comment]
OK
it works with this menu_local.conf
```
do '/usr/share/thruk/menu.conf';
if(has_role('authorized_for_admin')) {
  add_section('Reports');
  add_section('System');
} else {
  remove_section('Reports');
  remove_section('System');
}
```

In the previous file i have this line at the end :

`insert_item('Reseau', { 'href' => '../../reseau/datatable/index.html', 'name' => 'Versions SNMP', 'target' => 'blank' });`

It works whis Thruk 2.44

**Comment by jbeaujour** [comment]
this item in the menu works fine

**Comment by sni** [comment]
With curl you probably don't see the warnings, they should end up in the apache log.
I think the issue is the `add_section`. It should be `add_section('name' => 'Reports');`

See http://thruk.org/documentation/menu.html#_adding-new-section

**Comment by jbeaujour** [comment]
Thank's, it works fine with :
```
do '/usr/share/thruk/menu.conf';
if(has_role('authorized_for_admin')) {
  add_section('name' => 'Reports');
  add_section('name' => 'System');
} else {
  remove_section('Reports');
  remove_section('System');
}
add_section('name' => 'Reseau');
insert_item('Reseau', { 'href' => '../../reseau/datatable/index.html', 'name' => 'Versions SNMP', 'target' => 'blank' });
```
