### ISSUE TITLE
THRUK yum local install

### ISSUE THREAD

**Issue by jbeaujour** [sni/Thruk#1222]
Describe the bug
When i launch install with yum some messages appears for "nrpe" :

/home/nrpe/rpm/tmp/rpm-tmp.sg4b2R: line 3: [: too many arguments
/home/nrpe/rpm/tmp/rpm-tmp.sg4b2R: line 7: [: too many arguments
/home/nrpe/rpm/tmp/rpm-tmp.sg4b2R: line 11: [: too many arguments

Install is done

Thruk Version
2.44 to 3.0

To Reproduce
download 4 thruk rpm from repo
yum --disablerepo=* localinstall *.rpm

** Results **
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Examining libthruk-3.00-0.rhel7.x86_64.rpm: libthruk-3.00-0.x86_64
Marking libthruk-3.00-0.rhel7.x86_64.rpm as an update to libthruk-2.44.2-0.x86_64
Examining thruk-3.00-12034.1.rhel7.x86_64.rpm: thruk-3.00-12034.1.x86_64
Marking thruk-3.00-12034.1.rhel7.x86_64.rpm as an update to thruk-2.44.3-11112.1.x86_64
Examining thruk-base-3.00-12034.1.rhel7.x86_64.rpm: thruk-base-3.00-12034.1.x86_64
Marking thruk-base-3.00-12034.1.rhel7.x86_64.rpm as an update to thruk-base-2.44.3-11112.1.x86_64
Examining thruk-plugin-reporting-3.00-12034.1.rhel7.x86_64.rpm: thruk-plugin-reporting-3.00-12034.1.x86_64
Marking thruk-plugin-reporting-3.00-12034.1.rhel7.x86_64.rpm as an update to thruk-plugin-reporting-2.44.3-11112.1.x86_64
Resolving Dependencies
--> Running transaction check
---> Package libthruk.x86_64 0:2.44.2-0 will be updated
---> Package libthruk.x86_64 0:3.00-0 will be an update
---> Package thruk.x86_64 0:2.44.3-11112.1 will be updated
---> Package thruk.x86_64 0:3.00-12034.1 will be an update
---> Package thruk-base.x86_64 0:2.44.3-11112.1 will be updated
---> Package thruk-base.x86_64 0:3.00-12034.1 will be an update
---> Package thruk-plugin-reporting.x86_64 0:2.44.3-11112.1 will be updated
---> Package thruk-plugin-reporting.x86_64 0:3.00-12034.1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved
Updating:
libthruk x86_64 3.00-0 /libthruk-3.00-0.rhel7.x86_64 20 M
thruk x86_64 3.00-12034.1 /thruk-3.00-12034.1.rhel7.x86_64 0.0
thruk-base x86_64 3.00-12034.1 /thruk-base-3.00-12034.1.rhel7.x86_64 28 M
thruk-plugin-reporting x86_64 3.00-12034.1 /thruk-plugin-reporting-3.00-12034.1.rhel7.x86_64 65 M

Transaction Summary
Upgrade 4 Packages
Total size: 113 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Updating : libthruk-3.00-0.x86_64
**_/home/nrpe/rpm/tmp/rpm-tmp.sg4b2R: line 3: [: too many arguments
/home/nrpe/rpm/tmp/rpm-tmp.sg4b2R: line 7: [: too many arguments
/home/nrpe/rpm/tmp/rpm-tmp.sg4b2R: line 11: [: too many arguments_**
Updating : thruk-base-3.00-12034.1.x86_64
warning: /etc/httpd/conf.d/thruk.conf created as /etc/httpd/conf.d/thruk.conf.rpmnew
Updating : thruk-plugin-reporting-3.00-12034.1.x86_64
Updating : thruk-3.00-12034.1.x86_64
Cleanup : thruk-2.44.3-11112.1.x86_64
Cleanup : thruk-plugin-reporting-2.44.3-11112.1.x86_64
Cleanup : thruk-base-2.44.3-11112.1.x86_64
Cleanup : libthruk-2.44.2-0.x86_64
thruk plugins enabled: business_process conf minemap panorama shinken_features
Verifying : thruk-3.00-12034.1.x86_64
Verifying : thruk-base-3.00-12034.1.x86_64
Verifying : libthruk-3.00-0.x86_64
Verifying : thruk-plugin-reporting-3.00-12034.1.x86_64
Verifying : thruk-plugin-reporting-2.44.3-11112.1.x86_64
Verifying : libthruk-2.44.2-0.x86_64
Verifying : thruk-2.44.3-11112.1.x86_64
Verifying : thruk-base-2.44.3-11112.1.x86_64

Updated:
libthruk.x86_64 0:3.00-0 thruk.x86_64 0:3.00-12034.1 thruk-base.x86_64 0:3.00-12034.1 thruk-plugin-reporting.x86_64 0:3.00-12034.1

Complete!

**Comment by sni** [comment]
that's strange. Thruk has nothing to do with nrpe.

**Comment by jbeaujour** [comment]
The repo
https://labs.consol.de/repo/stable/rhel7/x86_64/

**Comment by dan-m-joh** [comment]
Hello Sven,

I also saw those three messages when I updated from 2.50 to 3.00 on our test-environment.
I did however ignore them at the time as everything works as expected.
However, I can not say to 100% that it was "nrpe" that was the "problem".

I'll watch closer when we upgrade production.

Dan

**Comment by sni** [comment]
thanks, i found some issues and fixed them in:
 - eaf94b70ad0cf271b9e5544a1bc3b0623a0a58ea
 - 9141ff0281060bd952096726b556eecfcfd3355f

Also adjusted the build pipeline to detect such issues earlier in the future.
