### ISSUE TITLE
Broadcasts - same "popup" for Clone and Edit

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1223]
Nitpicking...

On the Broadcast page the popup says "Clone Broadcast" for both "Clone" and "Edit" in Thruk 3.00.

![Screenshot_2022-11-29_16-25-40](https://user-images.githubusercontent.com/26163222/204571046-8a14cfdb-00d8-4057-9b33-1cca78371cff.png)
![Screenshot_2022-11-29_16-26-13](https://user-images.githubusercontent.com/26163222/204571054-26d346cb-9430-4871-9e8d-aae5aaf7b10c.png)

Regards,
Dan

**Comment by sni** [comment]
But it's wrong :-) And if this is the type of issues after a major redesign, then i am happy

**Comment by dan-m-joh** [comment]
Just trying to help and make Thruk an even better piece of software...
