### ISSUE TITLE
Target main parameters not working

### ISSUE THREAD

**Issue by krooarbo** [sni/Thruk#1229]
**Describe the bug**
action_url_target='main' parameter not working. PNP4Nagios graphs alway open in a blank page.
The 'target' => 'main' also not working in the menu_local.conf insert_item section.

**Thruk Version**
Version of Thruk (and OMD if applicable)
Thruk 3.00

**To Reproduce**
Set action_url_target=main in cgi.conf
Set 'target' => 'main' in menu_local.conf
e.g.:

insert_item('System', { 'href' => '/nagiosql', 'name' => 'Nagiosql', 'target' => 'main' });

**Expected behavior**
Open URL in the main frame.

**Screenshots**

**Desktop (please complete the following information):**
Chrome 108.0.5359.98 
Firefox 107.0.1 (64 bit) 

**Additional context**
In the Nagios 4.1.1 its works well

**Comment by sni** [comment]
but i'll have a look if this can be automated somehow if target => main is set.

**Comment by dan-m-joh** [comment]
Great!

Thanks for the Feedback.

Dan

**Comment by sni** [comment]
i fixed using the main target:
 - ce92b4fbaf102bf49e9ee0499e15b6aa91fccf51 for action/notes url
 - 61aaba0694d006a2fb0c38b13f64a7242fd9aebd from the side navigation
