### ISSUE TITLE
Upgrade to 3.00 broke history via Livestatus

### ISSUE THREAD

**Issue by dlucredativ** [sni/Thruk#1232]
Our 2.50 installation was able to display host and service history, fetching it via livestatus. After an upgrade to 3.00 we get `Unexpected escape character` errors. It seems to me that this is due to e8078603f6e7b36b0574a860d29912481dcd77c9, by which the history is no longer served via `history.pm` but `showlog.pm`. The former controller did not inject `~~` filters, while the latter does in the absense of a logcache. Thruk treats regexes as PCRE while livestatus expects POSIX, hence `\s` and `quotemeta`-results are mostly unusable.

**Comment by sni** [comment]
do you have an example hostname or service name which breaks the page?

**Comment by sni** [comment]
what kind of backend is this? I tried hosts/services with spaces, with and without logcache and it works as expected. (Tested with naemon-core and naemon-livestatus)

**Comment by dlucredativ** [comment]
I think you can close this as «wontfix». The official Checkmk packages are built against RE2 and don't have this problem. We will have to rebuild our livestatus instance.

**Comment by sni** [comment]
alright, thanks for the feedback
