### ISSUE TITLE
THRUK 3.02 : login form % width

### ISSUE THREAD

**Issue by jbeaujour** [sni/Thruk#1235]
Hello
Happy New year everybody here
We need a width scalable login form for auth login button and other text to include in this form.

We found a 300px class that restreign the width. Is it possible to autoscale the form.
in this example, i replace oauth login text by "0123456789012345678901234567890"
![image](https://user-images.githubusercontent.com/14891591/210384721-e6cb7cff-b7d8-494b-87ef-97d8c4c37931.png)
In chrome if i replace w-[300px] with for example w-[30%], it works fine: 
div class="w-[300px] card rounded-xl shadow-float h-fit z-10 p-8 flexcol flex-nowrap gap-y-0 loginmask">
div class="w-[30%] card rounded-xl shadow-float h-fit z-10 p-8 flexcol flex-nowrap gap-y-0 loginmask">
![image](https://user-images.githubusercontent.com/14891591/210386515-6311d10d-be61-4f5c-9109-3a3f9cdc4efa.png)

**Comment by sni** [comment]
w-30% basically removes the width, because the 30% is based on the screen/browser width. How about changing the w-[300px] into a min-w-[300px]? That probably should do the trick as well?

**Comment by jbeaujour** [comment]
Thank's, min-w-[300px] value is OK when testing in chrome DevTools
How to implement this solution without touching Thruk code or themes ?

**Comment by sni** [comment]
a simple:
`jQuery(".w-[300]px").removeClass("w-[300]px").addClass("min-w-[300]px");`
in there should do the trick.
But i also changed it upstream, so it should be fine with the next build as well.
