### ISSUE TITLE
Home page breaks on autorefresh

### ISSUE THREAD

**Issue by tomaszdubiel18** [sni/Thruk#1238]
**Describe the bug**
Home page breaks on autorefresh

**Thruk Version**
v3.02

**To Reproduce**
1. Go to the main page.
2. Wait for autorefresh
3. See error
![obraz](https://user-images.githubusercontent.com/85760200/211762500-681da2e1-4207-4d17-9416-84290217c839.png)

**Desktop (please complete the following information):**
 Opera 94.0.4606.54

**Comment by gelsbern** [comment]
I also have this problem and am unable to discern why it is happening.  You can manually refresh the page and it looks correct, however the next auto-refresh and it looks just like the screenshot supplied above.

**Comment by sni** [comment]
cannot reproduce it so far. Tried chrome and opera without luck. Does it happen all the time? Does it happen on demo.thruk.org as well?

**Comment by tomaszdubiel18** [comment]
I'm no longer able to reproduce that. It stopped occuring. How it is for you, @gelsbern?

**Comment by tomaszdubiel18** [comment]
I reproduced it just now. It was either more autorefreshes than just one and/or after locking and coming back to PC.

**Comment by tomaszdubiel18** [comment]
The next autorefresh fixed the view. So its quite random. You will get n autorefreshes and after n+1 autorefresh it could break the view.

**Comment by sni** [comment]
which browser on which os is that?

**Comment by tomaszdubiel18** [comment]
I reproduced that today on Google Chrome 109.0.5414.120 64 bit on Windows 11.

**Comment by jbeaujour** [comment]
> I also have this problem and am unable to discern why it is happening. You can manually refresh the page and it looks correct, however the next auto-refresh and it looks just like the screenshot supplied above.
> 
> **Desktop (please complete the following information):** Chrome Version 109.0.5414.120 (Official Build) (64-bit)

Hello
Same issue and same Chrome but also with another version

**Comment by gelsbern** [comment]
So to answer some questions,   Chrome on Windows 11, Edge on Windows 11.  Chrome on Windows 10, Edge on Windows 10.  Thruk was running on Centos 7, now running on Debian 11.    Same issue every time.

**Comment by gelsbern** [comment]
Sadly, I have nothing else to add other than it is still going on with version 3.06.2 on same browsers listed above.  Even with 0 addons it happens.   Just go to Dashboard and wait for an auto refresh.

**Comment by sni** [comment]
thanks for reporting this issue, should be fine with the next release.
