### ISSUE TITLE
Thruk 3.0.2 Core Scheduling - only reschedule "my" checks

### ISSUE THREAD

**Issue by MattCrum1** [sni/Thruk#1240]
We have a multisite setup with multiple customer-specific Naemon/Thruk systems feeding a centralised read only Thruk instance (via HTTP).

I've enabled a cron job to run "core_scheduling fix" every hour and applied it to our centralised Thruk instance, assuming that it would only reschedule the services that it was monitoring directly; but it started to run the command across all of the connected customer systems instead. 

Is there a way to limit the scope of the command to only reschedule the local instance's monitored services, so I can get each Thruk instance to manage itself?

**Comment by sni** [comment]
you could set the backend in the command line with `-b` and limit the command to certain backends only.
