### ISSUE TITLE
Thruk v3: "0" as a argument disappear in action menu commands 

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1242]
**Describe the bug**
If a "0" is in the command of an action menu command, then the script is not gonna get this argument. If I change the 0 to something else, then the called script is getting the argument again.

**Thruk Version**
OMD 5.01~2023-01-10-labs-edition

**To Reproduce**
1. Create an action in <action_menu_actions> with a script (bash script for example) and at least one argument with 0 and print out the argument
2. Execute the action  
3. See that a 0 is not gonna print out but other string will

**Screenshots**
These commands
![Bildschirm­foto 2023-01-18 um 20 40 44](https://user-images.githubusercontent.com/29919422/213279730-6358bf65-0558-40af-813a-36a993fbdec0.png)
will look like this:
![Bildschirm­foto 2023-01-18 um 20 40 17](https://user-images.githubusercontent.com/29919422/213279811-ce29f7d7-5658-49f6-844e-916e0f82e707.png)
![image](https://user-images.githubusercontent.com/29919422/213279941-02a717e7-5fa1-47b5-9189-b99cc97b318a.png)

**Comment by sni** [comment]
thanks for reporting this, should be fine again tomorrow.
