### ISSUE TITLE
[Thruk 3] Unable to use list wizard after adding new attribute

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#1243]
**Describe the bug**
When adding new attribute to host in config tool say hostgroups or contacts, we are not able to use the list wizard to populate the list.

**Thruk Version**
[OMD 5.01~2022-07-13-labs-edition]

**To Reproduce**
1. Go to demo.thruk.org
2. Click on config tool
3. select host then naemon one
4. Click on new attribute => add contacts
5. Try to use list wizard

**Expected behavior**
Both left and right lists.

**Screenshots**

![image](https://user-images.githubusercontent.com/498115/213496277-f4db4726-de95-4462-8c6d-48289a135ba3.png)

**Desktop (please complete the following information):**
 - Browser: Firefox, Chrome
 - Version: last

**Comment by sni** [comment]
Thanks for reporting this. Indeed this is broken for new attributes. Existing ones worked well. Seems like the cause is uninitialized input fields. Should be fine with tomorrows daily.
