### ISSUE TITLE
Clicking on a Host gives us "internal server error"

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1245]
Hello Sven,

Today one of our users complained that he could no longer (after update to 3.02) click on a host to get to the "Host Information view".
Here are two screenshots of what happens:
1) Click on the hostname:
![Screenshot_2023-01-24_16-37-45](https://user-images.githubusercontent.com/26163222/214340600-d0650eb2-4ac5-4710-8253-4bd75f99cec0.png)
2) The resulting page:
![Screenshot_2023-01-24_16-39-33](https://user-images.githubusercontent.com/26163222/214340838-03510117-9a92-4cec-805f-58a77339e5b3.png)

If I do the same thing as "Administrator" (can see and do everything) the page displays correctly:
![Screenshot_2023-01-24_16-42-09](https://user-images.githubusercontent.com/26163222/214341167-e95d74be-bcaa-4905-b9c5-792cc3932340.png)

Here is the output of "Preview included details":
```
Url:        extinfo.cgi?type=1&host=idxxxxxxxxxx01
Browser:    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Version:    3.02
Release:    December 15, 2022
OS Release: Red Hat Enterprise Linux Server release 7.9 (Maipo)

Backends:
  State | Program Version | Data Source Version
    0   | 4.4.6           | Livestatus 1.2.8p18


Stacktrace:
undef error - Can't use string ("") as a HASH ref while "strict refs" in use at /usr/share/thruk/lib/Thruk/Utils/Filter.pm line 1338.
 on extinfo_type_1.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 117.

stacktrace from error controller at /usr/share/thruk/lib/Thruk.pm line 344.
	Thruk::_dispatcher('HASH(0x5176180)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
	eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
	Plack::Util::run_app('CODE(0x18ed260)', 'HASH(0x5176180)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 147
	Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x800c48)', 'CODE(0x18ed260)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 28
```

**Thruk Version**
3.02

If you need more information, don't hesitate to contact me.

Regards,
Dan

**Comment by dan-m-joh** [comment]
And here is the relevant part of thruk.log:

```
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] ***************************
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] page:    GET https://<nagioshost>.uzh.ch/thruk/cgi-bin/extinfo.cgi?type=1&host=idxxxxxxxxxx01
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] params:  {'host' => 'idxxxxxxxxxx01','type' => '1'}
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] user:    xxxxxxx
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] address: 10.xx.xx.53
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] time:    0.0s
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] internal server error
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] please have a look at your log file
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] undef error - Can't use string ("") as a HASH ref while "strict refs" in use at /usr/share/thruk/lib/Thruk/Utils/Filter.pm line 1338.
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR]  on extinfo_type_1.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 117.
[2023/01/24 16:39:19][<nagioshost>.uzh.ch][ERROR] ***************************
```

**Comment by sni** [comment]
thanks, i'll try to reproduce this here. Does it happen on all of the hosts?

**Comment by dan-m-joh** [comment]
Hmmmmm, this is really "strange". 
Today when I tested this host, it worked again, but for the user who reported the problem it still exists.
I can also "see it" for other hosts, but not all of them.

**Comment by sni** [comment]
i cannot reproduce it, i assume it has something to do with the nagios livestatus
implementation which returns an empty string "" for unknown columns. And according to the
stacktrace its either in the parents list or in the dependency list. And i am not sure if
nagios supports those dependency lists in livestatus. If i remember correctly, that was
something we added later in naemon.
I will simply strip those empty strings out, then it should be fine.

**Comment by dan-m-joh** [comment]
Great, thanks for looking into this.
I am still looking into why it works for an "admin" user and not for some (not all) "normal" users.
An update of livestatus (1.2.8p18 --> 1.4.0p31) is planned for my next "update round".

**Comment by sni** [comment]
I don't think that'll help. But probably not a bad idea anyway.

**Comment by dan-m-joh** [comment]
Hi Sven,
I know you have closed this already, but I just wanted to share some more info.
1) If the user is added to either "authorized_for_admin" or "authorized_for_all_hosts" in thruks cgi.cfg the error does not happen. For all other "authorized_for_" entries it does not matter if the user is listed or not.
2) We are heavily relying/using mod_gearman to distribute the load to different "zones". In setting up this we also set each "mod_gearman-worker-host" as a"parent" in the config. Now, if the user does not have rights to the parent/worker-host (which most users does not have) we are seeing this issue (this also explains why "authorized_for_admin" and/or "authorized_for_all_hosts" "solves" the issue). So Yes, this has definitely to do with parent/dependency processing.

Well, lets see how your change https://github.com/sni/Thruk/commit/1898bbf2503935d94d79578ded57a724a791940c works. 
Do you have an ETA for 3.04?

Regards,
Dan

**Comment by sni** [comment]
there will be a release this week.
