### ISSUE TITLE
rrdtool graph invalid option lower/upper

### ISSUE THREAD

**Issue by afernique** [sni/Thruk#1249]
Hi, Just upgraded to omd 5.0 thruk 3.0 on a debian bullseye from 4.6/2.3
Everything works just fine and the new interface is very nice (Great work!).

Still i have an issue with rrdtools/pnp4nagios graph generations.
Some graph returns error and looking closely the call is made using --lower or --upper parameters where the actual doc tells it should be --lower-value/--upper-value
Tried manually calling with the correct parameters and everything seems nice.
Would you have a Clue as to where i could change these parameters? I suspect an "old" configuration file but I can't pinpoint which one.

**Comment by sni** [comment]
This is a known and fixed issue. You could try the daily OMD 5.01.
