### ISSUE TITLE
When you click "problems" it highlights "Hosts"!

### ISSUE THREAD

**Issue by infraweavers** [sni/Thruk#1254]
**Describe the bug**
If you click "problems" on the left hand menu, when it loads, "Hosts" is highlighted

**Thruk Version**
```
Version | Thruk 3.03.20230210
OMD 5.01~2023-02-10-labs-edition
```

**To Reproduce**
1. Go to 'Tactical Overview'
2. Click on 'Problems'

**Expected behavior**
Problems should be highlighted on the left rather than hosts

**Screenshots**
![image](https://user-images.githubusercontent.com/36475663/219054744-2e1b6a13-54f4-4c17-a3f6-d450c7623d86.png)

**Desktop (please complete the following information):**
- Chrome 110.0.5481.78 & Firefox 102.7.0esr

**Additional context**

**Comment by sni** [comment]
thanks, should be fine tomorrow.
