### ISSUE TITLE
refresh_rate less than 90 seconds has a 20 second "pause" around the 20 second mark

### ISSUE THREAD

**Issue by infraweavers** [sni/Thruk#1255]
**Describe the bug**
If you configure `refresh_rate = 30` the page doesn't refresh after 30 seconds, it takes like 45-50 seconds to refresh. It seems to get "stuck" at 20 and stuff. 

If you configure refresh_rate <=10 then the counter will hang for 20 seconds before it even counts down.

**Thruk Version**
Version of Thruk (and OMD if applicable)

**To Reproduce**
1. Configure `refresh_rate = 10`
2. Click on the cog (top right)
3. Watch the counter tick down, but hang on 10s for like 20 seconds or so.

**Expected behavior**
Counter should count down by 1 per second

**Screenshots**
In this gif we have configured it at 10, so you can see that it hangs for a bit before counting down:
![chrome_1smoSLVx5A](https://user-images.githubusercontent.com/36475663/219066053-702beac5-8a0d-40ef-a0ca-113e5d0de5bc.gif)
The gif here is accurate, it's not faulty or anything

**Desktop (please complete the following information):**
- Firefox 102.7.0esr (64-bit)
- Chrome Version 110.0.5481.78 (Official Build) (64-bit)

**Additional context**

**Comment by tschmitt** [comment]
I am seeing similar behavior using Edge on a Mac. Refresh is set at 90 seconds, but does not seem to refresh at all.
I am also seeing this message, which I believe is related. Dev Tools is definitely NOT open.

![image](https://user-images.githubusercontent.com/491150/220419385-04bb4220-bb23-4d64-82b3-88aab6affefb.png)
