### ISSUE TITLE
Thruk 3.00 ConfTool: Custom Variables

### ISSUE THREAD

**Issue by white-line** [sni/Thruk#1257]
The problem of applying custom variables in ConfTool:
![image](https://user-images.githubusercontent.com/13614853/219935548-b878b53b-f6f2-47ea-a86a-28a73c7e74b9.png)

Reproduced in Thruk 3.00 ( OMD 5.0.0 )

**Comment by sni** [comment]
i cannot reproduce this, what exactly did you do to get to this point?

**Comment by white-line** [comment]
In ConfTool select or create new host. Click on "new attribute". Add custom var **_LOGIN**, for example, and click "Apply":
![image](https://user-images.githubusercontent.com/13614853/220160347-455e01ff-c1a2-4ccd-ad08-ca342e9dffdc.png)

You will see - **_LOGIN** change to "customvariable":
![image](https://user-images.githubusercontent.com/13614853/220160718-576c4e4a-6be7-4eec-9c91-9bb0011904b9.png)

This also affects the cfg file:
![image](https://user-images.githubusercontent.com/13614853/220161012-219ec2f3-fc86-4f94-9406-7a1a0394489b.png)

If I will add one more custom variable, the result will be the same as in the screenshot in the comment above. Example in cfg file:
![image](https://user-images.githubusercontent.com/13614853/220161915-c9f0c4e0-fe5e-4a21-878c-03db6391ceb8.png)

**Comment by white-line** [comment]
Checked in omd 5.0.0 Before this, I upgraded from version 4.40 to 5.0.0. I did not make any changes to the omd components

**Comment by white-line** [comment]
I think problem reproduced on old custom variables from current cfg files. 
If i add a new unique custom variable ( thruk won't find it in cfg files ) - problem not reproduced.
If i add this custom variable again to other "host" object - problem reproduced.

For example - select hostA in ConfTool ( host must be created ), add new unique custom var **_FOO**, click "apply" and "save and reload" - work fine, not problems. After select hostB in ConfTool ( host must be created too ), add custom var **_FOO** and click "apply" - we reproduced problem.

**Comment by sni** [comment]
yeah, seems like there are two issues here. You should not be able to add the same attribute twice and it should not replace the customvariable name with literal "customvariable"

**Comment by sni** [comment]
thanks for reporting this, should be fine with the next release.
