### ISSUE TITLE
Error in new version 3.04 on demo thruk

### ISSUE THREAD

**Issue by malcombecerra** [sni/Thruk#1260]
**Describe the bug**
When you want to filter with and or or's, in the host status type or host properties,  appear an error that mention that doesnt have elements. and then appear the popup for the host status/properties filter.

**Thruk Version**
3.04 

**To Reproduce**
1. Click on display filter
2. add an or 
3. Click on status or properties.

**Expected behavior**
that only appears the options of host status
**Screenshots**
![image](https://user-images.githubusercontent.com/20689770/221863384-51c7594c-2fb2-4ba2-8a2e-2088172af511.png)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 109

**Additional context**

**Comment by sni** [comment]
Thanks for reporting this. It is fixed with the next release and already updated on demo.thruk.org. You might have to do a shift+reload for the js files to reload.
