### ISSUE TITLE
Ability to specify blocksize for logcache update

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#1261]
**Is your feature request related to a problem? Please describe.**
I am having OOM errors updating logcache if i am very far behind (over 1-2 weeks).

Reimporting the entries with small blocksize (i tried 4h) is very fast and seems to be the preferred solution to updating the logcache.

I'd like to be able to specify blocksize during updates. The docs suggest it's not possible.

**Comment by sni** [comment]
Have you tried setting the blocksize for updates?

**Comment by yoshi314** [comment]
not yet, i assumed it's not supported.

**Comment by yoshi314** [comment]
well, it doesn't seem to be working. I got an OOM.

**Comment by sni** [comment]
implemented with https://github.com/sni/Thruk/commit/e0e2bb2427537ef6511cdf63826505df6aed0458
so either you apply that small patch or use tomorrows nightly build

**Comment by yoshi314** [comment]
It does not seem to be working. I applied the patch by hand to the aforementioned file.

I am still hitting oom. Will try nightlies - maybe i made a mistake somewhere.
