### ISSUE TITLE
Issue with Home Dashboard duration counter >24h

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1265]
**Describe the bug**
The duration counter is not converting hours to days
**Thruk Version**
Latest [Thruk 3.04+48~6033033

**To Reproduce**
1. Got to Home
2. See Duration counter in "Unhandled Problems"

**Screenshots**
![image](https://user-images.githubusercontent.com/29919422/227811668-410324ef-c1d5-4b35-9363-34cd905fb3ec.png)

**Comment by sni** [comment]
But it's not wrong, isn't it? ;-)

Thanks, i'll have a look.
