### ISSUE TITLE
Thruk Backend connection peer display (only 1)

### ISSUE THREAD

**Issue by NymbleW** [sni/Thruk#1268]
On the Thruk backend display under version 2.30-3 if you had multiple peers under a single entry they would each appear under Connection and you could test each of them. This appears to have changed in 3.04. The thruk_local configuration looks to be correct, the lmd.ini file looks the same for either server. I was able to put a print in the PM for config and see that only one of the servers is bring sent to the display. I tried to track down the code with the problem but no lich yet.

**Comment by sni** [comment]
What do you mean with `multiple peers under a single entry`? Do you connect to multiple sites over a single thruk http connection?

**Comment by NymbleW** [comment]
Here is a section of a sample thruk_local.conf


<peer>

   name    = server1

   id           = xxxx

   type      = livestatus

   section = abcd

   <options>

      peer = serverA:6557

      peer = serverB:6557

   </options>

</peer>


The peers I am talking about are serverA and serverB

________________________________

**Comment by NymbleW** [comment]
The update worked brilliantly
