### ISSUE TITLE
Unable to start thruk using apache

### ISSUE THREAD

**Issue by legendary-acp** [sni/Thruk#1272]
**Describe the bug**
I have setup thruk using fastcgi but seems like apache is not able to run thruk. When I see error logs it gives following.

 ```
[fcgid:warn] [pid 14839] (104)Connection reset by peer: [client <IP>:47372] mod_fcgid: error reading data from FastCGI server
[core:error] [pid 14839] [client <IP>:47372] End of script output before headers: fcgid_env.sh
```

If I manually try to run thruk command it gives this error:

```
Can't load '/usr/lib64/thruk/perl5/x86_64-linux-thread-multi/auto/Cpanel/JSON/XS/XS.so' for module Cpanel::JSON::XS: /usr/lib64/thruk/perl5/x86_64-linux-thread-multi/auto/Cpanel/JSON/XS/XS.so: undefined symbol: PL_nan at /usr/share/perl5/XSLoader.pm line 68.
 at /usr/lib64/thruk/perl5/x86_64-linux-thread-multi/Cpanel/JSON/XS.pm line 2394.
Compilation failed in require at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 16.
BEGIN failed--compilation aborted at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 16.
Compilation failed in require at /usr/share/thruk/lib/Thruk/Config.pm line 10.
BEGIN failed--compilation aborted at /usr/share/thruk/lib/Thruk/Config.pm line 10.
Compilation failed in require at /usr/bin/thruk line 124.
```

**Thruk Version**
3.04

**Expected behavior**
Thruk able to run using apache

**Server (please complete the following information):**
 - Distro: Oracle Linux Server
 - Version: 7.9

**Additional context**
This is fresh installation. Other server with same config is working fine.

**Comment by sni** [comment]
This sounds like you installed either the wrong rpm like ex. rhel 8. Or the rhel7 rpm is not compatible with oracle linux 7.
