### ISSUE TITLE
Availibility computation

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#1280]
**Describe the bug**
It seems that availability computation doesn't take into account report timeperiod

**Thruk Version**
OMD 5.10

**Expected behavior**
I added today a timeperiod like that:

![image](https://github.com/sni/Thruk/assets/498115/6f6a58c6-8729-45f5-826a-d79161234cfb)

Then affected it to my report (A SLA report on just one host and its services), criticals only, one month.

Only one service has been affected during 40 mn, but **out of my timeperiod**:

Worst Outages
09 Apr 2023 04:14:48 - 09 Apr 2023 04:54:48
LOAD CRITICAL - total load average: 32.57, 83.14, 52.91

or

![image](https://github.com/sni/Thruk/assets/498115/0a3d2d39-b2a5-4c90-9266-dc0b14c8383a)

The report should compute a 100% availability value. But that's not the case:

![image](https://github.com/sni/Thruk/assets/498115/f731eb13-e502-4fcb-91d7-c6b16441b712)

I changed the report timeperiod with other values, w/o any effect, it seems the report compute availibility value based on 24x7 timeperiod.

jfr

**Comment by jframeau** [comment]
I just figured out that availability computation is done from timeperiod transition in logs, and not applied back to the data as soon you choose any timeperiod when configuring the report.

So not a bug of course, even if applying antimeperiod on any logs could be useful.

**Comment by sni** [comment]
When using the logcache database, you can generate timeperiods backwards with the `scripts/generate_timeperiod_transitions.pl` tool and then import the generated log into the database.

**Comment by jframeau** [comment]
oh, nice, i'll give a try morrow
Thx for the info..
