### ISSUE TITLE
Backslash in service name does not work for commands via REST

### ISSUE THREAD

**Issue by sideshowcecil** [sni/Thruk#1282]
**Describe the bug**
Executing commands for services with the special backslash character via the REST API leads to the following error:  "400: Failed validation of service as type service (argument 0)"
It seems the service name is not properly forwarded to the livestatus endpoint as the backslash character is stripped away from the logs, see below.

**Thruk Version**
3.0.6

**To Reproduce**
1. Create a service with a backslash in it, e.g. "C:\ Disk Space"
2. Try to execute commands for that service via the REST API, e.g. "enable_svc_notifications" or "schedule_forced_svc_check"
3. Get a 400 response with error "400: Failed validation of service as type service (argument 0)"

The error occurs with both endpoints:
- `POST /services/<host>/<service>/cmd/schedule_forced_svc_check`
  - here the host and service name are properly URL encoded
- `POST /cmd`
  - host and service names are sent as is
  - payload:
```
{
	"cmd": "enable_svc_notifications",
	"host": "Hostname",
	"service": "C:\\ Drive Space"
}
```

Payload for 

**Expected behavior**
Successful execution of the service command

**Screenshots**
not applicable

**Desktop (please complete the following information):**
not applicable

**Additional context**
Corresponding logs from the livestatus.log:
```
2023-06-06 12:52:24 Unsuccessful command: '[1686048743] ENABLE_SVC_NOTIFICATIONS;Hostname;C: Drive Space'
2023-06-06 12:52:24 error: 400: Failed validation of service as type service (argument 0)
```

**Comment by sni** [comment]
thanks for reporting this issue, should be fine with the next release.
