### ISSUE TITLE
Update/available repo for Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by FoUStep** [sni/Thruk#1285]
**Describe the bug**
When upgrading to Debian 12, there is no available repo (at the time of writing) for Thruk (through labs.consol.de). Also the current way to add the gpg key is deprecated.

**Thruk Version**
Latest version

**To Reproduce**
1.  Update to Debian 12
2. Change repo from bullseye to bookworm
3. Apt update, apt upgrade

**Comment by sni** [comment]
I updated the way keys should be added in the labs repo.
There is a repo for debian testing here: https://build.opensuse.org/repositories/home:naemon
That should work for debian 12 pretty good right now. I'll add debian 12 on obs as soon as it's available.

For the long term, the main repository will be obs for thruk and other tools. And labs will be the main repository for OMD only.

**Comment by FoUStep** [comment]
Hmmm correct me if I'm wrong but the thruk.org website says the repo of labs is the easiest way to install it:
<img width="970" alt="Screenshot 2023-06-20 at 22 39 36" src="https://github.com/sni/Thruk/assets/14996435/1a4eb090-d647-49e6-970d-4fead6446a12">

Should this be changed to the opensuse naemon repo? I don't change repo often (I've been using the labs for years).

**Comment by sni** [comment]
it is, but it is way more work to add new linux distributions there than it is on obs. So if a linux distribution is available on the suse obs, then it's just one click to enable builds/repo for it.
Thing is, sometime they take some time as well. So you can't tell which repo has a new linux distribution first. If they are available in both, then it doesn't matter.
Anyway, i updated the download page to add a bit more context and links to obs.

**Comment by sni** [comment]
Btw, meanwhile OBS has added debian 12, so it's available there now.

**Comment by FoUStep** [comment]
Works like a charm! Good solution.
