### ISSUE TITLE
"action_url" does not display a "pop-up"-graph on hover

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#1286]
Hello Sven,

Today I noticed a change in behavior when "hovering" on the "action_url"-icon.
Before (v. 3.04) , when hovering it looked like this:
![Screenshot_2023-06-15_14-02-33](https://github.com/sni/Thruk/assets/26163222/6f111a58-e2c1-4cae-8b60-30ba6ca91067)

Now (v.3.06.2), it just looks like this:
![Screenshot_2023-06-15_13-58-24](https://github.com/sni/Thruk/assets/26163222/6bcbf615-662c-4fe8-8dd0-d35c40ed2ef9)

Clicking the "action_url"-icon brings up the "histou.js" grafana "interface" as before in both cases.
Is this an intentional change or has it something todo with the change "- support native grafana dashboards in action_url"?

Any Idea how we can get "the old" functionality back?

Regards
Dan

**Comment by sni** [comment]
that's not intentional, it should work with more url patterns, not less. I'll have a look. Can you give an example action url?

**Comment by dan-m-joh** [comment]
Of cause I can :wink: 

Here are my templates for host and service action_url's:

```
define host {
        name                            host-grafana
        action_url                      /grafana/dashboard/script/histou.js?host=$HOSTNAME$&theme=light&annotations=true
        register                        0
        process_perf_data               1
        _GRAPH_SOURCE                   2
}

define service {
        name                            srv-grafana
        action_url                      /grafana/dashboard/script/histou.js?host=$HOSTNAME$&service=$SERVICEDESC$&theme=light&annotations=true
        register                        0
        process_perf_data               1
}
```

**Comment by dan-m-joh** [comment]
Hello Sven,

I just noticed that this seems to be "Browser dependent".
When I open Thruk in my "normal" browser (FireFox 102.12.0esr (64-bit) on Linux) it behaves like I described in this issue, when I try my "failback" browser (Chromium 113.0.5672.126 (Official Build) (64-bit)) it works as before.

**Comment by dan-m-joh** [comment]
Update 2...

I think this is something in my local environment.
The "error" appeared in my "development/test" environment. After installing 3.06-2 in the production environment I was pleased to see that the problem **did not** manifest itself there.

As I said, this looks it something on my side, so you can close this case if you like.

Regards,
Dan

**Comment by sni** [comment]
thanks for the update, typical issues might come from setting graph_url or such things.
