### ISSUE TITLE
Trends: Custom period selection in timestamp format instead of date+time

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1288]
**Describe the bug**
in host and service trends the custom period selection is shown as timestamp and not datetime.
As I remember in Thruk v2 it was possible to select the datetime with a calendar popup by clicking on the calendar symbol. That's not possible anymore as well.

**Thruk Version**
Thruk 3.05.20230306 (OMD 5.11~2023-03-06-labs-edition)

**To Reproduce**
1. Go to Trends
2. Selet "Custom" in Report period
3. see Start and End 

**Expected behavior**
A calendar popup is useful to select the correct date and time. Timestamp as the date format is not helpful

**Screenshots**
![image](https://github.com/sni/Thruk/assets/29919422/20b06170-d75a-4789-bbad-35f71022de9c)

**Comment by sni** [comment]
what page/url lead to this behaviour?

**Comment by kafos** [comment]
Hi sni,
host or service trends. For example:
https://demo.thruk.org/demo/thruk/cgi-bin/trends.cgi?host=Company+App

**Comment by sni** [comment]
thanks for reporting this issue, should be fine with the next release.
