### ISSUE TITLE
Schedule downtime for this host (and all services) not work

### ISSUE THREAD

**Issue by AlArtashir** [sni/Thruk#1289]
**Describe the bug**
When you click "Schedule downtime for this host (and all services)" it put in downtime only the host item and not the related services.

**Thruk Version**
3.06.2

**To Reproduce**
1. Go to service list
2. Click on any host
3. Click on Schedule downtime for this host (and all services) not work
4. See error in /var/log/thruk/thruk.log

**Screenshots**
![image](https://github.com/sni/Thruk/assets/75425095/454ea3db-9012-404e-bdce-23d5746e830c)
![image](https://github.com/sni/Thruk/assets/75425095/03191863-8b66-4407-8442-5a8f9e423ef9)

**Additional context**
It seems that new feature add spaces before command and not work.

**Comment by sni** [comment]
thanks for reporting this issue, should be fine with the next release.
