### ISSUE TITLE
 violation timeout when selecting / unselecting backend feed

### ISSUE THREAD

**Issue by bradymd** [sni/Thruk#1293]
**Describe the bug**
When I go into your thruk demo, if I select one of the backends, naemon or icinga2, I get this in developer tools:
[Violation] 'setTimeout' handler took 101msis.
And functionally the feed doesn't come back (change color from gray).
This happens to my site.  I'm in the process of migrating my naemon service to one I've just built on Rocky 9 and when I put the backends in I noticed this. You can unselect a feed, but don't get it back.

**Thruk Version**
Version of Thruk is 3.0.8

**To Reproduce**
Well I assumed it was me but then I saw its on your site too. But when I clear my cache  - chrome,firefox,edge - I can at least start again and see the backends.

**Expected behavior**
Well you normally can click to select, and click again to unselect.

**Screenshots**
If its something on my machine I do apologise. I work alone on this.

**Desktop (please complete the following information):**
I just have a Mac here
Chrome Version 114.0.5735.198 (Official Build) (x86_64)
Edge Version 114.0.1823.67 (Official build) (x86_64)
firefox  102.13.0esr (64-bit

**Additional context**

Best Regards.
Mark Brady

**Comment by sni** [comment]
Thanks for the report. I fixed this 30 minutes ago. Should be fine again tomorrow
