### ISSUE TITLE
Filter results with = and != all lowercase

### ISSUE THREAD

**Issue by lgmu** [sni/Thruk#1295]
**Describe the bug**
Search results are all lowercase when using = or != with ~ it works as expected

**Thruk Version**
Thruk 3.08.2

**To Reproduce**
1. Search like shown on the screenshot

**Expected behavior**
Case sensitive

**Screenshots**
![image](https://github.com/sni/Thruk/assets/80966566/e2849f97-f180-4c11-91fb-84329bdb6f0b)

**Desktop (please complete the following information):**
Chrome

**Comment by sni** [comment]
thanks, will be fine with the next release.
