### ISSUE TITLE
Bug when using more than 2 "OR" with *** syntax (thruk r /services)

### ISSUE THREAD

**Issue by lgmu** [sni/Thruk#1296]
This works fine:

![image](https://github.com/sni/Thruk/assets/80966566/ba78c9b6-fae4-4108-99a4-77fb3e64d574)

This doesn't work, because the filter is wrong:
![image](https://github.com/sni/Thruk/assets/80966566/d0c6c455-685b-412c-bdc1-02514bb02111)

**Comment by sni** [comment]
thanks, will be fine with the next release.
