### ISSUE TITLE
Grafana image in SLA reports

### ISSUE THREAD

**Issue by marcom29** [sni/Thruk#1297]
Hello, I have installed OMD and I want to be able to generate reports with the graphs of grafana, I have already reviewed tutorials, manuals but I have not been able to see the graphs of grafana in my report. I do see the metrics when I select the service. But not when generating the report, could you tell me what should I do to get the graphs of Grafana in my report?
Greetings.

![255076434-beffe6c9-8dfd-434d-9c91-e11e2057debc](https://github.com/sni/Thruk/assets/55645181/f014d2ba-67d2-45f6-9e9a-082dae6a654a)

**Comment by sni** [comment]
you could run the report with verbose mode. ex.: `thruk report 1 -vvv` (depending on which number the report has)

**Comment by marcom29** [comment]
Thank you very much for the answer, is there any page where I can find all the thruk commands?

Greetings.

**Comment by sni** [comment]
`thruk` without any arguments should list all commands, afaik there is no dedicated page listing them all.

**Comment by marcom29** [comment]
Thank you very much I managed to place the graph metrics in the reports, I just have a doubt, when generating the report the graph is displayed on the next page, which leaves a big blank space in the SLA report.

![imagen](https://github.com/sni/Thruk/assets/55645181/acba9051-bb58-4bff-99df-ffa974eeb9c4)

Is there any way that the graph can be placed on the first page of the report?

**Comment by sni** [comment]
Each page is in a <div> and it has a limited size. The easiest way to develop report layout is
to use this link: `.../reports2.cgi?refreshreport=1&html=1&report=<nr>` which generates the
report as html so you can use the inspector and developer tools of your browser.

**Comment by marcom29** [comment]
Thank you very much I managed to see the grafana and pnp4nagios metrics in the reports.
