### ISSUE TITLE
Upgrading to 3.08.3-12419.1 leads to a Livestatus error on Landing Page

### ISSUE THREAD

**Issue by riton** [sni/Thruk#1299]
**Describe the bug**
On a CentOS 7 server, we've upgraded our `thuk` package from `3.08.2-12404.1` to ` 3.08.3-12419.1`.

Many of our users now see a `No Backend available: Naemon    : OK     ERROR: 400: The request contains an invalid header. - cannot create filter on table hosts (addr: /var/cache/naemon/live)` error on the _Landing Page_ (see _ScreenShot_ )

I say _Many of our users_ , cause they don't all face this error and we still don't understand why.

**Thruk Version**

```
$ rpm -qa '*thruk*' | sort
libthruk-2.44.2-0.x86_64
naemon-thruk-1.3.0-0.noarch
thruk-3.08.3-12419.1.x86_64
thruk-base-3.08.3-12419.1.x86_64
thruk-plugin-reporting-3.08.3-12419.1.x86_64
```

```
$ rpm -qa '*naemon*' | sort
libnaemon-1.3.0-0.x86_64
naemon-core-1.3.0-0.x86_64
naemon-livestatus-1.3.0-0.x86_64
naemon-thruk-1.3.0-0.noarch
```

```
$ puppet facts | jq .os
{
  "name": "CentOS",
  "release": {
    "full": "7.9.2009",
    "major": "7",
    "minor": "9"
  },
  "distro": {
    "release": {
      "full": "7.9.2009",
      "major": "7",
      "minor": "9"
    },
    "codename": "Core",
    "id": "CentOS",
    "description": "CentOS Linux release 7.9.2009 (Core)",
    "specification": ":core-4.1-amd64:core-4.1-noarch"
  },
  "family": "RedHat",
  "architecture": "x86_64",
  "hardware": "x86_64",
  "selinux": {
    "enabled": false
  }
}
```

**To Reproduce**

Upgrade to latest `3.08.3-12419.1` version from `3.08.2-12404.1`.

A simple `yum downgrade thruk thruk-base thruk-plugin-reporting` to revert to `3.08.2-12404.1` solves the problem for all our users.

**Expected behavior**

The actual _Landing Page_ as we're used to :-)

**Screenshots**

![no_backend_landing_page](https://github.com/sni/Thruk/assets/553730/f1561511-c684-4314-a3ad-8688ac4029d4)

**Desktop (please complete the following information):**
The problem can be reproduced with **all** browsers, even in _private browsing mode_.

**Additional context**

I'm not sure that this is related, bu I see a `livestatus` query such as:

```
GET hosts
Columns: name groups
Filter: >= = REDACTED_FIRSTNAME REDACTED_LASTNAME
Filter: groups != 
OutputFormat: wrapped_json
ResponseHeader: fixed16
```

when a user that faces the problem tries to load the _Landing Page_ . The `groups !=` _Filter_ seems strange, isn't it ?

We do have a _test infrastructure_ than can easily reproduce the problem, feel free to ask us extra information.

Regards

Rémi

**Comment by sni** [comment]
The groups filter is fine, this simply filters out all hosts without any group. The line above seems wrong. There should be something before the `>=`.
