### ISSUE TITLE
[reporting plugin] Availability report for servicegroup from icinga2 only presents one service

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#1300]
**Describe the bug**
When generating availability report from icinga2, i only get one service in report.

Same happens if i add all services by hand to report and make service-based report.

**Thruk Version**
3.08.2 , 3.08.3

**To Reproduce**
Run availability report on servicegroup or selected services.

**Expected behavior**
It lists entire servicegroup

**Additional context**
If there is more info needed, i'll provide it. I recently updated icinga2 to 2.14, perhaps that is the problem ?

**Comment by yoshi314** [comment]
It seems it was a permissions issue in thruk itself - i've recently enabled SAML auth in apache2 and user mappings have changed. 

Newer thruk version displayed it was a permissions issue in raport, so that gave me a hint towards the problem.

**Comment by sni** [comment]
glad you got it working, thanks for the feedback
