### ISSUE TITLE
THRUK v3.02 : escape_html_tags in thruk_local.conf not used

### ISSUE THREAD

**Issue by jbeaujour** [sni/Thruk#1306]
Hello

**Describe the bug**
the parameter escape_html_tags=0 in thruk_local.conf is not used 
Thruk Documentation for cgi.cfg :
"All config values here, except the roles and authentication related can be set in the thruk_local.conf as well."

**Thruk Version**
v3.02

**To Reproduce**
```
cgi.cfg => escape_html_tags=1
thruk_local.conf => escape_html_tags=0
```

Create a comment with html code like :
```<a target='_blank' style='color:black' href='https://xxxxxxxxxxx.com /nav_to.do?uri=incident.do?sysparm_query=number=2837332'>Number 2837332</a> (14-09-23 12:08)```

**Expected behavior**
only `Number 2837332` should appear and clickable

**Comment by sni** [comment]
the cgi.cfg always beats the thruk_local.conf. So yes, you can set it in both files, but the cgi.cfg wins if it is set in both files.

**Comment by jbeaujour** [comment]
we don't want to modify the cgi.cfg which is overwritten with each version, right?

**Comment by sni** [comment]
if that's the case, then this is a bug. The cgi.cfg should be handled as config file and only be overwritten if it hasn't been modified.

**Comment by jbeaujour** [comment]
Okay, I'm going to test this case:
blank install
modification of cgi.cfg
version update

otherwise if it is always cgi.cfg which wins, what is the point of being able to put these parameters in thruk_local.conf?

**Comment by sni** [comment]
you are totally right, it makes no sense here. The idea was more for other list settings which can be extended from multiple files now.
