### ISSUE TITLE
Unable to use !~ or != with servicegroups on icinga2 backend.

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#1309]
**Describe the bug**
When i try to filter servicegroups with !~ or != i get an error: 

e.g for ~ servicegroup1 and !~ servicegroup2 I get the following : 

```
icinga2   : OK     ERROR: 452: internal livestatus error - Error: Invalid operator for column 'groups': !>= (expected '>=' or '='). (addr: 192.168.16.21:6557)
```

**Thruk Version**
3.08.3

Icinga2 r2.14.0-1 (official debian packages)

**Comment by sni** [comment]
the Icinga2 livestatus is pretry limited and shows different behaviour here and there, that's why i usually advice to use LMD in between.
See https://thruk.org/documentation/lmd.html for some details.
