### ISSUE TITLE
Calendar buttons in Service or Host Availability Report for Report period "Custom" do not work

### ISSUE THREAD

**Issue by Mac-Dui** [sni/Thruk#1310]
If you click on the calendar buttons in the Service or Host Availability Report (when choosing Report period "Custom") then nothing happens. One would expect a popup calendar.

**Thruk Version**
Tested with Thruk Thruk 3.04 (OMD 5.10-labs-edition and 5.20-labs-edition).

**To Reproduce**
While on the host details page click on "View Availability Report For This Host". Then choose "Custom" under "Report period". "Start" and "End" fields appear with a calendar image next to it. However nothing happens when clicking on it.

**Expected behavior**
One would expect a popup calendar.

**Screenshots**
![Host-Availability-Report](https://github.com/sni/Thruk/assets/95912103/e15bc5b0-11ff-4bca-aaac-b4e372ac18f3)

**Desktop (please complete the following information):**
Tested with Google Chrome Version 117.0.5938.92

**Comment by sni** [comment]
seems to be fixed meanwhile.
