### ISSUE TITLE
Removing Grid from Menu doesn't work

### ISSUE THREAD

**Issue by gevadeka** [sni/Thruk#1314]
**Describe the bug**
Removing Host Groups or Service Groups Grid view doesn't work.
Removing Host Groups or Service Groups Summary view removes both Summary and Grid view

**Thruk Version**
Thruk 3.08.3 / OMD 5.20

**To Reproduce**
In menu_local.conf, this:

`remove_item('Current Status', 'Host Groups', 'Grid');`

will not remove the Grid view on Host Groups
 

In menu_local.conf, this:

`remove_item('Current Status', 'Service Groups', 'Summary');`

will remove both the Grid and Summary view on Service Groups

**Screenshots**
![image](https://github.com/sni/Thruk/assets/149672946/dda0bf21-3714-4ac0-aeef-349ddf790eca)
Above screenshot shows the result of this menu_local.conf:
```
do $ENV{'OMD_ROOT'}.'/share/thruk/menu.conf';
remove_item('Reports', 'Availability');
remove_item('Current Status', 'Host Groups', 'Grid');
remove_item('Current Status', 'Service Groups', 'Summary');

```

**Desktop (please complete the following information):**
 - Browser Edge (Chromium)
 - Version 116

**Comment by sni** [comment]
Technically the "Grid" item was a sub element of "Summary". So if you remove "Summary", the "Grid" was removed along with the "Summary".

Anyway, it should work of course. Fixed in the next release...
