### ISSUE TITLE
Issue after session timeout

### ISSUE THREAD

**Issue by tomaszdubiel18** [sni/Thruk#1315]
**Describe the bug**
I have Thruk opened in multiple tabs of a browser

**Thruk Version**
3.08.3

**To Reproduce**
Log in.
After session (cookie) time out, after getting to the main webpage (before log in) in the address it is added:
thruk/cgi-bin/login.cgi?nocookie&thruk/#main.html
Try to log in. Then I want to refresh the other Thruk tabs (with some services view for example). Then the session is reset and I need to log in again. ONLY if I enter the main Thruk webpage, Thruk recognizes the session, but when I refresh URL of some exact part of the Thruk, then session gets reset. I need to re sign in in every tab or I need to get to them from main Thruk webpage.

**Expected behavior**
I log in once and I don't need to log in anymore.

**Desktop (please complete the following information):**
 - Firefox 119.0

**Comment by sni** [comment]
what was the URL before the session timeout?

**Comment by tomaszdubiel18** [comment]
I think this doesn't matter, because it is the issue for all tabs and I have multiple different URLs, but for example:
thruk/cgi-bin/minemap.cgi
thruk/cgi-bin/status.cgi?host=<some_host>&style=detail&complex=&dfl_columns=host_name%2Cdescription%2Cstate%2Cplugin_output%2Clast_check

**Comment by tomaszdubiel18** [comment]
Any new info? This bug is annoying.

**Comment by sni** [comment]
I cannot reproduce this. Could you upgrade to the lastest release and make sure you have the latest apache configuration for thruk. Sometimes the apache config does not get updated correctly and is available a .rpmnew or dpkg-new file.

**Comment by tomaszdubiel18** [comment]
This is very easily reproducible:
thruk/cgi-bin/login.cgi?nocookie&thruk/#main.html
after successful login:
thruk/cgi-bin/main.cgi
I open any window in new tab, for example mine map:
thruk/cgi-bin/minemap.cgi
in first tab I logout and after logout:
thruk/cgi-bin/login.cgi
I refresh second tab and address becomes:
thruk/cgi-bin/login.cgi?nocookie&thruk/cgi-bin/minemap.cgi
in first tab I log in again:
address of first tab becomes:
thruk/cgi-bin/main.cgi
I refresh second tab. I still am on login page and this refresh caused logout in first tab

**Comment by tomaszdubiel18** [comment]
We have the latest Thruk, v3.16.

**Comment by sni** [comment]
i see, that's expected behaviour. Whenever you open the login page, all existing cookies will be removed.
But i guess this could be changed in the future.

**Comment by tomaszdubiel18** [comment]
It needs to be corrected. You see - I have a set of multiple Thruk tabs. I work one day, at the end of the day I leave it and come back again the next day. This way I have to login in every tab.
That's not normal.

**Comment by tomaszdubiel18** [comment]
I don't refresh those tabs on my own. They refresh themselves, they catch expired session and either I have to manually open those tabs from the main page or I have to relogin in every tab.

**Comment by sni** [comment]
i agree, this should be changed.

**Comment by sni** [comment]
should be fine with the next release, thanks.
