### ISSUE TITLE
Custom colums not loaded correctly on problems page

### ISSUE THREAD

**Issue by dhoffend** [sni/Thruk#1319]
**Describe the bug**

Looks like when saving custom colums/order on the combined problems page, those settings aren't correctly loaded when reopening the page.

**Thruk Version**

Version of Thruk 3.0.0 / OMD 5.00
I haven't checked it with newer versions yet, but the changelog doesn't mention custom column settings fixes.

**To Reproduce**

Prerequirement:
cleanup/delete custom server side settings for your user

Steps:
To directly to the Problems page, add column "comments" to to the Service Problems in the Combined Problems view. Hit Apply + Hit "use as my defaults view". The view gets updated, but as soon as you reload the page or restart the browser the selected column doesn't appear on screen.

Background:
When looking at the stored server side settings, the settings are correctly stored for the "ovr" key but not loaded.

Workaround:
Go to Services Page. Change + Save Columns/Order (settings get saved as "svc" key), go back to the Combined Problems page columns are loaded from svc key.

**Expected behavior**

Correct saved settings are loaded.

**Desktop (please complete the following information):**
 - Browse: Firefox
 - Version 115.5.0esr

**Comment by sni** [comment]
thanks for reporting this, i'd say this is fixed with the last release.
