### ISSUE TITLE
Thruk 2.48 won't load on Fedora 39

### ISSUE THREAD

**Issue by Yu6936** [sni/Thruk#1324]
**Describe the bug**
After upgrading from OS Fedora 36 to Fedora 39, my Thruk 2.48 instance is reporting Perl conflict error.   Thruk is not coming up.
 
 Apache httpd server log error:
 tail -f /var/log/httpd/error_log
Can't load '/usr/lib64/thruk/perl5/x86_64-linux-thread-multi/auto/Cpanel/JSON/XS/XS.so' for module Cpanel::JSON::XS: /usr/lib64/thruk/perl5/x86_64-linux-thread-multi/auto/Cpanel/JSON/XS/XS.so: undefined symbol: Perl_newRV_noinc at /usr/share/perl5/XSLoader.pm line 94.
 at /usr/lib64/thruk/perl5/x86_64-linux-thread-multi/Cpanel/JSON/XS.pm line 2274.
Compilation failed in require at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 16.
BEGIN failed--compilation aborted at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 16.
Compilation failed in require at /usr/share/thruk/lib/Thruk/Config.pm line 11.
BEGIN failed--compilation aborted at /usr/share/thruk/lib/Thruk/Config.pm line 11.
Compilation failed in require at /usr/share/thruk/script/thruk_fastcgi.pl line 15.
BEGIN failed--compilation aborted at /usr/share/thruk/script/thruk_fastcgi.pl line 15.

**Thruk Version**
Thruk 2.48

**Comment by Yu6936** [comment]
Hi Sven,  


I was thinking it would probably be best to upgraded to Thruk 3.10 but I have upgraded to the latest Fedora 39. 
From here https://build.opensuse.org/project/show/home:naemon 

I don't see a tested Thruk version 3.10  for Fedora 39 as of yet. Anyways, thank you for all your work.  Let me know what you think I should do at this point.

**Comment by sni** [comment]
Yeah, you cannot use the version from fedora 36 on fedora 39. I just enabled builds for fedora 39, so the repository on OBS should soon contain packages.

**Comment by Yu6936** [comment]
Sven,

  You are the man!  Thanks for the quick turnaround.  My Fedora 39/Thruk 3.10 works!  I appreciated all your work.
