### ISSUE TITLE
Actions Menus not working with  OAuth - "The requested URL was not found on this server."

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1325]
**Describe the bug**
Login of Thruk is used with OAuth - after clicking on a action menu item from my action menu I get 
![image](https://github.com/sni/Thruk/assets/29919422/196a1f73-b861-41b0-aade-769453bae262)

The URL then is: https://DOMAIN/SITE/thruk/cgi-bin/ACTION_MENU_NAME

Thruk 3.10
OMD 5.21~2023-11-08-labs-edition

**Comment by sni** [comment]
how is this action menu configured?

**Comment by kafos** [comment]
the menu is in js format:
function menu(cfg) {
  return({
      "icon":"../themes/{{theme}}/images/dropdown.png",
      "title": "action",
      "menu":[{
          "icon":"fa-toggle-on",
          "label":"Switch ON",
          "action":"screen_on"
        }

    ]
    }
  )
}

and the configurations:

<action_menu_items>
    host_menu             = $USER4$/etc/thruk/action_menus/host_menu.js
</action_menu_items>


<action_menu_actions>
    screen_on       = $USER1$/check_by_ssh/check_by_ssh COMMAND...
</action_menu_actions>

<action_menu_apply>
    host_menu    = .*;$             # matches all hosts only
</action_menu_apply>
