### ISSUE TITLE
Error nagios core 4.5.0

### ISSUE THREAD

**Issue by sistemmsn** [sni/Thruk#1329]
**Describe the bug**

**Thruk Version**
Version of Thruk: 3.10

**To Reproduce**
After restarting the Nagios service several times it detects it, but when I want to save it cycles, this is happening to me in version 4.5.0, but in 4.4.14 it works without problems

**Screenshots**
![image](https://github.com/sni/Thruk/assets/38023703/d519684a-d8b1-4421-a453-e801e19423a8)
![image](https://github.com/sni/Thruk/assets/38023703/869240f8-23d3-4677-ace8-e8b539d3af30)
![image](https://github.com/sni/Thruk/assets/38023703/30f7fe11-13ee-4307-8feb-8a4690c8784a)
![image](https://github.com/sni/Thruk/assets/38023703/b7b17a66-d08a-4280-8559-73e1be128eec)
![image](https://github.com/sni/Thruk/assets/38023703/2cc79d7a-bbfd-4425-bd00-c5c36d05d5b1)

**Desktop (please complete the following information):**
 - Browser Edge
 - Version Versión 120.0.2210.77 (Compilación oficial) (64 bits)

**Comment by FoUStep** [comment]
I have the same issue, and the issue also occurs with Thruk v.3.12.

It doesn't look like a permission issue, reverting back to an older nagios version works and I even played with permissions (777 to the maximum) does not make a difference on live, the folder or the entire structure.

**Comment by sni** [comment]
Is there anything in Nagios livestatus log? "failed to connect" basically just means the livestatus socket does not respond.

**Comment by FoUStep** [comment]
> Is there anything in Nagios livestatus log? "failed to connect" basically just means the livestatus socket does not respond.

_/usr/local/nagios/var/livestatus.log_
`2024-01-29 13:21:33 deinitializing`
`2024-01-29 13:21:33 Waiting for main to terminate...`
`2024-01-29 13:21:33 Waiting for client threads to terminate...`
`2024-01-29 13:21:33 Logfile cache: flushing complete cache.`

_/usr/local/nagios/var/nagios.log_
`[1706530893] Nagios 4.5.0 starting... (PID=868161)`
`[1706530893] Local time is Mon Jan 29 13:21:33 CET 2024`
`[1706530893] LOG VERSION: 2.0`
`[1706530893] qh: Socket '/usr/local/nagios/var/rw/nagios.qh' successfully initialized`
`[1706530893] qh: core query handler registered`
`[1706530893] qh: echo service query handler registered`
`[1706530893] qh: help for the query handler registered`
`[1706530893] wproc: Successfully registered manager as @wproc with query handler`
`[1706530893] wproc: Registry request: name=Core Worker 868165;pid=868165`
`[1706530893] wproc: Registry request: name=Core Worker 868164;pid=868164`
`[1706530893] wproc: Registry request: name=Core Worker 868163;pid=868163`
`[1706530893] wproc: Registry request: name=Core Worker 868162;pid=868162`
`[1706530893] livestatus: Livestatus 1.2.8p11 by Mathias Kettner. Socket: '/usr/local/nagios/var/rw/live'`
`[1706530893] livestatus: Please visit us at http://mathias-kettner.de/`
`[1706530893] livestatus: Hint: please try out OMD - the Open Monitoring Distribution`
`[1706530893] livestatus: Please visit OMD at http://omdistro.org`
`[1706530893] livestatus: Finished initialization. Further log messages go to /usr/local/nagios/var/livestatus.log`
`[1706530893] Event broker module '/usr/local/lib/mk-livestatus/livestatus.o' initialized successfully.`

All seems okay, Nagios 4.5.0 itself works, but Thruk cannot connect.

**Comment by FoUStep** [comment]
Still the same issue with Nagios Core 4.5.1 and the latest Thruk version 3.14.2.

> 491: failed to connect - failed to connect to /usr/local/nagios/var/rw/live: Connection refused.

The permissions and Thruk work fine if I downgrade to 4.4.14.

**Comment by sni** [comment]
no idea tbh, i am not closely following the nagios project anymore. So if it works with an old version of that, i'd assume the issue is somewhere in nagios itself.

**Comment by sistemmsn** [comment]
Hello, how are you, apparently it is a nagios bug with the livestatus compilation, I am closing the problem because in the end it is from nagios, thank you

Annex the temporary solution of nagios
https://support.nagios.com/forum/viewtopic.php?t=75312
