### ISSUE TITLE
Toggle Site Visibility window not showing scrollbars if there is more monitoring servers than fit current window

### ISSUE THREAD

**Issue by vesajylha** [sni/Thruk#1330]
**Describe the bug**
Toggle Site Visibility window not showing scrollbars if there is more monitoring servers than fit window when thruk.conf sitepanel=auto is selected. 

**Thruk Version**
3.10

**To Reproduce**
1. Click on 'xx Up / xx Disabled / xx Down' button
2. 'Toggle Site Visibility' window doesnt' show scrollbars if there is more servers than fit window.

**Expected behavior**
Toggle Site Visibility window should show scrollbars when needed if sitepanel=auto setting is enabled.

**Comment by sni** [comment]
could you add a screenshot to get an idea of what is wrong?

**Comment by teanva** [comment]
Thruk v3.14.2:

sitepanel=tree

![SitePanelTree](https://github.com/sni/Thruk/assets/117991310/2c2479f8-76ac-4c39-b364-4ce68b8ae00e)

**Comment by sni** [comment]
i see. Do you want to have them like that? Otherwise you could group these backends into sections which would make the list more organized.

**Comment by teanva** [comment]
Seems that sections would not help in our case. If tree sitepanel is used then scrollbars would be needed to be able to see all backends.

![Section](https://github.com/sni/Thruk/assets/117991310/771edd4e-a08c-4847-b592-033a8f9e1ea7)

**Comment by sni** [comment]
it's hard to figure out what you are doing based on these mostly black screenscrots. I've seen
installations with over 300 connected backends without issues.
What i mean when i say use sections, is to create multi-level groups of backends, ex.:
`section europe/germany` would create a top level collapsable folder `europe` with a sub folder `germany`. That way you would not have to scroll that much. The other advantage is you can toggle and select backends based on their section all at once.

**Comment by teanva** [comment]
In our case it is a bit challenging to divide backends to multi-level sections.

Anyway, point in previous comment was that scroll bars would be helpful also with sections since limited amount of top level sections fit to window. 

![Section2](https://github.com/sni/Thruk/assets/117991310/ee60d939-ae70-44ed-ba69-c3bd15b14939)

**Comment by sni** [comment]
i see. Sure scrollbars should help here. A side note, those screenshots show the "collapsed" sitepanel, not the tree site panel.
The tree sitepanel (with sections) looks like this:
<img width="1126" alt="Screenshot 2024-04-18 at 11 10 07" src="https://github.com/sni/Thruk/assets/150844/4767c8a3-3f59-4cc8-9d72-49f0d10ea32b">

**Comment by teanva** [comment]
Yes, you are right. Different machine and I forgot to check the sitepanel configuration.

I think that we can fit top level sections to window with tree site panel setting.
