### ISSUE TITLE
Config-Tool state!=stat ends up in splitting the arguments

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1332]
**Describe the bug**
As an example I created a service check with check_nsc_web with own warning definitions. 
definition like :
<img width="818" alt="image" src="https://github.com/sni/Thruk/assets/29919422/4fdad9f5-ee34-4976-8e04-2cd4b7e47b76">

is ending up in splitting the 'warn=state!=started' because of the exclamation mark. Single quotes for this warning definitions has no effects. Saving ends up in:
![image](https://github.com/sni/Thruk/assets/29919422/510cae43-e7f0-47fa-9dd9-4194ee6330d3)

**Thruk Version**
![image](https://github.com/sni/Thruk/assets/29919422/b8deeb70-3c68-4870-b16a-38306dd695ce)

backslash before exclamation mark does not work either

**Comment by sni** [comment]
i'd say it's better to use a single $ARG1$ and put everything in there. Otherwise you would have to create a new command for every combination or arguments.
