### ISSUE TITLE
Problem with reporting, does not generate reports

### ISSUE THREAD

**Issue by r4f4m4r** [sni/Thruk#1338]
Problem with reporting, does not generate reports

**Thruk Version**
this appears in 3.12 and 3.10 

It appears on both debian 12 and rocky 9, I tried several systems before reporting it.

If you do a clean install, the first thing that appears is a puppeter problem if you are going to generate a report. i have followed the steps to solve them as it comes in the installation web, (although this was not necessary in previous versions).

When I install puppeter what appears when I try to generate a report is:

![imagen](https://github.com/sni/Thruk/assets/33825719/e27f3bb6-36ec-4482-9401-680c802a1669)

I have tried to install chrome on the server itself, but the result is the same.

**Comment by sni** [comment]
did you use the `puppet_installer.sh` script from thruk or did you install puppeteer manually?

**Comment by r4f4m4r** [comment]
I did it with the script, and that way an error that I had before disappears, in the main screen of report saying that the puppeter is not there, this capture I don't have it because that failure no longer appears to me.

**Comment by r4f4m4r** [comment]
I had another server and did not remember.

This is the error that appears initially, before executing the script:

![imagen](https://github.com/sni/Thruk/assets/33825719/fa78ada3-f515-4c71-9a80-d6d4d2d42a95)


when you run the scipt it disappears, but then remains the one I have reported in the issue.

**Comment by sistemmsn** [comment]
> I had another server and did not remember.
> 
> This is the error that appears initially, before executing the script:
> 
> ![imagen](https://private-user-images.githubusercontent.com/33825719/305998334-fa78ada3-f515-4c71-9a80-d6d4d2d42a95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NzE1NTYsIm5iZiI6MTcwODQ3MTI1NiwicGF0aCI6Ii8zMzgyNTcxOS8zMDU5OTgzMzQtZmE3OGFkYTMtZjUxNS00YzcxLTlhODAtZDZkNGQyZDQyYTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIzMjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZmJjZGM3NzVmNmVhYTA2MDEwNjQzNWZiOTM3YWI4ODUzZDZhZWI2ODA5Zjk1ZTkwOTBlYjkxMTFkNGE5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Fp1DWlAaF8oBBQ5P12fVe9mMsyxJ6eMVAK9njI5WAU)
> 
> when you run the scipt it disappears, but then remains the one I have reported in the issue.

This is an error due to puppeteer in its recent versions, downgrade to version 21.11.0 edit the script on line 74

**Comment by sni** [comment]
ah, indeed, i forgot about that. The newest installer sticks to version 21.11.0 already:
https://github.com/sni/Thruk/blob/master/script/install_puppeteer.sh#L11

**Comment by r4f4m4r** [comment]
With that modification, the script works great.

Thanks for everything to both of you!
