### ISSUE TITLE
"unhandled services" view shows only services with active check enabled 

### ISSUE THREAD

**Issue by mlausch** [sni/Thruk#1339]
**Describe the bug**
The "Unhandled Services" view linked in the menu and from the main dashboard shows only services with "active checks enabled". I don't see a reason why services with only passive checks should be filtered out.

**Thruk Version**
3.12

**To Reproduce**
1a. Menu -> Problems -> Unhandled Services
1b. Homeview -> Klick on Panel Title "Unhandled Service Problems" 
2. Only unhandled services with active check enabled are displayed

**Expected behavior**
All unhandled services (not acked and not in downtime) should be shown regardless of active checks enabled or not

**Screenshots**
![image](https://github.com/sni/Thruk/assets/7404899/6d5bc2e6-30ed-414d-9685-2e982d777202)

**Additional context**
The URL to the view is currently 
thruk/cgi-bin/status.cgi?host=all&type=detail&hostprops=10&hoststatustypes=3&serviceprops=42&servicestatustypes=28
should be 
thruk/cgi-bin/status.cgi?host=all&type=detail&hostprops=10&hoststatustypes=3&serviceprops=10&servicestatustypes=28

**Comment by sni** [comment]
i agree, i guess that was for "historical" reasons...

**Comment by sni** [comment]
will be changed with the next release.
