### ISSUE TITLE
Expanded check command box not present anymore

### ISSUE THREAD

**Issue by garadar** [sni/Thruk#1342]
**Describe the bug**
Since updating thruk, despite activating show_full_commandline_source  I can no longer see the expand command on service page.  The box where the command was printed has disappeared.

**Thruk Version**
thruk v3.10 and thruk v3.12

**To Reproduce**
Connect on Thruk and view a check, the box "check_command" a the bottom of page is not here.

**Screenshots**
![image](https://github.com/sni/Thruk/assets/11789709/0c279cf3-469a-489e-931d-b25f36bb1ea7)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 122.0.6261.95

Any Ideas ?

**Comment by sni** [comment]
`show_full_commandline_source` only changes the source of the command line, it does not change whether you are allowed to see it or not.
