### ISSUE TITLE
Possible Reflective xss vulnerability 

### ISSUE THREAD

**Issue by boxinegmbh** [sni/Thruk#1343]
**Describe the bug**
[ https://host-ip/thruk/cgi-bin/login.cgi?debug=alert(document.domain ]
Reflective xss vulnerability possible using debug

**Thruk Version**
3.12

**Expected behavior**
Is there a way to disable the debug behaviour in the configuration?

**Screenshots**
<img width="2043" alt="image(1)" src="https://github.com/sni/Thruk/assets/57713631/d48f1e8f-ff5a-4fe2-a617-33f8d6c731e6">
<img width="1254" alt="image(2)" src="https://github.com/sni/Thruk/assets/57713631/9d6a2a7b-be1b-4e9e-8462-070e907672f6">

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 123.0.1 (64-bit)

**Comment by sni** [comment]
thanks for reporting this, should be fixed with the commit https://github.com/sni/Thruk/commit/d9979d9f4a0189d0731a732589806c871b57c9a2.
Please report security related issues here https://github.com/sni/Thruk/security or by mail to security (at) thruk.org
