### ISSUE TITLE
while debugging, Thruk/Utils/OAuth.pm 5.30 shows only HTTP::Response=HASH(...)' instead of content.

### ISSUE THREAD

**Issue by pbiering** [sni/Thruk#1346]
./versions/5.30-labs-edition/share/thruk/lib/Thruk/Utils/OAuth.pm

```
{ res => $res }
```

Can this be enhanced to display the hash content instead?

This would be also helpful for this case: https://github.com/sni/Thruk/issues/1287

**Comment by sni** [comment]
that was the idea initially. Should be working again...
