### ISSUE TITLE
Quick operation "disable eventhandler" does not offer a comment field

### ISSUE THREAD

**Issue by lausser** [sni/Thruk#1352]
**Describe the bug**
Disabling event handlers is not possible through quick commands, because a comment is required but there is no way to enter a comment.

**Thruk Version**
Thruk 3.15.20240409
OMD 5.31-2024-04-09

**To Reproduce**
1. Open web page "Service Status Details"
2. Click on a service to highlight it and make the "Quick Commands" pop up in the right upper corner
3. Select "Disable Eventhandler" from the Command dropdown
4. Unlike with "Disable notifications/active checks" there is no comment field.
5. Submit the command, then there is an error message "Comment is a required field"

**Expected behavior**
Either a comment should not be mandatory when disabling event handlers or a comment text input should be offered.

**Comment by sni** [comment]
should be fine again tomorrow
