### ISSUE TITLE
Excel Export doesn't contain characters like ä ö ü

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1355]
**Describe the bug**
By exporting to excel, characters like ä ö ü are missing. On hostnames, status information or comments
Thruk 3.13.20240307
OMD 5.31~2024-03-07-labs-edition

**To Reproduce**
1. Create a comment on a host or Service
2. create an excel export with "Export to Excel" and choose the columns

**Comment by sni** [comment]
thanks, should be fine again with the next release
