### ISSUE TITLE
Config Tool: Dependency -> Hostdepenceny -> dependent_host_name: List Wizzard?

### ISSUE THREAD

**Issue by pbiering** [sni/Thruk#1358]
Thruk 3.12 from OMD 5.30 / Config Tool:

Would it be possible to improve the Hostdependency config by enabling the List Wizzard on "dependent_host_name" similar to Service -> host_name?

Potentially this can be enabled on more where useful and comma separated list is permitted.

Thank you very much!

**Comment by sni** [comment]
thanks for the idea. Enabled the wizard for host- and service-dependencies.
