### ISSUE TITLE
Invalid URL in tactical view -> service notification disabled

### ISSUE THREAD

**Issue by az-reno** [sni/Thruk#1366]
In the tactical view, the link to service with "notification disabled" is invalid.

File templates/tac.tt:

`<a class="itemblock unimportantProblem" href='[% uri_with(c, { _page => "status.cgi", style => "detail", servicveprops => 4096 }) %]'>[% service_stats.notifications_disabled %] Services Disabled</a>`

It should be serviceprops instead of servicveprops

** Thruk version **
git main

**Comment by sni** [comment]
fixed, thanks for reporting this.
