### ISSUE TITLE
Bug: Rescheduling a check changes URL

### ISSUE THREAD

**Issue by lgmu** [sni/Thruk#1368]
If you reschedule a check on /extinfo.cgi?type=2 it changes the URL as shown below:

Before: ... &service=Service with spaces&backend=3ed9
After: ... &service=Service+with+spaces&backend=3ed9

If you press "Back" in your browser after rescheduling a check, you always have to press it twice, which can be quite annoying.

Thanks.

**Comment by sni** [comment]
thanks, fixed with the next release
