### ISSUE TITLE
Dynamic Business Process title

### ISSUE THREAD

**Issue by twproject** [sni/Thruk#1369]
**Is your feature request related to a problem? Please describe.**
I'm using panorama to display some BP to a big screen but all BP have a static title "Business Process"

**Describe the solution you'd like**
I suggest to replace the static "Business Process" text with the BP name so everyone can quickly see the Business Process name

**Describe alternatives you've considered**
I didn't find any alternative

**Additional context**
![image](https://github.com/sni/Thruk/assets/7046065/62fa4dd0-f2ba-4c98-9b30-5392f55af9d4)

Thanks

**Comment by sni** [comment]
thanks, should be better with the next release.
