### ISSUE TITLE
Thruk -> mklivestatus -> Nagios 4.5.x

### ISSUE THREAD

**Issue by izghitu** [sni/Thruk#1373]
**Describe the bug**
Nagios dies whenever the Thruk interface is accessed.

**Thruk Version**
3.14.2-1

**To Reproduce**
1. Install Nagios 4.5.x
2. Set it up with mklivestatus 1.4.0p31
3. Install Thruk and configure it
4. Start nagios then open the Thruk web interface and the Nagios logs will suddenly say:
```
Caught SIGTERM, shutting down...
```

**Expected behavior**
I would expect it to work fine

**Additional context**
I am not sure if it's an incompatibility between Nagios 4.5.x and mklivestatus 1.4.0p31 but I can't find any way to download and install/compile latest mklivestatus so I am forced to use the older version. I tried mklivestatus 1.5.0 but for some reason that breaks the reporting in Thruk and it shows odd syntax errors when trying to generate reports.

Is there any better way to download/compile/setup mklivestatus latest version? Is there any "latest version" cause according to the website advertised on thruk.org mklivestatus is part of some other big software and the vendor does not provide any info about compiling and downloading mklivestatus specifically.

Please help.
Thanks

**Comment by sni** [comment]
Maybe this helps:
https://github.com/sni/Thruk/issues/1329#issuecomment-2155465977

**Comment by izghitu** [comment]
That did the trick. Thanks for the help.
