### ISSUE TITLE
How to escape "!" in service arguements?

### ISSUE THREAD

**Issue by heinowalther** [sni/Thruk#1381]
**Describe the bug**
I am trying to monitor a switch via the snmp check.  The community string includes a "!" which I am trying to pass as an arg via "$ARG1$" to the command...  But of cause this is interpreted as a separator...  I have of cause tried the most common options like \"community!\" and "community!!" and "community\!" etc. etc.  but nothing seems to work?

**Thruk Version**
3.12 OMD 5.30

**Comment by sni** [comment]
tbh, i would replace the community string with something that does not contain funny characters like quotes, dollar or exclamation marks.
If that is not an option, a common workaround is to define the "!" as user macro in your resource config and the use that macro.

ex.: resource.cfg
`$USER25$=!`

objects.cfg:
`check_command check_snmp!... -p community$USER25$ ...`

**Comment by heinowalther** [comment]
I agree, but sadly it is used as part of another system, so we cannot change the communitystring...
But I guess there is no escape char for this?
We will create a custom command for this then... it's not pretty.. I think we will just add the communitystring in the command, and not use the resource.cfg for this...    
Thanks for the fast response...

**Comment by sni** [comment]
have you tried `\!`

**Comment by heinowalther** [comment]
Yes I have, but then the config-check complains :-)
