### ISSUE TITLE
Custom variable values not visible in safari

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#1385]
**Describe the bug**
The table with custom variable names and values is not shown correctly. Names column is too big or value column too small.
**Thruk Version**
Thruk 3.17.20240806

**To Reproduce**
Create some custom variables

**Expected behavior**
Names and values should be visible correctly
**Screenshots**
![image](https://github.com/user-attachments/assets/164e7ffb-39dc-4a6f-a4ff-b84f1627d0c3)

**Desktop (please complete the following information):**
 - Safari Version 17.6

**Comment by sni** [comment]
should be fine with the next release
