### ISSUE TITLE
ambigous site selector "go" jumps to host and not to service

### ISSUE THREAD

**Issue by pbiering** [sni/Thruk#1391]
**Describe the bug**
Having a service monitored from more than one site and select this it shows a drop-down box -related to "ambigous site". Selecting a different site and push "go" will turn into display of the host and not update the service page.

**Thruk Version**
Thruk 3.16

**To Reproduce**

1. deploy 2 sites with equal configuration (e.g. georedundant "external" monitoring)
2. connect the 2 sites to a collector site
3. select a service
4. select specific site and push "go"

**Expected behavior**
Service information will be updated from related site

Current behavior is that it jumps to the host related page

**Comment by sni** [comment]
should be fine with the next release.
