### ISSUE TITLE
_OBFUSCATE_ME support same syntax as commandline_obfuscate_pattern

### ISSUE THREAD

**Issue by lgmu** [sni/Thruk#1394]
Hi!

It would be great if the _OBFUSCATE_ME macro in a service/host would also support the same syntax as here:
https://www.thruk.org/documentation/configuration.html#_commandline_obfuscate_pattern

Currently if you have passwords with special characters like $ or ^ that have a regex meaning, you need to escape them every time in order to be correctly obfuscated.

**Comment by sni** [comment]
https://github.com/sni/Thruk/commit/f896eebe151d2e861fa0544deb9538af111f8149
