### ISSUE TITLE
After Update:  AH: Unsafe URL with %3f URL rewritten without UnsafeAllow3F

### ISSUE THREAD

**Issue by Beatlor** [sni/Thruk#1395]
Since an update on Rocky Linux 9.4 and Apache Apache/2.4.57 Server Built Aug 5. 2024 

**Thruk Version**
OMD - Open Monitoring Distribution Version 5.40-labs-edition, Python version 3.9.18

**Failure**
I can no longer login and see in the OMD Error log 

**AH: Unsafe URL with %3f URL rewritten without UnsafeAllow3F**

For all accesses. No more Thruk Gui available all time getting "Forbidden error"

**Comment by sni** [comment]
You can install the latest OMD-Nightly, it has been fixed since a couple of weeks, but there is no stable OMD release yet.

**Comment by sni** [comment]
Can you double check to not only install the omd nightly but also update the site to this version?
