### ISSUE TITLE
Agents Thruk Plugin

### ISSUE THREAD

**Issue by sistemmsn** [sni/Thruk#1396]
**Describe the bug**
internal server error

Url: agents.cgi
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Version: 3.18
Release: September 10, 2024
OS Release: AlmaLinux release 8.10 (Cerulean Leopard)

Backends:
State | Program Version | Data Source Version
0 | 1.4.2 | Livestatus 1.4.2.source-naemon

Stacktrace:
failed to initialize objects of peer 328c5 at /etc/thruk/plugins//plugins-enabled/agents/lib/Thruk/Utils/Agents.pm line 354.

stacktrace from error controller at /usr/share/thruk/lib/Thruk.pm line 353.
Thruk::_dispatcher(HASH(0x56176f2b5260)) called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
Plack::Util::run_app(CODE(0x56176bc605d0), HASH(0x56176f2b5260)) called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 147
Plack::Handler::FCGI::run(Plack::Handler::FCGI=HASH(0x56176a31f3e8), CODE(0x56176bc605d0)) called at /usr/share/thruk/script/thruk_fastcgi.pl line 28

**Thruk Version**
Version of Thruk 3.18
Naemon 1.4.2 source code
 Livestatus 1.4.2.source-naemon 

**To Reproduce**
It doesn't always give me the error but when it does I have to reset the container

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 129.0.6668.90 (Build oficial) (64 bits)

**Additional context**
I've been trying the plugin but I've had a lot of issues with its integration to the thruk and its interface, then you mention that you can set default settings when using the agent plugin, which could be this, but it fails because I don't know how host settings are set, here I see only for services and I would also like to add oh that when it detects what OS version it is, add icons on the host

![image](https://github.com/user-attachments/assets/7ba3d068-cdc5-4fd1-8930-204373ff95ae)
![image](https://github.com/user-attachments/assets/f22ea761-70d9-4c28-b743-2bb531b05b1a)

https://www.thruk.org/documentation/plugins/agents

**Comment by sni** [comment]
is there anything else in the log file maybe? Regarding host attributes, the idea is to set a useful template and maybe some more attributes.
So far i did not require any more attributes, that's why there are none.
Besides that, you can create `<extra_host_opts>` rules to set all kind of host attributes.

**Comment by sistemmsn** [comment]
If your recommendation worked for me, the error no longer appeared, I consider the incident closed. If there is anything else, I'll let you know.
