### ISSUE TITLE
Backend still at 1 despite multiple peers

### ISSUE THREAD

**Issue by duylong** [sni/Thruk#1397]
Hi,

Same problem as this issue but solved (https://github.com/sni/Thruk/issues/1268). 

The individual configuration of each peer displays the node but as soon as I add several peers with LMD (use_lmd_core=1), I only see one peer.
The LMD daemon is launched, the conf is loaded with peers.

Do you also have this problem?

**Thruk Version**
Version of Thruk (and OMD if applicable) : 3.18 (LMD 2.2.1)

**Comment by sni** [comment]
using lmd does not change the way you add peers. Using LMD is simply a switch which changes the way backends are handled internally.
So what exactly did you do?

**Comment by sni** [comment]
that's one backend with 3 alternative connections. What you need is something like this:

```
<Component Thruk::Backend>
    <peer>
        name    = node1
        type    = livestatus
        <options>
            peer   = node1:6557
        </options>
    </peer>
    <peer>
        name    = node2
        type    = livestatus
        <options>
            peer   = node2:6557
        </options>
    </peer>
    <peer>
        name    = node3
        type    = livestatus
        <options>
            peer   = node3:6557
        </options>
    </peer>
</Component>
```

**Comment by duylong** [comment]
This is what I was doing before, but I thought LMD aggregates the peers together and Thruk connects to them to retrieve the data.
