### ISSUE TITLE
does not show the image generated by grafana

### ISSUE THREAD

**Issue by sistemmsn** [sni/Thruk#1402]
**Describe the bug**
I have this strange behavior with nagflux
![image](https://github.com/user-attachments/assets/8f5febc3-18f2-4fea-be41-1a8dc61862e1)

**Thruk Version**
Version of Thruk 3.18

**To Reproduce**
I can't understand why it doesn't show me the image before if it was visible, but I don't remember what changes I made, I just updated, and even in the reports the graphs can't be seen.

**Screenshots**
![image](https://github.com/user-attachments/assets/3645be81-87ac-4aef-ae0e-389ebe7130b0)
![image](https://github.com/user-attachments/assets/7921477b-1372-4065-9a3e-a91eb056f07d)

URL: http://localhost/thruk/cgi-bin/extinfo.cgi?type=grafana&host=localhost&service=Current%20Load&source=2&from=1729791747&to=1729795347&theme=&font_color=&background_color=&width=414&height=234

**Desktop (please complete the following information):**
 - Browser  chrome
 - Version 129.0.6668.101 (Build oficial) (64 bits)
 -  Grafana v11.4

**Additional context**
- Go 1.22.4
- nagflux 5.0
- histou latest

**Comment by sni** [comment]
The fix is to add another arg in the puppeteer.js, you can patch your file locally or wait for the next release.
