### ISSUE TITLE
Oauth2 on Microsoft Entra ID

### ISSUE THREAD

**Issue by eythori-sensa** [sni/Thruk#1405]
Missing from the documentation that the package "libcrypt-jwt-perl" is required when using Microsoft Entra ID or ADFS, on Debian based distros.

When setting up Oauth2 on Microsoft Entra ID everything works fine, but authentications fail with the error:
"Crypt::JWT is required when user id assertions not fetched from api_url at"

Thruk 3.16, OMD 5.40

**Comment by sni** [comment]
it is mentioned here: http://thruk.org/documentation/oauth2.html#_microsoft-ad-fs
Where would you have expected it? Btw, the documentation is open source as well, pull requests to clarify things are always welcome.

**Comment by eythori-sensa** [comment]
I will try to find a wording worthy of the docs :) - thank you for your attn.

**Comment by sni** [comment]
@eythori-sensa and thank you very much, much appreciated.
