### ISSUE TITLE
Updated To Fedora Server 41 from 40 broke Thruk 3.16 - mod_fcgid: error reading data from FastCGI server - XS.c: loadable library and perl binaries are mismatched (got first handshake key 0xf380080, needed 0xeb80080)

### ISSUE THREAD

**Issue by Yu6936** [sni/Thruk#1407]
**Describe the bug**
We had updated from Fedora Server from 40 to 41.  After the upgrade, we are getting "500" from httpd errror_log and 
reports "mod_fcgid: error reading data from FastCGI server - XS.c: loadable library and perl binaries are mismatched (got first handshake key 0xf380080, needed 0xeb80080)".  The message appears that the Perl packages does not jive with Thruk install.  Would you provide some pointers of how I should resolve this? 

 I see that  Naemon site does not have Fedora Server 41 as of yet for the Thruk base/Lib packages. This is where I normally grab the update Thruk packages.     
https://build.opensuse.org/project/repository_state/home:naemon/Fedora_40

**Thruk Version**
-rwxr-xr-x.  1 root root 2986350 Jul  1 05:10 libthruk-3.14-19.1.x86_64.rpm
-rwxr-xr-x.  1 root root    7049 Jul 18 12:45 thruk-3.16-40.1.x86_64.rpm
-rwxr-xr-x.  1 root root 8050002 Jul 12 08:01 thruk-base-3.16-40.1.x86_64.rpm
-rwxr-xr-x.  1 root root   91766 Jul 18 12:46 thruk-plugin-reporting-3.16-40.1.x86_64.rpm

**Nagios Core Version** 
Nagios Core 4.4.14

Any help that you can provide is appreciated.  Thanks!
-Yu Lok Lam

**Comment by sni** [comment]
yeah, you can't do that. I enabled Fedora 41 builds, but unfortunatly they don't work.
I fixed those things, so the daily builds here are fine already:
https://build.opensuse.org/project/show/home:naemon:daily

**Comment by Yu6936** [comment]
Thanks Sven!  I've download the daily builds and reinstall Thruk 3.18.  I works great!  Thanks for the quick response.
