### ISSUE TITLE
no way to embedded other page with menu_local.conf

### ISSUE THREAD

**Issue by Gliyck** [sni/Thruk#1410]
I try to embendded a page in menu_local.conf with this functions :
insert_item
insert_sub_item
add_link
i use 'target' => 'main' in the json but when i click the link in the menu the page appear in another tab.

Exemple in /etc/thruk/menu_local.conf :
insert_item('Outils', { 'href' => '/test/test.html', 'name' => 'TEST', 'target' => 'main'});

- Thruk 3.20-1
-  Browser Chrome Version 95.0.4638.69

**Comment by sni** [comment]
the link is probably not allowed to be embedded, you need to whitelist it with: `allowed_frame_links`

- http://thruk.org/documentation/configuration.html#_allowed_frame_links

**Comment by Gliyck** [comment]
sorry i find
the documentation say : 'target' => 'main'
but lol it's now : 'target' => 'embedded'

**Comment by Gliyck** [comment]
perhaps if you have time change documentation in https://www.thruk.org/documentation/menu.html

**this line :**
target: Target frame for this link. (_parent and _blank open as popup, main opens embedded. Empty target opens in the same window.)

and

Open grafana embedded:
add_link('name' => 'Grafana, 'href' => '/grafana', 'target' => 'main');

**Comment by Gliyck** [comment]
documentation issue

**Comment by sni** [comment]
It should work with target `main` as well if the url is allowed to be embedded. But using `embedded` directly leads to a more clear error message so that's probably better.
I changed this in the docs. Thanks for noticing.
