### ISSUE TITLE
SLA report on services - missing hostname

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#1414]
**Describe the bug**
After running a SLA report with only services,  some services are mising their hostname.

**Thruk Version**
OMD 5.40 but also thruk.demo.org.

**To Reproduce**
1. Go thruk.demo.org
2. Built a SLA report on last week with only services and all hosts

![image](https://github.com/user-attachments/assets/66592c7f-324c-43af-bfac-d52edd1442d9)

**Screenshots**

![image](https://github.com/user-attachments/assets/7c220684-ffbb-422a-bd4c-ed408dbaf5cb)

**Comment by sni** [comment]
Thanks, should be fine with the next release.
