### ISSUE TITLE
Nagios 4.x

### ISSUE THREAD

**Issue by jmcook** [sni/Thruk#177]
It appears Thruk not work with Nagios 4? Running with latest Nagios 4 and Livestatus 1.2.x.

I'm getting an Invalid Header message.

**Comment by anil4u-04** [comment]
Hi Sni,

i am also getting the same error, i have added the above column to the <livestatus-master>/src/TableStatus.cc , and compiled again , but still getting the error, can you please help me

i am using the Thruk(2.14)  , livestatus and Nagios (4.0.2) 

Appreciate your response on this. Thanks.
