### ISSUE TITLE
Escalations...

### ISSUE THREAD

**Issue by ofalk** [sni/Thruk#229]
Hi!

Any chance we can get escalations configuration view in Thruk? Even better would be to also show the command on the service page.

Thx,
 Oliver

**Comment by lumberjackshaw** [comment]
Has there been any change to the prospect of escalations?

**Comment by ofalk** [comment]
@lumberjackshaw: Nope. The idea grew in my head, but I had other topics to follow... Feel free to file a feature request against livestatus!
