### ISSUE TITLE
mobile interface not filtering names that are not in the current open window

### ISSUE THREAD

**Issue by beinbliss** [sni/Thruk#328]
Mobile interface does not filter names that are not in the current open window.

I must press button "More" and then it finds those that opens up a little more.
If i have 200 problems i need to click "More" a lot and filtering has no meaning then.

**Comment by sni** [comment]
Finally... :-)

**Comment by jframeau** [comment]
Hi sven,

thx very much

2018-01-11 16:44 GMT+01:00 Sven Nierlein <notifications@github.com>:
