### ISSUE TITLE
Sound when service/host as acknowledged/notifification disabled

### ISSUE THREAD

**Issue by ryosaeba87** [sni/Thruk#336]
Hi,

on service problem page, when i have the services with notification disable or in acknowledge, the sound still play.

Version:    1.82~2 
Release:    February 21, 2014 
Url:       /thruk/#cgi-bin/status.cgi?host=all&servicestatustypes=28
Browser:    Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.16 

Thanks

**Comment by Corbyn** [comment]
That the sound is triggered by the totals is quite a big problem for us: We have a 24/7 Remote-Operations-Center monitoring our business critical services with Thruk. But they should only be alerted by hard states. So as the 'servicestatustypes' does not work for sounds they don't see the soft state alerts but are alarmed by the sound. They count this every time as an false alarm.
IMHO it really would be better to make sound alarms dependent on the display filter!
