### ISSUE TITLE
Reporting and searching by display name

### ISSUE THREAD

**Issue by BarnesJeff** [sni/Thruk#387]
Hello Sven,

I am busy configuring a naemon monitoring system that has a bit of a weird use case. Host names are UUIDs and display names are used for the host description.  This allows the description of the host to be changed without losing any history.

As far as I can tell it is not possible to search or report by display name in thruk. Could this be possible in future versions?

Thank,
Jeff

**Comment by sni** [comment]
There are no plans right now. However, it should work in the search but you will run into lots of problems probably.
