### ISSUE TITLE
Problem installing from source

### ISSUE THREAD

**Issue by russoisraeli** [sni/Thruk#391]
When doing a standard install from source, "make install" fails, because DESTDIR is not getting set to a reasonable default:

perl Makefile.PL
...
...
*** To install dependencies type 'make installdeps' or 'make installdeps_notest'.
    (You may need to do that as the 'root' user.)
*** Module::AutoInstall configuration finished.
Warning: prerequisite Test::JavaScript 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Thruk
Writing MYMETA.yml and MYMETA.json
patched Makefile
no update necessary
created cached js/css files
finished

make
...
...
Manifying blib/man3/Thruk::Utils::Log.3pm
Manifying blib/man3/Thruk::Utils::Menu.3pm
Manifying blib/man3/Thruk::Utils::RecurringDowntimes.3pm
Manifying blib/man3/Thruk::Utils::Scripts.3pm
Manifying blib/man3/Thruk::Utils::SelfCheck.3pm
Manifying blib/man3/Thruk::Utils::Status.3pm
Manifying blib/man3/Thruk::Utils::Trends.3pm
Manifying blib/man3/Thruk::View::Excel.3pm
Manifying blib/man3/Thruk::View::GD.3pm
Manifying blib/man3/Thruk::View::JSON.3pm
Manifying blib/man3/Thruk::View::TT.3pm

[nagios@ims205 (1 jobs) ~/Thruk-1.84-5 ]$ LANG=en_US.utf8 make install
mkdir -p blib/replace
cp -rp support/*.patch                      blib/replace
cp -rp support/thruk_cookie_auth_vhost.conf blib/replace
cp -rp support/thruk_cookie_auth.include    blib/replace
sed -i blib/replace/* -e 's+@SYSCONFDIR@++g'
sed -i blib/replace/* -e 's+@DATADIR@++g'
sed -i blib/replace/* -e 's+@LOGDIR@++g'
sed -i blib/replace/* -e 's+@TMPDIR@++g'
sed -i blib/replace/* -e 's+@LOCALSTATEDIR@++g'
sed -i blib/replace/* -e 's+@BINDIR@++g'
sed -i blib/replace/* -e 's+@INITDIR@++g'
sed -i blib/replace/* -e 's+@LIBDIR@++g'
sed -i blib/replace/* -e 's+@CHECKRESULTDIR@++g'
sed -i blib/replace/* -e 's+@THRUKLIBS@++g'
sed -i blib/replace/* -e 's+@THRUKUSER@++g'
sed -i blib/replace/* -e 's+@THRUKGROUP@++g'
sed -i blib/replace/* -e 's+@HTMLURL@++g'
sed -i blib/replace/* -e 's+@HTTPDCONF@++g'
sed -i blib/replace/* -e 's+log4perl.conf.example+log4perl.conf+g'
# breaks naemon travis tests
#@if [ "x" = "x" ]; then echo "*** no DESTDIR set ***"; exit 1; fi
mkdir -p 
mkdir: missing operand
Try `mkdir --help' for more information.
make: *** [local_install] Error 1

[nagios@ims205 (1 jobs) ~/Thruk-1.84-5 ]$ grep "^DESTDIR" Makefile
DESTDIR =

**Comment by sni** [comment]
Please use the packages or the source installation guide from http://thruk.org/documentation/install_from_source.html
Thruk is not meant to be installed by configure/make/... Maybe in the future, but not yet.
