### ISSUE TITLE
Feature request: show custom vars in excel export output

### ISSUE THREAD

**Issue by liedekef** [sni/Thruk#396]
I'm using icinga with gearman and a number of different workers to distribute the workload.
I can also get the gearman worker to show in the thruk webinterface using
  show_custom_vars = _WORKER
but this info is nowhere to be found when exporting to excel, while being present in the json output.
Sometimes it is usefull to have this info: in my case I use the gearman worker also as ssh-hop to get to the real servers, and when there's an issue on a number of servers that I can treat automatically via e.g. ansible or fabric, the ssh-hop is usefull to have in the excel output.

**Comment by demonhell** [comment]
is this still an open issue or has it been solved? 
i'm using Thruk 2.18 here, and it seems that custom vars appears in the columns from _xls export_ but then they are not populated in  the XLS file.
their value is visible in the main gui.  
maybe is a new issue? something maybe i forgot in the config?
