### ISSUE TITLE
Panorama: Service/Hostwindow - missing close button

### ISSUE THREAD

**Issue by dklueh** [sni/Thruk#401]
Panorama: Choosing a detailed view of an service or host, the close button on the new windows is missing. Firefox and chrome (newest); see picture attached. Could not be closed anymore
![window](https://cloud.githubusercontent.com/assets/3582803/4197022/6a8ba506-37e1-11e4-9adc-489c2afdc4ca.png)

**Comment by freneticf** [comment]
Same here.
It seems that the close-button is only on the missing, if the dashboard is disabled for editing.

**Comment by sni** [comment]
for the moment i'd say, the real error is that the host/service window opens in first place. But of course i see the need to have that window to set downtimes, etc...
But that seems a bit more complicated to fix, so the quick fix would be disabling the popup.

**Comment by sni** [comment]
should be fixed with the next release.
