### ISSUE TITLE
Changing report_from_email has no effect. Replace MIME::Lite?

### ISSUE THREAD

**Issue by Mutisk** [sni/Thruk#404]
I've had problems trying to set a custom from e-mail address that the reports originate from, and since even overriding parameters just before $msg->Send; didn't work I began looking beyond thruk itself.

I found others with the similar problem:
http://www.perlmonks.org/?node_id=620602

And linked from that, finally a work-around.
http://www.perlmonks.org/?node_id=751610

And finally a comment about MIME::Lite is not the recommended by it's maintainer
https://metacpan.org/pod/MIME::Lite#WAIT

(Using Thruk Version 1.85-20140919 on omd)

**Comment by sni** [comment]
Mail::Sender seems to be more powerful and used by more people, so i would prefer that one.

**Comment by gabortakacs78** [comment]
Hi Sven,
I have similar issue.
If I set:
#set E-Mail address (Sender / From) for reports
<Component Thruk::Plugin::Reports2>
    report_from_email      = 'UserName <example@mail.com>'
</Component>
or
#set E-Mail address (Sender / From) for reports
<Component Thruk::Plugin::Reports2>
    report_from_email      = "UserName <example@mail.com>"
</Component>
or
<Component Thruk::Plugin::Reports2>
    report_from_email      = UserName <example@mail.com>
</Component>
there is no affect.

In case of:
<Component Thruk::Plugin::Reports2>
    report_from_email      = User Name <example@mail.com>
</Component>
we get error:
Please report this issue by mail to: bugs@thruk.org

Please describe what you did:
Make sure the report does not contain confidential information.
---------------
Url:        reports2.cgi
Browser:    
Version:    2.38-2
Release:    October 27, 2020
LMD:        lmd - version 1.9.4 (Build: , go1.15.5)
Backends:   State / Program Version / Data Source Version
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
0 / 2.12.0-1 / 2.12.0-1
uname:      Linux thruk-tui 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64
release:    Red Hat Enterprise Linux Server release 7.7 (Maipo)
Stacktrace:
can't extract address at < Name > in >
at /usr/share/thruk/lib/Thruk.pm line 368.
Thruk::_dispatcher('HASH(0x22fed18)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
Plack::Util::run_app('CODE(0x1337db8)', 'HASH(0x22fed18)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 147
Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x606c48)', 'CODE(0x1337db8)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 23

What would be right setting? ;-)
