### ISSUE TITLE
Event log not showing everything when filtering

### ISSUE THREAD

**Issue by liedekef** [sni/Thruk#406]
Using a specific user, I can see the whole eventlog just fine, but once I put a simple string in the filter (to search for e.g. a specific server), it turns up empty.
So this works:
/thruk/#cgi-bin/showlog.cgi?entries=100&host=&service=&pattern=&exclude_pattern=&start=2014-09-22+00%3A00&end=2014-09-23+00%3A00&archive=
But this (pattern "bod") results in an empty result:
/thruk/#cgi-bin/showlog.cgi?entries=100&host=&service=&pattern=bod&exclude_pattern=&start=2014-09-22+00%3A00&end=2014-09-23+00%3A00&archive=

Using another user it works just fine. Some patterns result in a very limited set of loglines to be displayed for the user where it is not working, but never shows everything as expected.
I tried to find the difference and I think it is because the one where the filter works ok is in a group that is allowed to see and do everything (icinga contactgroup used in cgi.cfg), while the user having troubles is not (just an apache authenticated user).
I do have this in cgi.cfg:
```
authorized_for_all_services=*
authorized_for_all_hosts=*
authorized_for_read_only = problemuser
```
So the info returned should be the same in both cases. Removing the user from the readonly setting didn't change anything (restarted httpd to be sure).

To confirm my suspision, I defined the user having troubles in icinga (contacts) and added the user to the same contactgroup that has the right to do everything in cgi.cfg. And bingo: all works as expected then.
So, some access right calculation seems to be off ...

**Comment by sni** [comment]
Should be fine with the next release. Thanks for the report.
