### ISSUE TITLE
Business process edit sessions not always cleaned up.

### ISSUE THREAD

**Issue by smetj** [sni/Thruk#413]
When someone is editing a business process and meanwhile Nagios restarts, (which perhaps makes ppl closing their browser) <number>.tbp.runtime.edit files start to linger in /var/lib/thruk/bp

From then on, if a user assigns a name to a node which is already defined in a lingering .edit file, then they will experience a sequential number being added to their node name.  Since the .edit file(s) keep existing forever it is a confusing situation.

**Comment by sni** [comment]
Old files should be cleaned up after 1day when creating a new business process.
