### ISSUE TITLE
Service escalations not restituted correctly in Object Browser

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#425]
See capture in attached image.

![capture-1](https://cloud.githubusercontent.com/assets/498115/5164588/c4af37a8-73d9-11e4-8685-d0a850d3f377.png)

jf rameau

**Comment by sni** [comment]
host and service escalations are not supported by the config tool at the moment and are tricky to handle.

**Comment by sni** [comment]
service escalation are fully supported now, so this should be fixed with the last release.
