### ISSUE TITLE
favicon problem number doesn't respect ACKs

### ISSUE THREAD

**Issue by vide** [sni/Thruk#430]
If I'm viewing the **Unhandled Services problems** page (which is a subset othe Service problem pages minus ACK, silenced etc) the number of problems shown in the favicon is the same as the in the general Service Problems page. I usually leave ACK'ed or silenced long satnding problems or problems we are gonna fix in a short time, and I usually keep Thruk in a pinned tab in my browser, so the number in the favicon is really important.
Thank you anyway for releasing this software, which is really great!!

**Comment by vide** [comment]
Yes, the number in the favicon is different from what I see on the page, so it is a bug :) Right now for example I have 10 alerts on that page and the favicon says 24 (because I have 14 services silenced or ack'ed and therefore filtered out)

**Comment by sni** [comment]
What page is that. Does the number correspond with the number from the "totals" table. In case
there is a totals table, that number is used for the counter. Do you have a screenshot?

**Comment by sni** [comment]
the counter shows the number of problems (right top corner). It is not possible to count the actual problems in the list of services because the list can be paged. This is only done on the "Problems" page where no totals are available and no paging is used.

**Comment by vide** [comment]
Mmmh I do not  agree. The list can be paged but it shows clearly "10 of 10", and it could be "50 of 120" if paged, and the favicon should display 120 nonetheless. Don't you think?
As I said earlier in this thread, my use case for this is pinning the thruk tab displaying only the unhandled services, so I can react quickly if that number changes (it should be 0 almost all the time). I know that we have mail notifications but I prefer to use Thruk

**Comment by sni** [comment]
Couldn't you just use the "Problems" link. This should be exactly what you want. Also it excludes acknowledged problems and downtimes already.

**Comment by vide** [comment]
Ok, you win :) Didn't know it was clickable. Thanks for your time & patience and for thruk!
