### ISSUE TITLE
Panorama PNPGraph does not show Source

### ISSUE THREAD

**Issue by gitmopp** [sni/Thruk#437]
Version: thruk-1.86-1.sles11sp3.x86_64.rpm
In Panorama PNPGraph I can select a "Graph", but after selecting the Graph I get an exclamation mark and cannot select any Source
I didn' t find anything in the logs.

**Comment by gitmopp** [comment]
I see the following in the network traffic:
<pre>
POST /pnp4nagios//index.php/json?host=MYPNP&srv=Service%20Check HTTP/1.1
Host: myhost.domain.com
</pre>
The script seems to query the wrong host "myhost.domain.com". It has to be the host from the other backend.

**Comment by sni** [comment]
Thruk just uses the url from your action url, if you want a this url point to a different domain, you have to set it in the action url. Thruk does not know where your pnp data is.
