### ISSUE TITLE
Statusmap object icons don't respect theme selection

### ISSUE THREAD

**Issue by fsSnowboard** [sni/Thruk#438]
It looks like the image source for parent view icons/logos is hard coded to `src="../../check_mk/images/icons/' + data.icon_image + '"`

The default thruk configuration puts all logos in `$url_prefix+'thruk/themes/'+$current_theme+'/images/logos/'`

Shouldn't Statusmap support default theme selection settings?  Currently the rest of Thruk respects the theme location for these icons.

As it currently stands, any icons put in the theme/images/logos directory work in the rest of thruk, but don't work and also need to be put in `../../check_mk/images/icons/` folder to show up in statusmap

**Comment by sni** [comment]
a hardcoded path to check_mk seems totally wrong. No idea where that came from.
Seems like it slipped in with commit 28143871a.

**Comment by sni** [comment]
Should be fixed now. Thanks
