### ISSUE TITLE
TypeError: link is undefined 

### ISSUE THREAD

**Issue by liedekef** [sni/Thruk#439]
The following javascript error happens when clicking on a link to another dashboard in panorama:

Version:    1.86~2 
Stacktrace: 
Url: https://xxx/thruk/cgi-bin/panorama.cgi?js=1&_dc=1422009043 Line 12425 
Error: TypeError: link is undefined

**Comment by sni** [comment]
this should do the trick. thanks

**Comment by liedekef** [comment]
Thanks for the quick fix!
