### ISSUE TITLE
Panorama: Summarized Results isn't showing what I expect for a Custom Filter

### ISSUE THREAD

**Issue by joshskinner** [sni/Thruk#440]
I could definitely be wrong here, but if I have a custom filter widget showing the service statuses for 1 host.  I expect the widget to reflect the worst status in that filter.  For instance:

this widget source:  "general": {
    "name": "test",
    "backends": [],
    "filter": "[{\"hoststatustypes\":15,\"hostprops\":0,\"servicestatustypes\":29,\"serviceprops\":10,\"type\":\"Host\",\"val_pre\":\"\",\"op\":\"=\",\"value\":\"ods04.prod.inapus\",\"value_date\":\"2015-01-25T16:29:16\",\"displayfield-3738-inputEl\":\"\"}]",
    "incl_svc": "on"
  },

produces this summary
![screen shot 2015-01-29 at 1 10 56 pm](https://cloud.githubusercontent.com/assets/1017690/5964368/2d5b0ea4-a7b9-11e4-92e4-65cd845fb32f.png)

What I would expect is the Summarized Results would be Critical and there would be counts in the tabular Services area.  No?

**Comment by freneticf** [comment]
The same here.
We started using custom filters since version 1.86-2. It did't work from there.

**Comment by sni** [comment]
should be fixed now, thanks
