### ISSUE TITLE
null is a correct value for fields

### ISSUE THREAD

**Issue by Hyllegaard** [sni/Thruk#442]
Hi.

When I enter a value of null on a host's contactgroup property to prevent it from inheriting any contactgroups i get a parse error in Apply Config Changes like this:

<code>referenced contactgroup 'null' does not exist in</code>

According to this page on naemon.org it should be ok:
http://www.naemon.org/documentation/usersguide/objectinheritance.html#cancelling_inheritance_of_string_values

As the product continues to work, it is not a critical error, just an annoyance :)

Regards

Jens

**Comment by sni** [comment]
you are totally right.
