### ISSUE TITLE
Problem parsing Check Command on configuration page

### ISSUE THREAD

**Issue by Hyllegaard** [sni/Thruk#444]
In one of my checks of a host I look for a string in the source of a web page. Currently this string includes the word TITLE in <> brackets. Unfortunately I can't type the tag here as it is also parsed by this input box. It appears that Thruk does not like this and actually parses the tag, which results in the hosts configuration page being broken.

I can of course circumvent this by changing my search string in the check, but I thought you might want to know this.

Regards

Jens

**Comment by ofalk** [comment]
I just stumbled over this request by accident... Anyway. Have you tried to escape the <>? Eg \< and \>?

**Comment by sni** [comment]
i don't think thats possible. Thruk just puts host and service names in the page so if the host/service names contain html code, its parsed by the browser.
