### ISSUE TITLE
Panorama/Thruk crashing in browser after ~24 hours

### ISSUE THREAD

**Issue by christrotter** [sni/Thruk#446]
I'm not really sure how to troubleshoot this properly, so please let me know if you need more to go on.

We are using Panorama as a dashboard that is displayed on a TV screen.  Initially I had it iframed onto a separate page (also had 'simple-nagios-dashboard' at the bottom), but this would crash pretty much after ~24 hours (full browser crash - tried both Chrome and FF).  I'm now running the direct OMD/Thruk URL on the page, and it seems to take longer to crash now (possibly the whole weekend?), but is still crashing.

Note that the URL mentioned below is part of a URL panlet inside Panorama - we have no issues w. other Grafana URLs crashing outside of Panorama (another department uses only a Grafana dash - it's been running solid for over two weeks).

Here's the latest crash dump, if it helps:
``` text
AdapterDeviceID: 0x0540
AdapterDriverVersion: 2.3.0.147
AdapterSubsysID: 2240102b
AdapterVendorID: 0x102b
Add-ons: %7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1
AvailablePageFile: 59022413824
AvailablePhysicalMemory: 24727879680
AvailableVirtualMemory: 855089152
BIOS_Manufacturer: American Megatrends Inc.
BlockedDllList: 
BreakpadReserveAddress: 47906816
BreakpadReserveSize: 41943040
BuildID: 20150122214805
CrashTime: 1423290982
EMCheckCompatibility: true
FramePoisonBase: 00000000f0de0000
FramePoisonSize: 65536
InstallTime: 1422384987
Notes: AdapterVendorID: 0x102b, AdapterDeviceID: 0x0540, AdapterSubsysID: 2240102b, AdapterDriverVersion: 2.3.0.147
D3D11 Layers? D3D11 Layers- D3D9 Layers? D3D9 Layers- Attempt to create DrawTarget for invalid surface. Size(1920,1080) Cairo Status: 1

ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SecondsSinceLastCrash: 781701
StartupTime: 1422540033
SystemMemoryUsePercentage: 27
Theme: classic/1.0
Throttleable: 1
TotalPageFile: 68648574976
TotalPhysicalMemory: 34325241856
TotalVirtualMemory: 4294836224
URL: http://grafana.domain.com/#/dashboard/db/pipe?_dc=1423290981183
Vendor: Mozilla
Version: 35.0.1
Winsock_LSP: MSAFD Tcpip [TCP/IP] : 2 : 1 : %SystemRoot%\system32\mswsock.dll 
 MSAFD Tcpip [UDP/IP] : 2 : 2 :  
 MSAFD Tcpip [RAW/IP] : 2 : 3 : %SystemRoot%\system32\mswsock.dll 
 MSAFD Tcpip [TCP/IPv6] : 2 : 1 :  
 MSAFD Tcpip [UDP/IPv6] : 2 : 2 : %SystemRoot%\system32\mswsock.dll 
 MSAFD Tcpip [RAW/IPv6] : 2 : 3 :  
 RSVP TCPv6 Service Provider : 2 : 1 : %SystemRoot%\system32\mswsock.dll 
 RSVP TCP Service Provider : 2 : 1 :  
 RSVP UDPv6 Service Provider : 2 : 2 : %SystemRoot%\system32\mswsock.dll 
 RSVP UDP Service Provider : 2 : 2 : 
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.
```

**Comment by sni** [comment]
Which version of Thruk is that. There had been some issues with content in iframes, which is used for the generic panlet or the pnp panel. Those problems should be fixed in the version 1.86.

**Comment by christrotter** [comment]
Oh, durr - sorry.  Version 1.84-6, OMD 1.20

OMD 1.30 has Thruk 1.86-3...I will update to OMD 1.30 - thanks!

**Comment by sni** [comment]
OMD 1.30 has not yet been release, but you can try the snapshots which contain a newer Thruk version already.

**Comment by christrotter** [comment]
Oh, that's right - forgot about that.  I'm good just knowing this has been resolved.  I saw the 1.30 changelog and it just said 'Thruk new version', no details.  Next time I will investigate the sub-component changelog!
