### ISSUE TITLE
Search in custom variables

### ISSUE THREAD

**Issue by ofalk** [sni/Thruk#450]
Hi!

Maybe there is an option somewhere hidden and I didn't find it, but is there a way to enable search in custom vars? Or can you imagine to implement this? I guess Thruk would need another hash holding this information, but I think it would be really useful!
My workaround for the moment would be to create a dummy service holding this information, since searching in the status output works...

However, I can imagine that using custom variable for filtering could be also extremely useful, don't you think?

Thx,
 Oliver

**Comment by sni** [comment]
this is possible already, just select "Custom Variable" in the filter drop down.

**Comment by ofalk** [comment]
But the AJAX search doesn't support it, right?

-of (mobile)

Am 26.02.2015 um 12:41 schrieb Sven Nierlein <notifications@github.com<mailto:notifications@github.com>>:


this is possible already, just select "Custom Variable" in the filter drop down.

**Comment by sni** [comment]
should work with the next release.

**Comment by ofalk** [comment]
You're the hero of my day, @sni!
Let me know when you'll be in/near Vienna; I own you a beer! ;-)
