### ISSUE TITLE
Thruk logcache update doesn't work for 'CURRENT HOST STATE'

### ISSUE THREAD

**Issue by Finn10111** [sni/Thruk#456]
I am using OMD 1.20 with Thruk 1.84-6 and Shinken 1.41. Long time ago I configured a MySQL logcache which works fine. Some time ago I configured Shinken to log the current host state which seemed to be a good idea for improving the Thruk reports. 

The lines in the sinken.log look like this:
```
[1425028768] CURRENT HOST STATE: example.org;UP;HARD;1;OK - 192.168.1.1: rta 26,051ms, lost 0%
``` 
The logcache update is done every five minutes via cron using the following command:

```
$OMD_ROOT/bin/thruk -a logcacheupdate >> $OMD_ROOT/var/log/thruk.log 2>&1
```

I get the following error in thruk.log:

```
ERROR: insert failed for: (1425028768,6,'CURRENT HOST STATE',UP,'HARD',NULL,198,NULL,471283,470902)
DBD::mysql::db do failed: Unknown column 'UP' in 'field list' at /omd/sites/example/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1700.
ERROR: DBD::mysql::db do failed: Unknown column 'UP' in 'field list' at /omd/sites/example/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1700.
```

The first thing I noticed is that UP isn't quoted and after some research I found bug #231 which seemes to describe the same or a similiar error.

**Comment by sni** [comment]
This sounds like a bug in the shinken livestatus implementation. Thruk expects the state to be a numeric value, but shinken sends a alphanumeric "UP" string. I suggest opening an issue for the shinken project.
