### ISSUE TITLE
No username for comments/downtimes/ack

### ISSUE THREAD

**Issue by NemesisRE** [sni/Thruk#458]
Hi,
we are using Thruk 1.86-4 with shinken and apache mod_auth_cas

It is working perfect except one issue, the field "Author (Your Name):" (com_author) is filled with "none" instead of the value from remote_user.

The only workaround so far was to unlock author names and edit it manually.

Maybe there is a better way or maybe this is just a bug.

regards
Steven

**Comment by sni** [comment]
never heard of that module, how does it make the username accessible?

**Comment by NemesisRE** [comment]
It sets %{REMOTE_USER} and I can see that is working in the infobox where the correct user is displayed.

It is from http://jasig.github.io/cas/4.0.x/index.html
the module is this one https://github.com/Jasig/mod_auth_cas

**Comment by sni** [comment]
Then its not a thruk problem but most likely with your apache config. Is the cmd.cgi protected like the other pages which show the correct username? Thruk just takes the username from the apache environement.

**Comment by NemesisRE** [comment]
Damn right... it was the apache config I thought I only changed the auth module but somehow messed up the whole config.

Thank you for the hint and for your work on this project.

**Comment by NemesisRE** [comment]
Could it be that it is caused by the SSL connection?

**Comment by NemesisRE** [comment]
Ok just checked what happens if i replace "comment_author" with "remote_user" templates/cmd/cmd_typ_1.tt:25
The correct username is displayed which means it is correctly saved.

Where does comment_author come from?

**Comment by sni** [comment]
its defined in the lib/Thruk/Controller/cmd.pm

**Comment by NemesisRE** [comment]
It always shows "none" even if I hard code something
```
    # locked author names?
    #if( $c->config->{'cgi_cfg'}->{'lock_author_names'} or !defined $c->{'request'}->{'parameters'}->{'com_author'} ) { 
        my $author = $c->stash->{'remote_user'};
        #$author = $c->user->alias if defined $c->user->alias;
        $c->{'request'}->{'parameters'}->{'com_author'} = 'test';
    #}```

**Comment by NemesisRE** [comment]
I reverted all changes restarted apache and thruk it still showed "none"
Then I had to restart shinken and now it displays the correct user again....

I keep watching this thing... I hope it was just that.

I am so sorry that I have stolen your time.

**Comment by NemesisRE** [comment]
Ok it seams that if in shinken the contacts alias is not set this problem occurs, after a short period of time if it is set it will use the alias...

I will check if it keeps now the correct user. If I do not write another update here this was the problem.
