### ISSUE TITLE
Thruk JS Error Report on frames

### ISSUE THREAD

**Issue by gerbier** [sni/Thruk#465]
I have a running thruk (1.86-4) over shinken and the site refresh as expected on my firefox browser.

Now, we have build a new web page to merge several monitoring tools on one screen. The html code is based on frameset and frame. And I now get the following error on thruk : 

Version:    1.86~4
Release:    February 12, 2015
Url:        /thruk/cgi-bin/status.cgi??svc_s0_hoststatustypes=3&svc_s0_servicestatustypes=28&style=combined&hst_s0_hoststatustypes=4&svc_s0_hostprops=10&hst_s0_hostprops=10&svc_s0_hostprop=2&svc_s0_hostprop=8&hst_s0_servicestatustypes=31&hst_s0_serviceprops=0&title=All%20Unhandled%20Problems&nav=0&svc_s0_serviceprops=10&relaod_nav=1
Browser:    Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
Backends:   uname:      Linux sxreso1.xxxxxxxxx 3.14.27-server-1.mga4 #1 SMP Sun Dec 21 22:58:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
release:    Mageia release 4 (Official) for x86_64

Stacktrace:
Url: http://thruk.cnrm.meteo.fr/thruk/javascript/all_in_one-1.86-4.js Line 2
Error: Error: Permission denied to access property 'href'

**Comment by sni** [comment]
If you want to use Thruk in frames, you have to disable the frames in thruk itself. See http://thruk.org/documentation/configuration.html#use_frames
