### ISSUE TITLE
Servicegroups (using additive inheritence) are not displaying correctly

### ISSUE THREAD

**Issue by jsnicaise** [sni/Thruk#466]
You can setup hostgroups and servicegroups either by creating the hostgroup/servicegroup and manually adding members or you can add the hostgroups/servicegroups tag to the host/service definition and specify the hostgroups/servicegroups there.

When using inheritence, you can add the "+" sign to add the value to the previous value of the template you're using.

The display of hostgroups is working fine:

![hostgroups](https://cloud.githubusercontent.com/assets/11619622/6789759/3510eec2-d179-11e4-8bcc-f54c8b3c78a6.PNG)

and the computed values are correct:
![hostgroupsvalues](https://cloud.githubusercontent.com/assets/11619622/6789798/717d4c3e-d179-11e4-995b-577b3d2f4e39.PNG)

The display of servicegroups is not working correctly:
![servicegroups](https://cloud.githubusercontent.com/assets/11619622/6789815/926ea370-d179-11e4-97b6-81175a41989f.PNG)

But the computed values are correct:
![servicegroupsvalue](https://cloud.githubusercontent.com/assets/11619622/6789875/0164b3aa-d17a-11e4-89e1-0d23971f20aa.PNG)

... and links to the correct servicegroup definition:
![servicegroup](https://cloud.githubusercontent.com/assets/11619622/6789887/199329b6-d17a-11e4-8fdd-12564df69b3a.PNG)

Thanks,

**Comment by sni** [comment]
maybe thruks config parser is wrong here and its not possible at all to use + to amend servicegroups. At least it looks like that, because it seems like the servicegroup actually has the "+" in its name.

**Comment by sni** [comment]
i just realized you are using shinken. Maybe this particular feature is not supported in shinken? You could raise an issue there.
