### ISSUE TITLE
Make shadownaemon refresh value configurable

### ISSUE THREAD

**Issue by simenaasland** [sni/Thruk#467]
When spawning shadownaemon from Thruk, it would be nice to have the possibility to change the refresh value (--refresh, -r) of shadownaemon and not always use the default (currently 3 seconds).

Something like

```
shadow_naemon_refresh=<int>
```

in thruk.conf / thruk_local.conf.

**Comment by sni** [comment]
i don't think you save a lot bandwidth when increasing that value. You still could start the shadownaemon manually. If there would be something like this necessary, i would opt for a shadow_naemon_extra_args=... option. But for now, i don't think we need something like that.
