### ISSUE TITLE
Thruk over icinga2 (Livestatus TCP) multi re-checks

### ISSUE THREAD

**Issue by jhon287** [sni/Thruk#468]
Hello,

I have a strange issue about rescheduling many checks in the same time.
I'm using Thruk 1.88-2 over Icinga2 2.3.3 (Livestatus).
The issue is when I like to recheck many failed checks in the same time, it seems icinga execute only the first one. Below are my logs... Is someone facing the same problem ? If so, how may I solve it ?

Thank you in advance.

==> icinga2/compat/icinga.log <==
[1427880491] EXTERNAL COMMAND: SCHEDULE_SVC_CHECK;host-a;Dummy 2;1427880491
[1427880491] SERVICE ALERT: host-a;Dummy 2;UNKNOWN;HARD;1;UNKNOWN : Dummy Check (3) 

==> thruk/thruk.log <==
[2015/04/01 11:28:11][icinga.tunz.com][INFO][Thruk.Controller.cmd] [jonathan][Livestatus TCP] cmd: COMMAND [1427880491] SCHEDULE_SVC_CHECK;host-a;Dummy 2;1427880491
[2015/04/01 11:28:11][icinga.tunz.com][INFO][Thruk.Controller.cmd] [jonathan][Livestatus TCP] cmd: COMMAND [1427880491] SCHEDULE_SVC_CHECK;host-b;Dummy 2;1427880491

**Comment by sni** [comment]
This is a (known?) issue in icinga 2. Thruk sends all commands at once, but it seems like icinga 2 only reads the first one.

**Comment by jhon287** [comment]
OK... Is it planned to solve this known issue ?

**Comment by sni** [comment]
no idea, this is the thruk issue tracker. Could you raise an issue on the icinga 2 tracker?

**Comment by sni** [comment]
https://dev.icinga.org/issues/9322

**Comment by TomGudman** [comment]
+1 here and on the icinga's issue tracker.

**Comment by TomGudman** [comment]
Fixed upstream in 2.3.11. I think this can be resolved.

**Comment by jhon287** [comment]
Good news ! Thank you for the feedback.

**Comment by ChrisHeerschap** [comment]
I'm still seeing issues with this, unsure if it should be re-opened. If I select many services and apply a comment, most of them will get the comment, but there is usually one, sometimes more - at the end which doesn't get the comment. I've started copying the comment, selecting all that I want, and applying the comment, then seeing which ones didn't get it, selecting those, applying the comment again. Sometimes if I choose enough (>20?) at once I'll have to do this process 3-4 times.
