### ISSUE TITLE
Missing "su" directive in /etc/logrotate.d/thruk for distributions using logrotate 3.8.0+

### ISSUE THREAD

**Issue by hogneh** [sni/Thruk#471]
In CentOS 7 and other distros using logrotate 3.8.0+ the "su" directive is now required, from the changelog:

"added "su" option to define user/group for rotation. Logrotate now skips directories which are world writable or writable by group which is not "root" unless "su" directive is used."

**Comment by sni** [comment]
i guess there is no solution which works with all versions of logrotate?

**Comment by hogneh** [comment]
I tested on RHEL6 to see if it just ignored and skipped unknown options, but it doesn't look like it:

```bash
# logrotate test
error: test:9 unknown option 'su' -- ignoring line
error: test:9 unexpected text
```

So I wouldn't bet on it working across major versions.

**Comment by sni** [comment]
should be better now, thanks
