### ISSUE TITLE
Strange behaviour when a backend is disabled by local state

### ISSUE THREAD

**Issue by fledorze** [sni/Thruk#472]
1- When a backend is disabled by local state, its button stay in green in backend panel, even if the onmouse text is :
"ERROR: peer check via local instance(s) returned state:DOWN"
and its hosts and services status dissappear. 

2- when backend is detected as back by local state check, the onmouse text is still :
"ERROR: peer check via local instance(s) returned state:DOWN" 
It seems that backend is not re-enabled and the corresponding hosts and services don't come back.
You have to login/logout to see on onmouse text : "UP: ....". and hosts and services of the backend. 

The consequences are : 
- our operators, who look at problems only,  don't notice that a backend is down,
- more serious, they have no more view on hosts/services when backend is suppose back but they don't know it.

**Comment by sni** [comment]
this should be better with the next release, i completly reworked the site panels.

**Comment by fledorze** [comment]
Wonderful. Thx a lot.

**Comment by fledorze** [comment]
Hi Sven.
Sorry to come back agin but still have the issue with Thruk 2.01 with Naemon, installed with Lab Console APT source for Jessie 64b. 
Any idea ?
Should be upgrade to the proposed new version by APT, that is  Thruk 2.05 ?

**Comment by sni** [comment]
The latest release is the 2.04. Please open a new issue with a detailed description of the problem. Or is
it exactly the same problem?
