### ISSUE TITLE
Panorama : Adding "comments" in the columns view for services/hosts

### ISSUE THREAD

**Issue by steevesaustin** [sni/Thruk#473]
Hi,

I just started playing with Panorama which is truly amazing and the only thing I miss to integrate it in the workflow of my team is the ability to have a column with the comments in the "services" or "hosts" view.
I can see almost all fields (eg : "host", "hostname", "Status information", "performances" etc ...) but nothing for the comments.

Is this easily doable ?

Thanks a lot

**Comment by sni** [comment]
Comments are in a 1:n relation to hosts/services. So they cannot be included easily in a single table cell.
