### ISSUE TITLE
Problem with latest version from repository

### ISSUE THREAD

**Issue by Hyllegaard** [sni/Thruk#481]
Hi.

I am using the testing repository for Naemon/thruk from konsol.de and the latest version there fails to run.
According to the logs naemon itself is running, but it appears that Thruk is not.
When I try to acces the website I get an error message: Internal Server Error

In the apache error log this appears:

[Tue May 19 10:45:15.920189 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: $VAR1 = 'not rendered and no template for: ';
[Tue May 19 10:45:15.920227 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: $VAR2 = bless( {
[Tue May 19 10:45:15.920234 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                  'env' => {
[Tue May 19 10:45:15.920239 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'AUTH_TYPE' => 'Basic',
[Tue May 19 10:45:15.920259 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'CONTENT_LENGTH' => '0',
[Tue May 19 10:45:15.920265 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'CONTEXT_DOCUMENT_ROOT' => '/usr/share/naemon/root/thruk/',
[Tue May 19 10:45:15.920270 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'CONTEXT_PREFIX' => '/naemon/',
[Tue May 19 10:45:15.920275 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'DOCUMENT_ROOT' => '/var/www',
[Tue May 19 10:45:15.920280 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'FCGI_ROLE' => 'RESPONDER',
[Tue May 19 10:45:15.920285 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'GATEWAY_INTERFAC
[Tue May 19 10:45:15.920292 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: E' => 'CGI/1.1',
[Tue May 19 10:45:15.920297 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
[Tue May 19 10:45:15.920302 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'HTTP_ACCEPT_ENCODING' => 'gzip, deflate',
[Tue May 19 10:45:15.920307 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'HTTP_ACCEPT_LANGUAGE' => 'da',
[Tue May 19 10:45:15.920313 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'HTTP_CONNECTION' => 'close',
[Tue May 19 10:45:15.920319 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'HTTP_COOKIE' => 'thruk_side=current_status=1&system=1&general=1&bookmarks=1&reports=1; thruk_favicon=on; thruk_obj_layout=table; thruk_theme=Thruk; thruk_mob
[Tue May 19 10:45:15.920327 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: ile=1; thruk_auth=f6cedbbf9cfc01c2ec3d0e8b533d04ca; thruk_conf=328c5; csrftoken=jteAj6iVR524ieExX0f4sH6z6bkjmBwt; pnp4nagios=foq0k2r4po5jvmqf31sgiqati7; PHPSESSID=g5eru81k12qul17vmoh96enma2; token=4-90007b88-1329-31b6-c875-d6e0c4de4457; lastFolderUri=/Reports; filtersPopularity=%7B%22resourceTypeFilter%22:%7B%22resourceTypeFilter-reports%22:8,%22undefined%22:0,%22resourceTypeFilter-all%22:1,%22resourceTypeFilter-reportOutput%22:0%7D,%22timeFilter%22:%7B%22timeFilter-anyTime%22:1,%22timeFilter-today%
[Tue May 19 10:45:15.920336 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: 22:0,%22timeFilter-yesterday%22:0,%22timeFilter-pastWeek%22:0,%22timeFilter-pastMonth%22:0,%22undefined%22:0%7D,%22scheduleFilter%22:%7B%22scheduleFilter-anySchedule%22:1,%22scheduleFilter-scheduled%22:0,%22scheduleFilter-scheduledByMe%22:0,%22scheduleFilter-notScheduled%22:0,%22undefined%22:0%7D,%22accessTypeFilter%22:%7B%22accessTypeFilter-all%22:1,%22accessTypeFilter-changedByMe%22:0,%22accessTypeFilter-viewedByMe%22:0,%22undefined%22:0%7D%7D; DataSourceControllerHistory=http%253A%252F%252Fnagios
[Tue May 19 10:45:15.920345 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: 3%253A8080%252Fjasperserver%252Fflow.html%253F_flowId%253DsearchFlow; PLAY_SESSION="6c1382c368ebc1e91763322742fe1580f5f5842f-disconnected_orig_uri=%2Fsearch%3Frangetype%3Drelative%26fields%3D%26width%3D1920%26relative%3D300%26from%3D%26to%3D%26q%3D102.227&sessionid=dc7cacc970718bc49fb73636d90d93e8f03db8e04ec8b143c01090da58b682742cdca11a7d67ce9aabb54645ab602adf"; SSID=8dqooecuvuaqk9hafbqdd9hhn3; AjaXplorer=m2ok5tf859uf8fc3tljlk6pmg2',
[Tue May 19 10:45:15.920352 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'HTTP_HOST' => 'nagios3',
[Tue May 19 10:45:15.920363 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:
[Tue May 19 10:45:15.920370 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0',
[Tue May 19 10:45:15.920375 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
[Tue May 19 10:45:15.920380 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'PATH_INFO' => '/naemon/',
[Tue May 19 10:45:15.920385 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'PATH_TRANSLATED' => '/usr/share/naemon/fcgid_env.sh/naemon/index.html',
[Tue May 19 10:45:15.920390 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'QUERY_STRING' => '',
[Tue May 19 10:45:15.920394 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'REMOTE_ADDR' => '192.168.102.227',
[Tue May 19 10:45:15.920399 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:
[Tue May 19 10:45:15.920405 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:          'REMOTE_PORT' => '10704',
[Tue May 19 10:45:15.920410 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'REMOTE_USER' => 'admin',
[Tue May 19 10:45:15.920415 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'REQUEST_METHOD' => 'GET',
[Tue May 19 10:45:15.920421 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'REQUEST_SCHEME' => 'http',
[Tue May 19 10:45:15.920426 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'REQUEST_URI' => '/naemon/',
[Tue May 19 10:45:15.920431 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SCRIPT_FILENAME' => '/usr/share/naemon/fcgid_env.sh',
[Tue May 19 10:45:15.920436 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SCRIPT_NAME' => '',
[Tue May 19 10:45:15.920441 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_ADDR' => '192.168.102.69',
[Tue May 19 10:45:15.920445 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_ADMIN' => 'webma
[Tue May 19 10:45:15.920464 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: ster@localhost',
[Tue May 19 10:45:15.920474 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_NAME' => 'nagios3',
[Tue May 19 10:45:15.920480 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_PORT' => '80',
[Tue May 19 10:45:15.920485 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_PROTOCOL' => 'HTTP/1.1',
[Tue May 19 10:45:15.920490 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at nagios3 Port 80</address>
[Tue May 19 10:45:15.920495 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: ',
[Tue May 19 10:45:15.920500 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)',
[Tue May 19 10:45:15.920505 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'plack.cookie.parsed' => {
[Tue May 19 10:45:15.920517 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'AjaXplorer' =
[Tue May 19 10:45:15.920524 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: > 'm2ok5tf859uf8fc3tljlk6pmg2',
[Tue May 19 10:45:15.920529 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'DataSourceControllerHistory' => 'http%3A%2F%2Fnagios3%3A8080%2Fjasperserver%2Fflow.html%3F_flowId%3DsearchFlow',
[Tue May 19 10:45:15.920535 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'PHPSESSID' => 'g5eru81k12qul17vmoh96enma2',
[Tue May 19 10:45:15.920540 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'PLAY_SESSION' => '"6c1382c368ebc1e91763322742fe1580f5f5842f-disconnected_orig_uri=/search?rangetype=relative&fields=&width=1920&relative=300&from=&
[Tue May 19 10:45:15.920547 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: to=&q=102.227&sessionid=dc7cacc970718bc49fb73636d90d93e8f03db8e04ec8b143c01090da58b682742cdca11a7d67ce9aabb54645ab602adf"',
[Tue May 19 10:45:15.920552 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'SSID' => '8dqooecuvuaqk9hafbqdd9hhn3',
[Tue May 19 10:45:15.920557 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'csrftoken' => 'jteAj6iVR524ieExX0f4sH6z6bkjmBwt',
[Tue May 19 10:45:15.920563 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'filtersPopularity' => '{"resourceTypeFilter":{"resourceTypeFilter-reports":8',
[Tue May 19 10:45:15.920568 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:
[Tue May 19 10:45:15.920574 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:            'lastFolderUri' => '/Reports',
[Tue May 19 10:45:15.920579 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'pnp4nagios' => 'foq0k2r4po5jvmqf31sgiqati7',
[Tue May 19 10:45:15.920584 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'thruk_auth' => 'f6cedbbf9cfc01c2ec3d0e8b533d04ca',
[Tue May 19 10:45:15.920589 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'thruk_conf' => '328c5',
[Tue May 19 10:45:15.920594 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'thruk_favicon' => 'on',
[Tue May 19 10:45:15.920599 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'thruk_mobile' => '1',
[Tue May 19 10:45:15.920604 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:
[Tue May 19 10:45:15.920617 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                        'thruk_obj_layout' => 'table',
[Tue May 19 10:45:15.920624 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'thruk_side' => 'current_status=1&system=1&general=1&bookmarks=1&reports=1',
[Tue May 19 10:45:15.920629 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'thruk_theme' => 'Thruk',
[Tue May 19 10:45:15.920640 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                        'token' => '4-90007b88-1329-31b6-c875-d6e0c4de4457'
[Tue May 19 10:45:15.920646 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                      },
[Tue May 19 10:45:15.920651 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'plack.cookie.string' => 'thru
[Tue May 19 10:45:15.920658 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: k_side=current_status=1&system=1&general=1&bookmarks=1&reports=1; thruk_favicon=on; thruk_obj_layout=table; thruk_theme=Thruk; thruk_mobile=1; thruk_auth=f6cedbbf9cfc01c2ec3d0e8b533d04ca; thruk_conf=328c5; csrftoken=jteAj6iVR524ieExX0f4sH6z6bkjmBwt; pnp4nagios=foq0k2r4po5jvmqf31sgiqati7; PHPSESSID=g5eru81k12qul17vmoh96enma2; token=4-90007b88-1329-31b6-c875-d6e0c4de4457; lastFolderUri=/Reports; filtersPopularity=%7B%22resourceTypeFilter%22:%7B%22resourceTypeFilter-reports%22:8,%22undefined%22:0,%22re
[Tue May 19 10:45:15.920667 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: sourceTypeFilter-all%22:1,%22resourceTypeFilter-reportOutput%22:0%7D,%22timeFilter%22:%7B%22timeFilter-anyTime%22:1,%22timeFilter-today%22:0,%22timeFilter-yesterday%22:0,%22timeFilter-pastWeek%22:0,%22timeFilter-pastMonth%22:0,%22undefined%22:0%7D,%22scheduleFilter%22:%7B%22scheduleFilter-anySchedule%22:1,%22scheduleFilter-scheduled%22:0,%22scheduleFilter-scheduledByMe%22:0,%22scheduleFilter-notScheduled%22:0,%22undefined%22:0%7D,%22accessTypeFilter%22:%7B%22accessTypeFilter-all%22:1,%22accessTypeFi
[Tue May 19 10:45:15.920676 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: lter-changedByMe%22:0,%22accessTypeFilter-viewedByMe%22:0,%22undefined%22:0%7D%7D; DataSourceControllerHistory=http%253A%252F%252Fnagios3%253A8080%252Fjasperserver%252Fflow.html%253F_flowId%253DsearchFlow; PLAY_SESSION="6c1382c368ebc1e91763322742fe1580f5f5842f-disconnected_orig_uri=%2Fsearch%3Frangetype%3Drelative%26fields%3D%26width%3D1920%26relative%3D300%26from%3D%26to%3D%26q%3D102.227&sessionid=dc7cacc970718bc49fb73636d90d93e8f03db8e04ec8b143c01090da58b682742cdca11a7d67ce9aabb54645ab602adf"; SSI
[Tue May 19 10:45:15.920685 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: D=8dqooecuvuaqk9hafbqdd9hhn3; AjaXplorer=m2ok5tf859uf8fc3tljlk6pmg2',
[Tue May 19 10:45:15.920690 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'plack.request.body' => bless( {}, 'Hash::MultiValue' ),
[Tue May 19 10:45:15.920695 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'plack.request.query' => bless( {}, 'Hash::MultiValue' ),
[Tue May 19 10:45:15.920700 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'plack.request.upload' => bless( {}, 'Hash::MultiValue' ),
[Tue May 19 10:45:15.920705 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.errors' => bless( \\*Symbol::GEN2, 'IO::Handle' ),
[Tue May 19 10:45:15.920710 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.input' => bless( \\*Symbol::GEN0, 'IO::Handle' ),
[Tue May 19 10:45:15.920715 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:
[Tue May 19 10:45:15.920721 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                    'psgi.multiprocess' => 1,
[Tue May 19 10:45:15.920727 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.multithread' => '',
[Tue May 19 10:45:15.920732 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.nonblocking' => '',
[Tue May 19 10:45:15.920742 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.run_once' => '',
[Tue May 19 10:45:15.920748 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.streaming' => 1,
[Tue May 19 10:45:15.920753 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.url_scheme' => 'http',
[Tue May 19 10:45:15.920757 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgi.version' => [
[Tue May 19 10:45:15.920762 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                 1,
[Tue May 19 10:45:15.920767 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                                                 1
[Tue May 19 10:45:15.920772 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:
[Tue May 19 10:45:15.920778 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:    ],
[Tue May 19 10:45:15.920783 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'psgix.harakiri' => '',
[Tue May 19 10:45:15.920788 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'thruk.request.body' => {},
[Tue May 19 10:45:15.920793 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'thruk.request.merged' => {},
[Tue May 19 10:45:15.920797 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'thruk.request.query' => {},
[Tue May 19 10:45:15.920802 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                             'thruk.request.url' => 'http://nagios3/naemon/'
[Tue May 19 10:45:15.920807 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                           }
[Tue May 19 10:45:15.920812 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:                }, 'Thruk::Request' );
[Tue May 19 10:45:15.920821 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: $VAR3 = undef;
[Tue May 19 10:45:15.920827 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:  at /usr/share/naemon/lib/Thruk.pm line 253.
[Tue May 19 10:45:15.920832 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \tThruk::_dispatcher('Thruk=HASH(0x2211930)', 'HASH(0x47c1600)') called at
[Tue May 19 10:45:15.920838 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr:  /usr/share/naemon/lib/Thruk.pm line 195
[Tue May 19 10:45:15.920844 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \tThruk::__ANON__('HASH(0x47c1600)') called at /usr/lib/naemon/perl5/Plack/Middleware/ContentLength.pm line 10
[Tue May 19 10:45:15.920849 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \tPlack::Middleware::ContentLength::call('Plack::Middleware::ContentLength=HASH(0x45f74d8)', 'HASH(0x47c1600)') called at /usr/lib/naemon/perl5/Plack/Component.pm line 50
[Tue May 19 10:45:15.920855 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \tPlack::Component::__ANON__('HASH(0x47c1600)') called at /usr/lib/naemon/perl5/Plack/Util.pm line 142
[Tue May 19 10:45:15.920860 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \teval {...} called at /usr/lib/naemon/perl5/Plack/Util.pm line 142
[Tue May 19 10:45:15.920865 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \tPlack::Util::
[Tue May 19 10:45:15.920871 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: run_app('CODE(0x45f74c0)', 'HASH(0x47c1600)') called at /usr/lib/naemon/perl5/Plack/Handler/FCGI.pm line 143
[Tue May 19 10:45:15.920883 2015] [fcgid:warn] [pid 3269] [client 192.168.102.227:10704] mod_fcgid: stderr: \tPlack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x21f5e98)', 'CODE(0x45f74c0)') called at /usr/share/naemon/script/thruk_fastcgi.pl line 24

Is there something that is missing in my setup?

Regards

Jens

**Comment by sni** [comment]
nope, probably not. Thruk is atm in the middle of a major rewrite. I am removing Catalyst and lots of dependencies. It should be fine again in a couple of days.

**Comment by Hyllegaard** [comment]
Ok, I will see if I can roll back to the previous version.

**Comment by sni** [comment]
tests are green again, so i'd say the nightlys are good to go again.
