### ISSUE TITLE
Problems with action_menu_apply

### ISSUE THREAD

**Issue by freneticf** [sni/Thruk#483]
Hi,

I'm still struggeling with applying action menus to services and hosts

I created some action menus which are assigned by <action_menu_apply> in thruk_local.conf.
If I want to apply the menu backupmenu to any Host with the service "Backup" I need to type this:
```
backupmenu = .*;.*Backup
```
or this:
```
backupmenu = .*;Backup
```

I did expect that `.*;^Backup$` will work because that's the exact name of the service.
But this doesn't work:
```
backupmenu = .*;^Backup$
```

**Comment by sni** [comment]
fixed typo in the documentation with 816f8e2c9
It should be:
backupmenu = .*;Backup$
