### ISSUE TITLE
thruk-1.88-4.rhel6.x86_64.rpm not signed

### ISSUE THREAD

**Issue by gtorre** [sni/Thruk#484]
Hello,

I was trying to install thruk-1.88-4 for RHEL 6, x86_64 and noticed that the RPM was not signed.

Thanks,
Gennaro

**Comment by sni** [comment]
```
%> rpm -Kv thruk-1.88-4.rhel6.x86_64.rpm 
thruk-1.88-4.rhel6.x86_64.rpm:
    Header V4 RSA/SHA1 Signature, key ID a57b9ed7: OK
    Header SHA1 digest: OK (81939facdb430d9a4eb21684baf59b5cb483db9a)
    V4 RSA/SHA1 Signature, key ID a57b9ed7: OK
    MD5 digest: OK (56ff59780b2211a84a2c674908e34e29)
```

**Comment by gtorre** [comment]
@sni 
rpm -qpi thruk-1.88-4.rhel6.x86_64.rpm
Name        : thruk                        Relocations: (not relocatable)
Version     : 1.88                              Vendor: Labs Consol
Release     : 4                             Build Date: Wed 22 Apr 2015 10:41:27 AM EDT
Install Date: (not installed)               Build Host: mon-build-centos6-1-64.virt.consol.de
Group       : Applications/Monitoring       Source RPM: thruk-1.88-4.src.rpm
Size        : 105987132                        License: GPLv2+
Signature   : (none)
Packager    : Sven Nierlein <sven.nierlein@consol.de>
URL         : http://thruk.org
Summary     : Monitoring Webinterface for Nagios/Icinga and Shinken

Download from: http://download.thruk.org/pkg/v1.88-4/rhel6/x86_64/thruk-1.88-4.rhel6.x86_64.rpm

**Comment by sni** [comment]
Alright, only the packages from the repository get signed. Use this repository: http://labs.consol.de/repo/stable/ to get signed packages.
