### ISSUE TITLE
Bug - Thruk :: Business Processes :: Backslash in names

### ISSUE THREAD

**Issue by brabax** [sni/Thruk#485]
Path:
Thruk -> Business Processes -> <Process> -> Enable Edit-Mode -> Edit Node -> Details -> Label

Action:
Enter a name containing a backslash ("\").
Ex: "My Node \"

Result:
Screen becomes empty until changes are discarded.

Thruk 1.88-3 on Ubuntu

**Comment by sni** [comment]
should work with the next release.
