### ISSUE TITLE
Debian jessie Package with nginx

### ISSUE THREAD

**Issue by sponkydive** [sni/Thruk#486]
Hi,
just found 1 Problem and one not so nice thing while installing thruk-1.88-4 on jessie with nginx_full.

Not so fine:
The folder and file /etc/apache2/conf-available/thruk.conf is created,
as it exists in the package.

Problem:
Postinstall script runs a2enmod even if no apache is installed.
```
    Preparing to unpack .../thruk_1.88-4_amd64.deb ...
    Unpacking thruk (1.88-4) ...
    Processing triggers for man-db (2.7.0.2-5) ...
    Processing triggers for systemd (215-17) ...
    Setting up thruk (1.88-4) ...
    thruk plugins enabled: business_process conf minemap mobile panorama reports2 shinken_features statusmap
    /var/lib/dpkg/info/thruk.postinst: 40: /var/lib/dpkg/info/thruk.postinst: a2enmod: not found
    dpkg: error processing package thruk (--configure):
    subprocess installed post-installation script returned error exit status 127
    Processing triggers for systemd (215-17) ...
    Errors were encountered while processing:
    thruk
    E: Sub-process /usr/bin/dpkg returned an error code (1)}
```
This line in postinstall also seems not to work.
```
    # create empty crontab
    /usr/bin/crontab -l -u www-data 2>/dev/null | /usr/bin/crontab -u www-data -
```
This warning is raised during apt-get purge thruk, cause the cronjob does not exists. 
ERROR: removing cron failed, please remove www-data cron manually

**Comment by sni** [comment]
I am not really into nginx but i would accept patches for better integration.

**Comment by sponkydive** [comment]
ok.. there are some more problems when using jessie, nginx, fastcgi and thruk.
I'll gather everything and try to rebuild a working package. If done i'll commit a patch.
But it might take some time ;)

**Comment by sni** [comment]
cool, sounds good. Thanks
