### ISSUE TITLE
Stray newline causing UI to show startup error in 1.89-20150523

### ISSUE THREAD

**Issue by tkent-xetus** [sni/Thruk#487]
After we picked up the thruk update 1.89-20150523 in Ubuntu, our thruk interface started incorrectly reporting that the start up failed. Very easy to reproduce, just restart apache and try to load the interface.

Checking the code, the issue is that `startup.html` does not trim the text response before checking if the result is `'startup done'` and the output from the server is `'startup done\n'` (but the actual newline).

Since it's so use visible, and so easy to fix (just a `jQuery.trim` or a server-side trim, or both) I would consider this a P1

**Comment by sni** [comment]
Thanks, should be fixed tomorrow.

**Comment by tkent-xetus** [comment]
Much appreciated, thank you!
