### ISSUE TITLE
Nagvis maps in panorama show menu bar 

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#488]
I think that these imports should be read only because even if the dashboard is locked, one can modify the Nagvis map.
Also, Nagvis supplies some options to configure this behaviour since 1.5:

header_menu=1/0
enableHeader	Enable/Disable the header menu. Overrides the configuration.
hover_menu=1/0
enableHover	Enable/Disable the hover menus. Overrides the configuration.
context_menu=1/0
enableContext	Enable/Disable the context menus. Overrides the configuration.

Al least, "enable_menu=0" should be  added to the url when dashboard is locked.

jf

ref : http://docs.nagvis.org/1.8/en_US/user_interface.html

**Comment by sni** [comment]
i just tried with a demo map like: 
.../nagvis/frontend/nagvis-js/index.php?mod=Map&act=view&show=demo-automap&enableHeader=0&enableHover=0&enableContext=0 
but it makes no difference at all. This is Nagvis Version 1.8.

**Comment by jframeau** [comment]
hmm, yes, you're right.

Nagvis 1.8 only provides header_menu / hover_menu / context_menu options.

Using these, both header and context menus should be off.

**Comment by sni** [comment]
that worked :-)
