### ISSUE TITLE
Duplicate entry '16777215' for key 'PRIMARY' 

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#490]
Hi,
We have manage to solved this issue by replacing the integer type from MEDIUMINT to INT from the MySQL table (_plugin_output). But we are not sure what is the impact of this in the future. Any thoughts?

error from thruk.log
ERROR: DBD::mysql::db do failed: Duplicate entry '16777215' for key 'PRIMARY' at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1298. Thu Jun 18 12:09:59 2015DBD::mysql::db do failed: Duplicate entry '16777215' for key 'PRIMARY' at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line                                             1298.

**Comment by sni** [comment]
There should be no negative sideeffects. With commit  e7c07439 this already has been changed to bigint upstream. But it only applies to newly created logcaches.
Make sure you change the log and the plugin_output table to int / bigint. Not only one of them. Or remove the logcaches and let thruk recreate it (might take a while)

**Comment by jgbuenaventura** [comment]
thank you! changing the log and the plugin_output table from MEDIUMINT to INT also solves our issue with event logs in thruk.
