### ISSUE TITLE
Import log with thruk -a logcacheimport (mysql) huge memory consumption on livestatus host

### ISSUE THREAD

**Issue by mickaelmarin** [sni/Thruk#492]
I have shinken server with livestatus that store log data 's services and hosts on mongodb.
My database on mongodb called "logs" is very large (7.5 Go).
When I start the import with "thruk -a logcacheimport" I can see on my server where the livestatus reside so that the  memory grow until is full (14Gb of RAM on Shinken server with livestatus).
Of course I think thruk try to fetch all data from mongodb via livestaus before  import  in mysql db.
The same result when I try to specify the "--start=3w" for fetch less than 3 weeks of data all memory is consumed on my shinken server. 

please help me

thanks

ps: excuse me for my english

**Comment by sni** [comment]
Thruk fetches the logdata day by day. This is a know issue in the Shinken livestatus implementation and there is nothing Thruk can do about it. Also Mongodb is known to be a memory eating monster.
You could try to import the inital logfiles from the files if shinken strictly follows the nagios logformat.

**Comment by sni** [comment]
Also please use the mailing list for general questions.

**Comment by mickaelmarin** [comment]
ok thanks
