### ISSUE TITLE
Panorama : dashboard empty on first load

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#494]
Use case:
* click on panorama view
* assume we have only one dashboard, a geo map one
* add some widget
* exit for panorama view
* then return to panorama view

=> no widget displayed on dashboard

Add any dashboard, then jump to the geo map one. Widget are there.

**Comment by sni** [comment]
which version is that, cannot reproduce with the current master.

**Comment by sni** [comment]
still unable to reproduce. Could you give the latest nightly a try and if it still fails, could you export the dashboard? Private mail is ok if it contains sensitive data or just strip that out :-)

**Comment by jframeau** [comment]
This thruk-1.99-20150709.x86_64, CentOS 6.6, naemon-1.0.4_20150702-1.el6.x86_64.

I did a screencast (mpeg) with an alert in add_panlet method ( panorama/root/all_in_one-1.99-20150709_panorama.js ) to help.

https://drive.google.com/file/d/0B8ptZrCLTPLvS0FWY0gxQ1dMeW8/view?usp=sharing

**Comment by jframeau** [comment]
Some comments : all_in_one-1.99-20150711_panorama.js, createInitialPanlets method.
Original code is:
[...]
        if(this.xdata.map && (!this.mapEl || !this.map)) {
            if(this.isActiveTab()) {
                window.setTimeout(Ext.bind(this.createInitialPanlets, this, [retries+1, autoshow]), 50);
            }
            return;
        }
For unknown reason, this.isActiveTab() returns false because activeTab.id = panel-1065 even if atm, the active tab is tabpan-tab_1 (don't know where the panel-1065 comes from btw). So code jump to the 'return' hereafter.

Now, moving that 'return' up, my panorama is working nicely.

        if(this.xdata.map && (!this.mapEl || !this.map)) {
            if(this.isActiveTab()) {
                window.setTimeout(Ext.bind(this.createInitialPanlets, this, [retries+1, autoshow]), 50);
                return;
            }
        }
I'm not sure to understand all the logic behind that peace of code, so just my two cents.

**Comment by sni** [comment]
Please reopen the issue if this still fails. I'd say it should work with the latest release.
