### ISSUE TITLE
Panorama Acknowledge

### ISSUE THREAD

**Issue by koizo** [sni/Thruk#495]
Hello,
Can we enable spaces " " on comments, on the acknowledge panel on panorama service dashboards?

Best Regards

**Comment by sni** [comment]
what do you mean?

**Comment by koizo** [comment]
On the Comment text box, spacebar is disabled

![thruk](https://cloud.githubusercontent.com/assets/1348501/8548691/2b930388-24be-11e5-846d-077b47347374.jpg)

**Comment by sni** [comment]
should be fixed with the next release. thanks
