### ISSUE TITLE
Auth broken after upgrade to v2

### ISSUE THREAD

**Issue by akrus** [sni/Thruk#497]
Hi,

After upgrading to Thruk v2 I can no longer login to Thruk - it's just showing me login form, while we use SSL authentication (use_ssl_authentication=1 in cgi.cfg). Logs are empty :(

**Comment by sni** [comment]
Please use the mailing list for such things unless its really a bug. This sounds more like a configuration problem. It should be ok again if you comment the cookie auth includes in your thruk apache config.

**Comment by BjornIngi** [comment]
Hi,

After upgrading to Thruk v2 I can't open Thruk anymore, it says "You are not authorized. It seems like you are not authorized.".  Can you please tell how to rollback to previous package and undo the changes made by the update process.
