### ISSUE TITLE
Migration to 2.0 adding a backend.

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#500]
CentOS
Naemon 1.0.4

After migration to 2.0, a new folder named thruk_local.d is added which contains two files:
* _migrated_naemon_thruk_local.conf
* naemon.conf

But naemon.conf defines a backend named Naemon and then doubles hosts and services in Thruk interface.

The same with Nagios installation has no issue.

**Comment by sni** [comment]
i will close this since it is a one time issue and i don't have any resources to look into this.
