### ISSUE TITLE
Enhancement request: make sound alarms dependent on the display filter

### ISSUE THREAD

**Issue by Corbyn** [sni/Thruk#501]
Hi,
it is quite confusing that sound alarms are played, even if no alerts are displayed.
That's because of sound alarms are only triggerd by the totals and do not respect the current display filter.
IMHO, it would be much better to make sound alarms dependent on the filter of the page you are currently watching (e. g. unhandled problems, only hard states).

**Comment by sni** [comment]
The alarm sounds should respect the filter as far as possible, however they do not respect the paging. So they trigger an alarm, even if the failed service/host is not on the current page. Maybe this is the case here?

**Comment by Corbyn** [comment]
As far as I could make out the details, it's because sound alarms are triggered by the Status Totals and not by the Status Details. And the Status Totals don't use the complete filter: host-/serviceprops aren't considered.
