### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by BjornIngi** [sni/Thruk#504]
Hi,

After upgrading to Thruk v2 I can't open Thruk anymore, it says "You are not authorized. It seems like you are not authorized.".
Can you please help me to get Thruk working again or tell me how to rollback to previous package and undo the changes made by the update process.

**Comment by danielitus** [comment]
Same problem here. I have to set the setting default_user_name to guest, but this is not the best.
Tried to change this setting to nothing and the result is not authorized. 
Please some one can help us with this problem?

**Comment by BjornIngi** [comment]
Hi
The solutions for us was to rename/disable "thruk_cookie_auth_vhost.conf" in folder conf.d and restart apache.

**Comment by danielitus** [comment]
It worked!

Thanks!

**Comment by jgwinner** [comment]
Well, I ran into the same error and the fix, above, didn't work.

Plain vanilla install of Shinken on RHEL, and tried to install Thruk the same way.

I get essentially the same error when I do thruk start -v.

Any ideas?

== John ==

**Comment by Seegras** [comment]
I use nginx, and I also get this. So that hasn't anything to do with apache configs.
