### ISSUE TITLE
A problem with parsing action menu items

### ISSUE THREAD

**Issue by kbbl1977** [sni/Thruk#505]
Hello,
after upgrade to thruk 2.00 my action menu does not work as on previous version (1.86-3 Centos x86_64 package)
Instead of specified icon, only a warning icon appear with a warning text in title.
The warning text can be read in server log and goes like this:
> [Thruk] error in action menu: , or } expected while parsing object/hash, at character offset 231 (before ":"_blank"},{"icon":"...") at /usr/share/thruk/lib/Thruk/Utils/Filter.pm line 452.`

I've found this is caused by character `#` in a link URL
whole action menu item looks like this:
> {"icon":"/thruk/themes/{{theme}}/images/logos/some_icon.png",\
> "label":"Some Label",\
> "action":"https://some.domain/\#/some/path/$HOSTNAME$",\
> "target":"_blank"},\

The `#` had to be escaped in thruk 1.86, however with thruk 2.00 this does dot work.

I've already discussed that with colleagues and this far it is importanat, that url contain the `#` character.

I also tried to do "url-escaping" of that character by defining
> "action":"https://some.domain/%23/some/path/$HOSTNAME$",\

the browser displayed the link correctly with `#` character, but after clicking the link, the URL bar just displayed url exactly with `%23` string and link did not work.

Is there any other way to escape that particular character?

Many thanks for help
Tomas Novosad

**Comment by sni** [comment]
I will have a look after my vacation. Its most likely a problem in the new config parser.

**Comment by kbbl1977** [comment]
Thanks, for reply.
This is just a small problem, no need to hurry about that.

Enjoy Your free time

**Comment by kbbl1977** [comment]
uff, i see now that i have accidentally closed the issue.
My mistake - reopening

**Comment by sni** [comment]
should be fixed now
