### ISSUE TITLE
textlabel position not saved

### ISSUE THREAD

**Issue by freneticf** [sni/Thruk#506]
Hi,

after the upgrade from 1.84 to 2.00 in the panorama view the positon (mouse click) of new textlabels will not be saved. The labels appear in the upper left corner.

    "layout" : {
       "scale" : 100,
       "x" : "",
       "y" : "",
       "zindex" : "0"
    },

This happens with new and existing, pre-2.00 dashboards.

Regards,
Frank

**Comment by pokotilenko** [comment]
Same issue here with 1.88-4.
Here is a workaround: change position by dragging while settings dialog is open and on Layout tab. Or change x,y directly on Layout tab

**Comment by freneticf** [comment]
My colleges told me that this issue was there before. They set x,y directly.
In 2.00 x,y do not change in the opened settings dialog while dragging the text label.

**Comment by pokotilenko** [comment]
Just re-checked in online demo (2.00). x,y DO change IF the settings dialog is opened on LAYOUT tab.

**Comment by freneticf** [comment]
Confirmed. x,y DO change IF the settings dialog is opened on LAYOUT tab. I was on the LABEL tab and there are the offset settings.
But the initial x,y values from the mouse click were not saved. The fields are empty.

**Comment by sni** [comment]
should be fixed now.
