### ISSUE TITLE
Panorama: Text labels are not displayed after F5 if there is BP on dashboard

### ISSUE THREAD

**Issue by pokotilenko** [sni/Thruk#509]
I noticed strage behaviour of panarama: if it contains BP panlet then all text labels are not normally displayed.
After F5 I can bring text labels back by switching to another board and then back. And I found no way to bring them back in "direct" mode.
I have this problem on 1.88-4, and it is also reproducable on online demo with 2.0

**Comment by sni** [comment]
I don't think this is related to the Business Process but there where general problems with text labels which are resolved. I cannot reproduce this right now. Could you verify it's still broken?
