### ISSUE TITLE
duplicate logrotate rule

### ISSUE THREAD

**Issue by Vebryn** [sni/Thruk#511]
Hi,

After package installation, there is 2 files into logrotate.d dir : 
* thruk
* thruk-base

In repo, we see many files related to logrotate rules : 
* support/0006-logrotate.patch
* support/thruk.logrotate
* debian/thruk-base.logrotate

thruk-base.install is mentionning /etc/logrotate.d/thruk file.

**Comment by sni** [comment]
the "thruk" file is probably a leftover from thruk 1.x. If not removed automatically by the update process you can safely delete it manually.

**Comment by flyinva** [comment]
thruk-base provides the two files

``` 
dpkg -S /etc/logrotate.d/thruk
thruk-base: /etc/logrotate.d/thruk
dpkg -S /etc/logrotate.d/thruk-base
thruk-base: /etc/logrotate.d/thruk-base
``` 

logrotate also complains about permissions on `/var/log/thruk` and  `/var/cache/thruk/`. I had to add in those files :

``` 
su www-data www-data 
```

**Comment by sni** [comment]
ok, thats definitly wrong then.

**Comment by sni** [comment]
The su thing is a separate issue, see #471

**Comment by sni** [comment]
should be fixed now, thanks
