### ISSUE TITLE
Thruk not starting up and showing Authorization failed

### ISSUE THREAD

**Issue by SricharanKattamanchi** [sni/Thruk#516]
Hello,

I am using thruk 1.68 over nagios for accessing the consoles. This was installed and running since 2013 but I had added a new config to nagios and after that thruk is not starting up. I have deleted those configurations but still no use.

I am not able to start thruk and it failed with an error as below.

[root@clrfmd1 conf.d]# service thruk start
Starting thruk.....failed
Setting --timeout (timeout) to 15
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.12 on linux-gnu.

--2015-08-14 08:10:20--  http://localhost/thruk/cgi-bin/remote.cgi?startup
Resolving localhost... 127.0.0.1, ::1
Caching localhost => 127.0.0.1 ::1
Connecting to localhost|127.0.0.1|:80... connected.
Created socket 3.
Releasing 0x0000000002463e10 (new refcount 1).

---request begin---
POST /thruk/cgi-bin/remote.cgi?startup HTTP/1.0
User-Agent: Wget/1.12 (linux-gnu)
Accept: */*
Host: localhost
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 2

---request end---
[POST data: '']
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 401 Authorization Required
Date: Thu, 13 Aug 2015 22:10:20 GMT
Server: Apache/2.2.15 (Red Hat)
WWW-Authenticate: Basic realm="Thruk Monitoring"
Vary: Accept-Encoding
Content-Length: 477
Connection: close
Content-Type: text/html; charset=iso-8859-1

---response end---
401 Authorization Required
Closed fd 3
Authorization failed.

I can see below error in Apache error.log

[Fri Aug 14 05:32:31 2015] [warn] [client 10.23.196.207] mod_fcgid: read data timeout in 120 seconds, referer: http://clrfmd1/thruk/startup.html?/thruk/
[Fri Aug 14 05:32:31 2015] [error] [client 10.23.196.207] Premature end of script headers: fcgid_env.sh, referer: http://clrfmd1/thruk/startup.html?/thruk/

I tried to then run the startup script manually with apache user and got below output which seems fine.

su - apache -c "/usr/share/thruk/fcgid_env.sh"
STDIN is not a socket: specify a listen location at /usr/lib/thruk/perl5/Plack/Handler/FCGI.pm line 48.

I tried to modify the permissions /var/log/thruk, /var/cache/thruk, /var/lib/thruk to nobody but stil tthruk is not coming up. 
I tried a lot to find the issue and google it but there wasnt lucky to find a resolution.

Could someone please advise how I can resolve this issue and get thruk started?

Your response is much appreciated.

**Comment by sni** [comment]
Hi,

your version is rather old. The 1.68 was released over 2 years ago. This bug tracker is only for the latest releases. So i recommend upgrading your installation which probably resolves the problem anyway.

Cheers
