### ISSUE TITLE
rewrite long commands by the thruk gui removes the last option

### ISSUE THREAD

**Issue by tsoehl** [sni/Thruk#518]
Hi

When thruk rewrites long commds it removes the last option:

@@ -1,7 +1,14 @@
 define command{
-
         command_name    check_snmp_traffic_device
-
-        command_line    $USER2$/check_snmp_int.pl -H $HOSTADDRESS$ -C $ARG1$ -w 300000,300000 -c 300001,300001 -n '$ARG2$' -k -f -Y -B -r
-
+  command_line                   $USER2$/check_snmp_int.pl \
+                                    -H $HOSTADDRESS$ \
+                                    -C $ARG1$ \
+                                    -w 300000,300000 \
+                                    -c 300001,300001 \
+                                    -n '$ARG2$' \
+                                    -k \
+                                    -f \
+                                    -Y \
+                                    -B
         }
+

Tested with Version 1.88-2

**Comment by sni** [comment]
thanks, should be fixed now.
