### ISSUE TITLE
Upgrade 2.00-2 SLA Report issues

### ISSUE THREAD

**Issue by praktikant1** [sni/Thruk#521]
Hi,

I upgraded Thruk to version 2.00-2. 
Since the Upgrade the SLA Overview Graph in service reports disappeared.
I also customized my Reports, with the update my css file (custom.tt) and changes on the file page_cover.tt were overwritten, but I also built a own template, this wasn't overwritten.

**Comment by sni** [comment]
Custom templates need to copied and edited in the user_template_path otherwise they will be overwritten with the next package update.
