### ISSUE TITLE
Selinux 

### ISSUE THREAD

**Issue by gramimoss** [sni/Thruk#522]
HI

I could not believe my eye's when I updated Thruk and get prompted the following message

```
Thruk will not work when SELinux is enabled
SELinux: Enforcing
```
This is a protection how can you tell us to turn off a security function. Please could you take the time to apply SElinux rules so that you don't leave every Centos / Red hat server open to attacks.

**Comment by gramimoss** [comment]
For now the only SELinux deny i can see if the following which can be easily fixed by a setsebool command

```
type=AVC msg=audit(1441606545.597:11818): avc:  denied  { fowner } for  pid=7357 comm="perl" capability=3  scontext=unconfined_u:system_r:httpd_t:s0 t                                                context=unconfined_u:system_r:httpd_t:s0 tclass=capability

        Was caused by:
        The boolean httpd_run_stickshift was set incorrectly.
        Description:
        Allow Apache to run in stickshift mode, not transition to passenger

        Allow access by executing:
        # setsebool -P httpd_run_stickshift 1
```

**Comment by sni** [comment]
I am not telling you anything. It's just a message saying it won't work. The decission is up to you and so far nobody complained. I sure agree it would be nice to have a SELinux integration, but i don't need
it and i don't have ressources for that. But i would accept patches which would make Thruk work with
SELinux, even if that means that i get propably a lot more support tickets.
Thruk does a lot of things, it creates reports, it runs htpasswd to let users change their passwords, it has an object configuration editor which writes files in /etc and probably a lot of things more. So i
assume it takes at leas 1-2 weeks for a proper SELinux integration which is tested on Centos 5, 6 and 7.
