### ISSUE TITLE
Add ack_no_sticky option to Thruk.

### ISSUE THREAD

**Issue by jacobamey** [sni/Thruk#523]
In Nagios 4.1.1 we now have the abilty to set the default sticky acknowledgment to off..

Location /usr/local/nagios/etc/cgi.cfg

378 # DEFAULTS FOR CHECKBOXES FOR ACKNOWLEDGEMENTS
379 # Enabling ack_no_sticky will default the "Sticky Acknowledgement" to 
380 # be unchecked.
381 # Enabling ack_no_send will default the "Send Notification" to 
382 # be unchecked.
383 
384 #ack_no_sticky=0
385 #ack_no_send=0

setting ack_no_sticky=1 sets the check mark default to be off.

It would be great if this was applied to thruk allowing us to utilize this feature.

**Comment by sni** [comment]
You can do that already:
http://thruk.org/documentation/configuration.html#command-settings

**Comment by jacobamey** [comment]
Oh Nice! Thanks, I was grep'ing for the wrong thing.
