### ISSUE TITLE
Feature Request: Configuration Export

### ISSUE THREAD

**Issue by gitmopp** [sni/Thruk#527]
On the thruk homepage the link Development -> Ideas / Feature Requests does not work anymore, so I' m posting it here.

It would be nice to export the System -> Configuration to Excel
I was able to add the button to templates/config_hosts.tt using
[% PROCESS _excel_export.tt columns=[ 'Host', 'Address' ] %]
but the export didn' t include any data.

**Comment by sni** [comment]
Thanks for the hint. Didn't know that google had shutdown the featues service. I removed that link from the navigation.
Why don't you use the excel export from the host or services list. Its basically the same information as on the config page.

**Comment by gitmopp** [comment]
Maybe my example with Host and Address was not optimal, in general it would be helpful to export some more advanced configuration settings like check_command, notification contacts, and check period to Excel. Excel has some good filters to search for configuration mistakes.
I know it is possible to do a simple copy & paste, but an export button is even more convinient.
