### ISSUE TITLE
Graphite integration name mangling doesn't match graphios' name mangling

### ISSUE THREAD

**Issue by ozamosi** [sni/Thruk#530]
I'm using graphios 2.0 to push perfdata into graphite.

Graphios removes all spaces from service descriptions, and then replaces all remaining non-alphanumeric characters with _. Thruk's service description mangling when graph_word matches my action_url replaces all non-alphanumeric with _, including spaces. This means about half of my checks claims that there is no data, when graphite does contain it, just under a different name.

If I could change [this regex](https://github.com/sni/Thruk/blob/b869c3/lib/Thruk/Utils.pm#L1413) in a config file, that would fix my problem.

**Comment by sni** [comment]
You could just fix it directly in the code. You probably need to change https://github.com/sni/Thruk/blob/b869c3/lib/Thruk/Utils.pm#L1408 too. Since all this "graph_word" thing is just about graphite, there is no need for a config option. I'd say its ok to just fix it.

**Comment by sni** [comment]
fixed with #531
