### ISSUE TITLE
Include line into default vhosts

### ISSUE THREAD

**Issue by Vebryn** [sni/Thruk#532]
Hi,

With Thruk 2, package adds thruk_cookie_auth_vhost.conf into apache conf.d dir. It also adds a line into all default vhosts.

Why does include line required into default virtual hosts ? Any method to only use conf file ?

```
# activate cookie in existing default virtual hosts
set +e
ls -1 /etc/apache2/sites-available/*default* | \
while read file; do
    if ! grep thruk_cookie_auth.include $file >/dev/null 2>&1; then
        sed -i -e 's|</VirtualHost>|\n    Include /usr/share/thruk/thruk_cookie_auth.include\n</VirtualHost>|g' $file
    fi
done
set -e
```

Thank you,

Best regards.

**Comment by sni** [comment]
VirtualHosts do not inherit rewrite rules from the global config. That's why there has to be one
include for each vhost.
