### ISSUE TITLE
Any plugin to view hostgroup summary view like tree view...

### ISSUE THREAD

**Issue by kkdk5535** [sni/Thruk#533]
Svn
Any thruk plugin available today to list hostgroup summary like a tree view(linux command), if not how easy is it to instrument and implement it in thruk? Can you share some insight on plugin development guidelines. I am looking for detail guidelines like the one we have for instrumenting new [Nagios Plugins]( https://nagios-plugins.org/doc/guidelines.html)

Something like,
```
hostgroups       total hosts
   OS                180/1500
       |
       --   linux    980/1000
                  |
                  -- centOS-6      10/190
                  |
                  -- redhatOS-6   10/590
                  |
                  -- redhatOS-7    100/100
       |
       -- AIX       480/500
              |
              -- aix-52   50/350
              |
              -- aix-57   10/140
```

**Comment by sni** [comment]
There is http://thruk.org/documentation/plugins.html#writing-your-own-plugins so far. The existing plugins should be a good start to read how plugins are written. They are not that complicated. And no, i don't know any plugin like that.

**Comment by kkdk5535** [comment]
@sni Thanks for quick response. I will check existing plugins and see if I can managed to build one.
