### ISSUE TITLE
Install on debian

### ISSUE THREAD

**Issue by rabi29** [sni/Thruk#534]
Hello,

Sorry for my question and english too;
I m new user of debian and linux.
I dont no how install Thruk with Makefile.pf. I try perl Makefile.pl but
////////////////////////////////////////////////////////////////////////////////////////////////////////
Can't locate inc/Module/Install.pm in @INC (you may need to install the inc::Module::Install module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at Makefile.PL line 3.
BEGIN failed--compilation aborted at Makefile.PL line 3.
///////////////////////////////////////////////////////////////////////////////////////
I search with google friend but no answer.

thank you

**Comment by sni** [comment]
Please use the mailing list for this kind of questions. The issue tracker is mostly for issues and bugs.
Also please use the packages if you are not used to Perl.
