### ISSUE TITLE
Trouble with sorting in Panorama

### ISSUE THREAD

**Issue by ShadowScorpion** [sni/Thruk#535]
Hello,

I have some issue with sorting items in Thruk Panorama.
I created the table with hosts and want to sort it by "up" or "down" status, but can't. I can to separate them by groups, but what I must do, to show at the first down hosts and after the up.

![panorama](https://cloud.githubusercontent.com/assets/4012947/10689542/b50e9a3a-7984-11e5-9363-fb445aad87b0.PNG)

P.S. If i clicking by status button, nothing happens.

Thanks.

**Comment by sni** [comment]
I don't think thats possible. The table header only sorts the data which is displayed already. But if there
are more hosts and the data is paged, then sorting still only sorts the data from the first page.
