### ISSUE TITLE
Question on csrf_allowed_hosts and requiring POSTs instead of GETs

### ISSUE THREAD

**Issue by pebtron** [sni/Thruk#536]
Thruk 2.02, lib/Thruk/Utils.pm lines 2300-2339, the logic says that if the request is not a POST, error out. If it is a POST then obey csrf_allowed_hosts and continue on. Is the purpose of csrf_allowed_hosts to selectively allow GET requests *and* hosts without a csrf token, or are GET requests strictly forbidden now? My (older) iPhone app can no longer acknowledge alerts since it's still sending GET requests.

**Comment by sni** [comment]
The idea is, that all Request which change something should be POST requests and they are 
protected by csrf token (unless deactivated). Only views and non-changing requests can be GET 
requests.

**Comment by pebtron** [comment]
Ok thank you. I'll submit a feature request with the developer of the iPhone app "On Call" that's using GETs for acknowledgements.
