### ISSUE TITLE
Settings ignored when put after Component section in thruk_local.conf

### ISSUE THREAD

**Issue by X-dark** [sni/Thruk#538]
It seems settings put in _thruk_local.conf_ after the `<Component>` section are being ignored.

I was trying to set a `graph_word` and struggled a long time before finding it was not working as it was just ignored.

It works fine when put in _thruk.conf_ or before the `<Component>` section.

**Comment by sni** [comment]
do you have an example?

**Comment by X-dark** [comment]
My example was with ```graph_word``` but try to change any setting through the webinterface (like one of the ```group_paging``` settings), you will see it is not getting applied (as it is put after the ```Component``` section in *thruk_local.conf*).

**Comment by sni** [comment]
Maybe something is wrong in the `<Component>` section. Do you have a simple config snippet which is parsed wrong?

**Comment by X-dark** [comment]
I have no longer access to this deployment and I do not currently use Thruk. Sorry.
