### ISSUE TITLE
Contact Group is missing from Configuration View Hosts and Services

### ISSUE THREAD

**Issue by gitmopp** [sni/Thruk#539]
The Configuration View System -> Configuration -> Hosts / Services does not show Contact Groups.

The column contact_groups is missing for hosts and services.
Current hosts live status query without contact_groups:
GET hosts
Columns: accept_passive_checks acknowledged action_url action_url_expanded active_checks_enabled address alias check_command check_freshness check_interval check_options check_period check_type checks_enabled childs comments current_attempt current_notification_number event_handler event_handler_enabled execution_time custom_variable_names custom_variable_values first_notification_delay flap_detection_enabled groups has_been_checked high_flap_threshold icon_image icon_image_alt icon_image_expanded is_executing is_flapping last_check last_notification last_state_change latency long_plugin_output low_flap_threshold max_check_attempts name next_check notes notes_expanded notes_url notes_url_expanded notification_interval notification_period notifications_enabled num_services_crit num_services_ok num_services_pending num_services_unknown num_services_warn num_services obsess_over_host parents percent_state_change perf_data plugin_output process_performance_data retry_interval scheduled_downtime_depth state state_type modified_attributes_list last_time_down last_time_unreachable last_time_up display_name in_check_period in_notification_period contacts
OutputFormat: json
ResponseHeader: fixed16

Can you please extend the query to support contact_groups.

**Comment by sni** [comment]
This is not possible because the undelying Livestatus API does not support that. And thats because Nagios does not support that. ContactGroup are resolved during startup of Nagios and do not exist
during runtime anymore.

**Comment by gitmopp** [comment]
I'm using  mk-livestatus-1.2.6p12 and the following command returns the contacts and contact_groups:
 echo -e "GET hosts\nColumns: Columns: address contacts contact_groups\n" | unixcat /usr/local/nagiosxi/var/subsys/livestatus

**Comment by sni** [comment]
good to know :-) just tried with the opensource core and livestatus 1.2.6p12 and it works there too.
However, this is still a new feature, so it would be complicated to add it without breaking any existing
setups.

**Comment by gitmopp** [comment]
It might work without breaking anything, because if you request a column which does not exist it is empty.

**Comment by sni** [comment]
not with older livestatus releases, you get no result at all and an error is logged like:
error: Table 'hosts' has no column 'Columns:'
(From your example command line)

**Comment by gitmopp** [comment]
As a last idea, maybe it would be possible to have two backends. Livestatus and Livestatus_new. Livestatus_new will support the new functions and new functions which might be available in the future.

**Comment by sni** [comment]
Thats ugly. But you could add a if clause like here:
https://github.com/sni/Thruk/blob/master/lib/Thruk/Controller/cmd.pm#L397

**Comment by gitmopp** [comment]
Sorry, but it was not possible for me to find the place where the query / coloumns were created. So I didn' t manage to add it.

**Comment by gitmopp** [comment]
I almost figured out how to get it working. Maybe you can help with the last steps.
Livestatus supports contact_groups since 16 Aug 2011 http://git.mathias-kettner.de/git/?p=check_mk.git;a=commit;h=9b0a27252143050f529f12bcf3cd522a4cc49dbf

I have no detection for the right livestatis version.
One problem is with the host table, the displayed data is correct, but it does not work to hide/show coloumns.

./lib/Thruk/Controller/config.pm:
71c71
<         $c->{'db'}->get_hosts(sort => 'name', remove_duplicates => 1, pager => 1, extra_columns => ['contacts'], filter => $filter );
---
>         $c->{'db'}->get_hosts(sort => 'name', remove_duplicates => 1, pager => 1, extra_columns => ['contacts', 'contact_groups'], filter => $filter );
81c81
<         $c->{'db'}->get_services(sort => [ 'host_name', 'description' ], remove_duplicates => 1, pager => 1, extra_columns => ['contacts'], filter => $filter);
---
>         $c->{'db'}->get_services(sort => [ 'host_name', 'description' ], remove_duplicates => 1, pager => 1, extra_columns => ['contacts', 'contact_groups'], filter => $filter);

./templates/config_hosts.tt:
14a15
>     <th class='data'>Contact Groups</th>
90a92,93
>     <td class='[% class %]'>[% FOREACH contact_group = d.contact_groups.sort %][% IF !loop.first() %] , [% END %]<a href="config.cgi?type=contactgroups&amp;jump=[% contact_group | uri %]#[% contact_group | uri %]">[% contact_group %]</a>[% END %]</td>
>     <td class='[% class %]'>[% d.max_check_attempts %]</td>

./templates/config_services.tt:
18a19
>     <th class='data'>Contact Groups</th>
89a91
>     <td class='[% class %]'>[% FOREACH contact_group = d.contact_groups.sort %][% IF !loop.first() %] , [% END %]<a href="config.cgi?type=contactgroups&amp;jump=[% contact_group | uri %]#[% contact_group | uri %]">[% contact_group %]</a>[% END %]</td>
[root@localhost thruk]# diff ./templates/config_hosts.tt.orig ./templates/config_hosts.tt
14a15
>     <th class='data'>Contact Groups</th>

**Comment by sni** [comment]
if its from 2011, then i'd say we do not need to check the version and just assume it will work.

**Comment by gitmopp** [comment]
I tested it again, this time it worked to show / hide the columns.
Can you integrate the patch from above? Or should I create a pull request.

**Comment by sni** [comment]
Please always create a pull request.

**Comment by sni** [comment]
thanks, i merged it
