### ISSUE TITLE
Performance Graph: timerange changes by changing the dataseries

### ISSUE THREAD

**Issue by Griesbacher** [sni/Thruk#542]
First change the timerange to something else than day
![thruk1](https://cloud.githubusercontent.com/assets/12564488/11143152/66a72d6a-89f3-11e5-9b9e-522830f7faae.PNG)
Change the dataseries
![thruk2](https://cloud.githubusercontent.com/assets/12564488/11143187/a6e265f2-89f3-11e5-9e21-1cff42e9e75a.PNG)
--> the timerange goes back to default day, but in the timepicker month is still selected

**Comment by sni** [comment]
it's fixed now, thanks
