### ISSUE TITLE
Thruk Report PDF size

### ISSUE THREAD

**Issue by dennis0212** [sni/Thruk#545]
Hallo, seid der aktuellen Version ist anscheinend das Problem mit dem verschwinden der Reports gelöst, aber leider sind nun PDF Reports abgeschnitten. Die röße (Breite) wird einfach abgeschnitten. Kann man das wieder beheben?

Hello , are the current version seems to be the problem with the disappearance of reports released , but unfortunately PDF reports are now cut off . The Size ( width ) is simply cut off . Can this be fixed again ?

**Comment by sni** [comment]
Do you have an example? Are you using the standard reports? How did you install Thruk, means, which
phantomjs is this, the shiped one or your own.

Btw, please keep the issues in english, so everybody is able to read and answer.

**Comment by dennis0212** [comment]
![24 11](https://cloud.githubusercontent.com/assets/15977233/11365335/f0b84baa-92a5-11e5-9636-679e3e40fc2b.png)


first is now
last is old

**Comment by dennis0212** [comment]
Okay I have Found the Error.

/usr/share/thruk/script/html2pdf.js

In this file is the zoomFactor to 1.5 (this is the Error!!)

    page.paperSize = { format: 'A4', orientation: 'portrait', margin: '0'  }
    // workaround for html page being too small
    page.zoomFactor = 0.5;

Change to 0.5 and the Reports are okay.

**Comment by sni** [comment]
This breaks all other reports. Seems like this value must be dynamically changed for url reports.

**Comment by dennis0212** [comment]
yes the SLA Reports is break!

**Comment by dennis0212** [comment]
who can change this for url reports?
