### ISSUE TITLE
Clickable customvar uses wrong status style detail when its a service

### ISSUE THREAD

**Issue by emcepe** [sni/Thruk#550]
wenn ich auf einem Service bin (extinfo.cgi) welcher eine customvar hat, die nun klickbar ist, dann geht der Link auf /thruk/cgi-bin/status.cgi?style=hostdetail, findet da nichts, weil das natürlich nicht der Host ist auf dem die customvar ist sondern der Service. Gehe ich beim Displayfilter dann auf Service details werden die Services gefunden die die customvar gesetzt haben

**Comment by sni** [comment]
Please try again. It should only link to the hostlist if the variable comes from a host. For service custom variables the service list should be linked.
