### ISSUE TITLE
thruk auth cookie path shouldn't include trailing slash

### ISSUE THREAD

**Issue by mattpr** [sni/Thruk#551]
Currently cookie path is set to /naemon/.  I believe this issue can be simply resolved by changing the path set in the auth cookie without the trailing slash.

## If I navigate to `http://monitor-host/naemon/` 
- I get the login screen
- POST login form
- auth cookie is set for path `/naemon/` 
- am redirected to `/naemon/` which receives the cookie 
- dashboard is shown

## If I navigate to `http://monitor-host/naemon` (no trailing slash)
- I get the login screen
- POST login form
- auth cookie is set for path `/naemon/` 
- am redirected to `/naemon` which **doesn't** receive the cookie
- I am redirected back to login screen

This is an issue with the 1.0.3 release of Naemon/thruk installed via RPMs for 64bit centos 6.

My user-agent is in the following screenshots (showing both the above cases).

## With trailing slash
![thruk-with-slash](https://cloud.githubusercontent.com/assets/1196252/11534686/2b5440a0-9910-11e5-9556-fe54a04c6caa.png)

## Without trailing slash
![thruk-no-slash](https://cloud.githubusercontent.com/assets/1196252/11534685/2b53e92a-9910-11e5-9188-2817bd8b3195.png)

**Comment by sni** [comment]
I'd say this is fixed in the nightly version of naemon already. Problem is, that either Firefox or Chrome or IE ( i cannot remember ) did not send the cookie if it does not contain the trailing slash. Latest Naemon should therefor just redirect naemon to naemon/

**Comment by mattpr** [comment]
Thanks for the quick update.
