### ISSUE TITLE
Unable to filter from Icinga2's livestatus API

### ISSUE THREAD

**Issue by TheFlyingCorpse** [sni/Thruk#552]
Thruk 2.04 on SLES 11 SP2, Icinga 2.4 on Debian 8.2:
For some reason Thruk does not allow me to filter using custom variables from Icinga2's livestatus output.

I have enabled printing all values and Thruk successfully prints the associated custom variables with the names as values. Copying what it reports as the value for the filtered value does not work as expected.

Tested the Monitoring::Livestatus plugin against Icinga2 livestatus and it returns the expected data from what I can understand, it looks similar for the custom variables. 
Testing the same simple "GET hosts" returns identical data structures for what I want to get from Icinga 1.x's livestatus.

The suggestion box for the name of the value is returned as expected, however I am not able to filter on the values even if I can see that Thruk sees them properly.

**Comment by sni** [comment]
Thruk just sends the filter to icinga, using the default config from a new installation, it sends this query for ex.:
```
GET hosts
Filter: custom_variables = OS Linux
```
Which works with other cores but not with Icinga 2, so i'd assume this is not implemented in Icinga 2.
