### ISSUE TITLE
Multiple Backends Issue : Multiple comments (doublons) when acknowledging

### ISSUE THREAD

**Issue by fullmetalucard** [sni/Thruk#553]
Hello,

We recently noticed that in multiple-backends platforms, we had doublons in the comments when adding an acknowledgment or adding a single comment.

Here is the scenario (thruk 2.0 and 4 shinken backends in 2.4 version):

- type hostXX in the search bar
- once you get the host, select a service and add a comment
- then go to the details of the concerned service
- you 'll see 4 comments
###

All we can say is that we've been testing several things such as:

- with older or newer version of thruk, we have the same behavior
- with older or newer version of shinken, we have the same behavior
- when trying on a platform with only two backends, we also get doublons, but only two.
- Before adding a comment, we disable the backends (at the top of thruk's interface), and the we see that the comment is uniq  this time.

So we found out that the number of doublons is related to the number of realms/backends.

Could you please test it and see if there's a workaround, because it is very annoying on platform with a lot of backends, so people won't have to switch off all their backends before acknowledging an alarm.

Thanks for your help.

Regards,

**Comment by sni** [comment]
I'd say this is a problem in shinken, because i didn't see this behaviour in any of our installations before.
Are this multiple shinken installation combined by in a single Thruk view or is this a distributed shinken
installation with multiple realms. In case of the distributed installation, i guess you have to add this as
one Backend in Thruk. If you have multiple livestatus broker in that connected installation and send the
command to all of them, then you probably get the behaviour which you currently see.
I don't have a multi-tier shinken installation anywhere, so i cannot test this right now.

**Comment by fullmetalucard** [comment]
Yes, we are in a case with 4 realms declared as backend in Thruk. Each realm has its own broker/livestatus, so we have to declare them in thruk's backends in order to see the hosts they manage.
As you say, maybe the only way to do it properly with shinken is to have only  one broker-master declared as a backend in thruk and several broker "slaves" and only one livestatus related to this broker-master.

**Comment by fullmetalucard** [comment]
Hello,

In my opinion, the fact that thruk sends the comment to multiple backends at the same time could be changed.
When we go to through the details of a service by clicking on it, thruk disables the other backends that are not concerned at the top of the interface. In this case, acknowledgement is well done and sent to only one livestatus, the one that manages the service we chose.
So thruk knows how to communicate with the right backend/livestatus.

So it should be possible at the "superior" level to do the same.
For example, a scenario
- type hostXX in the search bar
- once you get the host, select a service and add a comment
- thruk should precisely know to which backend it has to send the order (when selecting the service, before getting the action popup, on mouse over, we see an URL which contains the right backend ID.
Something like http://mysupervision/thruk/cgi-bin/extinfo.cgi?type=2&host=MYHOST&service=Partition%3A %2Fvar&backend=d8966

The ID "d8966" is the right one, so i guess it should be sent only to him.

Could you take a look at it again please?
I know this is a specific interaction between thruk and shinken, but we know several people with distributed shinken infrastructures who have the same problem.

The architecture of those huge infrastructures cannot be changed so easily, managing only one broker/livestatus for a whole very big  infrastructure is not that simple.

Thanks for your help.

Regards,

**Comment by sni** [comment]
Thruk already sends the command only to the selected backends. So if you select 10 services and add a comment for all of them, then thruk checks the backend for each service and sends the command only to
that combination of backend and service.
If you select a single service or host on the extinfo page and add a comment, do you have multiple comments or just a single one? There can be only one acknowledgement at a time, so i guess its better to test with comments.

**Comment by fullmetalucard** [comment]
When I select a single service on the extinfo.cgi page, i only get one comment.
You're right, i was mentionning acknowledgments, but i only concerns comments related or not to an acknowledgment to be more precise.

**Comment by sni** [comment]
Maybe #555 is related to this problem.
