### ISSUE TITLE
Display filters being rewritten wrongly after page refresh

### ISSUE THREAD

**Issue by eythori-sensa** [sni/Thruk#554]
I'm seeing a faulty behavior of the display filters after a page refresh. Either after an automatic page refresh or when pushing the refresh button in the upper right corner.

When assigning the = sign as a parameter for any attribute the url gets wrongly rewritten from:
&dfl_s0_type=hostgroup&dfl_s0_val_pre=&dfl_s0_op==&dfl_s0_value=Test
to:
&dfl_s0_type=hostgroup&dfl_s0_val_pre=&dfl_s0_op=&dfl_s0_value=Test 
This causes the former = sign to become a tilde ~, which I guess is the default value.
The same thing happens with !=

It seems the reason lies in the url encoding. When submitted, the value for dfl_s0_op is not encoded as %3D. This causes, at least Chrome and Firefox to discard the second equal sign.

**Comment by Captsha** [comment]
Hi,
I think this is a regression. In the past, I already meet this problem and it have been fixed after on a newest version (maybe around 1.86-4). When, I tested the version 2.04 & 2.06, I meet this problem again. Personally, I have rollback-ed to an old version.
Cheers

**Comment by sni** [comment]
Could you try: https://github.com/sni/Thruk/commit/71ac65bc85d9753acebc62e017bb1f716d682d7d
I only experienced this issue if the session expires for some reason, not on the usual page refresh.

**Comment by sni** [comment]
Should be fixed with 44c19afb2
