### ISSUE TITLE
"FAILED - logcache is not enabled", even though it is.

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#560]
Thruk frequently claims logcache is disabled, despite being able to use it few moments later.

Commands are ~1-2 seconds apart.

icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
FAILED - logcache is not enabled
icinga:/etc/thruk# thruk  -a logcachestats
Backend              Index Size      Data Size       Items
icinga                 2.0 KB          0.0 B             0
icinga2                2.0 KB          0.0 B             0
nagios               129.1 MB        615.8 MB      14859626
softlayer_hk         418.0 KB          2.4 MB        40418
offsite              314.0 KB          1.3 MB        21074
dcnet-nagios           1.2 MB          5.0 MB       132047

I also cannot seem to be able to pull logs off icinga2. Known issue?

**Comment by yoshi314** [comment]
This is on 2.04

**Comment by sni** [comment]
There are a couple of open issues with the icinga 2 livestatus implementation:
https://dev.icinga.org/projects/i2/issues?utf8=%E2%9C%93&set_filter=1&f[]=status_id&op[status_id]=o&f[]=category_id&op[category_id]=%3D&v[category_id][]=216&f[]=&c[]=project&c[]=tracker&c[]=status&c[]=priority&c[]=subject&c[]=assigned_to&c[]=category&group_by=
