### ISSUE TITLE
Status details hidden after page open for some time

### ISSUE THREAD

**Issue by alexkiousis** [sni/Thruk#562]
Not sure if I can properly explain this.

If you open a status detail page for a host, after a while the host string changes to something like XXX.77778010309484.66666896254934 which obviously doesn't exist, so the page shows no data. 
I'm guessing on the page refresh something is improperly appended to the host string.

For example i'm seeing this now:
Service Status Details For Host 'gnt8-07.eie.grnet.gr.77778010309484.66666896254934'

Any ideas on how that can happen?

**Comment by sni** [comment]
I cannot reproduce that, can you provide more details?

**Comment by alexkiousis** [comment]
Sorry for the noise, seems I can't replicate it anymore.

Thruk is awesome. Thanks for your work.

**Comment by sni** [comment]
Thanks for coming back. Such issues are hard to solve, feel free to reopen when you have a way to reproduce it.
