### ISSUE TITLE
Missing require Plack::Util

### ISSUE THREAD

**Issue by Belse** [sni/Thruk#564]
I had to add a require Plack::Util near row 620 of lib/Thruk.pm. See details below. Took me a while to figure out. Also not sure if the package requires libplack-perl, I installed it anyway.

Ubuntu 14.04 + nginx etc etc
Package installed from repo: http://labs.consol.de/repo/stable/ubuntu trusty main

Package: thruk
Version: 2.04
Bugs: https://github.com/sni/Thruk/issues
Maintainer: Sven Nierlein <sven.nierlein@consol.de>
Installed-Size: 35,8 kB
Depends: perlapi-5.18.2, thruk-base (= 2.04)
Recommends: thruk-plugin-reporting (= 2.04)

Output of /var/log/uwsgi/app/thruk.log:

Sun Jan 24 03:36:54 2016 - [uwsgi-perl error] Undefined subroutine &Plack::Util::headers called at /usr/share/thruk/lib/Thruk.pm line 620.
[pid: 7343|app: 0|req: 1/1] 79.136.70.87 (belse) {48 vars in 828 bytes} [Sun Jan 24 03:36:54 2016] GET / => generated 21 bytes in 90 msecs (HTTP/1.1 500) 1 headers in 57 bytes (0 switches on core 0)
Sun Jan 24 03:40:32 2016 - Sun Jan 24 03:40:32 2016 - *** uWSGI perl stacktrace ***
Sun Jan 24 03:40:32 2016 - Trace begun at (eval 69) line 1
eval 'Devel::StackTrace->new->as_string;' at /usr/share/thruk/lib/Thruk.pm line 620
Thruk::_after_dispatch('Thruk::Context=HASH(0x5555cf0)', 'ARRAY(0x7f4c043f7010)') called at /usr/share/thruk/lib/Thruk.pm line 309
Thruk::_dispatcher('HASH(0x24a76f8)') called at (eval 69) line 0
eval {...} at (eval 69) line 0
Sun Jan 24 03:40:32 2016 - *** end of perl stacktrace ***

**Comment by sni** [comment]
This is probably due to the different method of launching Thruk with nginx. I added the missing use anyway.

Thanks for your report
