### ISSUE TITLE
Any plans to get shadownaemon feature to mainstream Thruk product.

### ISSUE THREAD

**Issue by kkdk5535** [sni/Thruk#565]
@sni 
Any plans to get shadownaemon feature to mainstream Thruk product. I know there was some discussion around isolating Thruk package that gets shipped with naemon releases and it appears current Thruk version that get shipped with naemon is older than mainstream version 2.x 

Naemon version:
```
naemon-thruk-1.0.3-1.el6.x86_64
Thruk 1.88-2 
```

**Comment by sni** [comment]
Shadownaemon will always be part of the naemon toolstack. Plan is to decouple Thruk from Naemon,
so you can just use the native Thruk package with the Naemon package. This would bring normal
update cycles for Thruk in Naemon. Unfortuntaly i don't have any time for Naemon in the near future,
so no idea when that will happen.
