### ISSUE TITLE
Incorrect check output

### ISSUE THREAD

**Issue by shermanchan** [sni/Thruk#566]
Hi,
We found thruk failed to store check output correctly on the database, as result it shows invalid check output on its gui
example
nagios services check output
[1455491562] SERVICE ALERT: wlc1.kl;TRAP;WARNING;HARD;1;When a Rogue AP is detected this Trap will be sent out along 60 48 26 00 14 02 A0 CF 5B A3 E3 B0 0 GHR 1 -81 2 no no dot11n5 ap3.kl unclassified

Thruk event log output
[2016-02-15 10:12:42] SERVICE ALERT: wlc1.kl;TRAP;WARNING;HARD;1;Critical: RTTValue=330 LateArrival=0 (CRITICAL: LostDS 161 > 10pkts.) OutOfSeq=105 Delay=268

on the database it shows
select * from 7215e_log where host_id = 776 and time = 1455491562
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'
'1455491562', '3', 'SERVICE NOTIFICATION', '1', '', '80', '776', '7428', '1', '8388607'
'1455491562', '1', 'SERVICE ALERT', '1', 'HARD', NULL, '776', '7428', '8388607', '133'

select * from 7215e_plugin_output where output_id = 8388607
'8388607', 'Critical: RTTValue=330 LateArrival=0 (CRITICAL: LostDS 161 > 10pkts.) OutOfSeq=105 Delay=268', 'C6324631436142632423'

BTW the version of thruk we are running is 1.88-4

Regards
Sherman

**Comment by sni** [comment]
There was an issue with too small IDs in the database. Please update Thruk and you probably have to recreate the logcache database.
