### ISSUE TITLE
Can't access icinga node behind basic_auth

### ISSUE THREAD

**Issue by vdmkenny** [sni/Thruk#571]
My icinga box's http is behind a basic_auth. When I try https://user:pass@icinga.example.com/ it returns a 404, while this works perfectly in browser. Any way around this? It would be nice to have support for this.

![screenshot from 2016-03-04 15-23-44](https://cloud.githubusercontent.com/assets/17249209/13529568/3f37a3a4-e21d-11e5-85b5-0d666a41cc96.png)

Real info redacted from screenshot.

**Comment by sni** [comment]
Are you trying to connect to another Thruk installation by https? This connection type does not support basic auth, you have to use the shared credentials as described in http://thruk.org/documentation/install.html#http

If you just want to connect to a icinga box, livestatus is the way to go. See http://thruk.org/documentation/install.html#livestatus
