### ISSUE TITLE
Different port , authentification fail

### ISSUE THREAD

**Issue by vesl** [sni/Thruk#576]
Hello,
Thruk 2.06 / Apache2.4

Everything works perfectly on port 80.
I need to use thruk on port 81.

I edited /etc/apache2/ports.conf => Listen 81
I edited /etc/init.d/thruk => STARTURL="http://localhost:81/thruk/cgi-bin/remote.cgi?startup"
Thruk start.
When I try to loggin, I get this message : technical problem during login, please have a look at the logfiles.

Enabling DebugLog, got this : 
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] logging initialized
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] http://MYDOMAINLOL/thruk/cgi-bin/login.cgi
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] $VAR1 = {
>           'login' => 'MYLOGINLOL',
>           'password' => 'MYCLEARPASSWORDLOL',
>           'referer' => '/thruk/',
>           'submit' => 'Login'
>         };
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] checking auth
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] login.cgi does not use authentication
> [2016/03/19 22:57:57][brs][INFO][Thruk] 14125 Req: 001   mem:  42.46 MB  12.01 MB   dur: 0.230s      ----   size:    0.019 kb   stat: 302   url: login.cgi
> [2016/03/19 22:57:57][brs][INFO][Thruk] 14125 Req: 001   mem:  42.46 MB  12.01 MB   dur: 0.230s      ----   size:    0.019 kb   stat: 302   url: login.cgi
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] http://MYDOMAINLOL/thruk/cgi-bin/login.cgi?problem&/thruk/
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] $VAR1 = {
>           '/thruk/' => '',
>           'problem' => ''
>         };
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] checking auth
> [2016/03/19 22:57:57][brs][DEBUG][Thruk] login.cgi does not use authentication
> [2016/03/19 22:57:57][brs][INFO][Thruk] 14125 Req: 002   mem:  42.98 MB   0.52 MB   dur: 0.029s      ----   size:    6.814 kb   stat: 200   url: login.cgi?problem&/thruk/
> [2016/03/19 22:57:57][brs][INFO][Thruk] 14125 Req: 002   mem:  42.98 MB   0.52 MB   dur: 0.029s      ----   size:    6.814 kb   stat: 200   url: login.cgi?problem&/thruk/

I looked for a solution by myself but without any success...
I guess problem comming from apache ? 

Regards

**Comment by sni** [comment]
You need to change 'cookie_auth_restricted_url' too if you use the login page.

**Comment by vesl** [comment]
Better, but login failed

> root@brs:/etc/thruk# rgrep localhost
>thruk.conf:cookie_auth_restricted_url        = http://localhost:81/thruk/cgi-bin/restricted.cgi

No more info in thruk logs or apache

**Comment by vesl** [comment]
You forgot lib/Thruk/Utils/CookieAuth.pm edit line 264.

You're welcome.
