### ISSUE TITLE
Availability Report fails

### ISSUE THREAD

**Issue by sdarwin** [sni/Thruk#584]
Hello,

Does anyone else have a somewhat similar setup, and does this work ok or not?

Thruk 2.06
Shinken 2.4.3
Ubuntu 14.04
Mongo 2.4.9 backend

Click on View Availability Report For This Service.   

Then it says:  

Background Job Failed
background job failed, look at your logfile for details

The log file:

[2016/04/04 08:10:31][mon01][ERROR][Thruk] broken pipe at /usr/share/thruk/lib/Thruk/Backend/Pool.pm line 30.
        Thruk::Backend::Pool::**ANON**('PIPE') called at /usr/share/thruk/lib/Thruk/Utils/External.pm line 127
        eval {...} called at /usr/share/thruk/lib/Thruk/Utils/External.pm line 127
        Thruk::Utils::External::perl('Thruk::Context=HASH(0x3d88060)', 'HASH(0x3df4f18)') called at /usr/share/thruk/lib/Thruk/Controller/avail.pm line 173
        Thruk::Controller::avail::_create_report('Thruk::Context=HASH(0x3d88060)') called at /usr/share/thruk/lib/Thruk/Controller/avail.pm line 75
        Thruk::Controller::avail::index('Thruk::Context=HASH(0x3d88060)') called at /usr/share/thruk/lib/Thruk.pm line 275
        eval {...} called at /usr/share/thruk/lib/Thruk.pm line 263
        Thruk::_dispatcher('HASH(0x3c35be8)') called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
        eval {...} called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
        Plack::Util::run_app('CODE(0x256b3f0)', 'HASH(0x3c35be8)') called at /usr/lib/thruk/perl5/Plack/Handler/FCGI.pm line 143
        Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x1bcde98)', 'CODE(0x256b3f0)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24
[2016/04/04 08:10:31][mon01][ERROR][Thruk] internal server error
[2016/04/04 08:10:31][mon01][ERROR][Thruk] on page: http://thruk.example.com/thruk/cgi-bin/avail.cgi?host=mon01&service=Check Shinken&show_log_entries
[2016/04/04 08:10:42][mon01][ERROR][Thruk] killed job: /var/lib/thruk/jobs/beb6f
[2016/04/04 08:10:42][mon01][ERROR][Thruk] total 20
drwxrwx---  2 www-data www-data 4096 Apr  4 08:10 .
drwxrwx--- 14 www-data www-data 4096 Apr  4 08:10 ..
-rw-rw----  1 www-data www-data   56 Apr  4 08:10 message
-rw-r--r--  1 www-data www-data  185 Apr  4 08:10 start
-rw-rw----  1 www-data www-data   14 Apr  4 08:10 user
[2016/04/04 08:10:42][mon01][ERROR][Thruk] job was killed
[2016/04/04 08:10:42][mon01][ERROR][Thruk] Background Job Failed
[2016/04/04 08:10:42][mon01][ERROR][Thruk] on page: http://thruk.example.com/thruk/cgi-bin/job.cgi?job=beb6f

**Comment by oliv225** [comment]
Hello, 

I have a similar problem on THRUK 2.08 and NAGIOS 3.5.1 on DEBIAN 8.5.

In THRUK, when I try to do an availability report with Timeperiod "None", I receive this error in the web interface : 
"Background Job Failed
background job failed, look at your logfile for details"

This is the error in apache logs : 
"GET /thruk/cgi-bin/job.cgi?job=75aa5 HTTP/1.1" 500 7014 "http://thruk.domain/thruk/cgi-bin/avail.cgi?get_date_parts=&hostgroup=Antennes" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"

And this is the error in thruk.log : 
[2016/08/23 15:31:18][lin01][ERROR][Thruk] on page: http://thruk.domain/thruk/cgi-bin/job.cgi?job=75aa5

I installed THRUK again after removing it, but the problem is not fixed.

When I try to do an avalibility report with TimePeriod "24X7", it's good.
When I try to do an avalibility report with TimePeriod "None" in NAGIOS, it's good.
I meet the problem only when I choose the TimePeriod "None" with THRUK web interface.

**Comment by oliv225** [comment]
Hello, 

I have installed THRUK 2.00-2 instead of 2.08 and it's OK.
I can do availability report with timeperiod "None" with THRUK.

**Comment by sni** [comment]
Thats from the apache access log, not the error log. Please have a look at the actual error log and also in the thruk.log. Also i cannot reproduce the problem,

**Comment by beinbliss** [comment]
Have similar problem.
7G of logs.

Version:
omd 2.11.20160831-labs-edition

executing: 
http://test/test/thruk/#cgi-bin/history.cgi?entries=100&start=2016-04-01+00%3A00%3A00&end=2016-09-02+00%3A00&archive=&host=**any-particular-host**&statetype=0&type=0

if host=all then i get almost instant feedback.

Getting apache error_log:
[Thu Sep 01 15:50:35.384872 2016] [fcgid:warn] [pid 23986] [client 127.0.0.1:44138] mod_fcgid: read data timeout in 40 seconds, referer: http://test/test/thruk/
[Thu Sep 01 15:50:35.385200 2016] [core:error] [pid 23986] [client 127.0.0.1:44138] End of script output before headers: fcgid_env.sh, referer: http://test/test/thruk/
broken pipe at /omd/sites/test/share/thruk/lib/Thruk/Backend/Pool.pm line 30.
	Thruk::Backend::Pool::__ANON__('PIPE') called at /omd/sites/test/lib/perl5/lib/perl5/Log/Log4perl.pm line 5
	eval {...} called at /omd/sites/test/lib/perl5/lib/perl5/Log/Log4perl.pm line 5
	Log::Log4perl::END() called at /omd/sites/test/share/thruk/lib/Thruk.pm line 484
	eval {...} called at /omd/sites/test/share/thruk/lib/Thruk.pm line 484
END failed--call queue aborted at /omd/sites/test/share/thruk/script/thruk_fastcgi.pl line 484.

or



Tried adding bigger timeouts either in 02_fcgid.conf or in apache/thruk.conf
IdleTimeout 3600
ProcessLifeTime 7200
MaxProcessCount 1000
DefaultMinClassProcessCount 3
DefaultMaxClassProcessCount 100
IPCConnectTimeout 8
IPCCommTimeout 360
BusyTimeout 300

but makes no difference whatsoever.

If i feed the query directly into live socket with unixcat, then it goes through without crashing. (takes about 3,5 minutes)


Then i downgrade to OMD 2.11~2016-03-18-labs-edition version and tried to execute availability report (i.e. anything that interacts with log files)

It went upto 300seconds and crashed with: 
Background Job Failed
background job failed, look at your logfile for details

Looking at the Thruk logs i see:
][ERROR][Thruk] ---------------
][ERROR][Thruk] JS-Error:
][ERROR][Thruk] Version:    2.07~20160318/ OMD 2.11~2016-03-18-labs-edition
][ERROR][Thruk] Release:    March 18, 2016
][ERROR][Thruk] Url:        /bs/thruk/cgi-bin/job.cgi??job=d506c&_=1472735564845
][ERROR][Thruk] Browser:    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
][ERROR][Thruk] Backends:   uname:      Linux 
][ERROR][Thruk] release:    CentOS Linux release 7.2.1511 (Core)
][ERROR][Thruk] Error List:
][ERROR][Thruk] Url: https://test/bs/thruk/cgi-bin/job.cgi?job=d506c&_=1472735564845 Line 64
][ERROR][Thruk] Error: Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://test/bs/thruk/cgi-bin/avail.cgi?show_log_entries=&host=specific-host&timeperiod=today&smon=1&sday=31&syear=2016&shour=0&smin=0&ssec=0&emon=9&eday=01&eyear=2016&ehour=24&emin=0&esec=0&rpttimeperiod=24x7&assumeinitialstates=yes&assumestateretention=yes&assumestatesduringnotrunning=yes&includesoftstates=no&initialassumedhoststate=0&initialassumedservicestate=0&view_mode=html' cannot be created in a document with origin 'https://test' and URL 'https://test/bs/thruk/cgi-bin/job.cgi?job=d506c&_=1472735564845'.
][ERROR][Thruk] 
][ERROR][Thruk] Full Stacktrace:
][ERROR][Thruk] Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://test/bs/thruk/cgi-bin/avail.cgi?show_log_entries=&host=specific-host&timeperiod=today&smon=1&sday=31&syear=2016&shour=0&smin=0&ssec=0&emon=9&eday=01&eyear=2016&ehour=24&emin=0&esec=0&rpttimeperiod=24x7&assumeinitialstates=yes&assumestateretention=yes&assumestatesduringnotrunning=yes&includesoftstates=no&initialassumedhoststate=0&initialassumedservicestate=0&view_mode=html' cannot be created in a document with origin 'https://test' and URL 'https://test/bs/thruk/cgi-bin/job.cgi?job=d506c&_=1472735564845'.
][ERROR][Thruk]     at Error (native)
][ERROR][Thruk]     at https://test/bs/thruk/cgi-bin/job.cgi?job=d506c&_=1472735564845:64:9
][ERROR][Thruk] Source:
][ERROR][Thruk] if(history.replaceState) {
][ERROR][Thruk] history.replaceState({}, "", history_url);
][ERROR][Thruk] }
][ERROR][Thruk] 
][ERROR][Thruk] ---------------
][ERROR][Thruk] failed to connect - Connection refused at /omd/sites/bs/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 343.
][ERROR][Thruk] Background Job Failed
][ERROR][Thruk] on page: http://test/bs/thruk/cgi-bin/job.cgi?job=abbae&_=1472735878747

and in apache error log i get sometimes:

broken pipe at /omd/sites/bs/share/thruk/lib/Thruk/Backend/Pool.pm line 30.
  Thruk::Backend::Pool::__ANON__('PIPE') called at /omd/sites/bs/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 161
  eval {...} called at /omd/sites/bs/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 161
  Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0xaf8c90)', 'CODE(0x158c410)') called at /omd/sites/bs/share/thruk/script/thruk_fastcgi.pl line 27
broken pipe at /omd/sites/bs/share/thruk/lib/Thruk/Backend/Pool.pm line 30.
  Thruk::Backend::Pool::__ANON__('PIPE') called at /omd/sites/bs/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 161
  eval {...} called at /omd/sites/bs/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 161
  Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x11f8c90)', 'CODE(0x1c8c410)') called at /omd/sites/bs/share/thruk/script/thruk_fastcgi.pl line 27


If i take small perdios like several days, then it works fine.

**Comment by pablodav** [comment]
I had very similar issue with large reports and finally got reports working changing in thruk_local.cfg

# https://www.thruk.org/documentation/configuration.html#report_use_temp_files
default_theme = Exfoliation
report_max_objects = 5000
# For more efficient reports:
report_use_temp_files = 31
report_update_logcache = 0

# allow error reports
show_error_reports = both
no_external_job_forks = 0
# Include messages with class = 2 (program messages) in reports.
# Setting this to 0 allows the MySQL backend to use indexes efficiently
report_include_class2 = 0

**Comment by beinbliss** [comment]
Didn't help. 
It is sad that reports makes OOM kill naemon process.

**Comment by pablodav** [comment]
I had problemas again and had to change more things, first had to reduce the max_objects as they consumes lot of RAM if the report is too big. 

Also had to enhance RAM, CPU and disk IO for the large reports to get them running.

Also had to modify /etc/mysql/my.cnf and increase buffer ram usage for innodb. 

I don't have all details with me right now, but that was what helped.
