### ISSUE TITLE
Missing hook.sh

### ISSUE THREAD

**Issue by blueredfish** [sni/Thruk#586]
Hello we are trying to use single sign on with thruk (1.88-2) and nagvis (1.8.5), and we have seen we have to enable in thruk_local.conf cookie_auth_login_hook = ./bin/hook.sh
We can't find hook.sh file anywhere. Where is it?
We can't find it in source code in github.
Thank you very much, regards.

**Comment by sni** [comment]
This is just an example. You have to write the hook by yourself. It's just a script run whenever a user logs in.
