### ISSUE TITLE
Adding downtime via CLI creates blank comment on every service

### ISSUE THREAD

**Issue by d-zalewski** [sni/Thruk#589]
When I add a downtime to a host using below command, Thruk adds an a blank comment with no author, no entry and no message to all services on this host

```
echo "[1461074224] SCHEDULE_HOST_DOWNTIME;SERVER1;1461466800;1461495600;1;0;0;user1;Downtime coment"
 > /var/nagios/rw/nagios.cmd

```

I'm using nagios core 4.0.8 and Thruk 1.84

Nothing in nagios log except successfully added downtime via EXTERNAL COMMAND

**Comment by sni** [comment]
It seems like there is an issue with livestatus and comments regarding nagios 4. Thruk just shows the information from Livestatus.
There is at least this in a germand forum: https://monitoring-portal.org/index.php?thread/35832-comment-sprechblase-auf-host-und-services/
