### ISSUE TITLE
Thruk issues when no diskspace is left :-/

### ISSUE THREAD

**Issue by ofalk** [sni/Thruk#591]
Hey Sven (@sni)!

I upgraded my Thruk machine to RHEL 6.8 today and got the following:

cannot stat /var/cache/thruk/thruk.cache: No such file or directory at /usr/share/thruk/lib/Thruk/Utils/Cache.pm line 198.

After some digging and strace, I had to find out it was caused by out of disk space in /var :-[

Totally my fault of course, especially for not looking at the disk space (of course I couldn't check monitoring at that time :-)), however, you might want to catch the error from nstore here:

    nstore($self->{'_data'}, $self->{'_cachefile'}.'.'.$$);

From Utils/cache.pm (function _store()).

Do you also think this would make sense?

KR,
 Oliver

**Comment by sni** [comment]
Sure, this totally makes sense.

**Comment by sni** [comment]
Thanks
