### ISSUE TITLE
Feature: Please, add action menu merging

### ISSUE THREAD

**Issue by MVKozlov** [sni/Thruk#593]
Will be fine if Thruk someway can merge several action menus
may be from
`<action_menu_apply>
 ( add some "merge/replace" key here )
`
or from custom variable like

```
   custommenu = {"icon":"/thruk/themes/{{'{{'}}theme}}/images/dropdown.png",\
                 "title": "Web administration",\
                 "menu":[\

$_HOSTCUSTOMMENU$\

                   {"icon":   "/thruk/themes/{{'{{'}}theme}}/images/page_white_text.png",\
                    "label":  "wiki",\
                    "target":"_blank",\
                    "action": "http://example.com/wiki/$HOSTNAME$"\
                   }\
                 ]\
                }
```

and host can set _CUSTOMMENU macro to other menu (menu name or menu itself)

or may be

```
<action_menu_items>
 maimenu = {...}
 addmenu = {...}

specialmenu = mainmenu,addmenu

</action_menu_items>

```

**Comment by sni** [comment]
Please have a look at the javascript action menus. There is no mergin support, but you can define reusable functions and define completly flexible menus.
