### ISSUE TITLE
Sorting by Site column

### ISSUE THREAD

**Issue by mgalbert** [sni/Thruk#596]
Hello there!
Thank you again for a wonderful product!  In one of our environments where we have multiple backends configured, we have also enabled the show_backends_in_table option.  The "Site" column shows up appropriately; however, when trying to sort by this column, it doesn't appear to list in alphabetical order.  I've found this in both versions 2.04 and 2.06 even with only two backends setup.  Is it suppose to function in this way?  Should you have any questions or need any additional information, please feel free to let me know.
Thanks again and in advance,
-- malbert

**Comment by sni** [comment]
Should be better now, thanks.
