### ISSUE TITLE
htpasswd2 not found on SLES11

### ISSUE THREAD

**Issue by rainer-tammer** [sni/Thruk#598]
Hello,
the htpasswd2 binary is not found on SLES11.

Proposed fix:

icinga01:/usr/share/thruk/plugins/plugins-available/conf/lib/Thruk/Controller # diff -c conf.pm.orig conf.pm
*** conf.pm.orig        Fri May 27 12:56:46 2016
--- conf.pm     Fri May 27 12:56:50 2016
***************
*** 1480,1486 ****
  # returns htpasswd path
  sub _get_htpasswd {
      # htpasswd is usually somewhere in sbin
!     local $ENV{'PATH'} = ($ENV{'PATH'} || '').':/usr/sbin:/sbin:/usr/bin';
      my $htpasswd = Thruk::Utils::which('htpasswd2') || Thruk::Utils::which('htpasswd');
      return($htpasswd);
  }
--- 1480,1486 ----
  # returns htpasswd path
  sub _get_htpasswd {
      # htpasswd is usually somewhere in sbin
!     local $ENV{'PATH'} = ($ENV{'PATH'} || '').':/usr/sbin:/sbin';
      my $htpasswd = Thruk::Utils::which('htpasswd2') || Thruk::Utils::which('htpasswd');
      return($htpasswd);
  }

Bye
  Rainer Tammer

**Comment by sni** [comment]
Looks ok, could you please create a proper pull request for this?

**Comment by rainer-tammer** [comment]
Hello,
I have not cloned the repository to my machine.
The installation was done via SLES rpm.

Could you please create the actual patch?

Note: I can provide a diff between the original and the patched file with every diff switches you like.

Bye
  Rainer

**Comment by sni** [comment]
You don't have to. Such small changes can be done directly here on github. Just edit the file here and github will do everything neccessary.

**Comment by rainer-tammer** [comment]
Done:  Add password change support for SLES11 #599

**Comment by sni** [comment]
thanks
