### ISSUE TITLE
Panorama dashboard not saving changes

### ISSUE THREAD

**Issue by emenare** [sni/Thruk#600]
I just started using Panorama panels and think it looks great. I have noticed some flakiness/instability with saving changes as far as the sort filters and the columns showing in any particular panel. I have about 12 panels on any given dashboard and have the same issue when one or multiple dashboards are viewable. 

Example: I have a panel showing services, with or without a filter enabled. I hide one or more columns, re-order, and add columns. The changes show up immediately. When the dashboard is locked again, the changed may or may not show. I get different results and have a lot of inconsistency. I have manually gone after the *.tab files to edit the views, but still do not get consistent results. It seems like some unknown state is constantly overwriting changes or that changes are just not saved. Have not seen any clear errors in the log.

Version 2.06. Running Thruk inside a docker.

**Comment by sni** [comment]
Can you retry with the 2.08. Afaik this has been fixed already.
