### ISSUE TITLE
Upgrading thruk from 1.68 to 2

### ISSUE THREAD

**Issue by alokispandey** [sni/Thruk#601]
Strange issue found after upgrading thruk from 1.68 to 2. Every-time clicking on "host" give "no backend available"  error whereas at same time when we click on service we get all services listed.

How to reproduce:
upgrade thruk on centos 6 using repo   lab.connsole.de repo.
http://labs.consol.de/repo/stable/rhel6/x86_64/

and access host information on thruk portal. 

I won't be able to provide much details now as i rolled back thruk back to 1.68 and all seems working as before.

**Comment by sni** [comment]
Could you try on a test instance and check out the logfiles.
