### ISSUE TITLE
server name and quote in pop-up comment

### ISSUE THREAD

**Issue by rirouxe** [sni/Thruk#602]
in the host page, the comment in reference to html glpi. The error is in the popup, the links appears well but adds the server name at the beginning of the url
example :
http://infvm-web04/'https://infoweb/glpi/index.php?redirect=tracking_397084\%27

but within the service page, html link is good
https://infoweb/glpi/index.php?redirect=tracking_397084

infvm-web04 is the name of thruk server

[image](http://www.hostingpics.net/viewer.php?id=973727thrukerror.png)

for remove this i modified /usr/share/thruk/templates/_parts_comments.tt

line 12, i remove escape_quotes and ()

the linc is ok in popup

**Comment by sni** [comment]
what exactly do you enter as comment?

**Comment by rirouxe** [comment]
<a href='https://URL'>ticket 12</a> (NGLink)

**Comment by rirouxe** [comment]
`<a href='https://URL'>ticket 12</a> (NGLink)`

**Comment by sni** [comment]
HTML is not allowed in downtimes or comments for security reasons.

**Comment by rirouxe** [comment]
with Thruk 1.84-6 the http in comments works
