### ISSUE TITLE
Thruk 2.08 not working properly with icinga2 and compat log

### ISSUE THREAD

**Issue by rainer-tammer** [sni/Thruk#605]
Hello,
Thruk depends on the old icinga 1.x compat log as far as I know. This compat log is not written properly by icinga2. This is described in the bug entry https://dev.icinga.org/issues/10130 , https://dev.icinga.org/issues/7288 . 

The result of these bug reports: Wont fix ... icingaweb2 does not need this.

This is very bad for thruk users because the event history is missing/incomplete.

Is there a solution to this problem?

Bye
  Rainer

**Comment by rainer-tammer** [comment]
Hello,
The events are also logged to the icinga2 DB. Would it be possible to read the events from the DB?

Bye
  Rainer

**Comment by rainer-tammer** [comment]
Hello,
thruk can read the data from icinga2 via livestatus (my config does read via tcp/6666). The log can be queried via livestatus. Is there a possibility to get the log via lievestatus instead via compat logging?

Bye
  Rainer

**Comment by sni** [comment]
Thruk just fetches the logs from livestatus. Thats the one API Thruk uses to get data from a backend. If the compat log is not a reliable source of the Logs, then Icinga2 should change livestatus to read the logs from a reliable source.
You probably could write an importer, which imports the Icinga logs from a database in the Thruk logcache, which is a database already. Then do this periodically and disable the on demand update by `report_update_logcache=0` in your thruk_local.conf

**Comment by rainer-tammer** [comment]
Hello,
OK, that's strange. I got some log entries after I had enabled the compat log. This was suggested in an article (did not tag the URL). This was then probably a coincidence.

I did some testing with livestatus via netcat. I did not get log entries back after adding a filter (sample):


GET log

Filter: time >= 1265062900

Any ideas?


Bye
  Rainer Tammer


On 10.06.2016, at 21:19, Sven Nierlein <notifications@github.com<mailto:notifications@github.com>> wrote:


Thruk just fetches the logs from livestatus. Thats the one API Thruk uses to get data from a backend. If the compat log is not a reliable source of the Logs, then Icinga2 should change livestatus to read the logs from a reliable source.
You probably could write an importer, which imports the Icinga logs from a database in the Thruk logcache, which is a database already. Then do this periodically and disable the on demand update by report_update_logcache=0 in your thruk_local.conf

**Comment by sni** [comment]
Yes, there are some more known issues with the Icinga 2 livestatus implementation.
-> <https://dev.icinga.org/projects/i2/issues?utf8=%E2%9C%93&set_filter=1&f[]=status_id&op[status_id]=o&f[]=category_id&op[category_id]=%3D&v[category_id][]=216&f[]=&c[]=project&c[]=tracker&c[]=status&c[]=priority&c[]=subject&c[]=assigned_to&c[]=category&group_by=>

You probably hit this one: https://dev.icinga.org/issues/10179

**Comment by rainer-tammer** [comment]
Hello,
That could be the case.

My problem with thruk/icinga2 is that I do not reliably get the log entries. To be more precise: The alert/event log dos not reliably display the log entries. I did not see this problem with icingaweb2.

To be honest I do like the thruk WEB GUI much better then icingaweb2. Thruk gives you a better visibility.

The log issue is the biggest problem so far.

I am new to icinga/thruk so please excuse this question: Is there a simple way to trace all livestatus queries/responses?

Bye
  Rainer Tammer


On 10.06.2016, at 21:37, Sven Nierlein <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, there are some more known issues with the Icinga 2 livestatus implementation.
-> https://dev.icinga.org/projects/i2/issues?utf8=%E2%9C%93&set_filter=1&f[]=status_id&op[status_id]=o&f[]=category_id&op[category_id]=%3D&v[category_id][]=216&f[]=&c[]=project&c[]=tracker&c[]=status&c[]=priority&c[]=subject&c[]=assigned_to&c[]=category&group_by=<https://dev.icinga.org/projects/i2/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&f%5B%5D=category_id&op%5Bcategory_id%5D=%3D&v%5Bcategory_id%5D%5B%5D=216&f%5B%5D=&c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=category&group_by=>

You probably hit this one: https://dev.icinga.org/issues/10179

**Comment by sni** [comment]
i am closing this. must be fixed in icinga 2, there is nothing thruk can do about that.

**Comment by rainer-tammer** [comment]
I have also opened a bug report for icnga2.
