### ISSUE TITLE
Feature Request: Business Process

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#606]
hello,

two enhancements on BP worth implementing I think:
- getting a list of affected business processes
  Rational: host downtime, service downtime, how these **could** affect business.
- when editing BP with BP children, opening a BP child into an new tab 
  Rational: avoid to return back to the BP list, search for the BP child and open it.

jfr

**Comment by sni** [comment]
The second may be better in the latest nightly. If a BP contains a service node which again points to a BP, there is an extra link to that BP now.

**Comment by sni** [comment]
Also there is now a link to all related hosts/services in a BP. Maybe thats what you meant the list of affected BPs.

**Comment by jframeau** [comment]
Nice job.

The two enhancements are ok for me.

Txh.
