### ISSUE TITLE
Feature request: copying downtimes/comments/ack's between services/backends

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#609]
I'm transitioning from Nagios to icinga with exact same list of hosts/services. I use thruk to have a merged side-by-side view of both backends to make sure they perform correctly.

In order to straighten out things, i sometimes need copy existing modifications on hosts/services from one backend to another. Some of them are old comments, ack's, downtimes. Some are new and mistakenly entered by users who forgot to register them on both backends. 

Not having to re-enter them manually would be very convenient.

**Comment by sni** [comment]
comments and downtimes are a "core" thing. But you could copy the retention.dat to the new/old system.
