### ISSUE TITLE
Service and host Status page: multiple thresholds

### ISSUE THREAD

**Issue by yassinekchiri** [sni/Thruk#613]
As a thruk and nagios expert integrator, I faced a big issue monitoring metrics within multiple thresholds, 

Thruk for now deal only with two thresholds level ( warning - writical ), unfortunately some metrics need to be checked for multiple thresholds  ( low_critical - low_warning - high_warning - high - critical )
as an example, i'll take the RX and TX Power of SFP Modules in SAN Fabrics, those values should be in the following interval :

0<- Critical ->200<- Warning ->300<- Ok ->800<- Warning ->900<- Critical ->1000

As for now in the Performance Data displayed in the Service and host details status we can see only 2 thresholds levels.

I started working on the Thruk Core to handle it but didn't finish it yet,
I would Love if it's taken in charge for next releases

**Comment by sni** [comment]
Sounds good, what have you done so far? Maybe i can help out.

**Comment by yassinekchiri** [comment]
I've done sort of reverse engineering of your code and I'm, trying to add a non mandatory fields in the perdata output as following : 
title = value unit;high_warning;high_critical;minimal;maximal;low_warning;low_critical;
as for now, I succeeded to update the _perdata_human.tt to understand such an output,
also I updated the split_perfdata function in Filter.pm in order to do the same.

one other cool feature that I added to Thruk while working on  _perdata_human.tt is to change the color of the perf_bar depending on the state of the current value.

And now I'm working on the perf_table funtion in the thruk-2.08-1.js file in order to allow the JS to draw the perf_bar, I've done some updates but steel didn't succeed to plot the perbar once I pass the low warning and critical values.
you can see them in the pictures attached.

![screenshot from 2016-07-23 16-36-05](https://cloud.githubusercontent.com/assets/17455081/17080992/2901599e-50fa-11e6-9f03-2527e272b54b.png)

![screenshot from 2016-07-23 17-21-33](https://cloud.githubusercontent.com/assets/17455081/17080994/322776d4-50fa-11e6-8217-3d69479fe4a6.png)

**Comment by sni** [comment]
nice, looks good. But i would merge the range thresholds in a single column instead of breaking it down. That makes things more readable. So just keep 30-90 in the critical column. There are outside ranges as well, so you had to add even more columns to display them.

**Comment by yassinekchiri** [comment]
yes I thought about that, but seeing it the way I did make it more easily readable cause we can see the order of the thresholds 
unfortunately if i display 30-90 and 50-70 it will introduce some ambiguity on the values,
the user will have a difficulty to figure out if the value should be inside or outside the range,
it will also cause some trouble for the state distinguish in order to print each perf bar with the right color

**Comment by sni** [comment]
The table layout should have no effect on determining the perf bar color.
Also i think its pretty clear that a 30-90 in the critical column means that it is critical from 30 to 90. If i put that in separate columns you still don't know easily if the value has to be below or higher than the threshold. Outside ranges could be displayed as 2 entrys, ex.: `∞ - 30, 90 - ∞`

**Comment by yassinekchiri** [comment]
oh that looks nice but is it supported in the actual version, the example that you gave ?

**Comment by sni** [comment]
no, its not. its just an example of how it could be :-)

**Comment by yassinekchiri** [comment]
ah ok sounds good I'll review my code to work that way,
Thanks for your advise, I'll try to request a pull my code in the Project

**Comment by sni** [comment]
thanks, looking forward to it.
