### ISSUE TITLE
Panorama not showing anything

### ISSUE THREAD

**Issue by Hyllegaard** [sni/Thruk#616]
Hi.
I am using the testing repository version of Thruk.

After a recent update I am unable to see any panorama dashboard.
Entering the url /thruk/cgi-bin/panorama.cgi returns a visually blank page.
I have attached the source from the returned page.

[panorama-content.txt](https://github.com/sni/Thruk/files/339418/panorama-content.txt)

Regards

Jens

**Comment by sni** [comment]
Sounds like a Javascript error. Can you make sure no browser cache is involved and have a look at the javascript error console?

**Comment by Hyllegaard** [comment]
Here are the errors that are shown. I have tried a few different browsers, and the result is the same in all of them.
![panorama-js-errors](https://cloud.githubusercontent.com/assets/2233675/16463127/a6bc0524-3e34-11e6-8320-8d6a3ee08dc5.png)
I just checked another install, and that has the same errors.

**Comment by sni** [comment]
should be fixed in the tomorrows daily.

**Comment by sni** [comment]
thanks for reporting this.
