### ISSUE TITLE
Multiline Output Problem

### ISSUE THREAD

**Issue by Mike-Sbg** [sni/Thruk#617]
The detail output is shown as ist was die pluginoutput (which can select to popup on mousemove-over or klicking)  ... by the way it show the new line Character (\n) in former versions it was interpreted as new line (and das detailoutput)

Thruk Version: 2.0.8

**Comment by sni** [comment]
sry, i don't understand. Maybe a screenshot would make the issue more clear?

**Comment by Mike-Sbg** [comment]
This is how it is presented in the older Version:

![thruk-correct](https://cloud.githubusercontent.com/assets/20350607/16687863/4800b0dc-451b-11e6-8fca-041af68c86a8.png)

And this it is presented now 

![thruk-new](https://cloud.githubusercontent.com/assets/20350607/16687870/5490c8e6-451b-11e6-8227-0f944973eacc.png)

The Settings in the Thruk-CGI are the same

**Comment by Mike-Sbg** [comment]
To me it seems that Thruk doesn't recognize, that it is a multiline output

**Comment by sni** [comment]
Thruk does detect Multiline Output by fetching the columns "plugin_output" and "long_pluging_output" via livestatus. If there is long_pluging_output, then the multi-line links
will be displayed. So thats something the monitoring core decides.

**Comment by Mike-Sbg** [comment]
Your are right, with my new Installation everything is entered in the "plugin_output" and nothing in the "long_plugin_output" ... so Thruk presents it correctly.

But I cannot find out, why this is happening ... the only difference is the version of Nagios ... Nagios 3 where it works correctly, Nagios 4 with this problem ... could you please give me a hint

**Comment by sni** [comment]
You might want to contact the Nagios support then.
