### ISSUE TITLE
Convert to HTML5

### ISSUE THREAD

**Issue by ofosos** [sni/Thruk#619]
Hi,
I'd like to convert Thruk to HTML5.

Issues:
1. Frames are no longer part of HTML5
2. table, td, tr, etc. have different properties. Specifically things like align or border are very much changed or deprecated

I'll volunteer to do the conversion in a backward compatible way. Is that ok for you?

**Comment by sni** [comment]
Well, i know frames are deprecated in html5, but they are quite useful in the way we use them right now, especcially if you embed graphing addons like pnp or grafana. I don't think there is a
good html5 way to do this. Besides that, this is quite some work with the original intention to make
IE choose the right compatibility mode which could be done with a single header :-)
