### ISSUE TITLE
Config Tool issue -> waiting for core reload failed._

### ISSUE THREAD

**Issue by sbouveta2fadvisor** [sni/Thruk#620]
Hi,

i'm using Thruk 2.08 with shinken 2.4.3; When i try to reload shinken aftrer create an host with Config Tool, i obtain the issue (and in thruk.log) :

_config reloaded by external command. Warning: waiting for core reload failed._

Any idea,

Best regards.

**Comment by sni** [comment]
check the shinken logfiles if the passive command is successfully accepted. Maybe the shinken logs contain some hints why the reload fails.

**Comment by sbouveta2fadvisor** [comment]
Thanks for your reply, indeed shinken reload failed.

I had to configure sudo for apache user and use the reload command below:

obj_reload_cmd = sudo /etc/init.d/shinken restart
