### ISSUE TITLE
SSO Login pnp4nagios Space in URL

### ISSUE THREAD

**Issue by Torsteng5** [sni/Thruk#622]
open Bookmark to:
http://Nagios/pnp4nagios/index.php/graph?host=MgmtHost&srv=Adobe**%20**Flash&theme=smoothness
get redirect to:
http://Nagios/thruk/cgi-bin/login.cgi?pnp4nagios/index.php/graph%3fhost=MgmtHost&srv=Adobe**%2520**Flash&theme=smoothness
after login redirect to:
http://Nagios/pnp4nagios/index.php/graph?host=MgmtHost&srv=Adobe**%2520**Flash&theme=smoothness
PNp4nagios Error Page: XML file "/var/lib/pnp4nagios/perfdata/MgmtHost/Adobe%20Flash.xml" not found

**Comment by sni** [comment]
I cannot reproduce this. Can you retry with the latest version and reopen the issue if it still persists.
