### ISSUE TITLE
Business Process dont work

### ISSUE THREAD

**Issue by vladnosferatu** [sni/Thruk#623]
Can some one help me on the "Business Process" feature,

i have this error

"internal server error
please have a look at your log file"

LOG:

internal server error
on page: http://172.25.66.75/thruk/cgi-bin/bp.cgi
Usage: JSON::XS::decode(self, jsonstr) at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 218.
internal server error
on page: http://172.25.66.75/thruk/cgi-bin/bp.cgi

**Comment by sni** [comment]
I have no idea whats happening here, but i added some code to help debug this.

**Comment by vladnosferatu** [comment]
thanks

**Comment by vladnosferatu** [comment]
i update the IO the error on log is 

[2016/08/01 11:58:01][THRUK01VPL][ERROR][Thruk] on page: http://172.25.66.75/thruk/cgi-bin/bp.cgi
[2016/08/01 11:58:01][THRUK01VPL][ERROR][Thruk] error while reading /var/lib/thruk/bp/2.tbp.runtime: Usage: JSON::XS::decode(self, jsonstr) at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 221.

**Comment by vladnosferatu** [comment]
the file is empty

-rw-rw----. 1 apache apache 0 Mar 22 21:41 /var/lib/thruk/bp/2.tbp.runtime

**Comment by sni** [comment]
Thanks, the last patch should fix the issue then.

**Comment by vladnosferatu** [comment]
thanks a lot, now works ;)
