### ISSUE TITLE
Images and Icons not working in Dashboard

### ISSUE THREAD

**Issue by mc55boy** [sni/Thruk#624]
Initially it worked fine, but now neither the images nor icons display at all on the dashboard.

Alongside this the default images/icons aren't loaded into the drop down list anymore.

This is the error log:

`[2016/07/29 12:18:04][73fbeb0dd89b][ERROR][Thruk] JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 1013.`
`[2016/07/29 12:18:04][73fbeb0dd89b][ERROR][Thruk] internal server error`
`[2016/07/29 12:18:04][73fbeb0dd89b][ERROR][Thruk] on page: http://localhost/thruk/cgi-bin/panorama.cgi?task=availability`

I'm assuming I accidentally deleted something, but cannot think of what as a clean install doesn't fix the issue.

**Comment by sni** [comment]
Hard to tell whats going wrong here. You could use firebug or similar to peak into the ajax requests, maybe they contain a useful error message.
