### ISSUE TITLE
Config tool: multiple inheritance issue (cumulative hostgroup assignment) 

### ISSUE THREAD

**Issue by simonmeggle** [sni/Thruk#630]
Given then following templates: 

```
define host {
  name                           tpl_host_netzwerk_switch
  use                            tpl_host_netzwerk
  hostgroups                     +hg_netzwerk_switch
  register                       0
}
define host {
  name                           tpl_host_netzwerk
  hostgroups                     +hg_netzwerk
  register                       0
}

define host {
  name                           tpl_host_basis_site
  hostgroups                     +hg_location_central,hg_site_central
  register                       0
}
```

Create a host with this configuration: 
```
define host {
  host_name                      sw_example
  address                        192.168.50.3
  use                            tpl_host_basis_site,tpl_host_netzwerk_switch
}
```

After reloading the config, livestatus will report the following hostgroups for *sw_example*: 
  * hg_location_central
  * hg_site_central
  * hg_netzwerk
  * hg_netzwerk_switch

As expected, the plus sign cumulated the hostgroups from both templates.  
The "computed" tab in Thruk config tool instead shows only the templates 
  * hg_location_central
  * hg_site_central

-> The "plus" signs seem to be ignored in this case.

**Comment by sni** [comment]
should be fixed now
