### ISSUE TITLE
Performance: fill_totals_box

### ISSUE THREAD

**Issue by ofosos** [sni/Thruk#633]
Hi,
fill_totals_box queries all services in the installation. This is not optimal.

On my Shinken installation the status.cgi takes approx. 3000ms to execute. After commenting out get_hosts_by_service_query in Thruk/Util/Status.pm:fill_totals_box the time to render the page falls to approx. 700ms.

Now get_hosts_by_service_query downloads quite a bit of information. There is however an alternative. I.e. to use Livestatus Aggregation/Count queries. The queries would be the following:

```
[root@xxx Utils]# time bash -c 'printf "GET hosts\nStats: state = 0\nStats: state = 1\nStats: state = 2\nStats: state = 3\nStats: state = 4\n\n\n" | socat - unix:/opt/livestatus/socket '
<approx 3000>

real    0m0.138s
user    0m0.002s
sys     0m0.005s
[root@monitor Utils]# time bash -c 'printf "GET services\nStats: state = 0\nStats: state = 1\nStats: state = 2\nStats: state = 3\n\n\n" | socat - unix:/opt/livestatus/socket '
<approx 30000>

real    0m0.544s
user    0m0.000s
sys     0m0.007s
```

Implementing these queries along those lines has a potential of cutting the execution time of status.cgi in half, reducing it from 3000ms to 700ms + 700ms.

What is you opinion on doing this using the count feature of Livestatus? I would like to go ahead with the implementation.

**Comment by sni** [comment]
Thats not accurate unfortunatly. You cannot use the host stats query to get the host stats for all hosts having services for example starting with a specific pattern. Or in general, it does not work whenever you filter for servicespecific things.

**Comment by ofosos** [comment]
Is it already possible to switch off the total boxes? That would be the alternative route.

**Comment by ofosos** [comment]
At least from looking at the Livestatus documentation it seems to be supported to filter the counts.

**Comment by ofosos** [comment]
Will you accept a pull request with an option to switch off these boxes?

**Comment by sni** [comment]
Have you tried the "&minimal=1" url parameter? Maybe thats already what you need.

**Comment by ofosos** [comment]
This does help somewhat with the browser display time, but this doesn't aid the execution time at all. Is it possible that the boxes are filled even though minimal is set? I think the code that fills the boxes is sxomewhat deeper into the utils package.

**Comment by ofosos** [comment]
Basically I'd like to stash no_totals = 1. That would do the trick.

**Comment by ofosos** [comment]
No actually stashing minimal = 1 would do the same trick, but as far as I can tell, &minimal=1 doesn't do this.

**Comment by sni** [comment]
if the box isn't displayed with minimal=1, then it should not be calculated at all. If thats not the case, then this is a bug. So i don't think we need another option here. Also i am working on a
new backend handler which should speed up livestatus and shinken drastically: https://github.com/sni/lampd

**Comment by ofosos** [comment]
I'm sorry, when I pass &minimal=1 this seems to get stashed in DefaultAction. The difference in request processing between minimal and normal amounts to 2700ms. That is 3000ms for a "normal" view vs. 300ms for a minimal view. 

&minimal=1 would do the trick, but I'd still have to hack it into some template or such. Also the search box is missing, so that's not ideal.

So what I would like to do is an option, that automatically stashes "no_totals" in DefaultAction, when a certain config parameter is set (status_no_totals). "no_totals" = 1 is already stashed in panorama.pm I'll go forward and implement that tomorrow.

**Comment by ofosos** [comment]
Mental note: set this as a default config, then stash it in DefaultAction. Then adapt templates/status_* to reflect the missing information.

**Comment by sni** [comment]
can you try this one: https://github.com/sni/Thruk/commit/5db00755c9ab1df323e94c875e0ad71aece62060
Maybe that helps already.

**Comment by sni** [comment]
Also i started a new project to handle the backend connections: https://github.com/sni/lmd
This should improve the overall livestatus performance drastically.

**Comment by ofosos** [comment]
Yep. Will try tomorrow.

--
Mark Meyer
mark@ofosos.org


On Tue, Sep 13, 2016, at 11:47 PM, Sven Nierlein wrote:
> can you try this one: 5db0075[1]
>  Maybe that helps already.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/sni/Thruk/commit/5db00755c9ab1df323e94c875e0ad71aece62060
  2. https://github.com/sni/Thruk/issues/633#issuecomment-246835835
