### ISSUE TITLE
Redirect to host details also with service filter

### ISSUE THREAD

**Issue by juaningan** [sni/Thruk#636]
Hi, It is possible to redirect to host details page if no services found also with service filter?

Actually we use only "Has not been acknowledgment" service filter so the use case is very similar to the original feature, doesnt?

Thanks in advance

**Comment by sni** [comment]
The service filter are not applicable to hosts, so they cannot be used. The main reason for the redirect was to be able to access hosts without services from the sidebar search.

**Comment by juaningan** [comment]
Maybe I dont explain well.

I have a dashboard where I aggregate host + service errors for every hostgroup. If I click it then goes to  service details view of services errors. If I only have host errors and no services errors Thruk automatically redirect me to host details view. This is perfect for my use case.

But, If I make the same thing but adding "Has not been acknowledgment" service filter then no redirect occurs. Can I enable it?

In former versions at least I have red text with a link to Host details view. Last version has no that link. Is there any option to come back this link?

Thanks again and apologize my poor english.

**Comment by sni** [comment]
Ok, now i understand. No, the redirect only happens if there are no filters involved. Otherwise it would be quite confusing if you for example have a filter on a service description which does not exist and suddenly get a list of all hosts because of the redirect.

**Comment by juaningan** [comment]
Ok, I understand your vision.

But, in former versions when no services match but hosts have errors I have text with a link to that Host details view. Last version has not. Is there any option to come back this link?

**Comment by sni** [comment]
no, there is no such option. In your case, i guess, the initial link should be improved to point to the right page in first place.
