### ISSUE TITLE
Thruk 2.10 doesn't read thruk_local.d/ files

### ISSUE THREAD

**Issue by alexkiousis** [sni/Thruk#637]
Hi,
after upgrading from 2.08 to 2.10 using the Debian packages, thruk no longer reads the files inside thruk_local.d.

For example:
```
:/etc/thruk# cat thruk_local.d/bgcolor 
# color the whole line with the check status - easier to parse with a glance
status_color_background = 1
```
This is no longer in effect.

Only relevant entry i can see in changelog is this:
```

2.10     Wed Aug 24 14:59:03 CEST 2016
....
          - support thruk_local.d/file.$hostname files to separate host specific configs
.....
```

Downgrading back to 2.08 fixes it. Is this a known issue?

**Comment by sni** [comment]
Only *.cfg and *.conf are possible now. Yes, this has to do with the mentioned change. Just rename your file to bgcolor.cfg and you should be fine.

**Comment by sni** [comment]
i also tried to make it more clear in the documentation.
