### ISSUE TITLE
graph_replace fails if service description contains hostname

### ISSUE THREAD

**Issue by Serration** [sni/Thruk#639]
When a service description contains the hostname, graph_replace will not properly substitute characters in the service description portion of the action URL.

Thruk creates a URL like this: 
`https://graphite.foobar.lan/?target=nagios.google_com.Foo bar - https://google_com/.*&width=600&height=300`
when it should look like this:
`https://graphite.foobar.lan/?target=nagios.google_com.Foo_bar_-_https___google_com_.*&width=600&height=300`

I use an edited version of Graphios that replaces spaces (and most other characters) with underscores. Given Nagios configuration like this:

    define host {
      host_name                      google.com
      address                        google.com
      use                            generic-host,host-pnp
    }

    define service {
            service_description             Foo bar - https://google.com/
            host_name                       google.com
            use                             generic-service,srv-pnp
            check_command                   check_http!-w 3 -c 6 -f follow --extended-perfdata -m 50
    }
    
    define host {
            name                            host-pnp
            action_url                      https://graphite.foobar.lan/render/?target=nagios.$HOSTNAME$.*&width=600&height=300
            register                        0
    }

Graphios and carbon-cache create these files:

    /var/lib/carbon/whisper/nagios/google_com/
    |-- Foo_bar_-_https___google_com_
    |   |-- size.wsp
    |   |-- time_connect.wsp
    |   |-- time_firstbyte.wsp
    |   |-- time_headers.wsp
    |   |-- time_transfer.wsp
    |   `-- time.wsp

With these settings in Thruk:

    graph_word = render            
    graph_replace = s/[^\w\-]/_/gmx

If the service description contains the hostname, the host substitution is applied to both the host and service description portions of the action URL, meaning the service description substitution is never applied.

**Comment by Serration** [comment]
Reordering the host and service description substitutions in `lib/Thruk/Utils.pm` (https://github.com/sni/Thruk/pull/640) is a simple hack that fixes this issue for most use cases, although it's not perfect. I imagine the reverse could occur if the host contained the service description. I've also seen the substitution apply to the website itself, e.g. `https://graphite.foobar_lan/...`.

**Comment by sni** [comment]
i merged your pull requests. Thanks.
