### ISSUE TITLE
malformed UTF-8 character in JSON string

### ISSUE THREAD

**Issue by mickenordin** [sni/Thruk#641]
We are running Thruk on top of icinga2. It is possible, at least for nsclient++ (have not tried to reproduce by any other mean), to output an invalid utf8 character, and icinga will accept that character, put it in the database and then spit it out via  both the restapi and via livestatus. 

When that happens Thruk will not display anything but the error message:

ERROR: malformed UTF-8 character in JSON string,.. (127.0.0.1:6558)

/var/log/thruk/thruk.log will at this time output:

> [2016/09/29 17:16:20][icinga-test-srv02][ERROR][Thruk] malformed UTF-8 character in JSON string, at character offset 10980 (before "\x{fffd}ndare ran su...") at /usr/share/thruk/lib/Monitoring/Livestatus.pm line 1164.
>  at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 343.
> [2016/09/29 17:16:20][icinga-test-srv02][ERROR][Thruk] No Backend available
> [2016/09/29 17:16:20][icinga-test-srv02][ERROR][Thruk] on page: https://monitor-test.example.com/thruk/cgi-bin/status.cgi?hidesearch=2&s0_op=~&s0_type=search&add_default_service_filter=1&s0_value=ho:dirsync-p-srv01.example.com
> [2016/09/29 17:16:20][icinga-test-srv02][ERROR][Thruk] icinga-test-srv02.example.com: ERROR: malformed UTF-8 character in JSON string,.. (127.0.0.1:6558)

The output from the actual check when run with check_npre is:

> OK: Scheduled Task Office 365 licensiering av anv�ndare ran successfully at 2016-09-29 17:00:00

This commit fixes the issue for us: https://github.com/sni/Thruk/compare/master...mickenordin:utf8 but @sni tells me that encode has a big footprint and that this is an performance critical part of thruk, so this might not be a valid solution to the problem and some other solution that makes sure that only valid utf8 is handle by Thruk so that the gui doesn't break when fault input is sent to the backend should probably be considered. 

This issue is also reported at icinga: https://dev.icinga.org/issues/12829

**Comment by mickenordin** [comment]
Here is an hexdump of the output from the plugin:

> root@icinga-test-srv02:~# /usr/lib/nagios/plugins/check_nrpe  -H dirsync-p-srv01.example.com -c "check_office365_licensing_scheduled_task" | hexdump -C
00000000  4f 4b 3a 20 53 63 68 65  64 75 6c 65 64 20 54 61  |OK: Scheduled Ta|
00000010  73 6b 20 4f 66 66 69 63  65 20 33 36 35 20 6c 69  |sk Office 365 li|
00000020  63 65 6e 73 69 65 72 69  6e 67 20 61 76 20 61 6e  |censiering av an|
00000030  76 84 6e 64 61 72 65 20  69 73 20 63 75 72 72 65  |v.ndare is curre|
00000040  6e 74 6c 79 20 72 75 6e  6e 69 6e 67 0a           |ntly running.|

The problem character is indicated by a dot in the output on the fourth row

**Comment by sni** [comment]
I setup a test command which exactly returns what your example returns. Double checked that with hexdump as well. But i cannot reproduce the error and it just works. This was an nagios 3 box. I tried to reproduce that with icinga2, but i didn't get the test command to work.
I only get strange errors when i tried my test command:
```
object CheckCommand "winlic" {
  command = "/omd/sites/devel/local/lib/nagios/plugins/winlic.sh"
}
```

```
critical/config: Error: Validation failed for object 'winlic' of type 'CheckCommand'; Attribute 'execute': Attribute must not be empty.
Location: in /omd/sites/icinga2/etc/icinga2/conf.d/test.conf: 1:0-1:27
/omd/sites/icinga2/etc/icinga2/conf.d/test.conf(1): object CheckCommand "winlic" {
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/omd/sites/icinga2/etc/icinga2/conf.d/test.conf(2):   command = "/omd/sites/devel/local/lib/nagios/plugins/winlic.sh"
/omd/sites/icinga2/etc/icinga2/conf.d/test.conf(3): }
```

**Comment by mickenordin** [comment]
The check that we run is done through nsclient++

**Comment by sni** [comment]
that shouldn't matter as long as it returns the same text.

**Comment by mickenordin** [comment]
Try to configure it like this:
object CheckCommand "winlic" {
        import "plugin-check-command"
        command = [ "/omd/sites/devel/local/lib/nagios/plugins/winlic.sh" ]
}

You are missing some configuration that you will get automatically if you use the template.

**Comment by sni** [comment]
Ok, that works. No word about that import in the icinga2 docs...
Anyway, at first i couldn't reproduce it either, then i noticed that i use LMD as Livestatus adaptor and it just worked. When i disabled LMD, i got the same utf8 error.
So this is somehow an error in Icinga2 i'd say because it works with vanilla livestatus and as a workaround i suggest enabling LMD. See https://labs.consol.de/omd/packages/lmd/ for some examples on how to enabled it in OMD. It works without OMD as well. The project itself is here: https://github.com/sni/lmd It "fixes" a couple of drawbacks of the icinga2 livestatus API. Like the missing sorting, broken custom variable filter, broken stats calculation, etc...
So when using Icinga2 i strongly recommend using LMD which also supports Icinga2 cluster.

**Comment by mickenordin** [comment]
Using LMD does fix this issue, and as LMD now detects some changes made via the Icinga2 http api as well I would recommend it for use with Icinga2 backends. I think we can close this issue as it works with LMD.
