### ISSUE TITLE
Panorama broken after 2.06 to 2.10 upgrade

### ISSUE THREAD

**Issue by glaurent-ullink** [sni/Thruk#643]
Hi,

We were running Thruk 2.06 for few months, with 3 backends, and one Panorama dashboard; and attempts to upgrade to 2.10 last weekend.

Server is running Debian 8.06 with all latest packages.

But after the upgrade, Panorama isn't working anymore:

> [2016/10/03 11:13:48][deb-nagios-dev][ERROR][Thruk] Error in: /thruk/cgi-bin/panorama.cgi
> [2016/10/03 11:13:48][deb-nagios-dev][ERROR][Thruk] missing argument at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 167.
>         Thruk::Backend::Manager::get_peer_by_key(Thruk::Backend::Manager=HASH(0x2fad5f0), undef) called at /usr/share/thruk/lib/Thruk/Utils.pm line 2549
>         Thruk::Utils::backends_hash_to_list(Thruk::Context=HASH(0x3b6a628), ARRAY(0x38870e0)) called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Utils/Panorama.pm line 255
>         Thruk::Utils::Panorama::load_dashboard(Thruk::Context=HASH(0x3b6a628), "tabpan-tab_2") called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 320
>         Thruk::Controller::panorama::_js(Thruk::Context=HASH(0x3b6a628), 1) called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 246
>         Thruk::Controller::panorama::index(Thruk::Context=HASH(0x3b6a628)) called at /usr/share/thruk/lib/Thruk.pm line 277
>         eval {...} called at /usr/share/thruk/lib/Thruk.pm line 266
>         Thruk::_dispatcher(HASH(0x3ac43d0)) called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
>         eval {...} called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
>         Plack::Util::run_app(CODE(0x212c480), HASH(0x3ac43d0)) called at /usr/lib/thruk/perl5/Plack/Handler/FCGI.pm line 143
>         Plack::Handler::FCGI::run(Plack::Handler::FCGI=HASH(0x8ab088), CODE(0x212c480)) called at /usr/share/thruk/script/thruk_fastcgi.pl line 24
>  at /usr/lib/thruk/perl5/Plack/Util.pm line 142.
>         eval {...} called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
>         Plack::Util::run_app(CODE(0x212c480), HASH(0x3ac43d0)) called at /usr/lib/thruk/perl5/Plack/Handler/FCGI.pm line 143
>         Plack::Handler::FCGI::run(Plack::Handler::FCGI=HASH(0x8ab088), CODE(0x212c480)) called at /usr/share/thruk/script/thruk_fastcgi.pl line 24
> [2016/10/03 11:13:48][deb-nagios-dev][ERROR][Thruk] internal server error
> [2016/10/03 11:13:48][deb-nagios-dev][ERROR][Thruk] on page: http://deb-nagios-dev/thruk/cgi-bin/panorama.cgi

Upgrade with no Dashboard defined (default Thruk setup) failed too with:
> Error
> adding new dashboard failed: 404 - Not Found
thruk.log are:

> [2016/10/03 11:42:49][deb-nagios-dev][ERROR][Thruk] error while loading dynamic dashboard from /etc/thruk/plugins//plugins-available/panorama/0.tab: missing argument at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 167.
>         Thruk::Backend::Manager::get_peer_by_key(Thruk::Backend::Manager=HASH(0x318c0d0), undef) called at /usr/share/thruk/lib/Thruk/Utils.pm line 2549
>         Thruk::Utils::backends_hash_to_list(Thruk::Context=HASH(0x39a62a8), ARRAY(0x3a8af88)) called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Utils/Panorama.pm line 255
>         Thruk::Utils::Panorama::load_dashboard(Thruk::Context=HASH(0x39a62a8), 2, 1) called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Utils/Panorama.pm line 111
>         Thruk::Utils::Panorama::get_dashboard_list(Thruk::Context=HASH(0x39a62a8), "my") called at /etc/thruk/plugins//plugins-available/panorama/0.tab line 74
>         eval '#line 1 /etc/thruk/plugins//plugins-available/panorama/0.tab
> # title:  Startpage
> # user:   thrukadmin
> # groups: [{"*" : "read-only"}]
> 
> $dashboard = load_data();
> 
> $dashboard->{\'ts\'} = [stat($c->config->{etc_path}.\'/panorama/.\')]->[9];
> 
> my $_add_panlet = sub {
>     my($x, $y, $d) = @_;
>     if($d->{\'ts\'} && $dashboard->{\'ts\'} < $d->{\'ts\'}) {
>         $dashboard->{\'ts\'} = $d->{\'ts\'};
>     }
>     return({
>         "xdata" => {
>             "appearance" => {
>                 "iconset" => "default_64",
>                 "type" => "icon"
>             },
>             "cls" => "TP.DashboardStatusIcon",
>             "general" => {
>                 "dashboard" => $d->{\'nr\'},
>             },
>             "label" => {
>                 "bgcolor" => "#cccccc",
>                 "bordercolor" => "#aaaaaa",
>                 "bordersize" => 1,
>                 "fontsize" => 10,
>                 "labeltext" => "<center>".$d->{\'name\'}."</center>",
>                 "offsety" => 42,
>                 "position" => "center",
>                 "width" => "60"
>             },
>             "layout" => {
>                 "x" => $x,
>                 "y" => $y,
>             },
>             "link" => {
>                 "link" => "dashboard://".$d->{\'nr\'},
>                 "newtab" => "on"
>             },
>             "nsize" => [ 64, 64 ],
>             "size" => 64
>         }
>     });
> };
> 
> my $_add_label = sub {
>     my($x, $y, $text) = @_;
>     return({
>         "xdata" => {
>             "cls" => "TP.TextLabelWidget",
>             "label" => {
>                 "fontbold" => "1",
>                 "fontsize" => 18,
>                 "labeltext" => $text,
>                 "position" => "top-left",
>             },
>             "layout" => {
>                 "x" => $x,
>                 "y" => $y,
>             }
>         }
>     });
> };
> 
> 
> my $nr = 1;
> $dashboard->{\'panlet_\'.++$nr} = &{$_add_label}(20, 40, "Create New Dashboard:");
> 
> # fetch my maps
> my $x  = 20;
> my $y  = 210;
> my $dashboards = Thruk::Utils::Panorama::get_dashboard_list($c, \'my\');
> if(scalar @{$dashboards} > 0) {
>     $dashboard->{\'panlet_\'.++$nr} = &{$_add_label}(20, 190, "Open Existing Dashboards:");
>     for my $d (@{$dashboards}) {
>         next if $d->{\'nr\'} == $dashboard->{\'nr\'}; # avoid recursion
>         if($x > 800) {
>             $x = 20;
>             $y = $y + 90;
>         }
>         $dashboard->{\'panlet_\'.++$nr} = &{$_add_panlet}($x, $y, $d);
>         $x = $x + 70;
>     }
>     $y = $y + 130;
> }
> 
> # fetch public maps
> $dashboard->{\'panlet_\'.++$nr} = &{$_add_label}(20, $y, "Public Dashboards:");
> $y = $y + 20;
> $x = 20;
> $dashboards = Thruk::Utils::Panorama::get_dashboard_list($c, \'public\');
> for my $d (@{$dashboards}) {
>     next if $d->{\'nr\'} == $dashboard->{\'nr\'}; # avoid recursion
>     if($x > 800) {
>         $x = 20;
>         $y = $y + 90;
>     }
>     $dashboard->{\'panlet_\'.++$nr} = &{$_add_panlet}($x, $y, $d);
>     $x = $x + 70;
> }
> 
> ' called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Utils/Panorama/Scripted.pm line 61
>         Thruk::Utils::Panorama::Scripted::load_dashboard(Thruk::Context=HASH(0x39a62a8), 0, "/etc/thruk/plugins//plugins-available/panorama/0.tab", undef) called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Utils/Panorama.pm line 183
>         Thruk::Utils::Panorama::load_dashboard(Thruk::Context=HASH(0x39a62a8), "tabpan-tab_0") called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 2358
>         Thruk::Controller::panorama::_task_dashboard_data(Thruk::Context=HASH(0x39a62a8)) called at /etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 107
>         Thruk::Controller::panorama::index(Thruk::Context=HASH(0x39a62a8)) called at /usr/share/thruk/lib/Thruk.pm line 277
>         eval {...} called at /usr/share/thruk/lib/Thruk.pm line 266
>         Thruk::_dispatcher(HASH(0x3999220)) called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
>         eval {...} called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
>         Plack::Util::run_app(CODE(0x22f6740), HASH(0x3999220)) called at /usr/lib/thruk/perl5/Plack/Handler/FCGI.pm line 143
>         Plack::Handler::FCGI::run(Plack::Handler::FCGI=HASH(0xa8a088), CODE(0x22f6740)) called at /usr/share/thruk/script/thruk_fastcgi.pl line 24
> 

Rollback to 2.06 succeed, but can't figure out what's wrong with the upgrade to 2.10.

Didn't find any specific instructions for the upgrade.

**Comment by sni** [comment]
Thanks, this is already fixed in https://github.com/sni/Thruk/commit/c61ff04c479881bf81d6b03ac081891fcf91c63e. There will be a new release soon.

**Comment by glaurent-ullink** [comment]
Great, waiting for next release then.
Thanks.
