### ISSUE TITLE
Unable to start/work with more than 2 backends

### ISSUE THREAD

**Issue by falzm** [sni/Thruk#644]
Hi

We've stumbled on a weird issue with Thruk (version 2.10): it works perfectly fine with 1 or 2 Nagios+Livestatus backends configured, however once we add a 3rd one it stops working: every attempt to request it ends up in timeout (setup with Nginx/uwsgi). Note: the 3 backends work fine individually – we've tested all combinations (A alone, B alone, C alone, A+B, B+C, A+C...): works every time with 2 backends, doesn't with 3.

We're unable to get a single line of log explaining the issue, can you please help? Let me know if you need me to provide more details about our setup.

**Comment by sni** [comment]
Are these "normal" livestatus backends? Because we sometimes had issues with https backends when they reach a certain number.

**Comment by falzm** [comment]
Yes "normal", exposed in TCP via Xinetd instead of UNIX socket.

**Comment by sni** [comment]
Starting with 3 or more backends, Thruk uses a Backend Thread Pool, maybe that leads to some issues here. You could set the environment variable THRUK_NO_CONNECTION_POOL=1 to disable it. However, it would be interesting to know whats going wrong here.

**Comment by falzm** [comment]
I confirm that with the `THRUK_NO_CONNECTION_POOL=1` environment variable set it works, so it is probably linked to the thread pool.

**Comment by sni** [comment]
You may want to have a look at the lmd side project: https://github.com/sni/lmd
This makes the backend handling a lot smoother when having multiple backends.
