### ISSUE TITLE
Thruk not picking up mod_fcgid IPCCommTimeout value

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#645]
Thruk 2.10 / CentOS 7 / mod_fcgid 2.3.9

Use case: combining many identical services
Symptom: mod_fcgid: read data timeout in 40 seconds in apache logs

However, fcgid conf file defines IPCCommTimeout as 120 s. 40 is the default value [1]

Solution: add IOTimeout <timeout is sec> option to FcgidCmdOptions in thruk.conf file as per doc [2]

Reference: 
[1] https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidiotimeout
[2] https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidcmdoptions

**Comment by sni** [comment]
Thanks for the information. I added a note to the example apache configuration file.
