### ISSUE TITLE
Panorama Infinite loading caused by using multiple custom icons (Hack found)

### ISSUE THREAD

**Issue by mc55boy** [sni/Thruk#649]
Hi there,

After looking through all of the available forums I cannot find anyone else who has experienced the same issue as I have (apart from perhaps this one: https://github.com/sni/Thruk/issues/280).

Once I add more than one custom icon onto my dashboard, save and reload from the save file the dashboard gets stuck in an infinite loop trying to load the dashboard.

After looking at the save files created I have found that the one that gets stuck doesn't hold all the data as seen below (I have removed the image data in the example below but have left them in the files I am loading into Thruk):

``` JSON
{
  "tabpan-tab_1_panlet_2": {
    "xdata": {
      "layout": {
        "rotation": 0,
        "zindex": "0",
        "scale": 100,
        "y": 216,
        "x": 872
      },
      "nsize": [
        256,
        256
      ],
      "cls": "TP.HostStatusIcon",
      "general": {
        "host": "Brewdog"
      },
      "link": {},
      "size": 363,
      "appearance": {
        "type": "icon",
        "iconset": "NAS"
      },
      "label": {},
      "state": 0
    }
  },
  "version": "2.10",
  "tab": {
    "xdata": {
      "groups": [],
      "background": "none",
      "state_type": "soft",
      "title": "Dashboard",
      "refresh": "90",
      "select_backends": 0,
      "backends": [],
      "owner": "thrukadmin",
      "autohideheader": 1,
      "defaulticonset": "default"
    }
  },
  "usercontent": {
    "images/status/CCTV/downtime_unreachable.png": "",
    "images/status/CCTV/downtime_unknown.png": "",
    "images/status/CCTV/downtime_pending.png": "",
    "images/status/CCTV/warning.png": "",
    "images/status/CCTV/downtime_ok.png": "",
    "images/status/CCTV/downtime_down.png": "",
    "images/status/CCTV/unreachable.png": "",
    "images/status/CCTV/acknowledged_critical.png": "",
    "images/status/CCTV/downtime_up.png": "",
    "images/status/CCTV/acknowledged_unknown.png": "",
    "images/status/CCTV/down.png": "",
    "images/status/CCTV/downtime_warning.png": "",
    "images/status/CCTV/downtime_critical.png": "",
    "images/status/CCTV/acknowledged_unreachable.png": "",
    "images/status/CCTV/acknowledged_down.png": "",
    "images/status/CCTV/unknown.png": "",
    "images/status/CCTV/up.png": "",
    "images/status/CCTV/critical.png": "",
    "images/status/CCTV/ok.png": "",
    "images/status/CCTV/pending.png": "",
    "images/status/CCTV/acknowledged_warning.png": "",
    "images/status/NAS/unreachable.png": "",
    "images/status/NAS/pending.png": "",
    "images/status/NAS/warning.png": "",
    "images/status/NAS/up.png": "",
    "images/status/NAS/critical.png": "",
    "images/status/NAS/down.png": "",
    "images/status/NAS/ok.png": "",
    "images/status/NAS/unknown.png": ""
  },
  "tabpan-tab_1_panlet_1": {
    "xdata": {
      "nsize": [
        256,
        256
      ],
      "layout": { #### <------- This section is missing rotation data
        "scale": 100,
        "y": 224,
        "x": 285,
        "zindex": "0"
      },
      "link": {},
      "general": {
        "host": "Border"
      },
      "cls": "TP.HostStatusIcon",
      "appearance": {
        "type": "icon",
        "iconset": "CCTV"
      },
      "size": 363,
      "state": 0,
      "label": {}
    }
  }
}

```

After adding in :

``` JSON
"rotation": 0,
```

The file loaded and worked fine.

I am currently investigating whether this is only for rotation data or whether other fields are affected and will post the results of my findings on larger and different files (as the above is only a test file).

Thanks.

**Comment by mc55boy** [comment]
After investigating this further I have found the cause of the problem (but not the underlying root cause) and a workaround for people who face the same issue as I have until this bug can be fixed.

The investigation above turned out to be a red herring and the actual issue lies with having multiple custom icons on the same dashboard so please **ignore** all information in the previous post.

My setup:
- Thruk running alongside Apache in a docker container with Ubuntu as the base image

The method I followed:
- Create two separate dashboards with a single custom icon on each = Both load
- Creating a dashboard which holds the same two custom icons with identical properties = Dashboard won't load
- Manually combining the JSON data from the individual dashboards to create a single dashboard = Dashboard won't load
     - Comparing the save file and the manually created combined file shows that they both are identical
- Take out the image data off of both files that hold both custom icons = Dashboard loads but icons don't appear and the image files in the folder are overwritten so that they hold no data
- When creating a dashboard using only default icons it doesn't matter how many icons you use, the dashboard will load

When looking at the save function in ~/thruk/plugins/plugins-available/panorama/lib/Thruk/Controller/panorama.pm I found this (starting line 795):

``` perl
if($p->{'xdata'}->{'appearance'} && $p->{'xdata'}->{'appearance'}->{'iconset'}) {
            my $file = $p->{'xdata'}->{'appearance'}->{'iconset'};
            if($file && $file !~ m|/|mx && $file !~ m|\.\.|mx) {
                next if $file eq 'default'; # skip our default sets
                next if $file eq 'default_64';
                next if $file eq 'tfl';
                next if $file eq 'emoji';
                next if $file eq 'emoji_64';
                my @files = glob($c->stash->{'usercontent_folder'}.'/images/status/'.$file.'/*');
                my $usercontent_folder = $c->stash->{'usercontent_folder'}.'/';
                for my $f (@files) {
                    my $short = $f;
                    $short =~ s|^$usercontent_folder||mx;
                    $images->{$short} = $f;
                }
            }
        }
```

Which excludes the default images in the saving process. So to skip all images being saved and make Thruk only use the files held in the folder rather than trying to load them from the file I change it to this:

``` perl
if($p->{'xdata'}->{'appearance'} && $p->{'xdata'}->{'appearance'}->{'iconset'}) {
            my $file = $p->{'xdata'}->{'appearance'}->{'iconset'};
            if($file && $file !~ m|/|mx && $file !~ m|\.\.|mx) {
                next;     # <---- FIX
                next if $file eq 'default'; # skip our default sets
                next if $file eq 'default_64';
                next if $file eq 'tfl';
                next if $file eq 'emoji';
                next if $file eq 'emoji_64';
                my @files = glob($c->stash->{'usercontent_folder'}.'/images/status/'.$file.'/*');
                my $usercontent_folder = $c->stash->{'usercontent_folder'}.'/';
                for my $f (@files) {
                    my $short = $f;
                    $short =~ s|^$usercontent_folder||mx;
                    $images->{$short} = $f;
                }
            }
        }
```

This is by far no a proper solution and means that in order to load a dashboard you need to have all the files locally, but it is a temporary hack. If I find the underlying solution to this problem then I will post again on this thread.

Hope this helps anyone experiencing the same problem.

**Comment by sni** [comment]
I fixed something recently which caused a similar error and an endless loop trying to load a dashboard. Have you tried the latest nightly?
Please reopen the issue if it still persists.
