### ISSUE TITLE
Carriage return in Excel Exports

### ISSUE THREAD

**Issue by heinowalther** [sni/Thruk#656]
Hi there
I use the Excel export feature of specific service groups with all their checks.
It works great, yet there is one little issue which should be "easy" to fix.
If one of the checks which I export has several lines in them, it shows OK in the Thruk GUI, one on each line.  Yet when I export to Excel, the output is one continues line with no carriage return.
It is the column called "Extra Status Information".
I have tried to alter the output of the check from "nagios to html to cmd".
I am able to do CR in the column myself so it's not the format of the cell (which is "general")
To do the CR in Excel I use "Alt+Return" (on Mac).

I hope that this can be "fixed" somehow?

Regards!
/Heino

**Comment by rroblik** [comment]
+1  

@heinowalther : maybe you've found a solution since this long time ?

**Comment by heinowalther** [comment]
Nope, sadly it's still a large mess for me :-(
I was actually going to export the status out via the "Live Status" tool released by the guys who also do CheckMK...  I use the OMDdist where is it included and I also use it to link several monitoring server together to one central site. (come to think of it, I think it is also standard in Thruk...) :-)
