### ISSUE TITLE
variable expansion works better than icinga1/nagios's implementation - and this is a problem

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#658]

**Comment by yoshi314** [comment]
Consider this example:

the actual command, as specified by thruk.
 	
/usr/local/lib/nagios/plugins/check_wmi_plus.pl -H  172.17.0.40 -u 'login' -p sekrit -m checkdrivesize -w _Used%=88 -c _Used%=92 -a .

it comes out of this check definition:

`check_wmi!checkdrivesize -w _Used%=$ARG2$ -c _Used%=$ARG3$ -a .!88!92`

and the command check_wmi defined as 

`$USER2$/check_wmi_plus.pl -H  $HOSTADDRESS$ -u 'login' -p sekrit -m $ARG1$ $ARG2$ $ARG3$ $ARG4$`


Now, the thing is that $ARG1$ contains $ARG2$ and $ARG3$. Thruk expands that correctly, but icinga1 itself does not.


Running the command that thruk suggested by hand caused the check to run correctly.

`WARNING - [Triggered by _Used%>88] - T: Total=649.997GB, Used=588.837GB (90.6%), Free=61.16GB (9.4%)     CRITICAL - [Triggered by _Used%>92] - V: Total=299.873GB, Used=281.782GB (94.0%), Free=18.091GB (6.0%)     OK - C: Total=68.018GB, Used=47.628GB (70.0%), Free=20.39GB (30.0%)     OK - D: Total=68.336GB, Used=51.616GB (75.5%), Free=16.72GB (24.5%)     OK - J: Total=99.873GB, Used=11.249GB (11.3%), Free=88.624GB (88.7%)     OK - M: Total=1,020.996MB, Used=75.609MB (7.4%), Free=945.387MB (92.6%)     OK - P: Total=49.873GB, Used=14.348GB (28.8%), Free=35.525GB (71.2%)     OK - R: Total=949.997GB, Used=832.375GB (87.6%), Free=117.622GB (12.4%)     OK - S: Total=399.997GB, Used=200.729GB (50.2%), Free=199.268GB (49.8%)     OK - U: Total=299.997GB, Used=5.55GB (1.8%), Free=294.448GB (98.2%)     |'C: Space'=51139661824B; 'C: Utilisation'=70.0%;88;92; 'D: Space'=55422328832B; 'D: Utilisation'=75.5%;88;92; 'J: Space'=12078743552B; 'J: Utilisation'=11.3%;88;92; 'M: Space'=79282176B; 'M: Utilisation'=7.4%;88;92; 'P: Space'=15405891584B; 'P: Utilisation'=28.8%;88;92; 'R: Space'=893755523072B; 'R: Utilisation'=87.6%;88;92; 'S: Space'=215531134976B; 'S: Utilisation'=50.2%;88;92; 'T: Space'=632259018752B; 'T: Utilisation'=90.6%;88;92; 'U: Space'=5958742016B; 'U: Utilisation'=1.8%;88;92; 'V: Space'=302560780288B; 'V: Utilisation'=94.0%;88;92;`


however, icinga1 and nagios had this output 👍 

```

Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
Warning/Critical specification (_Used%=$) not defined correctly
OK - C: Total=68.018GB, Used=47.628GB (70.0%), Free=20.39GB (30.0%)     OK - D: Total=68.336GB, Used=51.616GB (75.5%), Free=16.72GB (24.5%)     OK - J: Total=99.873GB, Used=11.249GB (11.3%), Free=88.624GB (88.7%)     OK - M: Total=1,020.996MB, Used=75.609MB (7.4%), Free=945.387MB (92.6%)     OK - P: Total=49.873GB, Used=14.348GB (28.8%), Free=35.525GB (71.2%)     OK - R: Total=949.997GB, Used=832.376GB (87.6%), Free=117.621GB (12.4%)     OK - S: Total=399.997GB, Used=200.729GB (50.2%), Free=199.268GB (49.8%)     OK - T: Total=649.997GB, Used=588.837GB (90.6%), Free=61.16GB (9.4%)     OK - U: Total=299.997GB, Used=5.55GB (1.8%), Free=294.448GB (98.2%)     OK - V: Total=299.873GB, Used=281.782GB (94.0%), Free=18.091GB (6.0%)     |'C: Space'=51139665920B; 'C: Utilisation'=70.0%; 'D: Space'=55422328832B; 'D: Utilisation'=75.5%; 'J: Space'=12078743552B; 'J: Utilisation'=11.3%; 'M: Space'=79282176B; 'M: Utilisation'=7.4%; 'P: Space'=15405891584B; 'P: Utilisation'=28.8%; 'R: Space'=893757095936B; 'R: Utilisation'=87.6%; 'S: Space'=215531393024B; 'S: Utilisation'=50.2%; 'T: Space'=632259018752B; 'T: Utilisation'=90.6%; 'U: Space'=5958742016B; 'U: Utilisation'=1.8%; 'V: Space'=302560780288B; 'V: Utilisation'=94.0%;
```


as it turns out, the actual invocation of the check was 

`/usr/local/lib/nagios/plugins/check_wmi_plus.pl -H  172.17.0.40 -u 'login' -p sekrit -m checkdrivesize -w _Used%=$ARG2$ -c _Used%=$ARG3$ -a .`

**Comment by sni** [comment]
Well, if nagios and icinga do not expand it this way, then its Thruk who is wrong. We just want to display the correct command like nagios would run it.

**Comment by sni** [comment]
Should be better now, thanks for the report.
