### ISSUE TITLE
Livestatus ordering of services

### ISSUE THREAD

**Issue by mboden** [sni/Thruk#661]
Hello,

I don't know if this is a bug/incompatilibity in icinga or thruk, the icinga folks didn't think it was in their end so I submit the issue here.

Anyway, the ordering of services in livestatus (at least in icinga) sorted by host:

echo -e 'GET services\n' | nc -U /var/run/icinga2/cmd/livestatus | grep -n hostX |cut -d: -f1
76
77
78
79
80
81
82
83
606
613
617
621

The effect this has is that when viewing services you only see for example a server with only like 7 services. The rest will come on a later page. If I select to view all services on one page they are sorted correctly.

It is easy to believe that there are no more services for that host when it is like this.

The screenshosts show what I mean. The host covered in blue is the same host.

Regards
Magnus

**Comment by mboden** [comment]
![thruk-all](https://cloud.githubusercontent.com/assets/6309655/21008689/1e45b044-bd43-11e6-9f58-23d96f7d3fff.png)
![thruk-pages](https://cloud.githubusercontent.com/assets/6309655/21008688/1e438850-bd43-11e6-8c00-a75c3f0ce23c.png)

**Comment by sni** [comment]
I am not sure if i understand the problem correctly. Is there a difference in Icinga 2 if you use "Limit: 100" in the livestatus query or if you fetch everything and then use the first 100 matches.
Thruk uses the "Limit:" livestatus header to reduce and speed up the livestatus result. Also Thruk does not sort the result unless you explicitly request that by clicking the column headers in that table. Thruk just uses the natural sort order of the backend.
It gets a bit more complicated if you have multiple backends selected. Then Thruk must merge, sort and page the data once.

**Comment by mboden** [comment]
Hello,

Yes there is a difference because at least icinga 2 doesnt return the services ordered by host name. So if you use get the first 100 entries only not all service from the first host might be in those first 100 entries.

As you can see in this output the individual services for hostX are returned as item 76, 77, 78... and the last one as entry 621.

echo -e 'GET services\n' | nc -U /var/run/icinga2/cmd/livestatus | grep -n hostX |cut -d: -f1
76
77
78
79
80
81
82
83
606
613
617
621

> Is there a difference in Icinga 2 if you use "Limit: 100" in the livestatus query or if you fetch everything and then use the first 100 matches.

I would guess no. But I think when thruk gets everything it will sort it by host before using the first 100 entries. So the way icinga 2 (I am running 2.6.0 now but 2.5.4 was the same) works "Limit: 100" is pretty useless if you care about keeping all services together in the list.

It doesn't seem like having two backends marked green makes any difference, I still don't see all the services from hostX in the first page. Don't you still retrieve the first 100 entries from both backend and then sort those two lists together? What needs to happen here I guess is retrieve everything and then sort those by host and then using the first 100 entries. 

I reported this to the icinga camp and they said there is nothing in the livestatus specs (it sounded like there are none really) that says the results should be sorted so they didn't think it was something for them to fix. (https://dev.icinga.com/issues/13465)

From the livestatus page:

7.6. Limitting the number of datasets

The Limits-header allows you to limit the number of datasets being displayed. Since MK Livestatus currently does not support sorting, you'll have to live with the Nagios-internal natural sorting of objects. Hosts, for example, are sorted according to their host names - just as in the standard CGIs. The following example will output just the first 10 hosts: 

In the thruk UI I tried to press the arrow to sort by hostname ascending but it still only shows a few of all the services from hostX on the first page. This seems logical when reading section 7.6 above which says there is no support for sorting in the livestatus query meaning I guess thruk will retrieve only the first 100 entries and sort those. If livestatus has "sort by host" then "Limit: 100" would be useful.

Retreiving everything to view the first 100 entries is of course less optimal especially if there are 50,000 entries to retrieve. So perhaps this could be a configuration option that says to retrieve everything instead of using the "Limit: 100" but still only display the first 100.

To me I think the best thing would be to extend livestatus and add sorting there (but that will probably not happen anytime soon). Then I think matching icinga with nagios sorting seems logical (Which they didn't think) and then thruk retreiving everything as a last resort.

Best Regards and thanks for the best monitoring frontend
Magnus Boden

**Comment by sni** [comment]
Yes, its not that easy. Thruk assumes that the services and hosts tables in livestatus are naturally ordered by host_name and service_description. Thruk uses this to do all kind of performance tweaks and optimizations. Its exactly like you said. When using paging (without sorting from the page) Thruk just fetches the first x rows. Of course this does not work if the backend returns the services in random order. When having multiple backends, Thruk fetches the first x rows from all of them, sorts them internally and cuts of everything after x matches. This cannot work either if the backend returns data in random order.
In fact, there are livestatus variants which support ordering, naemon for example or the LMD project.
When using Icinga 2, i strongly recommend using LMD as a transparent livestatus proxy between Thruk and Icinga 2. It fixes all sort of problems in the Icinga2 livestatus implementation and makes Thruk faster and use less memory. The stats filter in Icinga 2 are broken and custom variable filters are broken as well, both fixed when using LMD. Unfortunatly the livestatus API is more or less unmaintained in Icinga 2, so LMD uses basic uncomplicated querys to fetch all data from Icinga 2 and does all the query stuff like filtering, sorting, etc.. itself.
I eventually will enable LMD by default in the future, but till then, you have to add it yourself.

- https://github.com/sni/lmd
- https://labs.consol.de/omd/packages/lmd/
- http://www.slideshare.net/SvenNierlein/lmd-livestatus-multitool-daemon

**Comment by mboden** [comment]
Hello again,

I guess the sorting options in the ui should be for sorting only within the first 100 entries retreived?
Some tests indicate it is not so. If I sort by service ascending for example I get a listing of the service called "Backup" on all hosts. Would that mean you in that case thruk resorts to retreiving all entries and then sort them by itself?

So using the backends natural order only applies to sorting on the host field?

If so then I would say thruk can't rely on the ordering of service in the livestatus services table to be ordered by hostname. (Which is not the case in icinga at least).

I started writing this before reading you reply and I understand the complicated nature of the problem.

LMD seems to be a brilliant way to fix the problem. I will implement it right away in my monitoring solution. I have almost ten backends so I guess this will speed up the ui experience for the users too.

Best Regards
Magnus
