### ISSUE TITLE
Spread Checks seems not to work

### ISSUE THREAD

**Issue by m-kraus** [sni/Thruk#663]
When selecting multiple checks and doing a "reschedule" of the checks with "spread checks" enabled, all checks get executed at the same time though.
There seems to be no difference with or without LMD enabled.

**Comment by sni** [comment]
Assuming you are having this issue with Icinga2, this is broken and does not work with Icinga 2 or as they say "works as designed".
See https://dev.icinga.com/issues/11016 for details.

**Comment by m-kraus** [comment]
Sorry Sven, not Icinga2 this time - OMD Labs with nagios core

**Comment by m-kraus** [comment]
Please tell me what you need to debug this issue

**Comment by sni** [comment]
you could check the nagios logfile if the commands were submited correctly.
