### ISSUE TITLE
Services views do not show immediately

### ISSUE THREAD

**Issue by m-kraus** [sni/Thruk#667]
Thruk Version 2.13-20161220 - OMD 2.21~2016-12-20-labs-edition

When clicking "Service problem"-links or on opening any other filtered services view, the results table is initially not shown or emtpy. Only after clicking the "filter accept" button, the results are displayed.

Filtered Host views seem to work as expected.

**Comment by m-kraus** [comment]
Annotation: The pagination header is shown already initially, e.g. showing "1 2 3 4", but the table is not shown.

**Comment by sni** [comment]
fixed with d330318e07
