### ISSUE TITLE
Panorama view: Shapes do not show state color

### ISSUE THREAD

**Issue by m-kraus** [sni/Thruk#668]
Thruk Version 2.13-20161220 - OMD 2.21~2016-12-20-labs-edition

Icon-Widgets for hosts, hostgroups, services and servicegroups are showing the correct icons (red, green, etc.) depending on status. When switching to shapes, no state based colors are shown.

**Comment by sni** [comment]
I'd say this is fixed meanwhile. Please reopen if this issue still persists.

**Comment by sshatney61** [comment]
In testing shape colors it appears down and unreachable are reversed.  Can someone comfirm.
