### ISSUE TITLE
Panorama View: Host/Services boxes lose column width on dashboard unlock

### ISSUE THREAD

**Issue by m-kraus** [sni/Thruk#669]
Thruk Version 2.13-20161220 - OMD 2.21~2016-12-20-labs-edition

After inserting a host or service box the column width can be changed by dragging. This width gets stored when locking the dashboard.

But after unlocking the dashboard again for editing the column width in all Host- and Service-Boxes are lost and reset to defaults.

**Comment by sni** [comment]
fixed with 7f9c1f8e44b
