### ISSUE TITLE
Build Thruk Debian packages

### ISSUE THREAD

**Issue by majales** [sni/Thruk#670]
Hi,
I have successfully built current main naemon packages of version 1.05 for debian armhf (Raspberry Pi). But I have trouble to install them since they depends on thruk deb package. I noticed that there are four packages for Thruk for x64 arch:

thruk-base_2.12-3_debian8_amd64.deb
thruk-plugin-reporting_2.12-3_debian8_amd64.deb
thruk_2.12-3_debian8_amd64.deb
libthruk_2.10-1_debian8_amd64.deb

Could you please provide some guide or howto for building these packages for debian armhf? 
Thanks in advance.

**Comment by sni** [comment]
Usually you can just do a "make deb". Both for thruk itself and the libthruk repository.

**Comment by majales** [comment]
I´m sorry, but I'm probably missing something.. I can build libthruk.deb but I don't know how to build the rest of the packages... I've got "make: *** No rule to make target 'deb'.  Stop." for building from "git://github.com/sni/thruk.git"

**Comment by sni** [comment]
I use `debuild -rfakeroot -i -us -uc -b` to build the package but i added a new make target with the last commit. For Thruk you should now be able to run
```
  perl Makefile.PL
  make deb
```
You will need to install the libthruk package befor that.
