### ISSUE TITLE
Action menus with macros after ? in url

### ISSUE THREAD

**Issue by mboden** [sni/Thruk#672]
Hello,

If I have an action menu with this target:
        "action":"https://xxx.se/dokuwiki/?id=kunder:noder:$HOSTNAME$",\

macro replacement doesn't work. when pressing the link I get to https://xxx.se/dokuwiki/doku.php

If I remove the ? from the action url macro replacement works but of course dokuwiki is not happy.

I also tried replacing the ? with %3f but that doesn't work either.

Regards
Magnus

**Comment by sni** [comment]
I cannot reproduce that. I tried your link and the macros gets replace like expected. Please reopen the issue if it still persists.
