### ISSUE TITLE
Thruk internal server error - backend manager

### ISSUE THREAD

**Issue by queox** [sni/Thruk#676]
Hi,

at first I'd like to thank you for all your efforts in making Thruk such
a great tool!
I never had any issues with the mk-livestatus (nagios) backends before, but in
Version 2.12-3 I get a lot of "internal server errors" like listed below.
Maybe you can help me in resolving this issue?

Thanks in advance, best regards
Kurt

**Error Report**
Url: status.cgi?nav=&amp;hidesearch=0&amp;hidetop=&amp;dfl_s0_hoststatustypes=15&amp;dfl_s0_servicestatustypes=28&amp;dfl_s0_hostprops=10&amp;dfl_s0_serviceprops=10&amp;style=detail&amp;dfl_s0_serviceprop=2&amp;dfl_s0_serviceprop=8&amp;dfl_s0_type=host&amp;dfl_s0_val_pre=&amp;dfl_s0_op=%3D&amp;dfl_s0_value=all&amp;dfl_s0_value_sel=5
Browser:    Version:    2.12-3
Release:    December 20, 2016
Backends:               0 / 3.5.1 / Livestatus 1.2.2p2
                        0 / 3.5.1 / Livestatus 1.2.2p2
                        0 / 3.5.1 / Livestatus 1.2.2p2
                        0 / 3.5.1 / Livestatus 1.2.2p2
                        2 / 4.0.8 / Livestatus 1.2.8p11
                        2 / 3.5.1 / Livestatus 1.2.2p2
                        0 / 3.5.1 / Livestatus 1.2.2p2
                        2 / 3.5.1 / Livestatus 1.2.2p2
                        2 / 3.5.1 / Livestatus 1.2.2p2

uname:      Linux <fqdn-scrubbed> 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64
release:    CentOS release 6.8 (Final)

Stacktrace:
Not a HASH reference at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 2273.

 at /usr/share/thruk/lib/Thruk.pm line 304
	Thruk::_dispatcher('HASH(0x6ca4d60)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 142
	eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 142
	Plack::Util::run_app('CODE(0x21f2800)', 'HASH(0x6ca4d60)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 143
	Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x17e0d48)', 'CODE(0x21f2800)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24`

**Comment by sni** [comment]
Should be fixed now. Thanks
