### ISSUE TITLE
flip-flop detail host to detail service

### ISSUE THREAD

**Issue by rirouxe** [sni/Thruk#677]
Hello,

with thruk 2.12-3

when i display a host with service, it's ok

from this same host, i display host detail, it's ok

from host detail to the same host, i display detail service, my column host and service is disable

![image](https://cloud.githubusercontent.com/assets/19713399/22254591/5255bf14-e255-11e6-8cfa-7fdeb7ed6172.png)

**Comment by rirouxe** [comment]
same problem when i display host detail from service detail, my column "host' is disable

**Comment by sni** [comment]
I am not sure if i understood you correctly. Could you please explain in detail what you did and what you expected.

**Comment by rirouxe** [comment]
i select a host
i see host and his services

i want to see just host detail

i click on :
![image](https://cloud.githubusercontent.com/assets/19713399/22258139/bc0270dc-e260-11e6-84ae-f710a24bc2a3.png)

and my column is "host" is disable
![image](https://cloud.githubusercontent.com/assets/19713399/22258163/d68f901a-e260-11e6-98e8-062b797440fd.png)


Same problem when I do the action in reverse

**Comment by sni** [comment]
Strange, i cannot reproduce that. Does that happen on http://demo.thruk.org as well?

**Comment by rirouxe** [comment]
yes i reproduce
in quick search, i select "Company App"

i forget to say, my default column is modify

![image](https://cloud.githubusercontent.com/assets/19713399/22285475/0f74a27c-e2ec-11e6-9e4f-3ff027cfe191.png)

when my default column is not modify, i don't have this problem

but onhttp://demo.thruk.org, i add "check_period" and "notification_period" i switch to host detail et my host i disable

**Comment by sni** [comment]
> i forget to say, my default column is modify
I guess that was the missing information. I will have a look
