### ISSUE TITLE
Thruk & LMD 'peer_addr' missing in JSON export

### ISSUE THREAD

**Issue by sshmanko** [sni/Thruk#678]
When LMD daemon is enabled there is *dataSource* field in HTML output but no similar field in JSON output:

data field can be restored by adding 'peer_addr' to [Livestatus.pm](https://github.com/sni/Thruk/blob/master/lib/Thruk/Backend/Provider/Livestatus.pm#L160)

however this will cause errors when some backend is unavailable

**Comment by sni** [comment]
You can set the columns for a json export by url parameter, see: https://thruk.org/documentation/json-exports.html

**Comment by sshmanko** [comment]
Setting columns does not have any effect on *Process information* page:

/thruk/cgi-bin/extinfo.cgi?type=0&view_mode=json

**Comment by sni** [comment]
Ok, i assumed you are talking about the status json export. However, should be better now.

**Comment by sshmanko** [comment]
Thanks a lot!
