### ISSUE TITLE
Business Process - Change selection

### ISSUE THREAD

**Issue by dcop7** [sni/Thruk#682]
Hi,

In edit mode in Business Process, I select and edit a node. Everything fine. But, in the same edit mode session, if I select another node to edit, it opens the first node I've selected. It appears that after opening the edit node options, the selection is locked. It also appears a blue delimiter indicating that the node is selected, but it appears for first and second node. If I select another node to edit, this one will also have a blue delimiter, as well as the other two.

Regards,
Diogo

**Comment by sni** [comment]
should be fixed now, thanks
