### ISSUE TITLE
500 when saving Panorama dashboards

### ISSUE THREAD

**Issue by sshmanko** [sni/Thruk#684]
Pressing Save on panorama dashboard (URL: /thruk/cgi-bin/panorama.cgi?task=save_dashboard&nr=tabpan-tab_8)

results in:

`Saving Data failed: /usr/local/thruk/var/users/username encountered object '1', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /usr/local/thruk/share/lib/Thruk/Utils/IO.pm line 206.`

thruk.log:
`2017-02-17_14:25:34.70632 at /usr/local/thruk/share/lib/Thruk.pm line 284
2017-02-17_14:25:34.70633 eval {...} at /usr/local/thruk/share/lib/Thruk.pm line 273
2017-02-17_14:25:34.70634 Thruk::_dispatcher('HASH(0x2b0b8f0)') called at /usr/local/thruk/share/script/thruk.psgi line 0
2017-02-17_14:25:34.70634 eval {...} at /usr/local/thruk/share/script/thruk.psgi line 0
2017-02-17_14:25:34.70634 Trace begun at (eval 50) line 1
2017-02-17_14:25:34.70635 main::__ANON__('encountered object \'1\', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /usr/local/thruk/etc/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 829.^J') called at /usr/local/thruk/etc/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 829
2017-02-17_14:25:34.70635 Thruk::Controller::panorama::_task_save_dashboard('Thruk::Context=HASH(0x29b9018)') called at /usr/local/thruk/etc/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 100
2017-02-17_14:25:34.70635 Thruk::Controller::panorama::index('Thruk::Context=HASH(0x29b9018)') called at /usr/local/thruk/share/lib/Thruk.pm line 284
2017-02-17_14:25:34.70636 eval {...} at /usr/local/thruk/share/lib/Thruk[pid: 9621|app: 0|req: 50/50] 107.20.166.29 (username) {44 vars in 1016 bytes} [Fri Feb 17 06:25:34 2017] GET /thruk/cgi-bin/panorama.cgi?task=save_dashboard&nr=tabpan-tab_8 => generated 7394 bytes in 8 msecs (HTTP/1.1 500) 6 headers in 243 bytes (0 switches on core 0)`

Panorama settings saved correctly to:
/usr/local/thruk/etc/panorama/8.tab

User data is emtpy:
/usr/local/thruk/var/users/username

Perl v5.16.3, on amazon-linux 2016.03

Thruk + LMD and libs compiled from sources, also tried RPM libs - same error

**Comment by sshmanko** [comment]
Adding 
`$json = $json->allow_blessed(1);`
to thruk/share/lib/Thruk/Utils/IO.pm:190 fixed the issue for me, however not sure that it is correct behaviour

**Comment by sshmanko** [comment]
It seems there is a mismatch between system library and thruk bundled one.

During compilation:
`- JSON::XS                                                                ...loaded. (2.34)`

But thruk-libs contains 3.01

after removing perl-JSON-XS.x86_64 package and installing JSON::XS from CPAN the problem was solved

**Comment by sshmanko** [comment]
Had to force JSON::PP in *panorama/lib/Thruk/Controller/panorama.pm*

Otherwise got:

`2017-02-20_13:51:09.41279 main::__ANON__('encountered object \'0\', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /usr/local/thruk/etc/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 2974.^J') called at /usr/local/thruk/etc/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 2974
2017-02-20_13:51:09.41280 Thruk::Controller::panorama::_merge_dashboard_into_hash('HASH(0x7fcf809c87c0)', 'HASH(0x7fcf80894ab0)') called at /usr/local/thruk/etc/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 325`

**Comment by sni** [comment]
there should be no blessable object in the panorama dashboard. If so, thats a bug.

**Comment by sshmanko** [comment]
any way I can dump the object to log to provide debug information?

**Comment by sni** [comment]
There is usually no need to install modules from cpan. I have seen this error which was the result of using JSON::XS in an threaded perl (for example when having multiple backends) on very recent perl releases, but perl 5.16 is not so new...
You could use Data::Dumper before the mentioned error lines above to print the json data.

**Comment by pedrojimenez** [comment]
Hi both,
We are facing a similar problem as reported by @sshmanko ... With migrated 2.08 Panorama dashboards and also with 2.16-2 blank ones

We have a compiled Thruk (v2.16-2) presenting the same errors:
```
Saving Data failed: /usr/local/thruk/var/users/username encountered object '1', but neither
allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method
missing) at /usr/local/thruk/share/lib/Thruk/Utils/IO.pm line 206.
```
We have applied the workaround described by @sshmanko ... and this error has vanished
```
Adding
$json = $json->allow_blessed(1);
to thruk/share/lib/Thruk/Utils/IO.pm:190 fixed the issue for me, however not sure that it is correct solution
```

Now we are getting the second part of the error in **panorama.pm** file (line 2951):
```
main::__ANON__('encountered object \'0\', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /opt/wocu/embedded/etc/thruk/plugins//plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 2951.^J') called at /opt/wocu/embedded/etc/thruk/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 2951
Thruk::Controller::panorama::_merge_dashboard_into_hash('HASH(0x7e6c978)', 'HASH(0x7fe9258)') called at /opt/wocu/embedded/etc/thruk/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 283
Thruk::Controller::panorama::_js('Thruk::Context=HASH(0x7e53408)', 1) called at /opt/wocu/embedded/etc/thruk/plugins/plugins-enabled/panorama/lib/Thruk/Controller/panorama.pm line 246
Thruk::Controller::panorama::index('Thruk::Context=HASH(0x7e53408)') called at /opt/wocu/embedded/share/thruk/lib/Thruk.pm line 297
eval {...} at /opt/wocu/embedded/share/thruk/lib/Thruk.pm line 286
Thruk::_dispatcher('HASH(0x7e970c8)') called at /opt/wocu/embedded/share/thruk/script/thruk.psgi line 0
eval {...} at /opt/wocu/embedded/share/thruk/script/thruk.psgi line 0
Trace begun at (eval 53) line 1
```
@sshmanko , could you describe the full workaround of **setting JSON::PP in panorama/lib/Thruk/Controller/panorama.pm** ?


Regards

**Comment by sshmanko** [comment]
@pedrojimenez sure, here you go:
```
use JSON::PP qw/decode_json encode_json/;
```
Never had any issues since this change.

**Comment by sni** [comment]
This error is related to threads (which will be enabled when having multiple backends) and latest JSON::XS version. Thats why i ship JSON-XS-3.01 with thruk-libs package. If you build Thruk manually yourself, make sure you use the right version of JSON::XS.

**Comment by pedrojimenez** [comment]
Thanks both ! @sshmanko  and @sni
