### ISSUE TITLE
Thruk Plugin output table auto repairs

### ISSUE THREAD

**Issue by sweetkrish** [sni/Thruk#685]
Hi,
Every two days, I see this file 5ca01_plugin_output.TMD created and deleted within 1 hour equal to the size of 5ca01_plugin_output.MYD. (No cron jobs regarding this) Which i think a temporary data file created to repair the original data file. I am not sure why this table needs to be repaired, I don't see any logs regarding this in either thruk.log or mysqld.log. This causes to increase our disk space, so before i increase the disk space, i would like to know if this is a normal process.

29G     5ca01_plugin_output.TMD
29G     5ca01_plugin_output.MYD
5.0G    5ca01_plugin_output.MYI

Specifications:
Running Thruk on Nagios core.
Thruk - thruk-2.00-2.x86_64
Nagios - nagios-3.5.1-1.el6.x86_64
Memory - 15G
Disk Space - 142 G
Mysql - mysql-5.1.73-5.el6_6.x86_64
Engine - MyISAM

**Comment by sni** [comment]
The suggested cronjobs for the logcache contain a repair:
`
thruk -h
...
 - logcacheoptimize            optimize and repair logcache
`
If you don't need that, just remove the cronjob.

**Comment by sweetkrish** [comment]
Thanks Sni,
I do see the logcacheoptimize running in cron,

# Do the logcache optimize daily
30 0 * * * /usr/bin/thruk -a logcacheoptimize > /dev/null 2>&1

I have two more questions: 
Log optimize runs every day but why would it repair only every 2 days ?
I see a table (5ca01_log) for log seperately and why would it repair the 5ca01_plugin_output table ?
