### ISSUE TITLE
Connection error with naemon only when generating reports o trends for time range "last month"

### ISSUE THREAD

**Issue by topinet** [sni/Thruk#686]
I'm experiencing problems when generating SLA reports o viewing trends for any service in the time range "last month".

In /var/log/thruk/thruk.log:
```
not a valid header (no content-length)
got: Couldn't connect to UNIX-socket at /var/cache/naemon/live: Connection refused.
at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 378.
on reports/sla_service.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.
```

Thruk connects to Naemon using a TCP port (xinetd) and there are no connection errors out of these cases.

Last versions of Naemon, Livestatus and Thruk.

**Comment by sni** [comment]
I cannot reproduce that. Are there any errors in the livestatus.log? Or could you increase the log level there?

**Comment by topinet** [comment]
I can't reproduce it now, by this time I was using "last 31 days" when generating reports but today I retried with "last month" and reports are being generated correctly.

Sorry for the inconvenience.
