### ISSUE TITLE
Authorization not compatible with NagBar

### ISSUE THREAD

**Issue by renard** [sni/Thruk#687]
I am using [NagBar](https://sites.google.com/site/nagbarapp/) with some nagios servers. It works fine.

But with thruk I go some a login issue:
* NagBar tries to fetch `/thruk/cgi-bin/status.cgi` (IFAIK `status.cgi` is hard coded) 
* even if I configured `cookie_auth_direct_agents = (curl|wget|nagbar)` I am redirected to `/thruk/cgi-bin/login.cgi`. I guess this is because NagBar does not send `Authorization` header unless it has a response from server asking for it (with the `WWW-Authenticate: Basic realm="Thruk Monitoring"` header)

I could see that `thruk_auth` is doing the job with:
```perl
        if($extra->[1] && $extra->[2] =~ $direct_auth_regex) { # TODO: make configurable
            print STDERR "thruk_auth: script bypass cookie auth for $path" if $verbose;
            my $session = Thruk::Utils::CookieAuth::external_authentication($config, {'Authorization' => $extra->[1]}, undef, $extra->[0]);
...
```
But `$extra->[1]` is empty (or undefined) so it redirects to the login page. 

Is there a way to check if `$extra->[1]` is empty or undef and return headers such as:

```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="Thruk Monitoring"
Content-Type: text/html; charset=iso-8859-1
```

Thanks in advance.

PS:

NagBar UA is `NagBar (unknown version) CFNetwork/760.6.3 Darwin/15.6.0 (x86_64)`

**Comment by renard** [comment]
After some research, code reading and tries, I managed to get the thing work. For those who might be interested:

```diff
--- /tmp/thruk_auth	2017-03-08 01:43:29.380962236 +0100
+++ /usr/share/thruk/thruk_auth	2017-03-08 01:50:21.328565556 +0100
@@ -105,6 +105,13 @@
             }
         }

+        # If no authentication header is found and bypass cookie for special user-agent
+        # Force an auth request
+        if(!$extra->[1] && $extra->[2] =~ $direct_auth_regex) {
+            print STDERR "thruk_auth: script bypass cookie but no auth for $path" if $verbose;
+		return "/no-auth/$path\n";
+        }
+
         # did we get a cookie
         if($cookies eq '' or $cookies !~ $cookie_regex) {
             print STDERR "thruk_auth: no cookie $path" if $verbose;
--- /tmp/thruk_cookie_auth.include	2017-03-08 01:43:40.120951908 +0100
+++ /usr/share/thruk/thruk_cookie_auth.include	2017-03-08 01:49:04.420641016 +0100
@@ -24,6 +24,8 @@
 RewriteRule ^/pass/(.*)$             /$1 [NS,PT,L,E=!REMOTE_USER]
 RewriteRule ^/redirect/(.*)$         /$1 [NS,L,R=302]
 RewriteRule ^/loginok/([^/]+)/(.*)$  /$2 [NS,PT,L,E=REMOTE_USER:$1]
+# Force special agent to auth themselves
+RewriteRule ^/no-auth/(.*)$         /$1 [L]

 # finally exclude everything from basic auth, except the restricted.cgi
 <LocationMatch ^/thruk(?!/cgi-bin/restricted.cgi)>
--- /tmp/000-default.conf	2017-03-08 01:43:52.452940278 +0100
+++ /etc/apache2/sites-enabled/000-default.conf	2017-03-08 01:47:11.552748703 +0100
@@ -29,6 +29,12 @@


     Include /usr/share/thruk/thruk_cookie_auth.include
+    <Location /thruk/cgi-bin/status.cgi>
+        AuthName "Thruk Monitoring"
+        AuthType Basic
+        AuthUserFile /etc/thruk/htpasswd
+        Require valid-user
+    </Location>
 </VirtualHost>

 # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

And put this line in `/etc/thruk/thruk_local.conf`:
```
cookie_auth_direct_agents = (curl|wget|nagbar)
```

And simply restart apache.


In NagBar you need to define a new  feed with:
* type: `Thruk`
* url: http://thruk-server/thruk/cgi-bin/ or https://thruk-server/thruk/cgi-bin/  (please note the tailing slash)
* username: your login
* password: your password

This works nicely with NagBar 1.2.5 (I guess i hasn't be updated for thruk 2+) and might also work for other broken nagios-like desktop clients.


@sni did I missed something or break any functionality or add any security flaw? thanks in advance.


Hope that helps.

S.

**Comment by sni** [comment]
Looks ok. But i guess the used apache syntax only works with apache 2.4, so i cannot put it in the default config examples which supports 2.2 and 2.4.

**Comment by renard** [comment]
@sni it's up to you ;)

I guess this is a very specific usage.
Maybe you can put it in a README or something similar.


Thanks again.
