### ISSUE TITLE
Host/service checks disabled after thruk restart

### ISSUE THREAD

**Issue by kisahm** [sni/Thruk#689]
after a thruk restart the host and service checks are disabled.
this there a setting to enable host tand service checks during the thruk start.

**Comment by sni** [comment]
Thruk does only display the current state of your monitoring core. It does not change anything unless you send some commands and it does not send any commands during start/stop of Thruk itself.

**Comment by kisahm** [comment]
oh ok. it sounds like a backend problem...

**Comment by sni** [comment]
i'd say so, yes
