### ISSUE TITLE
Logcache Problem

### ISSUE THREAD

**Issue by gitmopp** [sni/Thruk#694]
Hello,
I' m using MariaDB with Nagios 4.2.4 and mk-livestatus-1.2.6p12.
The command ```thruk -a logcacheimport --local``` fails with
```DBD::mysql::db do failed: Data truncated for column 'type' at row 1 at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1760.```

The import tries to run this SQL statement:
```
INSERT INTO `63e3a_log` (time,class,type,state,state_type,contact_id,host_id,service_id,plugin_output,message) VALUES(1424880331,0,'ndomod registered for acknowledgement data\'',0,'NULL',NULL,NULL,NULL,1,37);
```
The command fails because ```type``` allows:
```enum('CURRENT SERVICE STATE','CURRENT HOST STATE','SERVICE NOTIFICATION','HOST NOTIFICATION','SERVICE ALERT','HOST ALERT','SERVICE EVENT HANDLER','HOST EVENT HANDLER','EXTERNAL COMMAND','PASSIVE SERVICE CHECK','PASSIVE HOST CHECK','SERVICE FLAPPING ALERT','HOST FLAPPING ALERT','SERVICE DOWNTIME ALERT','HOST DOWNTIME ALERT','LOG ROTATION','INITIAL HOST STATE','INITIAL SERVICE STATE','TIMEPERIOD TRANSITION')```

The import runs the Livestatus query:
```
GET log
Columns: class time type state host_name service_description plugin_output message state_type contact_name
Filter: time >= 1424162378
Filter: time < 1424248778
And: 2
OutputFormat: json
ResponseHeader: fixed16
```

It returns data like:
```
[...]
[6,1424235600,"CURRENT SERVICE STATE",0,"localhost","Current Load","OK - load average: 1.16, 0.78, 0.68","[1424235600] CURRENT SERVICE STATE: localhost;Current Load;OK;HARD;1;OK - load average: 1.16, 0.78, 0.68","HARD",""],
[...]
[0,1424162378,"ndomod registered for acknowledgement data'",0,"","","","[1424162378] ndomod registered for acknowledgement data'","",""],
```

Is it wrong Livestatus returns non status data? If yes then solutions would be to create a ```Filter: type``` for it.
Let me know if you expect this data in the logcache DB. From my understanding it should be filtered out.

**Comment by gitmopp** [comment]
I tried the same configuration with an older MySQL-5.1.73 and most likely a slightly different configuration.
It works for this installation and I can see the log entries which do not match the criteria of column ```type```. 
The ```type``` is empty (not NULL) and the message is stored in the _plugin_output table.
It seems like MariaDB does not accepts insert if the type does not match. Might be a security setting.
So all data from  ```GET log``` have to be in the thruk database.

**Comment by gitmopp** [comment]
The following should fix the problem, will test it tomorrow.
Line 1716 in lib/Thruk/Backend/Provider/Mysql.pm
```
        # Set type to NULL to prevent SQL insert errors if type is not a special type.
        $type = 'NULL' if !defined $Thruk::Backend::Provider::Mysql::db_types->{$type};
```

**Comment by sni** [comment]
Thanks for digging into that. Could you create a pull request for the the fix?

**Comment by sni** [comment]
Should be better now.

**Comment by kajla** [comment]
I have the same problem. :(

```
[Tue Dec 19 11:12:03 2017][INFO] ERROR SQL: INSERT INTO `7215e_log` (time,class,type,state,state_type,contact_id,host_id,service_id,plugin_output,message) VALUES(1513677973,0,'LOG ROTATION',NULL,'NULL',NULL,NULL,NULL,1,35)
DBD::mysql::db do failed: Data truncated for column 'state_type' at row 1 at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 2028, <$fh> line 4606.
[Tue Dec 19 11:12:03 2017][INFO] ERROR DETAIL: DBD::mysql::db do failed: Data truncated for column 'state_type' at row 1 at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 2028, <$fh> line 4606.
[Tue Dec 19 11:12:03 2017][INFO] ERROR SQL: INSERT INTO `7215e_log` (time,class,type,state,state_type,contact_id,host_id,service_id,plugin_output,message) VALUES(1513677973,0,NULL,NULL,'NULL',NULL,NULL,NULL,1,34)
```

Thruk Version 2.16~2
Icinga2 version: r2.8.0-1

Thank you in advance!

**Comment by sni** [comment]
This will be fixed with the next release, meanwhile you could try the daily builds if you want.

**Comment by kajla** [comment]
When will the next release appear?
Thank you in advance!

**Comment by sni** [comment]
Soon, if everything works out, probably this or next week.
