### ISSUE TITLE
core_scheduling schedules checks that are not in check period

### ISSUE THREAD

**Issue by kalvarez56** [sni/Thruk#696]
I have about 1300 checks that have different timeperiods for active checks what I notice if I put 
thruk -a fix_scheduling in my crontab that checks that should not be active get rescheduled outside of their check_periods.  I tried sg: and hg: but that doesn't help as they all have different check_periods.

Is there a way to ignore checks that are not in current check_period from being rescheduled.

BTW I pulled the new Thruk2 skin and manually added it to 2.12-3, looks great!

Keep up the great work

Thanks,

**Comment by sni** [comment]
You can use regular filter in the page itself, but they are not available from the command line.

**Comment by sni** [comment]
Should be better next time.
