### ISSUE TITLE
Error in report from url 	

### ISSUE THREAD

**Issue by krysjose** [sni/Thruk#697]
When I try to execute report from url I get the following error

	show long error output move /var/lib/thruk/reports/4.dat.pdf to /var/lib/thruk/reports/4.dat failed: No such file or directory at /etc/thruk/plugins//plugins-enabled/reports2/lib/Thruk/Utils/Reports/Render.pm line 356.
on reports/report_from_url.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.

S.O. Ubuntu xenial 
Pacakges:
ii  libthruk                           2.10-1                          amd64        Thruk perl libraries
ii  thruk                              2.12-3                          amd64        Monitoring Webinterface for Nagios/Icinga and Shinken
ii  thruk-base                         2.12-3                          amd64        Monitoring Webinterface for Nagios/Icinga and Shinken
ii  thruk-plugin-reporting             2.12-3                          amd64        This package contains the reporting addon for thruk useful for sla

**Comment by sni** [comment]
Which url did you try?

**Comment by krysjose** [comment]
The url is:  thruk/cgi-bin/status.cgi?host=all&type=detail&hostprops=10&serviceprops=42&servicestatustypes=28

**Comment by sni** [comment]
Cannot reproduce that at the moment, please try with the next release which is ready in a few days or with the nightly builds.
