### ISSUE TITLE
Not able to use the web based configurator after upgrade to 2.14

### ISSUE THREAD

**Issue by randelhofs** [sni/Thruk#700]
Hi

After upgrading to Thruk version 2.14 I am no longer able to use the web based configuration tool for my objects.
When clicking the **Configuration** menu item I only get the option to view config data.

![image](https://cloud.githubusercontent.com/assets/1880500/24503563/e2a245bc-1552-11e7-84bf-93b18d8bd000.png)

**Comment by sni** [comment]
the web based configuration is a separate plugin available via the "config tool" link which i cannot see in your screenshot, so it seems like you did not enable this plugin.
