### ISSUE TITLE
Refresh business process not function automatic - Panorama - thruk 2.14

### ISSUE THREAD

**Issue by gpuertac** [sni/Thruk#702]
good day,

Currently I notice a problem with the update of a dashboard on panorama, a business process is not updated in the interface according to the defined period, nor is it updated for the period defined for the general dashboard.

This dashboard has 9 items, and all are updated well, minus the business process item.

The update is done manually and works.

Can anyone tell me what it may be missing for the BP update to work properly on this dashboard?

For the presentation of the dashboard the chrome explorer is used.

Thank you

**Comment by sni** [comment]
Sounds like you disabled the refresh rate in the BP widget itself?

**Comment by gpuertac** [comment]
![image](https://cloud.githubusercontent.com/assets/26796202/24659780/5b340204-1913-11e7-8d86-5c14ac40ca59.png) refresh 14 seg in widget
![image](https://cloud.githubusercontent.com/assets/26796202/24659874/9bf0af40-1913-11e7-81d2-33e4271d017b.png) refresh 30 seg in dashboard

**Comment by gpuertac** [comment]
![image](https://cloud.githubusercontent.com/assets/26796202/24660114/4d7a7516-1914-11e7-901b-96a4439845de.png)

**Comment by sni** [comment]
Thanks, should be fixed now.
