### ISSUE TITLE
VERY long (multiline) output of plugin renders service detail page (and/or multiline popup) unusable

### ISSUE THREAD

**Issue by wAmpIre** [sni/Thruk#704]
here: `.../check_ssl_cert [...] --long-output all`

Both popup (on service overview) and detail page become VERY wide and unusable.

I don't have an idea for a good fix :-/

**Comment by gpuertac** [comment]
Que es lo que requieres validar con este pluging? o necesariamente requieres la salida del comando que indicas en la consola? ... es para poder saber si tienes otras opciones.
