### ISSUE TITLE
Selection host or service in error not visible

### ISSUE THREAD

**Issue by rirouxe** [sni/Thruk#707]
Hello,

This error work on thruk demo

on thruk 2.14.1

When I click "host", I have 2 host selected but only the host in the OK state appears selected

It also happens on services in warning / critical / unknown

![image](https://cloud.githubusercontent.com/assets/19713399/25391645/fc583898-29d6-11e7-984a-3b8569f3112e.png)

when the option "status_color_background" = 0 it's work

**Comment by rirouxe** [comment]
hello

This error is always on thruk demo

![image](https://user-images.githubusercontent.com/19713399/26836748-f3100b8c-4adb-11e7-9562-1ea550cf278a.png)

When I click "host", I have 11 host selected but only the host in the OK state appears selected (in yellow)

thanks

**Comment by sni** [comment]
Should be fixed now, thanks.
