### ISSUE TITLE
internal server error when adding a third backend

### ISSUE THREAD

**Issue by michelbernier** [sni/Thruk#711]
Hi,
i have an internal server error when i add a third backend to thruk, and this trace from apache error.log:
[Fri May 05 14:35:18 2017] [warn] [client 172.25.0.11] mod_fcgid: stderr: hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at /opt/nagios/thruk/share/lib/Thruk/Action/AddDefaults.pm line 157., referer: http://172.31.230.40/thruk/startup.html?wait

Everything is ok with only 2 backends. Any idea? Thanks

**Comment by sni** [comment]
Which version is that? Please always update to the latest release before reporting issues.

**Comment by michelbernier** [comment]
i had this behavior first, with version 2.12-3. So, i did update it to version 2.14 with finally, the same issue.
I did suspect the JSON::XS module perl, but nobody else seems having met this problem before. I have no explaination.
I have tried to specify allow_nonref method on json object of AddDefaults.pm and Filter.pm before json encoding, but no result at least.

**Comment by sni** [comment]
Ah, that is a know issue in recent JSON::XS versions when using perl threads (which is the case when having more than 2 backends). There are a few possible workarounds:

 - set `connection_pool_size` to 1 which disables threads
 - install the `Thruk::Utils::XS` module from https://github.com/sni/perl-Thruk-Utils-XS which implements backend handling in C and removes the perl threads therfor
 - use LMD: https://thruk.org/documentation/lmd.html
