### ISSUE TITLE
Availability Report gives "Internal Server Error"

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#718]
When trying to create a Availability Report I only get a "Internal Server Error" back.

In the apache-error-log I see the following (client IP redacted):
[Tue May 30 15:20:16.179823 2017] [fcgid:warn] [pid 32456] [client ###.###.###.###:43150] mod_fcgid: stderr: undef error - Not an ARRAY reference at /usr/share/thruk/lib/Thruk/Utils/Status.pm line 1834., referer: https://nagios/thruk/cgi-bin/avail.cgi?get_date_parts=&hostgroup=Monitoring
[Tue May 30 15:20:16.179863 2017] [fcgid:warn] [pid 32456] [client ###.###.###.###:43150] mod_fcgid: stderr:  on avail_report_hostgroup.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76., referer: https://nagios/thruk/cgi-bin/avail.cgi?get_date_parts=&hostgroup=Monitoring
The thruk.log is empty.

Thruk 2.14-2 (logcache is enabled).
mk-livestatus 1.2.8p18

D/\N

**Comment by dan-m-joh** [comment]
It is not only for the Availability Report that I see the error.
Trying Trends also give the same error.

D/\N

**Comment by sni** [comment]
Should be better now, thanks for the report.

**Comment by dan-m-joh** [comment]
Great, now it looks OK.
Thanks!!!

D/\N
