### ISSUE TITLE
Cookie based authentication not possible with HTTPS

### ISSUE THREAD

**Issue by druchoo** [sni/Thruk#719]
Hi @sni,

I'm still experiencing the Issue described in #657 w/ v2.14 EL6 packages. Can you provide any more information on how to troubleshoot this issue?

**Comment by sni** [comment]
Check the apache config. If you use virtualhosts, which is quite likely when using https together with http, you probably have to include the cookie auth apache config (thruk_cookie_auth.include) in your https virtual host. Virtual hosts do not inherit the rewrite rules from the main apache config.

**Comment by druchoo** [comment]
@sni,

I owe you a beer sir! You clearly have this [documented](http://thruk.org/documentation/faq.html#how-can-i-enable-form-based-authentication) in at least two places but I wasn't aware / didn't think about virtual hosts inheritance.

> Get thruk_cookie_auth.example and put everything except the RewriteLock into the **_virtualhost of your choice_**.

```
$ head -n2 /usr/share/thruk/thruk_cookie_auth.include
# extend default virtual host. put/include these rewrite rules in https or
# any other virtual host if you want to enable cookie authentication
```

Really appreciate your response. Thanks again!

**Comment by sni** [comment]
Glad to hear that worked.
