### ISSUE TITLE
Empty geomap when loaded as first tab

### ISSUE THREAD

**Issue by mariano-fiorentino** [sni/Thruk#721]
Hi,
we found an issue when the geomap is the first tab. The issue is that the panel didn't loads objects (minemap, arrows,etc...), the objects are loaded after a click on another tab and a click  on the first  tab where we have the geomap.
The thruk version that we have is 1.88-4, i saw that newer version of thruk didn't has the issue, but by now i can't upgrade.
There is a way to fix that issue with this older version of thruk? 

Best regards

**Comment by mariano-fiorentino** [comment]
I close the issue. Found the solution here:
https://github.com/sni/Thruk/issues/494

**Comment by sni** [comment]
Thanks for the heads up. You still should consider upgrading. The 1.x is quite old already.
