### ISSUE TITLE
Re-schedule next check of this service (Now) not working

### ISSUE THREAD

**Issue by rirouxe** [sni/Thruk#722]
Hello

on thruk 2.14-2 and red hat 7.3

the command re-schedule next check not working

i submit a critical alert and when i re-schedule, my alert stay critical

I have to wait for the next planning so that it goes back ok

icinga log's :
![image](https://user-images.githubusercontent.com/19713399/27192255-ec159312-51fa-11e7-8793-d05bd2fcf1e2.png)

PS : demo thruk is broken

**Comment by sni** [comment]
Thanks, i fixed demo.thruk.org :-)

Well, Thruk just submits the command and it looks like that worked. Everything else is up to the core (Nagios/Naemon/Icinga).
You could check if there is a command for this service defined because its not required for passive checks.

**Comment by rirouxe** [comment]
Thruk use script to send a "Re-schedule next check of this service/host"?

thruk send the order
![image](https://user-images.githubusercontent.com/19713399/27219359-c07637c0-5281-11e7-97c3-fac62af85427.png)

icinga receives the order
![image](https://user-images.githubusercontent.com/19713399/27219338-a4dcfdd2-5281-11e7-8b33-94d889ca04f6.png)
but no result!

"Re-schedule next check of this service/host" work on thruk 2.08 and 2.14 but not in my thruk 2.14-2

**Comment by sni** [comment]
If icinga receives the command but doesn't do the right thing, its an icinga issue.

**Comment by rirouxe** [comment]
ok thanks
