### ISSUE TITLE
Thruk using LMD without managing LMD process and still seeing backends

### ISSUE THREAD

**Issue by hkowallik** [sni/Thruk#725]
Greetings!

Is it possible to configure Thruk to use LMD but not manage the LMD process and still be aware of the backends configured in LMD?
When I set up LMD with multiple backends and then configure Thruk to use LMD as its backend I don't get the list of real backends in Thruk.
Why do I want to do that?
I want to send REST calls to LMD directly (TCP or HTTP endpoint) and in that case it seems strange that the UI manages the process I need for that.

**Comment by sni** [comment]
Thats not possible. If Thruk needs to use LMD, it has to manage its configuration by itself because LMD only uses a subset of Thruks backend configuration. So its not possible the other way round. However it would be possible to use LMD standalone without Thruk.
