### ISSUE TITLE
Where to configure access permissions for "Schedule service downtime"

### ISSUE THREAD

**Issue by jsteel44** [sni/Thruk#726]
When I choose to "Schedule service downtime" (or host) I get "you are not authorized for this command" URI is /thruk/#cgi-bin/cmd.cgi?cmd_typ=56 - where would I configure access permissions for this?
I haven't touched can_submit_commands or command_disabled in my config but believe the default should be fine?

I can schedule recurring downtimes OK, just not one-off downtimes.

I use GSSAPI authentication with Apache if that makes any difference.

Thanks.

**Comment by sni** [comment]
See http://www.naemon.org/documentation/usersguide/cgiauth.html for a start.
