### ISSUE TITLE
Plugin Shinken Features

### ISSUE THREAD

**Issue by bouvets** [sni/Thruk#727]
Hi,

I just installed Thruk 2.14 with shinken 2.4.3 and the plugin Shinken Features failed with the following message:

_This plugin is not available or enabled
If you believe this is an error, check the documentation for this plugin_

With thruk 2.08 the plugin is available, is this problem known ?

**Comment by sni** [comment]
Have you checked if the plugin is enabled?

**Comment by bouvets** [comment]
Hi Sven,

plugin seems to be enable:

[shinken@vlxsupbdd ~]$ ls -l /etc/thruk/plugins/plugins-enabled/shinken_features
lrwxrwxrwx 1 apache apache 37 27 juin 23:33 /etc/thruk/plugins/plugins-enabled/shinken_features -> ../plugins-available/shinken_features

On demo.thruk.org, there is the same problem.

**Comment by sni** [comment]
You need to set `enable_shinken_features` in your thruk_local.conf.
