### ISSUE TITLE
[testing] [stretch] Dependency issue in daily builds for stretch

### ISSUE THREAD

**Issue by snarf6** [sni/Thruk#728]
Hi, 

> This bug concern the daily build from the testing channel. 

today, the daily build for Debian Stretch presented a dependency with package `libfontconfig1 (>= 2.12)`. 

```bash
The following packages have unmet dependencies:
 thruk-plugin-reporting : Depends: libfontconfig1 (>= 2.12) but 2.11.0-6.7+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
``` 

Latest update for Strech is `2.11.0-6.7+b1` 

```bash
# apt-cache policy libfontconfig1
libfontconfig1:
  Installed: 2.11.0-6.7+b1
  Candidate: 2.11.0-6.7+b1
  Version table:
 *** 2.11.0-6.7+b1 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

stretch-backport don't seems to be online yet.

**Comment by snarf6** [comment]
mmm this issue may be useless, Travis saw it : https://download.thruk.org/nightly_builds/2017-07-04/ 

;)

**Comment by sni** [comment]
I haven't updated the build machines since the debian 9 release. Will as soon as i find some time.

**Comment by sni** [comment]
should be fine again tomorrow.
