### ISSUE TITLE
Syntax error on global_user_data with thruk-20170704

### ISSUE THREAD

**Issue by marcomusso** [sni/Thruk#730]
When running thruk CLI I get:

`syntax error at /var/lib/thruk/global_user_data line 2, near ""bookmarks" :"`

on a previously (thruk-20170630) valid json (redacted):

```
{
   "bookmarks" : {
      "Bookmarks" : [
         ........
      ],
      "Dashboards" : [
         ........
      ]
   }
}

```

"Aggressive" linter (space before colon) or a symptom for something else?

NOTE: added missing comma before Dashboards, that was in the original file

**Comment by sni** [comment]
Isn't there a comma missing after the Bookmarks section?

**Comment by marcomusso** [comment]
Good catch but probably my mistake in redacting, the original file has it.

**Comment by marcomusso** [comment]
Copied a working copy of global_user_data from production (2.14-1), still the same. I'll try with last night build as well.

**Comment by marcomusso** [comment]
To provide more info: I get that error **twice** when running a command like this (`{}` are placeholders):

`"thruk --local -A thrukadmin -a url=avail.cgi?host={}&service={}&timeperiod=lastmonth&csvoutput=1'`

**Comment by sni** [comment]
I cannot reproduce that, can you check what the syntax error is in your global_user_data file?

**Comment by marcomusso** [comment]
Mmmm that's why I suspected a trivial error, I cannot see any errors in that file, I even used a json validation site to check it... line 2 is also really at the beginning:
```
$ head -4 /var/lib/thruk/global_user_data
{
   "bookmarks" : {
      "Bookmarks" : [
         [
```
loading it from python works fine as well:
```
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> with open('/var/lib/thruk/global_user_data') as json_data:
...     d = json.load(json_data)
...     print (d)
... 
{u'bookmarks': {u'Bookmarks': [[u'Mapshare Production', u'/thruk/cgi-bin/status.cgi? [.........................]
```
This is with 2.15-20170704... Updating to 2.15-20170705

```
[...]
Running transaction
  Updating   : thruk-base-2.15-20170705.x86_64                                                                                                
Redirecting to /bin/systemctl condrestart  httpd.service
syntax error at /var/lib/thruk/global_user_data line 2, near ""bookmarks" :"
syntax error at /var/lib/thruk/downtimes/1.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/10.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/2.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/3.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/4.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/5.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/6.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/7.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/8.tsk line 1, at EOF
syntax error at /var/lib/thruk/downtimes/9.tsk line 1, at EOF
syntax error at /var/lib/thruk/reports/1.rpt line 2, near ""backends" :"
Cannot lock /var/lib/thruk/reports/1.rpt: No locks available at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 204.
```
could be that /var/lib/thruk is on a nfs share (which is weird because it's working fine for everything else)?
Anyway, low priority, I'll keep an eye on this, I was hoping that could be useful info for you on a testing version.

**Comment by sni** [comment]
At least NFS is known to have problems with file locks.

**Comment by sni** [comment]
Well, the error message is misleading here. The syntax error comes from perl because loading the file as json fails due to the nfs locking. Thruk then falls back to load the file as Data::Dumper format for compatibility reasons (till Jan 2018).
So the real problem is the nfs locking issue. The json is probaly fine.

**Comment by marcomusso** [comment]
Yep, that "no locks available" is more informative indeed.

**Comment by sni** [comment]
Just pushed a small change which should display both errors.

**Comment by marcomusso** [comment]
Always good, thanks.
