### ISSUE TITLE
"internal server error" after disabling Mobile Thruk

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#731]
After disabling the Mobile Thruk plugin and accessing the Thruk site via mobile device I get the "internal server error" mentioned.
Apache says:
[Thu Jun 29 15:04:12.639434 2017] [fcgid:warn] [pid 18192] [client 79.195.70.126:41832] mod_fcgid: stderr: file error - mobile_choose.tt: not found on mobile_choose.tt at /omd/sites/SITE/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76., referer: https://IP/SITE/thruk/cgi-bin/login.cgi?SITE/omd/

**Comment by sni** [comment]
Thanks, should be fixed in the next release.
