### ISSUE TITLE
ERROR: The request contains an invalid header

### ISSUE THREAD

**Issue by krishnabagal** [sni/Thruk#733]
Hello,

I'm using thruk 2.12-2 with Icinga Classic 1.11.5 as multiple backend.

Its showing backend is down and not able to view all hosts from same backend. refer below error logs for reference. 
`[ERROR][Thruk] No Backend available
[ERROR][Thruk] on page: http://SERVERFQDN/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&_=1499420506136
[ERROR][Thruk] BACKEND-NAME: ERROR: The request contains an invalid header. .  (BACKEND-IP:PORT)
[ERROR][Thruk] BACKEND-NAME: ERROR: The request contains an invalid header. . (BACKEND-IP:PORT)
[ERROR][Thruk] Error in: /thruk/cgi-bin/status.cgi
[ERROR][Thruk] undefined result at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1233.
 at /usr/lib/thruk/perl5/Plack/Util.pm line 142.
	eval {...} called at /usr/lib/thruk/perl5/Plack/Util.pm line 142
	Plack::Util::run_app('CODE(0x422f1b0)', 'HASH(0x6026768)') called at /usr/lib/thruk/perl5/Plack/Handler/FCGI.pm line 143
	Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x2029e98)', 'CODE(0x422f1b0)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24`

Thanks in advance.

-
B. Krishna.

**Comment by sni** [comment]
Updating Livestatus should fix this issue.
