### ISSUE TITLE
shinken_status.cgi

### ISSUE THREAD

**Issue by bouvets** [sni/Thruk#736]
Hi,

After enabled shinken_features in thruk_local.conf, i've configured the following bp_rule_shinken_app:

bp_rule!(localhost,Shk2-arbiter & localhost,Shk2-broker & localhost,Shk2-poller & localhost,Shk2-reactionner & localhost,Shk2-scheduler & localhost,Disks & localhost,check_http)

If per example service localhost,Disks  is in critical state and i try to find "impact for this problem", shinken_status.cgi is empty and if on bp_rule_shinken_app i try to find "Root problem" it's the same thing . 

Is there anything misconfigured ?

**Comment by sni** [comment]
Thruk just uses livestatus queries to fetch the data. You might want to ask in the shinken forum for support since this is likely to be a shinken problem and there is nothing Thruk can do about it.
