### ISSUE TITLE
Bad redirect

### ISSUE THREAD

**Issue by aanriot** [sni/Thruk#744]
@sni ,

As seen on IRC, it seems that the demo link on [dashboard.html](https://www.thruk.org/documentation/dashboard.html) triggers a bad redirect, which leads to https://demo.thruk.orgthruk/cgi-bin/panorama.cgi (missing "/"), but only when the user is not already connected to Thruk.

I'm using Firefox 54.0 but it seems that it also happens with Safari.

Thanks.

**Comment by sni** [comment]
Thanks, should be better now. You might have to clear the cache.

**Comment by aanriot** [comment]
Great, thanks @sni.
