### ISSUE TITLE
"i/o timeout" in lmd.log when generating reports

### ISSUE THREAD

**Issue by topinet** [sni/Thruk#746]
I've configured a report for a ServiceGroup (last 12 months, break by month) with only one Service. This reports crashes on every execution with the message:
```
undef error - The request contains an invalid header. at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 378.
 on reports/sla_service.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.
```

Thruk/lmd and Naemon/livestatus are running on different machines, using xinetd.

**lmd.log** shows this error:
```
[2017-08-02 13:20:59][Warn][response.go:370] client error: read tcp THRUK_IP:42158->NAEMON_IP:6557: i/o timeout
```

**livestatus.log** shows these 2 lines associated:
```
2017-08-02 13:20:58 Maximum response size of 314572800 bytes exceeded!
2017-08-02 13:21:58 Maximum response size of 314572800 bytes exceeded!
```

I've been playing with different values for max_response_size (using 300M seems to be not enough) without success.

I have 6 other similar reports and run fine (sometimes failing but if I retry they run fine)

**Comment by dan-m-joh** [comment]
Are you using  Thruk's log-cache functionality?
If not, this could be wort a try.
If you are not using log-cache, then Thruk has to read every archived log (through livestatus), and this could take some time (timeout) when asking for data for the last 12 months.

-- 
D/\N

**Comment by topinet** [comment]
The point is why other similar reports doesn't fail the same way?
All my reports read log for the last 12 months.

**Comment by topinet** [comment]
While playing with different values of "max_response_size", I realized that when "fetching logs" phase lasts for more than 30 seconds, appears the "i/o timeout" message in lmd.log, so i've increased the lmd "NetTimeout" parameter and reports now are being generated without problems.

Maybe the error message could point that a timeout accessing livestatus data has caused the report to fail instead of the "invalid header" message

**Comment by topinet** [comment]
After increasing NetTimeout to 180 and avoiding to generate more than one report per minute, all my reports are generated successfully.
