### ISSUE TITLE
statusmap filter using down tag is not working

### ISSUE THREAD

**Issue by hugleo** [sni/Thruk#749]
Just works if I filter by up status. If I filter by down status show no hosts.
![status-map](https://user-images.githubusercontent.com/4573505/29777116-4075062a-8be1-11e7-8c63-c453ff348db9.png)

**Comment by sni** [comment]
And there are hosts which are not ok?

**Comment by hugleo** [comment]
Yes.

If I filter by up I got just ok hosts (green icons).
If I filter by ok/down together I got all hosts (red and green icons).
If I filter just by down I got nothing.

**Comment by hugleo** [comment]
I found out. I have parent relationships hosts. If the parent is up then status map doesn't show the down host.
I've created a host without a parent and in this case the down host are showed normally.

**Comment by sni** [comment]
I guess it just isn't supported right now. I mean, what do you expect if you group by partents but then leave out hosts in the middle?

**Comment by hugleo** [comment]
I think if the parent of the host is not down then follow deep in the tree and find the next down parent and make the one the new parent of the host. But I find out that Tactical Overview or Mine Map is a very nice way to show down hosts.
