### ISSUE TITLE
Timeout during object cloning

### ISSUE THREAD

**Issue by jframeau** [sni/Thruk#750]
Stacktrace:

[Tue Aug 29 10:00:44.385769 2017] [fcgid:warn] [pid 96537] [client 172.18.241.162:48742] mod_fcgid: read data timeout in 120 seconds, referer: https://monitoring/vision/thruk/cgi-bin/conf.cgi
[Tue Aug 29 10:00:44.385861 2017] [core:error] [pid 96537] [client 172.18.241.162:48742] End of script output before headers: fcgid_env.sh, referer: https://monitoring/vision/thruk/cgi-bin/conf.cgi
Traceback (most recent call last):
  File "/omd/versions/2.40-labs-edition/lib/python/mod_python/importer.py", line 1934, in ReportError
    req.write(text)
IOError: Write failed, client closed connection.
[Tue Aug 29 10:00:44.569201 2017] [:error] [pid 96537] [client 172.18.241.162:48742] python_handler: Dispatch() returned non-integer., referer: https://monitoring/vision/thruk/cgi-bin/conf.cgi
ERROR: got signal TERM while handling request, possible timeout in https://monitoring/vision/thruk/cgi-bin/conf.cgi
 at /omd/sites/vision/share/thruk/lib/Thruk.pm line 528.
        Thruk::__ANON__('TERM') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 797
        eval {...} called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 797
        Monitoring::Config::Object::Parent::_make_id('Monitoring::Config::Object::Host=HASH(0x3570a98)', 23514024) called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 706
        Monitoring::Config::Object::Parent::set_uniq_id('Monitoring::Config::Object::Host=HASH(0x3570a98)', 'HASH(0x55898f0)') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config.pm line 1912
        Monitoring::Config::_update_obj_in_index('Monitoring::Config=HASH(0x4033150)', 'HASH(0x55898f0)', 'Monitoring::Config::Object::Host=HASH(0x3570a98)') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config.pm line 1859
        Monitoring::Config::_rebuild_index('Monitoring::Config=HASH(0x4033150)') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config.pm line 934
        Monitoring::Config::update_object('Monitoring::Config=HASH(0x4033150)', 'Monitoring::Config::Object::Host=HASH(0x3570a98)', 'HASH(0x5593c18)', '') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Thruk/Controller/conf.pm line 1932
        Thruk::Controller::conf::_object_save('Thruk::Context=HASH(0x5819ed8)', 'Monitoring::Config::Object::Host=HASH(0x3570a98)') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Thruk/Controller/conf.pm line 979
        Thruk::Controller::conf::_process_objects_page('Thruk::Context=HASH(0x5819ed8)') called at /omd/sites/vision/etc/thruk/plugins-enabled/conf/lib/Thruk/Controller/conf.pm line 138
        Thruk::Controller::conf::index('Thruk::Context=HASH(0x5819ed8)') called at /omd/sites/vision/share/thruk/lib/Thruk.pm line 289
        eval {...} called at /omd/sites/vision/share/thruk/lib/Thruk.pm line 278
        Thruk::_dispatcher('HASH(0x55b9100)') called at /omd/sites/vision/lib/perl5/lib/perl5/Plack/Util.pm line 142
        eval {...} called at /omd/sites/vision/lib/perl5/lib/perl5/Plack/Util.pm line 142
        Plack::Util::run_app('CODE(0x24e17e8)', 'HASH(0x55b9100)') called at /omd/sites/vision/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 143
        Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x19dac90)', 'CODE(0x24e17e8)') called at /omd/sites/vision/share/thruk/script/thruk_fastcgi.pl line 27

**OMD 2.40 / CentOS 7**

**Comment by sni** [comment]
Did this happen just once or is it reproducable?

**Comment by jframeau** [comment]
Can't reproduce it.
I close the issue.

**Comment by GilbyDettori** [comment]
Hey,

I've just reproduced this on Debian Jessie.
It seems as though it's hanging when I get to 31 hosts.

If I remove one host, I can add another host, but then same issues happens when I try for number 32.

This is causing me much grief, and I've no idea how to fix it! :(

thanks!
D.

**Comment by sni** [comment]
Should be fixed with: https://github.com/sni/Thruk/commit/c9ada71f343e1973983a332d16c5ba77b156f153
