### ISSUE TITLE
Reporting Error

### ISSUE THREAD

**Issue by mjs2012** [sni/Thruk#751]
Hello everybody,

I have updated my Thruk envirnment to Thruk version "Thruk Version 2.16~2" via consol labs reposetory. But now in the actual version I get the following error by using the logcacheupdate command:

```
# /usr/bin/thruk -a logcacheupdate -b ICINGA2 /var/log/icinga2/compat/icinga*.log
running update for site ICINGA2
[14:43:00,505][INFO][Thruk] logcache update failed: Can't use string ("1") as an ARRAY ref while "strict refs" in use at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1109.
ERROR: Can't use string ("1") as an ARRAY ref while "strict refs" in use at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1109.

ERROR - imported 0 log items from 1 site with 1 errors in 0.06s (0/s)
```

In the old version 2.14 this command and feature works fine.
Ist there any change by the command in the new version?
How can I fix my issue to run the command via cron and get no error?

Thanks and kind regards
Matthias

**Comment by sni** [comment]
Thanks, should be fixed now.

**Comment by yoshi314** [comment]
I just noticed it today. I assume there was no patched release yet, so i did it by hand.

Speaking of which, is there any nagios check to verify that thruk logcache is up to date?

**Comment by kajla** [comment]
Thanks, I did it by hand. We need to wait next stable version.
