### ISSUE TITLE
Backend with ipv6

### ISSUE THREAD

**Issue by fufroma** [sni/Thruk#753]
Hi,

I tried having a IPv6 backend.

I tried the following configuration: 
* `peer    = [2a03:0:0:6::3]:6558`
* `peer    = 2a03:0:0:6::3:6558`
* `peer    = myserver.ipv6:6558` _with the ipv6 fixed in /etc/hosts_

No success.

Are ipv6 backend possible ? If so, could you add an example in the example config file?

**Comment by sni** [comment]
I never tried, but at least the 3rd variant should just work i guess. What error do you get?

**Comment by fufroma** [comment]
` K-cendre: ERROR: failed to connect - Invalid argument. (myserver:6558)`

I saw `IO::Socket::INET` in `./lib/Monitoring/Livestatus/INET.pm` but no mention of anything related to IPv6.

**Comment by fufroma** [comment]
@snii would you like me to do some more test?

**Comment by sni** [comment]
No, i just don't have time to look into it right now.

**Comment by sni** [comment]
Could you try the mentioned patch?
