### ISSUE TITLE
Error in Availability.pm in latest nightly build (09/09/2017)

### ISSUE THREAD

**Issue by noret** [sni/Thruk#755]
Hi!

While using 'trends' in connection with icinga2 I'm getting sometimes this error:
`Use of uninitialized value in numeric eq (==) at /usr/share/thruk/lib/Monitoring/Availability.pm line 958.
Use of uninitialized value in numeric eq (==) at /usr/share/thruk/lib/Monitoring/Availability.pm line 958.
Use of uninitialized value in numeric eq (==) at /usr/share/thruk/lib/Monitoring/Availability.pm line 958.
Use of uninitialized value in numeric eq (==) at /usr/share/thruk/lib/Monitoring/Availability.pm line 958.`
`
I'm  facing the problem using the nightly build from 09/09/2017. 

I'll be  happy to provide you any info to solve the problem (configs, dumps etc).

Thanks in advance!
Best regards, Petr

**Comment by sni** [comment]
Are you using the thruk logcache feature?

**Comment by noret** [comment]
logcache_delta_updates = 0
report_update_logcache = 0
logcache=mysql://log:pass@server:3306/thruk_logs
enable_icinga_features = 1

**Comment by noret** [comment]
Any news?

**Comment by sni** [comment]
Seems like the logfiles are kind of unusual with icinga 2. Thruk expects logentries to contain a state which seems not to be the case here. Can you open the reports page with `?debug=1` for example:
`https://<hostname>/thruk/#cgi-bin/reports2.cgi?debug=1`.
Then there will be a new button to create the report in debug mode. Afterwards, there should be a download link for debug information.
<img width="1052" alt="debug" src="https://user-images.githubusercontent.com/150844/30736308-87676406-9f82-11e7-8c3c-3e2242ebcbef.png">

The resulting file probably contains sensitive information, so please sent it directly by mail.

**Comment by noret** [comment]
I'm trying to build this report, but it's stuck at 0% form more than 10 mins. We have a large setup, but it's not that large. This could be related to this (found in log files of thruk):
[2017/09/26 11:07:04][monitor.boardreader.com][WARN][Thruk] date_format(-2147483648) failed: Date::Calc::Localtime(): time out of range at /usr/share/thruk/lib/Thruk/Utils/Filter.pm line 211

I can send you the logs from icinga so you could reproduce the problem. Would it help?

**Comment by yoshi314** [comment]
I have the same problem on latest stable thruk release when calculating svgroup availability , not through reports plugin. 

Can i also use debug mode here?
