### ISSUE TITLE
Hostgroup negated regex not working

### ISSUE THREAD

**Issue by pall-valmundsson** [sni/Thruk#758]
Reproduction links using the demo site.

Hostgroup negated regex not working:
https://demo.thruk.org/thruk/#cgi-bin/status.cgi?hidesearch=0&hidetop=&dfl_columns=&dfl_s0_hoststatustypes=15&dfl_s0_servicestatustypes=31&dfl_s0_hostprops=0&dfl_s0_serviceprops=0&style=detail&dfl_s0_type=hostgroup&dfl_s0_val_pre=&dfl_s0_op=%21%7E&dfl_s0_value=%5Egrou.*&dfl_s0_value_sel=5

Host negated regex works:
https://demo.thruk.org/thruk/#cgi-bin/status.cgi?hidesearch=0&hidetop=&dfl_columns=&dfl_s0_hoststatustypes=15&dfl_s0_servicestatustypes=31&dfl_s0_hostprops=0&dfl_s0_serviceprops=0&style=detail&dfl_s0_type=host&dfl_s0_val_pre=&dfl_s0_op=%21%7E&dfl_s0_value=%5Enaem.*&dfl_s0_value_sel=5

Am I missing something?

**Comment by sni** [comment]
Could you try again?

**Comment by pall-valmundsson** [comment]
It's still not working AFAICT.
