### ISSUE TITLE
Multiple broadcasts not allowed.

### ISSUE THREAD

**Issue by baamf** [sni/Thruk#760]
Recently upgraded to release 2.16-2.  Noticed after a user created two broadcasts, the next creation would just hang the GUI.  Seems to me there is a problem with the broadcast.pm script when it names these broadcast files.  After the first, the next is named using variable "x" in the script.  This variable is set to "1" so after the first time it tries to create the same file name and for my set up fails.  I changed it to use a random number which works for me.  Not sure if this is specific to me or not but thought I'd share.  Thanks.

Old Code:
if($id eq 'new') {
                $id = POSIX::strftime('%Y-%m-%d-'.$c->stash->{'remote_user'}.'.json', localtime);
               **my $x  = 1;**
               while(-e $c->config->{'var_path'}.'/broadcast/'.$id) {
                    $id = POSIX::strftime('%Y-%m-%d-'.$c->stash->{'remote_user'}.'_'.**$x**.'.json', localtime);
                }
}

New Code:
if($id eq 'new') {
                $id = POSIX::strftime('%Y-%m-%d-'.$c->stash->{'remote_user'}.'.json', localtime);
                **my $x  = int(rand(10000));**
                while(-e $c->config->{'var_path'}.'/broadcast/'.$id) {
                    $id = POSIX::strftime('%Y-%m-%d-'.$c->stash->{'remote_user'}.'_'.**$x**.'.json', localtime);
                }

**Comment by sni** [comment]
Oh, i forgot to increment $x. Should be fixed now.
