### ISSUE TITLE
Carriage return in CSV exports?

### ISSUE THREAD

**Issue by heinowalther** [sni/Thruk#764]
Hello there,
I have been using the great CSV export feature of Thruk, to create an Excel report.
Some of my checks have extensive output where it spans several lines.  In the Thruk web gui, it of cause uses "<br>" to break the line, and it looks great.  Yet when it gets exported, it is shown as one long line with no line breaks.
I have checked the check-script I use, and it does add a CR at the end of each line, but I suspect the export code to somehow strip this off?

I use version 2.17-20170824 with the  OMD 2.61~2017-08-24-labs-edition

Any suggestions are welcome.

/Heino

**Comment by sni** [comment]
I am not sure if its possible to export newlines in csv. But have you tried the excel export if you want to get excel files after all?
