### ISSUE TITLE
Recurring Downtimes: since update on Thruk 2.16-2, no services will be listed in the "Recurring Downtime" Tab

### ISSUE THREAD

**Issue by vossi76** [sni/Thruk#766]
After an update from the Thruk version 2.12 (OMD 2.20-labs-edition) to 2.16-2 (OMD 2.60-labs-edition), no scheduled downtimes for services are displayed in the "Recurring Downtime" Tab for normal monitoring users. Planned downtimes for hosts will be listed.
If I switch back to the OMD 2.20-labs-edition, the services will be displayed normally in the "Recurring Downtimes" overview.

As Monitoring Admin, everything is displayed in thruk frontend

**Comment by sni** [comment]
Thanks, should be fixed now.
