### ISSUE TITLE
BUG with 2 or more Backends

### ISSUE THREAD

**Issue by dennis0212** [sni/Thruk#768]
Hello,

when I config 2 Backends with http connect then Thruk no starting. When I config 1 then okay. Test with Backend 1 okay with 2 okay but together error!

p1mon007:~ # /etc/init.d/thruk restart
Stopping thruk.... Not running.
Starting thruk.....failed
Setting --timeout (timeout) to 15
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.11.4 on linux-gnu.

--2017-10-16 12:09:13--  http://localhost/thruk/cgi-bin/remote.cgi?startup
Resolving localhost... ::1, 127.0.0.1
Caching localhost => ::1 127.0.0.1
Connecting to localhost|::1|:80... connected.
Created socket 3.
Releasing 0x00000000006492e0 (new refcount 1).

---request begin---
POST /thruk/cgi-bin/remote.cgi?startup HTTP/1.0
User-Agent: Wget/1.11.4
Accept: */*
Host: localhost
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 2

---request end---
[POST data: '']
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 500 Internal Server Error
Date: Mon, 16 Oct 2017 10:09:13 GMT
Server: Apache/2.2.12 (Linux/SUSE)
Vary: accept-language,accept-charset
Accept-Ranges: bytes
Connection: close
Content-Type: text/html; charset=iso-8859-1
Content-Language: en
Expires: Mon, 16 Oct 2017 10:09:13 GMT

---response end---
500 Internal Server Error
Closed fd 3
2017-10-16 12:09:13 ERROR 500: Internal Server Error.

**Comment by dennis0212** [comment]
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4

**ERROR with 2 Remote with HTTP**
Thruk 2.16-2  Server MASTER
Thruk 2.16-2  Remote 1 SLAVE
Thruk 2.16-2  Remote 2 SLAVE

**OKAY with 2 Remote with HTTP**
Thruk 2.14-2  Server MASTER   (old Version)
Thruk 2.16-2  Remote 1 SLAVE
Thruk 2.16-2  Remote 2 SLAVE

**Comment by sni** [comment]
There should be a hint in the logfiles. You have to install additional perl modules when connecting to multiple http(s) backends or use LMD.
