### ISSUE TITLE
Statusmap: Circular Layout, Group by "parent" and using a filter shows nothing

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#769]
If I'm using the circular layout with group-by "parent" without filter, then I get a visualisation of the complete network beginning from the highest parent.
Then I tried to add a filter to see not my whole network but just beginning from a router all child hosts but I see nothing. Tried with different filter types.

**Comment by sni** [comment]
I guess there is nothing much we can do about it. Thruk cannot draw a tree with gaps inside.
