### ISSUE TITLE
Unable to save dashboards - saves without changes.

### ISSUE THREAD

**Issue by ThatAdamsGuy** [sni/Thruk#770]
If I've made any changes in panorama view (even as simple as moving an object), save the dashboard, and reopen it, it saves without these changes being made. As a result, we've had to hand-edit the JSON files to make any changes.

**Comment by sshmanko** [comment]
@ThatAdamsGuy Take a look at workaround in #684 maybe related

**Comment by sni** [comment]
I don't think thats related. Also this should be fixed in recent nightlys and the next release. And the next release adds a icon indicator when the dashboard is saved.
