### ISSUE TITLE
Performance problem with thruklog

### ISSUE THREAD

**Issue by Pierhomme** [sni/Thruk#774]
Hello,

I am DBA in a company that uses Thruk (v2.14-2).

We are frequently faced with log display problems in Thruk and I found that the BDD side (10.1.25-MariaDB), despite optimizations made on the MySQL instance, the response times are catastrophic.

So I activated the slow log, and noticed that several transactions or tables design are not optimized.
This has already been mentioned by a user ofalk (https://github.com/sni/Thruk/issues/320) a few years ago, but the problem is still present.

Here is a transaction that poses, for example, a problem :
Count: 261  Time=17.81s (4649s)  Lock=0.00s (0s)  Rows_sent=0.6 (144), Rows_examined=28391627.2 (7410214688), Rows_affected=0.0 (0), thruk_log[thruk_log]@localhost
  SELECT output_id FROM `866a5_plugin_output` WHERE output = 'S' LIMIT N

MariaDB [thruk_logcache]> explain SELECT output_id FROM `866a5_plugin_output` WHERE output = 'S' \G;
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: 866a5_plugin_output
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 20861047
        Extra: Using where
1 row in set (0.00 sec)

MariaDB [thruk_logcache]> show table status like '866a5_plugin_output' \G;
*************************** 1. row ***************************
           Name: 866a5_plugin_output
         Engine: InnoDB
        Version: 10
     Row_format: Compact
           Rows: 20861868
 Avg_row_length: 150
    Data_length: 3130015744
Max_data_length: 0
   Index_length: 0
 
MariaDB [thruk_logcache]> show index from thruk_logcache.866a5_plugin_output \G;
*************************** 1. row ***************************
        Table: 866a5_plugin_output
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: output_id
    Collation: A
  Cardinality: 20902127
     Sub_part: NULL
       Packed: NULL
         Null:
   Index_type: BTREE
      Comment:
Index_comment:
1 row in set (0.00 sec)

Like you see, no index, query that uses fullscan and many rows. All the ingredients for bad performance.

Thanks in advance.

(sorry for my poor english)

**Comment by sni** [comment]
Latest release does have an index on the plugin_output table already.
