### ISSUE TITLE
Garbled output in SLA-Report

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#775]
We have setup a SLA-Report on a "SLA-Servicegroup" where we have "Latest Outages" and "Worst Outages" both set to 1.
When there have been an outage and those two pages are created we get garbled output in the PDF-output (and hence in the sent email as well) if the Status-Information is too long. The "preview" output is OK (the long lines are just cut-off).

Here is a screenshot of the PDF output:
![screenshot_20171114_123954](https://user-images.githubusercontent.com/26163222/32778646-f8589ab8-c93a-11e7-9530-c6bd76287d3f.png)

Is this a problem with our environment or is it a bug in Thruk?

Regards,
D/\N

**Comment by sni** [comment]
thanks for the update, i still haven't found time to investigate this issue, but glad to hear you've found a solution.
