### ISSUE TITLE
 Error in tempfile() using template

### ISSUE THREAD

**Issue by rajuprabhub** [sni/Thruk#778]
After upgrading to 2.16-2 getting the following error.

[ERROR][Thruk] Error in tempfile() using template /tmp/XXXXXXXXXX: Have exceeded the maximum number of attempts (1000) to open temp file/dir at /usr/share/thruk/lib/Thruk/Utils/IO.pm line 261.

**Comment by sni** [comment]
Is this a reproducable issue? I assume there is something wrong with the server. Thruk just calls `File::Temp::tempfile` here. Check your filesystem and inodes.

**Comment by rajuprabhub** [comment]
Thank you @sni it's a server side issue.
