### ISSUE TITLE
Login form left justified with Exfoliation theme and cookie auth 

### ISSUE THREAD

**Issue by druchoo** [sni/Thruk#785]
Not sure if it's intentional or just something on my end.. All other themes have a form that's centered. Happens in Chrome, Firefox, and Safari; on my local install as well as demo.thruk.org.

![image](https://user-images.githubusercontent.com/2237523/34320771-f4bf5894-e7ce-11e7-95dc-757d41f5bef2.png)

**Comment by sni** [comment]
Should be better now, thanks.
