### ISSUE TITLE
Can't save business process

### ISSUE THREAD

**Issue by gzalo** [sni/Thruk#786]
Hi.

I'm having an issue with the Business Process plugin of Thruk v2.18.
The "save changes" button that appears when editing a business process doesn't work. It shows the spinner icon but it eventually fails and displays the exclamation mark warning. 
**No data is being sent to the server after pressing the save button** (checked with Chome developer tools and httpd's access_log) No javascript errors/warnings appear.

Thanks,
Gzalo
  
Extra info:
Linux 3.10.0-229.el7.x86_64 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.1.1503 (Core)
Installed using the *-2.18-1.rhel7.x86_64 RPMs

**Comment by sni** [comment]
thanks, should be fixed now.
