### ISSUE TITLE
error with Mysql.pm

### ISSUE THREAD

**Issue by rirouxe** [sni/Thruk#787]
Hello,

i have installed Thruk 2.18 on CentOS 7.3 and mysql  Ver 15.1 Distrib 10.1.28-MariaDB, for Linux (x86_64)

in my log i have this error everyday at the same time :

[Tue Jan  9 01:20:05 2018][INFO] Wed Sep 20 03:52:58 2017. 0 entries added
[Tue Jan  9 01:20:05 2018][INFO] OK - imported 1404 log items from 3 sites successfully in 2.81s (500/s)
[Tue Jan  9 01:24:34 2018][INFO] running clean for site 1
[Tue Jan  9 01:24:34 2018][INFO] cleaning logs older than: Fri Nov 10 01:24:34 2017
[Tue Jan  9 01:24:34 2018][INFO] cleaning old orphaned plugin outputs
[Tue Jan  9 01:24:35 2018][INFO] fetched ids
[Tue Jan  9 01:24:35 2018][INFO] sorted used ids
[Tue Jan  9 01:24:36 2018][INFO] running clean for site 2
[Tue Jan  9 01:24:36 2018][INFO] cleaning logs older than: Fri Nov 10 01:24:36 2017
[Tue Jan  9 01:24:36 2018][INFO] cleaning old orphaned plugin outputs
[Tue Jan  9 01:24:36 2018][INFO] fetched ids
[Tue Jan  9 01:24:36 2018][INFO] sorted used ids
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
[Tue Jan  9 01:24:36 2018][INFO] OK - removed 7932171 log items (and 3261694 plugin ouput references) from 3 sites successfully in 1474.20s (5380/s)

Thanks

**Comment by sni** [comment]
Should be better with tomorrow

**Comment by rirouxe** [comment]
always in error !






[Fri Jan 12 01:05:52 2018][INFO] running update for site 2
[Fri Jan 12 01:05:52 2018][INFO] latest entry in logcache: Fri Jan 12 00:24:45 2018
[Fri Jan 12 01:05:52 2018][INFO] latest entry in logfile:  Fri Jan 12 01:04:51 2018
[Fri Jan 12 01:05:52 2018][INFO] importing Fri Jan 12 00:24:45 2018 till Fri Jan 12 01:04:51 2018
[Fri Jan 12 01:05:52 2018][INFO] Fri Jan 12 00:24:45 2018. 2 entries added
[Fri Jan 12 01:05:52 2018][INFO] running update for site 3
[Fri Jan 12 01:05:52 2018][INFO] latest entry in logcache: Wed Sep 20 03:52:58 2017
[Fri Jan 12 01:05:52 2018][INFO] latest entry in logfile:  Wed Sep 20 03:52:58 2017
[Fri Jan 12 01:05:52 2018][INFO] importing Wed Sep 20 03:52:58 2017 till Wed Sep 20 03:52:58 2017
[Fri Jan 12 01:05:52 2018][INFO] Wed Sep 20 03:52:58 2017. 0 entries added
[Fri Jan 12 01:05:53 2018][INFO] OK - imported 1 log items from 3 sites successfully in 51.32s (0/s)
[Fri Jan 12 01:07:01 2018][INFO] running clean for site 2
[Fri Jan 12 01:07:01 2018][INFO] cleaning logs older than: Mon Nov 13 01:07:01 2017
[Fri Jan 12 01:07:01 2018][INFO] cleaning old orphaned plugin outputs
[Fri Jan 12 01:07:01 2018][INFO] fetched ids
[Fri Jan 12 01:07:02 2018][INFO] sorted used ids
[Fri Jan 12 01:07:02 2018][INFO] running clean for site 3
[Fri Jan 12 01:07:02 2018][INFO] cleaning logs older than: Mon Nov 13 01:07:02 2017
[Fri Jan 12 01:07:02 2018][INFO] cleaning old orphaned plugin outputs
[Fri Jan 12 01:07:02 2018][INFO] fetched ids
[Fri Jan 12 01:07:02 2018][INFO] sorted used ids
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
Use of uninitialized value $file_id in numeric lt (<) at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1266.
[Fri Jan 12 01:07:02 2018][INFO] OK - removed 716902 log items (and 404505 plugin ouput references) from 3 sites successfully in 420.36s (1705/s)
[Fri Jan 12 01:10:01 2018][INFO] running update for site 1
[Fri Jan 12 01:10:02 2018][INFO] latest entry in logcache: Fri Jan 12 00:55:01 2018
[Fri Jan 12 01:10:02 2018][INFO] latest entry in logfile:  Fri Jan 12 01:10:02 2018
[Fri Jan 12 01:10:02 2018][INFO] importing Fri Jan 12 00:55:01 2018 till Fri Jan 12 01:10:02 2018
[Fri Jan 12 01:10:02 2018][INFO] Fri Jan 12 00:55:01 2018........ 7192 entries added

**Comment by sni** [comment]
yes, please try again with tomorrows nightly or with the above referenced fix.

**Comment by rirouxe** [comment]
it's work
thanks
