### ISSUE TITLE
Limit of simultaneous manual check 

### ISSUE THREAD

**Issue by Raynor59** [sni/Thruk#788]
I am running Icinga2 / Thruk 2.14-2 in Docker  1.12 
I'm running inside VM CentOS Linux release 7.4.

I have an issue when trying to manual recheck a lot of services. (~100)

I am always stuck to 42 services rechecked no more.
I can't get where is the limitation (unix limit ? docker limit ? thruk hardcoded limit ?)...

I can't get specific errors in my log files, just have 42 services rechecked.
Moreover, when I am running same tests from a Icingaweb2 GUI (running also in Docker, same system, same versions, I don't have this limit).

I have found nothing usefull on internet.
Does someone already had this kind of problem ?

Thanks.

**Comment by sni** [comment]
You should update Thruk, this has been fixed meanwhile.

**Comment by Raynor59** [comment]
I have just upgraded to Thruk 2.18 and unfortunately I have the same issue.
