### ISSUE TITLE
Search for hostgroup alias not possible

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#789]
In many cases we have to set the host_name or host_group as an id-number and a description-name in the alias field. It is possible to search for an alias in config-tool to edit them but not in Thruk itself. I think it is a good a needed feature to be able to search for the alias in the search-field

**Comment by sni** [comment]
I cannot reproduce, the sidebar search searches in the host_name, host_alias, host_display_name, address, groups and plugin_output. See https://github.com/sni/Thruk/blob/master/lib/Thruk/Utils/Status.pm#L819:L825
When selecting the host filter, it still searches name, alias, address and display_name, see https://github.com/sni/Thruk/blob/master/lib/Thruk/Utils/Status.pm#L861

**Comment by kafos** [comment]
sorry my fault! 
The sidebar search is working but it only doesn't list the found entries. 

My prior problem was the alias of the hostgroups. (I edited the heading) Is it possible to integrate that function? ( best case would be the integration of the hostgroup alias in the ajax search as well)
