### ISSUE TITLE
showlog.cgi only showing "INITIAL HOST STATE" and "INITIAL SERVICE STATE"

### ISSUE THREAD

**Issue by smetj** [sni/Thruk#790]
Hi,

It seems that Thruk Version 2.16-2 only shows logs of type "INITIAL HOST STATE" and "INITIAL SERVICE STATE" when visiting showlog.cgi.

There's no filtering active (filter fields are empty) and I tried different regexes to see whether this changes anything to no avail.

Is this a known issue ?

**Comment by sni** [comment]
never had that issue. Is there anything on the Alerts or Notifications page? Is there a logcache involved?

**Comment by smetj** [comment]
Both the alerts and notifications page show normal and complete content...
There is NO logcache involved.

**Comment by smetj** [comment]
OK I found the cause of this:

> 2018-01-18 10:44:46 More than 1000000 lines in /var/log/naemon/naemon.log. Ignoring the rest!
> 2018-01-18 10:44:47 Maximum response size of 104857600 bytes exceeded!

We simply have too much of the "INITIAL STATE" entries at the beginning of the log which already consumes the allowed buffer.  Please disregard.
