### ISSUE TITLE
Filters Order

### ISSUE THREAD

**Issue by sdouce** [sni/Thruk#792]
Hello , 

is it possible to choose the filter order . Actually the list is alphabetically sorted ...

May be usefull to place your favorite filter first to choose??

Thank You .... ;-) 

![image](https://user-images.githubusercontent.com/6204522/35332639-eac2b6f0-010b-11e8-88cf-f219a3db6041.png)

**Comment by sni** [comment]
Well, yes and no. Everybody has different opinions on what is useful or important. I guess we could move Host/Service/Hostgroup/Servicegroup on top, would that make sense?

**Comment by sdouce** [comment]
Thank you sven,
In our case yes....This four options are  the most used....
Sébastien.

Le mer. 21 mars 2018 à 21:25, Sven Nierlein <notifications@github.com> a
écrit :

**Comment by sni** [comment]
should be better now.
