### ISSUE TITLE
Thruk show partial hostgroup

### ISSUE THREAD

**Issue by malcombecerra** [sni/Thruk#795]
hi everyone,

we have an issue with the show of the hostgroup, i read about this in some other plattforms like icinga, the problem is about the contact can see another hostgroup without have their autorization to all members of this group, i see this like "show_partial_hostgroup" we need the opposite of this, cuz we have a lot of clients that see his hosts and they see another hostgroups that not asiggned for them, and this cause a little confussion.

this logic can be applied to thruk?

**Comment by sni** [comment]
No, this is not possible. You will see all hostgroups where you have access to at least one host. However, sending hostgroup commands is only allowed if you have command access to all hosts in this group.

**Comment by steaksauce-** [comment]
Two potential fixes to your scenario:

- Use OMD and create multiple sites (assign one site per client).

- Use multiple Naemon instances with their own Thruk interface. To keep everything centralized to you, you may be able to add their monitoring stats to your Thruk instance via the LiveStatus integration

**Comment by malcombecerra** [comment]
on this scenario, we have nagios with modgearman for backend and distributed monitoring, and for the frontend mk-livestatus with  thruk.

the second option that you mention is not applicable for us ,  and for the first one, i don't understand how can we make it, 

can you put some links to how to make the first option that you mentioned?

**Comment by steaksauce-** [comment]
The first option would likely require some migration steps. OMD is pretty vast, and I would recommend checking out [the project page](https://labs.consol.de/omd/index.html).

However, you state that you are using livestatus, which you can totally add additional livestatus backends to Thruk. Just replace 'naemon' in my suggestion with 'nagios' :)

**Comment by malcombecerra** [comment]
that isn't an option for us use more backends, cuz we distribute the monitoring with mod_gearman, using a central nagios with workers

**Comment by steaksauce-** [comment]
Completely missed that part, even though you stated it before.

I'm afraid that I do not have any experience with mod_gearman :(
