### ISSUE TITLE
add missing info regarding redirection to https

### ISSUE THREAD

**Issue by Osa1989** [sni/Thruk#796]
Hello, 

on the website https://www.thruk.org/documentation/faq.html#enable-https-tls-ssl-in-apache-webserver-for-thruk . 
It's mentioned how one can redirect to https. But that's enough you have to change the URL of thie cookie to https as well.

**Comment by steaksauce-** [comment]
I can take a look at this later on today. Just to verify, following the documentation you can create a redirect to https, but you are running into trouble with cookies when doing so?

**Comment by sni** [comment]
You probably have to change the `cookie_auth_restricted_url` to https as well unless you redirect http to https automatically. But even then, changing it to https is still a good idea, because it saves one redirect every login.
And yes, a hint to change that as well might be good idea. Pull requests are welcome.

**Comment by Osa1989** [comment]
I was running into trouble. After directing http to https. No one was able to sign in. 
After investigating it with a cookie inspector the thruk_auth cookie wasn't being generated. 
After changing the url of the cookie, it was ok.

**Comment by steaksauce-** [comment]
Did you change it in your thruk.conf or in thruk_local.conf?

In my testing, when changing `cookie_auth_restricted_url` in my thruk.conf, I could not log in. However, when reverting the setting and instead placing it in my thruk_local.conf, I could.

**Comment by Osa1989** [comment]
I changed it in thruk.conf. In my thruk_local.conf I don't have the cookie settings

**Comment by steaksauce-** [comment]
From [my understanding](https://www.thruk.org/documentation/configuration.html), thruk_local.conf is the place to put changes that you want to override the defaults on.

In my case, it was blank by default. I simply copy the settings that I want to change from thruk.conf, place it in my thruk_local.conf, and then make the changes.

**Comment by sni** [comment]
Thats right, please do not change anything in the thruk.conf, instead add your overrides to the defaults in thruk_local.conf.
