### ISSUE TITLE
500 when trying to sort custom variable column

### ISSUE THREAD

**Issue by sshmanko** [sni/Thruk#798]
Url:        status.cgi?nav=&hidesearch=0&hidetop=&dfl_columns=name%2Cstate%2Clast_check%2Cduration%2Cpeer_name%2Cplugin_output%2Ccust_IAM_ROLE&dfl_s0_hoststatustypes=15&dfl_s0_servicestatustypes=31&dfl_s0_hostprops=0&dfl_s0_serviceprops=0&style=hostdetail&dfl_s0_type=custom+variable&dfl_s0_val_pre=TEAMS&dfl_s0_op=%3D&dfl_s0_value=x-team&sorttype=1&sortoption=36
Browser:    
Version:    2.21-20180208
Release:    February 08, 2018
Backends:   State / Program Version / Data Source Version
0 / 4.3.1 / 1.2.8p18
0 / 4.3.1 / 1.2.8p18

thruk.cfg:
show_custom_vars = IAM_ROLE

```
Stacktrace:
internal lmd error - /usr/local/thruk/tmp/lmd/live.sock: The request contains an invalid header. - bad request: table hosts has no column cust_iam_role to sort
at /usr/local/thruk/share/lib/Monitoring/Livestatus/Class/Lite.pm line 382.
at /usr/local/thruk/share/lib/Thruk.pm line 318.
Thruk::_dispatcher('HASH(0x7f7e887cfa80)') called at /usr/local/thruk/share/script/thruk.psgi line 0
eval {...} called at /usr/local/thruk/share/script/thruk.psgi line 0
```

**Comment by sni** [comment]
Have you tried updating LMD?

**Comment by sshmanko** [comment]
Yes, lmd - version 1.2.0 (Build: b243fa0)

**Comment by ntokos** [comment]
I noticed the same problem, clicking to sort a column of custom variable produces internal server error.
I first observed it on Thruk v.2.20-2 (part of OMD labs v2.70), upgraded OMD labs to last version (2.90, Thruk v.2.26) and it has the same problem.

I use Icinga2 as core.
The custom host variable is named device_model.
Here is the bug error report text from Thruk:
---------------
Url:        status.cgi?hostgroup=all&style=hostdetail&dfl_columns=name%2Cstate%2Cplugin_output%2Clast_check%2Ccust_device_model&sorttype=2&sortoption=35
Browser:    
Version:    2.26-2 / OMD OMD 2.90-labs-edition
Release:    December 18, 2018
LMD:        lmd - version 1.3.7 (Build: 2.90-labs-edition-v1.3.7)
Backends:   State / Program Version / Data Source Version
0 / r2.9.2-1 / r2.9.2-1
uname:      Linux nmon 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64
release:    Debian GNU/Linux 9
Stacktrace:
internal lmd error - /omd/sites/noc/tmp/thruk/lmd/live.sock: The request contains an invalid header. - bad request: table hosts has no column cust_device_model to sort
at /omd/sites/noc/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 386.
at /omd/sites/noc/share/thruk/lib/Thruk.pm line 349.
Thruk::_dispatcher(HASH(0x55ab98c429d8)) called at /omd/sites/noc/lib/perl5/lib/perl5/Plack/Util.pm line 145
eval {...} called at /omd/sites/noc/lib/perl5/lib/perl5/Plack/Util.pm line 145
Plack::Util::run_app(CODE(0x55ab967358b0), HASH(0x55ab98c429d8)) called at /omd/sites/noc/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 147
Plack::Handler::FCGI::run(Plack::Handler::FCGI=HASH(0x55ab95b771b8), CODE(0x55ab967358b0)) called at /omd/sites/noc/share/thruk/script/thruk_fastcgi.pl line 27

Thank you.

**Comment by sni** [comment]
should be better with the next release.

**Comment by ntokos** [comment]
Great, thank you.
