### ISSUE TITLE
View dashboard without login

### ISSUE THREAD

**Issue by bigfrankwny** [sni/Thruk#799]
I'd like to create a dashboard for the end user's use that's viewable without logging in.  I don't want to allow them access to anything else, only the dashboard, from a URL.  It needs to update automatically.

Check MK allows you to embed the user and password in the URL but I don't think that will work with Thruk.  Is there any way to accomplish this?

Thanks...

**Comment by steaksauce-** [comment]
I think the tricks are telling Apache to allow anonymous users while telling Thruk that anonymous http users have read-only access. This opens up a whole other set of issues if prying eyes have access to the webpage through the firewall or anything like that.

**Comment by sni** [comment]
I thought about this feature some time already but its complicated and i didn't have resources for this yet. Besides bypassing the usual authentication mechanisms, you would also need to make sure that you can't do anything harmful within the dashboard.

**Comment by bigfrankwny** [comment]
Thanks guys!

I have an existing Nagios setup with multiple customers.  I want to give them each a dashboard without allowing them visibility to the other customers devices and I really like the panorama dashboards.  I was hoping to leave my existing Nagios alone and just add Thruk but it looks like I need to move to OMD with Thruk and create separate sites for each customer.

Any thoughts on a better way to accomplish this?

Thanks again.

**Comment by steaksauce-** [comment]
That's the way I would do it. For the "master" Thruk page, you can add the livestatus of each other site

**Comment by bigfrankwny** [comment]
Thanks again for the help!

All hail Hypno Toad!

**Comment by steaksauce-** [comment]
I made a blog post (that I will _not_ shamelessly plug) that covers the OMD method mentioned previously. Since it seems to be a popular question, I will probably attempt to make a documentation page and submit a PR for it :)

**Comment by sni** [comment]
That'll be great. Thanks.

**Comment by sni** [comment]
I totally forgot, there is another approach: https://github.com/sni/Thruk/blob/master/support/panorama2img
This script exports a dashboard as png image which then can be put anywhere.
