### ISSUE TITLE
Business Process save button not working?

### ISSUE THREAD

**Issue by smetj** [sni/Thruk#804]
Hi all,

We are running Thruk 2.18
When hitting the save button in the "business process" edit-mode it fails displaying a yellow warning sign in the save button:

![selection_212](https://user-images.githubusercontent.com/1007219/36902850-311407de-1e2c-11e8-954f-14b1a6f7c89b.png)

When using the "save changes" link in the "Edit Action" menu then changes are saved properly...

Can someone confirm the same behavior?

**Comment by sni** [comment]
This is a known issue in chrome and fixed already, see #786

**Comment by smetj** [comment]
Overlooked that  one! Tnx Sven.
