### ISSUE TITLE
Automatic page refresh adds timestamp

### ISSUE THREAD

**Issue by liedekef** [sni/Thruk#805]
Sometimes, after a normal automatic page refresh, a timestamp gets added to the url of thruk.
So before the refresh:
http://.../thruk/#cgi-bin/status.cgi?host=all
And after 90 seconds:
http://.../thruk/#cgi-bin/status.cgi?host=all.88888549804688

Using thruk-2.18-1.x86_64 on EL7, backend is nagios-4 via mk-livestatus. Browser is google chrome.
Am I just missing a setting of some kind?

Edit: after some refreshes, the url becomes for example:
http://.../thruk/#cgi-bin/status.cgi?host=all.22222137451172.33333587646484.88888549804688

**Comment by sni** [comment]
This should be fixed in the nightlies already, see #776
