### ISSUE TITLE
bpcommit silently fails when apache doesn't have access to the destination directory

### ISSUE THREAD

**Issue by wasserman** [sni/Thruk#808]
Running ```sudo -u apache thruk -a bpcommit``` silently fails to write thruk_bp_generated.cfg when apache doesn't have read permissions to the destination directory.
It wrongly reports that it successfully writes the BPs when it can read, but not write to the thruk_bp_generated.cfg file, at least when there would be no effective changes.

This is with Thruk 2.16-2.

**Comment by sni** [comment]
Yes, thats intentional. If there are no changes, the file won't be touched and therefor no permission errors occur.
