### ISSUE TITLE
Wrong (double) total count for backend status

### ISSUE THREAD

**Issue by gitmopp** [sni/Thruk#809]
I updated to thruk-2.20-2, before I was using 2.19-20180129.
Since the new version the total backend count on top of the screen shows double amount of backends to be up.
All backends are LMD.
If I look at the frame source it looks like this:
```
var sites            = {"down":0,"disabled":0,"up":20,"peers":["1203f","90287","b30b5","a2bf2","20224","2ff96","d7aeb","e1a2c","a2ad2","ad649"],"total":20,      "sub":{"Default":{"down":0,"disabled":0,"up":10,"peers":["1203f","90287","b30b5","a2bf2","20224","2ff96","d7aeb","e1a2c","a2ad2","ad649"],"total":10}}};
```
The backends are okay and only once in the list, but the total count is wrong.

**Comment by sni** [comment]
thanks, should be better now.
