### ISSUE TITLE
time out of range

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#812]
Hi,

Any idea with this warning? am seeing a lot of this warning in thruk.log. am running on thruk version 2.16-2. Thanks in advance

[WARN][Thruk] date_format(-2005635248) failed: Date::Calc::Localtime(): time out of range at /usr/share/thruk/lib/Thruk/Utils/Filter.pm line 211.

**Comment by Delat0918** [comment]
Hi any comment on this kind of issue? hoping for your kind advise

**Comment by sni** [comment]
Can you reproduce that somehow?

**Comment by Delat0918** [comment]
Hi, we are just seeing this on the logs...

**Comment by sni** [comment]
Then i wouldn't care. This message can occur if somebody types wrong dates into the datefields of commands or something like that.
