### ISSUE TITLE
Display Filters 

### ISSUE THREAD

**Issue by djmcint** [sni/Thruk#816]
Hi, 

Thruk Version 2.20:

When using Custom Variables   
If I use a Custom Variable as second filter in 2nd position:

1. I add my first filter. Then add a second filter "Custom Variable", 

![1](https://user-images.githubusercontent.com/38287928/38623730-ae942dc6-3da6-11e8-9796-810b8eefd012.png)

2.  When I validate (green accept) it 
3.  Screen refreshes Value column disappears 

![2](https://user-images.githubusercontent.com/38287928/38623731-aeb17d0e-3da6-11e8-8944-b5af69cd6efa.png)

4.  I then refresh the screen again the Display Filter appears but Custom Variable Vlau eis Empty

![3](https://user-images.githubusercontent.com/38287928/38623732-aed13338-3da6-11e8-805b-57aa31d2b0ba.png)

thruk.log shows no inputs. 

thanks for taking this into account

**Comment by sni** [comment]
Thanks, should be fixed in the next release.
