### ISSUE TITLE
Reporting error

### ISSUE THREAD

**Issue by Tera-Two** [sni/Thruk#819]
Hi, 
I'm having a problem with Thruk reporting in 2.20-2.
When refreshing a report i've got an error i didn't remember having in previous version.
In one report i've got this error :
`DBD::mysql::st execute failed: Got error 'empty (sub)expression' from regexp at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 460.  on reports/sla_service.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.
`

In an other report, I've got this error :

`
DBD::mysql::db selectall_arrayref failed: Got error 'empty (sub)expression' from regexp at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 465.  on reports/sla_service.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76.
`
Any idea of what can cause this problem ?
Find attached the config of one of those reports : 
[1.txt](https://github.com/sni/Thruk/files/1924532/1.txt)

**Comment by sni** [comment]
what kind of report is that?

**Comment by Tera-Two** [comment]
Hi Sni,

It's a SLA Service report type.
Here is a print screen of one of those reports : 
![sla report type](https://user-images.githubusercontent.com/30077152/38991773-0dd831ae-43df-11e8-9e03-883949bdaf52.JPG)

**Comment by Tera-Two** [comment]
Hi, 
I've tried to run them again in 2.22 and there is still an error but just a small question about those reports...
What should I type in the field  HOST and in the field SERVICE of the report if I want to generate a report for all HOSTS and all SERVICES ? 
Should I leave those fields blank in that case ?

**Comment by solarisfire** [comment]
Just typing a * in either the host or service box should work.
