### ISSUE TITLE
logcacheclean using extreme amounts of ram

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#821]
I have been noticing one of my icinga2 nodes going OOM at night. Turns out it happened exactly at 1am , when logcacheclean is running on that node.

Running the command manually also causes the memory usage to skyrocket, from 2gb of ram to 7+ in a matter of 30 seconds.

Normally the node hovers at ~2-3GB ram usage out of alotted 8GB, so such a memory usage spike is rather abnormal.

**Comment by sni** [comment]
which version is that?
