### ISSUE TITLE
Some Backend(s) are in connecting status and found out later that its disconnected from customer side 

### ISSUE THREAD

**Issue by Delat0918** [sni/Thruk#822]
Hi, 
Good day.

We have this re occurring issue in thruk and LMD or Livestatus  Multitool Daemon plugin.

What we usually do to resolve is to restart the httpd service if we see two lmd process are running.
[root@XXXXXXthrukp01 ~]# ps -aux | grep lmd
apache   32035 49.2 24.5 6893136 6072196 ?     Sl   11:30   0:52 /opt/local/go/bin/lmd -pidfile /var/cache/thruk/lmd/pid -config /var/cache/thruk/lmd/lmd.ini -config /etc/thruk/lmd.ini
apache   32149  132 28.8 7870468 7134120 ?     Sl   11:30   2:08 /opt/local/go/bin/lmd -pidfile /var/cache/thruk/lmd/pid -config /var/cache/thruk/lmd/lmd.ini -config /etc/thruk/lmd.ini

and then kill the process  ID that is not in the /var/cache/thruk/lmd/pid.

Below are the information and logs prior in the httpd service restart.

Would like to seek for your help and advice what would resolve this issue permanently.

Hoping for your kind advice.

thruk -l
Def   Key      Name        Address
-------------------------------------------------
 *   51656    NEU-1      172.26.66.52:6557 (OK)
 *   bc29d    NEU-2      172.26.66.58:6557 (OK)
 *   51d28    CEU-1      172.26.66.53:6557 (OK)
 *   d4c78    CEU-2      172.26.66.59:6557 (OK)
 *   53dec    MED-1      172.26.66.54:6557 (OK)
 *   bde22    MED-2      172.26.66.60:6557 (connecting...)
 *   5f10e    APAC-1     172.26.66.55:6557 (OK)
 *   a103e    NCSA-1     172.26.66.56:6557 (OK)
 *   4120b    NCSA-2     172.26.66.57:6557 (OK)
 *   86368    NAG99      172.26.66.12:6557 (OK)
     90ba2    APPL-1     10.0.53.142:6557 (OK)
 *   b86d7    APPL-ChinaHUB 10.78.8.134:6557 (OK)
------------------------------------------------- 

[Thu Apr 26 08:46:42 2018][INFO] Thu Apr 26 06:28:17 2018. 439 entries added
broken pipe at /usr/share/thruk/lib/Thruk/Backend/Pool.pm line 30
        Thruk::Backend::Pool::__ANON__('PIPE') called at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 132
        eval {...} called at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 132
        Thruk::Backend::Provider::Mysql::_disconnect('Thruk::Backend::Provider::Mysql=HASH(0x3d69fd8)') called at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 885
        Thruk::Backend::Manager::close_logcache_connections('Thruk::Context=HASH(0x39f3470)') called at /usr/share/thruk/lib/Thruk/Utils/CLI/Logcache.pm line 169
        Thruk::Utils::CLI::Logcache::cmd('Thruk::Context=HASH(0x39f3470)', 'logcache', 'ARRAY(0x2164570)', 'HASH(0x3c2e280)', 'local', 'HASH(0x204d8d0)') called at /usr/share/thruk/lib/Thruk/Utils/CLI.pm lin
e 701
        Thruk::Utils::CLI::_run_command_action('Thruk::Context=HASH(0x39f3470)', 'HASH(0x204d8d0)', 'local', 'logcacheupdate') called at /usr/share/thruk/lib/Thruk/Utils/CLI.pm line 597
        Thruk::Utils::CLI::_run_commands('Thruk::Context=HASH(0x39f3470)', 'HASH(0x204d8d0)', 'local') called at /usr/share/thruk/lib/Thruk/Utils/CLI.pm line 505
        Thruk::Utils::CLI::_from_local('Thruk::Utils::CLI=HASH(0x2163d18)', 'Thruk::Context=HASH(0x39f3470)', 'HASH(0x204d8d0)') called at /usr/share/thruk/lib/Thruk/Utils/CLI.pm line 394
        Thruk::Utils::CLI::_run('Thruk::Utils::CLI=HASH(0x2163d18)') called at /usr/bin/thruk line 82
DBD::mysql::db DESTROY failed: MySQL server has gone away during global destruction.
DBD::mysql::db DESTROY failed: MySQL server has gone away during global destruction.
[Thu Apr 26 08:47:31 2018][INFO] running update for site NEU-1
[Thu Apr 26 08:47:31 2018][INFO] latest entry in logcache: Thu Apr 26 06:29:37 2018
[Thu Apr 26 08:47:31 2018][INFO] latest entry in logfile:  Thu Apr 26 08:47:23 2018
[Thu Apr 26 08:47:31 2018][INFO] importing Thu Apr 26 06:29:37 2018 till Thu Apr 26 08:47:23 2018
[Thu Apr 26 08:47:31 2018][INFO] Thu Apr 26 06:29:37 2018.......... 9172 entries added
[Thu Apr 26 08:47:33 2018][INFO] running update for site NEU-2
[Thu Apr 26 08:47:33 2018][INFO] latest entry in logcache: Thu Apr 26 06:29:40 2018
[Thu Apr 26 08:47:33 2018][INFO] latest entry in logfile:  Thu Apr 26 08:47:32 2018
[Thu Apr 26 08:47:33 2018][INFO] importing Thu Apr 26 06:29:40 2018 till Thu Apr 26 08:47:32 2018
[Thu Apr 26 08:47:33 2018][INFO] Thu Apr 26 06:29:40 2018.............. 13529 entries added
[Thu Apr 26 08:47:35 2018][INFO] running update for site CEU-1
[Thu Apr 26 08:47:36 2018][INFO] latest entry in logcache: Thu Apr 26 06:29:57 2018
[Thu Apr 26 08:47:36 2018][INFO] latest entry in logfile:  Thu Apr 26 08:47:30 2018
[Thu Apr 26 08:47:36 2018][INFO] importing Thu Apr 26 06:29:57 2018 till Thu Apr 26 08:47:30 2018
[Thu Apr 26 08:47:36 2018][INFO] Thu Apr 26 06:29:57 2018........ 7116 entries added
[Thu Apr 26 08:47:37 2018][INFO] running update for site CEU-2

**Comment by sni** [comment]
Which versions of LMD and Thruk is that? Looks like thruk starts two of them.

**Comment by Delat0918** [comment]
Hi, I just got the thruk version ... 
rpm -qa thruk
thruk-2.16-2.x86_64

i'm in thr src file of the lmd but couldnt find the version of it.

[root@dkrdswppthrukp01 lmd]# pwd
/opt/local/go/src/github.com/sni/lmd
[root@dkrdswppthrukp01 lmd]# ll
total 72
-rw-r--r-- 1 root root  3251 Jan  3 02:43 Changes
drwxr-xr-x 2 root root  4096 Jan  3 02:43 docs
-rw-r--r-- 1 root root 35147 Jan  3 02:43 LICENSE
drwxr-xr-x 2 root root  4096 Jan  3 02:43 lmd
-rw-r--r-- 1 root root  2744 Jan  3 02:43 lmd.ini.example
-rw-r--r-- 1 root root  4659 Jan  3 02:43 Makefile
-rw-r--r-- 1 root root  6538 Jan  3 02:43 README.md
drwxr-xr-x 3 root root  4096 Jan  3 02:43 t
[root@dkrdswppthrukp01 lmd]#

**Comment by Delat0918** [comment]
Hello any update on this please... THanks in advance

**Comment by sni** [comment]
You could try the latest daily with an updated LMD to see if this is still broken. There happenend a lot of changes in that area recently.

**Comment by Delat0918** [comment]
Hi, 

We have already updated the LMD Version from 1.1.5 to 1.3.0 
 But we still encounter issues after the update.

[2018/06/05 11:37:54][dkrdswppthrukp01.vestasext.net][ERROR][Thruk] Error in: /thruk/cgi-bin/status.cgi
[2018/06/05 11:37:54][dkrdswppthrukp01.vestasext.net][ERROR][Thruk] internal lmd error - did not get a valid response for at least any site at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1598.
 at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
        eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
        Plack::Util::run_app('CODE(0xfefef8)', 'HASH(0x2923030)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 145
        Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x6cdd48)', 'CODE(0xfefef8)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24
[2018/06/05 11:37:54][dkrdswppthrukp01.vestasext.net][ERROR][Thruk] No Backend available
[2018/06/05 11:37:54][dkrdswppthrukp01.vestasext.net][ERROR][Thruk] on page: http://wpp-monitoring.vestasext.net/thruk/cgi-bin/status.cgi?s0_op=~&s0_type=search&add_default_service_filter=1&s0_value=10.105.64.220&dfl_columns=host_name,description,state,host_address,last_check,duration,plugin_output,cust_OPRSTATUS&_=1528191458516
[2018/06/05 11:37:54][dkrdswppthrukp01.vestasext.net][ERROR][Thruk] CEU-2: connecting... (172.26.66.59:6557)
[2018/06/05 11:37:54][dkrdswppthrukp01.vestasext.net][ERROR][Thruk] CEU-1: connecting... (172.26.66.53:6557) 

Hoping for your kind advice on this as its getting a little bit weird on the issues. :)

**Comment by sni** [comment]
is it working without LMD?

**Comment by jgbuenaventura** [comment]
Hi sven,  our setup works wirhout lmd, but if one of our 12 nagios backends goes down, the whole thruk dashboard becomes inaccessible,

**Comment by sni** [comment]
is there anything in them `lmd.log`related to that backend which is always connecting?
