### ISSUE TITLE
IE11: Refresh of 'Comments' and 'Downtimes' and 'Recurring Downtimes' yields a 404 page

### ISSUE THREAD

**Issue by flingo64** [sni/Thruk#825]
No idea, if IE is still a supported browser, so in case it is:

IE11: Selecting 'Comments', 'Downtimes' or 'Recurring Downtimes' in the navigation pane shows the correct content, but the URL in the address line is missing the trailing 'extinfo.cgi?type=n', e.g. in an OMD setup, you would see:
> https://hostname/site/thruk/cgi-bin/

instead of :

> https://hostname/site/thruk/cgi-bin/extinfo.cgi?type=n

Therefore, refresh or automatic refresh fails. This issue applies only to IE, first seen in version 2.20-2 (OMD 2.70). FF and Chrome work fine.

**Comment by sni** [comment]
IE11 is not my favorite, but still supported. However, i cannot reproduce this issue. Could you try demo.thruk.org or the daily packages to see if this is still an issue?

**Comment by flingo64** [comment]
This works fine on demo.thruk.org using IE11!  I have this issue on 3 different OMD installations. If you think it's fixed already, we should close the issue, otherwise I could send you the log from IE11 Network Analyser (XML file), but the only thing that you will see is, that after refresh the URL is broken, although the Referer is correct the whole time.
