### ISSUE TITLE
Performance Map: Perfdata w/o warn/crit thresholds will be sorted alphabetically rather than numerically

### ISSUE THREAD

**Issue by flingo64** [sni/Thruk#826]
If I have a check which provides performance data without accompanying warning / critical threshold, then sorting by this perfdata in Performance Map will uses alphabetical sort rather than numerical sort.

E.g. check returns: 

> check output |active_leases=6 fill_level=21%;90;99;0;100

then in Performance Map sorting by 'active_leases' will do an alphabetical sort, sorting by 'fill_level' will do a numerical sort.

**Comment by flingo64** [comment]
The reason for the differerent sorting is not the missing performance threshold values, but the fact that some of the checks returned an blank performance data, so that the whole data column was interpreted as string. 
Sorry for the confusion!

**Comment by flingo64** [comment]
Arrrgh

**Comment by sni** [comment]
as far as i remember, the first value is used to determine if its a number or a string.

**Comment by flingo64** [comment]
Did some more testing: it has nothing to do with thresholds values being present in the performance data or not. I get the alphabetical sort order as soon as a least one perfdata has the value 0.

In some cases the respective column in the Performance then shows a blank value, 
![permap-0values-showing-blank](https://user-images.githubusercontent.com/10708998/39762650-7bd51bbc-52db-11e8-99c6-821547fe7d95.jpg)
in other cases it shows the check output rather than the perfdata. 
![permap-0values-showing-check-output](https://user-images.githubusercontent.com/10708998/39762617-66251dd0-52db-11e8-928c-521195111a19.jpg)Quite strange. 

The first one uses [check_mem.sh](https://exchange.nagios.org/directory/Plugins/System-Metrics/Memory/check_mem-2Esh/details) -w 80 -c 90 -W 80  -C 90
where systems with no swap memory enabled will return something like:
> MTOTAL=8201887744;;;; MUSED=218886144;;;; MCACHE=785444864;;;; MBUFFER=364507136;;;; STOTAL=1073737728;;;; SUSED=0;;;; 

Anyway, I would expect that perfdata is always numeric.

**Comment by sni** [comment]
Should be better now. Thanks for your report.

**Comment by flingo64** [comment]
Thanks! Will check with next OMD update.
