### ISSUE TITLE
classic log format is becoming deprecated in icinga2, which will probably break logcacheimport

### ISSUE THREAD

**Issue by yoshi314** [sni/Thruk#828]
as per https://github.com/Icinga/icinga2/issues/6032

Is there a workaround in the works ?

**Comment by yoshi314** [comment]
I thought icinga-reporting is actively supported and ido layout is not to be changed. Do you have any more information on that?

**Comment by sni** [comment]
no, i don't have more information on that. But i took a look at IDO and it contains not nearly all information neccessary to create useful reports. For example it doesn't contain timeperiod changes.
Maybe its not a good idea to deprecate things without having alternative solutions ready or at least planned.

**Comment by sni** [comment]
have a look at https://thruk.org/documentation/logfile-cache.html#icinga-2
there is an example for ido based imports.
