### ISSUE TITLE
Custom Search bar, I have 100+ backends to add and i'm not sure nagios core server for my monitored host.

### ISSUE THREAD

**Issue by rc00512011** [sni/Thruk#829]
**100+ Backens for Thruk need custom search bar**

We have 100+ backends to connect to Thruk. We are not sure which host belongs to which nagios server.
We dont want to keep 100 backends connected simultaneously, but we want to create custom search bar which will search the nagios server for host and activate nagios server once host identifies its nagios server.

Any modules needs to be updated,

**Comment by sni** [comment]
There is no such search. But it shouldn't be a problem to have all 100 backends permanently connected when using LMD, see: https://thruk.org/documentation/lmd.html

**Comment by rc00512011** [comment]
Thanks Sven, will try LMD..
