### ISSUE TITLE
Starting thruk.....failed

### ISSUE THREAD

**Issue by m2cci-KGY** [sni/Thruk#831]
Hi,
I install shinken and thruk on redhat7.4, I'm using the rpm packages of redhat7.4
I'm trying to start thruk with this commands "/etc/init.d/thruk start" but I have this error :

Starting thruk.....failed
Setting --timeout (timeout) to 15
Setting --output-document (outputdocument) to -
DEBUG output created by Wget 1.14 on linux-gnu.

URI encoding = ‘UTF-8’
Converted file name 'remote.cgi?startup' (UTF-8) -> 'remote.cgi?startup' (UTF-8)
--2018-06-06 14:46:39--  http://localhost/thruk/cgi-bin/remote.cgi?startup
Resolving localhost (localhost)... ::1, 127.0.0.1
Caching localhost => ::1 127.0.0.1
Connecting to localhost (localhost)|::1|:80... Closed fd 3
failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:80... Closed fd 3
failed: Connection refused.
Releasing 0x00000000016cad20 (new refcount 1).

Can you help me please.
Thank you for your help.

**Comment by sni** [comment]
`Connection refused` sounds like the webserver isn't running. Usually you don't have to start manually, just point your browser to the url displayed after the installation.
