### ISSUE TITLE
Error with reporting automatically running

### ISSUE THREAD

**Issue by umocolombo** [sni/Thruk#833]
**Describe the bug**

When reporting automatically running i have next error

```
no such service: *
$VAR1 = [
{
'-and' => [
{
'host_name' => 'NEW-UK-Core-Cat3750'
},
{
'description' => {
'~~' => '.*'
}
}
]
}
];
on reports/sla_host.tt at /usr/share/thruk/lib/Thruk/Views/ToolkitRenderer.pm line 76
```

**Thruk Version**
thruk-base-2.16-2.x86_64
thruk-2.16-2.x86_64
thruk-plugin-reporting-2.16-2.x86_64
libthruk-2.20-1.el7.centos.x86_64

**To Reproduce**
That error reproduce only when reporting automatically running.If i start reporting manual (clicked on the button) then i have no error.

**Expected behavior**
I have report like manual execution

**Screenshots**
![ps_report](https://user-images.githubusercontent.com/23745720/41464287-d40e0144-70aa-11e8-917b-734695f7c387.png)

**Comment by sni** [comment]
please try again with the latest nightly or the next release. I cannot reproduce this issue.
