### ISSUE TITLE
scrollTo url parameter mixes with others

### ISSUE THREAD

**Issue by vanscheijen** [sni/Thruk#835]
**Describe the bug**
The "scrollTo" url parameter mixes with other parameters after an automatic refresh

First page request:
GET /thruk/cgi-bin/status.cgi?s0_op=~&s0_type=search&add_default_service_filter=1&s0_value=ho%3ALINUX01&scrollTo=331.20001220703125&_=1530002564689

After waiting a few moments it became:
GET /thruk/cgi-bin/status.cgi?s0_op=~&s0_type=search&add_default_service_filter=1&s0_value=ho%3ALINUX01.20001220703125&scrollTo=331.20001220703125&_=1530002690079

It's not unusual that the scrollTo parameter keeps stacking onto the s0_value parameter until the URL becomes too large.

**Thruk Version**
thruk-2.16-2

**To Reproduce**
1. Search something using quick search.
2. Scroll down to any position.
3. Wait for automatic refresh, now it *might* (somehow this is not always reproducible) mix up the parameters.

**Additional context**
I have a hunch the issue is within thruk-2.16-2.js.
There are 3 relevant lines that IMHO are bad:
    var scroll = newUrl.match(/(\?|\&)scrollTo=(\d+)/);
    str = str.replace(/\?scrollTo=\d+/g, '?');
    str = str.replace(/\&scrollTo=\d+/g, '');

All 3 lines assume the parameter only consists of an integer. However most browsers put a float in there, so something with a "." (dot). I think it is fixable by matching on [\d.]+
Or by matching until end of line or & ?
Or maybe the bug is somewhere else and the browser shouldn't put a float there in the first place?

**Comment by sni** [comment]
thanks for your report, however, this should be fixed with #776 meanwhile.
