### ISSUE TITLE
read_resource_file ignore variables with underscores

### ISSUE THREAD

**Issue by srtxg** [sni/Thruk#836]
**Describe the bug**
The vairables like $WMI_INI_DIR$ are not replaced with the actual value.

**To Reproduce**
Go to the service page and look at the command line;
variables with "_" in them are not replaced

**Expected behavior**
They should be replaced, as those variables are used.

Furthermore, the  _get_replaced_string does include the underscore on candidates to pass
to macros replacement.

Patch:

--- /usr/share/thruk/lib/Thruk/Utils.pm.bak     2018-06-27 17:28:41.853845431 +0200
+++ /usr/share/thruk/lib/Thruk/Utils.pm 2018-06-27 17:29:24.566099719 +0200
@@ -735,7 +735,7 @@
     $macros   = {} unless defined $macros;
     open(my $fh, '<', $file) or die("cannot read file ".$file.": ".$!);
     while(my $line = <$fh>) {
-        if($line =~ m/^\s*(\$[A-Z0-9]+\$)\s*=\s*(.*)$/mx) {
+        if($line =~ m/^\s*(\$[A-Z0-9_]+\$)\s*=\s*(.*)$/mx) {
             $macros->{$1}   = $2;
             $comments->{$1} = $lastcomment;
             $lastcomment    = "";

**Comment by sni** [comment]
Could you create a pull request for this?
