### ISSUE TITLE
Downtimes Pages numbering  

### ISSUE THREAD

**Issue by aloloic** [sni/Thruk#839]
**Is your feature request related to a problem? Please describe.**

THRUK monitors several thousands of equipment and their services. I've configured several hundred downtime on equipment.
Given that i want to go through the downtimes. I go on the _system_ menu and click on _downtimes_ . All the downtimes are displayed on one page.

**Describe the solution you'd like**

In order to have a better overlook on the downtimes, i would like to be able to 'page' downtimes display. 

**Describe alternatives you've considered**

**Additional context**

**Comment by sni** [comment]
Unfortunatly, thats no so easy since there are host and service downtimes on one page.
