### ISSUE TITLE
Display Filter based on more variables

### ISSUE THREAD

**Issue by hakong** [sni/Thruk#841]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I'd like to filter based on more variables. For example icon_image.

**Describe the solution you'd like**
Display filter based on custom variables from a service configuration.

**Describe alternatives you've considered**
n/a

**Additional context**
Trying to filter out all windows-related services and hosts from a display. The windows hosts are not in a specific hostgroup, so I can't use that. I've been building filters for various windows-only checks and am currently struggling with getting rid of a "Disk Usage" check that returns "DISK WARNING /C" for Windows, but "DISK WARNING /" for Linux, and can't get the regex to work(`DISK WARNING /[A-Z]` is basicly what I want), so I thought about filtering the windows icon (`icon_image win40.png`) but that dosen't seem possible.
![image](https://user-images.githubusercontent.com/4422113/42648127-71d3ac58-85f5-11e8-9c79-6934f6732fdb.png)

**Comment by steaksauce-** [comment]
Not a direct solution to your problem, but with a bit of hostgroup magic, you can easily achieve this. We use hostgroups like win-disk-c, win-disk-f that run the checks for specific disks that might be present on a Windows system. Linux? linux-disk-/ and linux-disk-/[other mount pont].. Same thing with various services. If you're monitoring a small amount of servers, changing hostgroups shouldn't be too hard.

**Comment by sni** [comment]
The regular expression looks fine, what does Thruk complain about?

**Comment by hakong** [comment]
![image](https://user-images.githubusercontent.com/4422113/42657833-fa1545c8-8612-11e8-80fc-d92f75efa8ef.png)

**Comment by sni** [comment]
Which version is that, i have a feeling that i fixed something in that area a while ago.

**Comment by hakong** [comment]
Even a non-regex doesn't work.
![image](https://user-images.githubusercontent.com/4422113/42657941-5ae88112-8613-11e8-9491-ac4b1e5e5553.png)
![image](https://user-images.githubusercontent.com/4422113/42658015-96cfa6ec-8613-11e8-9984-c2628837e5fb.png)

**Comment by hakong** [comment]
Thruk Version 2.20-2

**Comment by sni** [comment]
Please retry with the latest release.

**Comment by hakong** [comment]
Does not seem to work.
Works:
![image](https://user-images.githubusercontent.com/4422113/42687382-3655982e-8688-11e8-9d20-a9e67990e8e5.png)

Does not work:
![image](https://user-images.githubusercontent.com/4422113/42687774-6e1cbcf0-8689-11e8-8c9a-7a8d71892492.png)

It seems to fail on the forwardslash, could that be?

**Comment by hakong** [comment]
### Found 2 that work:
```
DISK WARNING .*\w
DISK WARNING .*[A-Z]
```
![image](https://user-images.githubusercontent.com/4422113/42688067-633d6ff4-868a-11e8-86db-04f38dc7ab12.png)
![image](https://user-images.githubusercontent.com/4422113/42688085-77a4c8ac-868a-11e8-809f-7c8afd03bc48.png)


Does not work:
![image](https://user-images.githubusercontent.com/4422113/42687956-07949fe2-868a-11e8-9159-4fa647c9e01f.png)

Works, but not what I need:
![image](https://user-images.githubusercontent.com/4422113/42687984-1aef4ad8-868a-11e8-874f-067caedf3745.png)

**Comment by hakong** [comment]
Those two that work still give an error in the drop-down ajax autocomplete thingy. This works the same in both versions (2.20 and 2.23).

![image](https://user-images.githubusercontent.com/4422113/42688221-f391f700-868a-11e8-8e1b-3dcb6fabd592.png)
![image](https://user-images.githubusercontent.com/4422113/42688259-1557b1ea-868b-11e8-842b-0e42018f6a97.png)

These 2 work aswell with the forward slashes:
```
DISK WARNING .*/[A-Z]
DISK WARNING .*/\w
```

**Comment by hakong** [comment]
Seem to have foud another bug.
When typing in `DISK [A-Z]` in "Service", the drop-down ajax list shows HTML tags.
![image](https://user-images.githubusercontent.com/4422113/42688529-13c07384-868c-11e8-8b4b-55f5835fd236.png)

**Comment by sni** [comment]
i fixed the issue with the preview. Forward slashes must be escaped like `\/`
