### ISSUE TITLE
Configuring Thruk 2.22 with Icinga2

### ISSUE THREAD

**Issue by ojomom** [sni/Thruk#845]
I keep getting the following error:

------------------------
No Backend available
None of the configured Backends could be reached, please have a look at the logfile for detailed information and make sure the core is up and running.

Details:
Icinga Master: peered partner not ready yet (/var/cache/thruk/lmd/live.sock)
------------------------

The host OS is: CentOS Linux release 7.5.1804.  

I have Icinga2 and Thruk installed on the same host.  I just cant seem to get thruk to recognize the running icinga2 instance and show its services/hosts information.

My backend configuration shows this:

-----------------------------------------------------------
Backends Configuration
--
Name: Icinga Master
Type: livestatus
Connection:  /var/cache/thruk/lmd/live.sock
Hidden: No
--------------------------------------------------------------

I see no errors in the logs.  Please advise.

**Comment by sni** [comment]
You have to set the connection to the socket of Icinga 2, not LMD. First try to get Icinga2 to work, then enable LMD if you want according to https://www.thruk.org/documentation/lmd.html
