### ISSUE TITLE
Filtering query parameters in REST API not working

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#848]
Trying the nightly builds 2.23 which has the new feature REST API:

Following the documentation, it aint possible to filter query parameters. Any filter you try to run it returns the output "[]".

To reproduce you can run an example from the documentation like "thruk r '/hosts?name=localhost'".

The  REST API is working because you can query things with commands like "thruk /r hosts", "thruk r /hostgroups"

It aint a problem with the browser. You can reproduce the problem with the command line.

**Comment by sni** [comment]
hmm, which version is that exactly, because i can't reproduce it. It just works here

**Comment by jevvz** [comment]
Version 2.23-20180812.

The installation tested is with naemon on one server and thruk on another (offloaded). As it seems you can't reproduce it I'll try another installation with both components on the same server.

**Comment by jevvz** [comment]
Before trying another installation I tried a few filters. Some work and some do not work. Example:

Filtering name or groups doesn't work. Filtering address, peer_name or peer_key does work.

**Comment by jevvz** [comment]
Still without trying another installation the filters seems to work if the returned value is an integer not a string.

Example:

If the hostname is defined as GW0069 it doesn't work. If the hostname is defined as 0069 it works.

thruk r '/hosts?name=GW0069' -> Does not work.
thruk r '/hosts?name=0069' -> Does work.

**Comment by sni** [comment]
the real issue was the upper case characters which should work with tomorrows nightly.
