### ISSUE TITLE
#848 Upper case queries REST API

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#851]
Hi,

The closed #848 issue allready closed which is about filtering queries with uppercase names in REST API isn't still working after upgrades from nightly builds.

Example of names tried:

"GW001" -> doesn't work.
"gw0001" -> works.

**Comment by sni** [comment]
I found another issue, thruk previously compared lc($val) vs. your submited value while it should be lc($val) vs. lc($your_value). Thats why it works when you compare the lower case value.
This should be fixed with: 45487856b2b1
