### ISSUE TITLE
Quering multiple names in REST API

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#852]
In the REST API is it possible to filter multiple names (array) in a query?

Something like: "thruk r '/hosts?name=hostA,hostB'

The documentation says it is possible to do a regular expressión. Can it be done without a regular expression?

**Comment by sni** [comment]
yes, you can use complex queries like described here: https://www.thruk.org/documentation/rest.html#_complex-filtering
So either use regex like:
```
thruk r '/hosts?name[regex]=^(hostA|hostB)$'
```
or complex queries:
```
thruk r '/hosts?q=***name = "hostA" or name = "hostB"***'
```
