### ISSUE TITLE
Services with "-" in the name not selectable in filter

### ISSUE THREAD

**Issue by Brickius** [sni/Thruk#853]
**Describe the bug**
Lots of my Services have "-" marks in their name, whenever I type the first few letters into a filter box and select one from the dropdown it only adds the words up to the "-" character, it doesn't populate the field with the entire entry

The weird thing is that it does work fine the first time I enter it - it only fails when I go back and change it to look for something else

I've tested it with other multiple word services and they are unaffected - its only ones that have the "-" character in them

**Thruk Version**
Version 2.20

**To Reproduce**
1. Open Filter Box
2. Search for Service that contains a "-" in its name
3. Select one of the services and carry out the search
4. Edit the search filter again
5. Search again for Service that contains a "-" in its name
6. this time when you select the service from the dropdown it will only populate the word up to the "-" character

**Expected behavior**
It should always populate the filter field with the entry selected from the dropdown

**Screenshots**
![image](https://user-images.githubusercontent.com/24792331/45097577-13d8aa80-b11b-11e8-9a57-3fa617db4ba4.png)
Searching for the term

![image](https://user-images.githubusercontent.com/24792331/45097550-04f1f800-b11b-11e8-93bd-473cfe01e2fe.png)
Selecting it properly enters it into the filter field

![image](https://user-images.githubusercontent.com/24792331/45097577-13d8aa80-b11b-11e8-9a57-3fa617db4ba4.png)
Searching for the term again after completing the first search

![image](https://user-images.githubusercontent.com/24792331/45097652-3d91d180-b11b-11e8-95a1-f930fbaa55ef.png)
This time it only populates the first word, note it changes the lowercase to uppercase so it is changing the field

**Desktop (please complete the following information):**
 - Chrome
 - Version 68.0.3440.75 (Official Build) (64-bit)

**Additional context**

**Comment by sni** [comment]
should be better with the next release, thanks for the report.
