### ISSUE TITLE
Disabled hosts cannot be easily re-enabled

### ISSUE THREAD

**Issue by renard** [sni/Thruk#856]
**Describe the bug**
When a host is temporary disabled using the _Disable this host temporarily_ link it's impossible to re-enable it without manually altering the file in which it is declared.

**Thruk Version**
2.20

**To Reproduce**
1. Go to Hosts configuration
2. Click on 'Disable this host temporarily'
3. Validte and save your configuration
4. Return to Hosts configuration
5. The dropbox does not provide you the host you just disabled.

**Expected behavior**

It would be nice to have a "re-enable this host" button.

If it's not easy to parse the comments, a solution may be to add a tag to the disabled host:

Instead of commenting like:
```
#define host {
#  host_name                      server01.example.com
#  use                            tpl-server
#}
```

Try
```
# @@disabled
#define host {
#  host_name                      server01.example.com
#  use                            tpl-server
#}
# @@end
```

I guess this is the same for the all other objects (such as services, commands, time periods, ...)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by sni** [comment]
please try again with the latest nightly or the next release. A disabled object should be searchable via the object search in the config tool where it can be enabled again.
