### ISSUE TITLE
report_max_objects not changing

### ISSUE THREAD

**Issue by raptureveteran** [sni/Thruk#857]
**Describe the bug**
I'm trying to increase report_max_objects and I can't get Thruk to take the config changes

**Thruk Version**
Newest version

**To Reproduce**
This is my /etc/thruk/thruk_local.conf file

```
<Component Thruk::Backend>
    <peer>
        name    = icinga
        id      = 7215e
        type    = livestatus
        <options>
            peer          = 192.168.4.74:6558
        report_max_objects = 4000
        </options>
    </peer>
</Component>
~
```

**Expected behavior**
When I run a report with a couple thousand services I am hoping to be able to run the report, nothing happens and I get an error that the limit is 1000

**Desktop (please complete the following information):**
CentOS 7

**Additional context**

**Comment by sshmanko** [comment]
try defining `report_max_objects = 4000` outside of `<Component Thruk::Backend>... </Component>` block

**Comment by raptureveteran** [comment]
That worked. Thanks.
