### ISSUE TITLE
No log history for today

### ISSUE THREAD

**Issue by raptureveteran** [sni/Thruk#858]
![1](https://user-images.githubusercontent.com/14016958/45572488-6743aa80-b837-11e8-8631-76daa68d911c.png)
![2](https://user-images.githubusercontent.com/14016958/45572490-6874d780-b837-11e8-9129-8385e71ff3dc.png)

**Describe the bug**
I just installed Thruk on Thursday, I have log history for yesterday but suddenly today, I don't. Basically, I find a host that has a service setting off a critical alert in Icinga2. I go to that host and service and click alert history and for 9-14 there is nothing, but if i click past day, it shows pages of alert history. I'm not sure why its stopped logging it for the current day. The same thing happens if you go to the left navigation panel and choose history under "Alerts". Log is there for yesterday but nothing once today starts.

**Thruk Version**
Newest 

**OS Verison**

CentOS7

**Comment by sni** [comment]
Logs in icinga2 are kind of broken, please see https://thruk.org/documentation/logfile-cache.html#icinga-2 for a start.
