### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by rgelber** [sni/Thruk#859]
**Describe the bug**
I receive an internal server error page when selecting multiple host/services and executing a command this happens intermittently but will occur when acknowledging alerts, putting host/services into downtime, and pretty much any other scenario.

**Thruk Version**

Thruk Version: 2.22 
Thruk is on a stand-alone server receiving data from 7 different live status backends

**To Reproduce**
The steps are undetermined but occur when executing commands on hosts from the Thruk dashboard 

**Expected behavior**
After executing a command on a host I'm redirected to a webpage displaying an internal server error message. 

**Desktop (please complete the following information):**
 - Browser = Chrome 
 - Version Version 69.0.3497.92 (Official Build) (64-bit)
 - Desktop = Manjaro Linux

Issues persist on different browsers and os types. 

**Additional context**
Apache Error Log

ERROR: got signal ALRM while handling request, possible timeout in https://thruk.prod.clearcapital.net/thruk/cgi-bin/status.cgi?s0_op=~&s0_type=search&add_default_service_filter=1&s0_value=ho:deepfreeze&_=1537483197711
ERROR: User: fname
ERROR: Address: 10.x.x.x
ERROR: Stacktrace: 
 at /usr/share/thruk/lib/Thruk.pm line 567.
	Thruk::__ANON__('ALRM') called at /usr/lib64/thruk/perl5/Thread/Queue.pm line 82
	eval {...} called at /usr/lib64/thruk/perl5/Thread/Queue.pm line 82
	Thread::Queue::dequeue('Thread::Queue=HASH(0x11220d9)', 6) called at /usr/share/thruk/lib/Thruk/Pool/Simple.pm line 48
	Thruk::Pool::Simple::remove_all('Thruk::Pool::Simple=HASH(0x117768)') called at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1823
	Thruk::Backend::Manager::_get_result_parallel('Thruk::Backend::Manager=HASH(0x42f7690)', 'ARRAY(0x47f9920)', 'get_can_submit_commands', 'ARRAY(0x49192a0)') called at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1671
	Thruk::Backend::Manager::_get_result('Thruk::Backend::Manager=HASH(0x42f5190)', 'ARRAY(0x47f9920)', 'get_can_submit_commands', 'ARRAY(0x47192a0)', undef) called at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1398
	Thruk::Backend::Manager::_do_on_peers('Thruk::Backend::Manager=HASH(0x42f23190)', 'get_can_submit_commands', 'ARRAY(0x47192a0)') called at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 2090
	Thruk::Backend::Manager::AUTOLOAD(undef, 'fuser') called at /usr/share/thruk/lib/Thruk/Utils.pm line 490
	Thruk::Utils::get_dynamic_roles('Thruk::Context=HASH(0x449b210)', 'fuser, 'Thruk::Authentication::User=HASH(0x44ae748)') called at /usr/share/thruk/lib/Thruk/Utils.pm line 583
	Thruk::Utils::set_dynamic_roles('Thruk::Context=HASH(0x4423b210)') called at /usr/share/thruk/lib/Thruk/Action/AddDefaults.pm line 562
	Thruk::Action::AddDefaults::add_defaults('Thruk::Context=HASH(0x449b210)', 2) called at /usr/share/thruk/lib/Thruk/Controller/status.pm line 25
	Thruk::Controller::status::index('Thruk::Context=HASH(0x4324210)') called at /usr/share/thruk/lib/Thruk.pm line 319
	eval {...} called at /usr/share/thruk/lib/Thruk.pm line 308
	Thruk::_dispatcher('HASH(0x4423418)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
	eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
	Plack::Util::run_app('CODE(0x3623450)', 'HASH(0x44234b18)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 145
	Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x823c48)', 'CODE(0x36234c50)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24

**Comment by sni** [comment]
This might happen if one of those Backends does not respond in a timely matter. When having multiple backends you might want to have a look at the LMD sideproject which eliminates those connecton issues:
https://thruk.org/documentation/lmd.html

**Comment by sdouce** [comment]
Hello, 
I have the same problem . After disabling the rest_api_enabled option, everything comes back to normal ..
It seems that it causes too much connection to livestatus ...

**Comment by rgelber** [comment]
@sdouce After following the LMD documentation @sni provided I have yet to experience any issues. Thanks.
