### ISSUE TITLE
REST API; Hostgroup stats

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#860]
Is it possible to gather with the REST API stats from a hostgroup?

The documentation (GET /hostgroups) points to this URL https://www.naemon.org/documentation/usersguide/livestatus.html#hostgroups

For example how do you get the total number of hosts in a hostgroup.

**Comment by sni** [comment]
You could use something like this: `/hosts/stats?groups[gte]=Linux`. But you are right, making hostgroup stats available via a more simple url would be nice.
