### ISSUE TITLE
Fetching data from REST API not working since a recently upgrade (http Alamofire library)

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#861]
Since we've updated a previous nightly build v2.23 180929 to a recently v2.23 180905 we're facing a problem when we want to fetch from the REST API. We fetch from the REST API with the library Alamofire and don't know why the Apache access.log we see the URL changes how we have written it.

In the Apache access.log we see an URL is written the following way: 

GET /thruk/r/host?&q=%28groups%3E%3D%22gateways%22%29&sort=_FLAG_NAME HTTP/1.1" 400 203 "-" "PAS Go/1.0 (corp.san.bce.PAS-Go; build:1; iOS 12.1.0) Alamofire/4.7.3"
::1

With the previous version we see it is written the same way in the access.log but it returns a 200 response.

It seems that with the recently version it only doesn't work with Alamofire and probably with the "&" how it is written in te Apache access.log "GET /thruk/r/host?&q". In our code we don't write the URL with "&".

In the previous version we force the way the access.log is written the URL (the example with the "&") with a few browsers and it returns OK the data. In the recently version we also do this but it returns the following output:

"POST /thruk/cgi-bin/restricted.cgi HTTP/1.1" 401 381 "-" "thruk_auth"

{
   "code" : 400,
   "description" : "no datarow has a attribute named: ",
   "failed" : true,
   "help" : "lists all available rest urls.\nalias for /index",
   "message" : "possible typo in filter"
}

**Comment by sni** [comment]
please try again with tomorrows nightly, its probably fixed by 2fd3526a6 or 544aebc7

**Comment by jevvz** [comment]
Hi,

Excuse me telling this so late. But it ain't fixed. We've downloaded the latest stable version and it isn't working. Until now we were working with a nightly snapshot that works.
