### ISSUE TITLE
Thruk - Get details using API

### ISSUE THREAD

**Issue by muraliselva10** [sni/Thruk#866]
I  want to know the possibility of getting the details which is listed in thruk interface using API calls.

For example, I need to collect details which is listed under Host Groups --> Summary(Grid) tab using python script, I need to know whether any API available for collecting those details. or any other means which will help me to collect those details in automated way ?

**Comment by steaksauce-** [comment]
@muraliselva10 This is going to sound silly, but have you replaced "your_webserver" with the actual DNS name or IP address of your web server?

For example, if your Thruk server is at 192.168.109.10, then you need to change the url to https://192.168.109.10/r/

**Comment by sni** [comment]
make sure you use the latest nightly package when testing the rest api. it has not yet been released.

**Comment by muraliselva10** [comment]
Can you be more clear ? You mean latest nightly package will be supporting REST API ? or REST API feature is not yet released
 ?

**Comment by sni** [comment]
the page https://thruk.org/documentation/rest.html say: 
```
new in release v2.24
```
Since that version does not yet exist, it can only be tested with the nightly preview packages with versions 2.23.
