### ISSUE TITLE
add to Bookmarks simbol ++

### ISSUE THREAD

**Issue by welj** [sni/Thruk#867]
**Describe the bug**
add to Bookmarks simbol ++

**Thruk Version**
Version 2.22
June 29, 2018

**To Reproduce**
1. Go to Service 
2. Click on filter
3. Filter service name "NSClient++ Version" and add to Bookmarks  
4. go to Bookmarks - Bookmarks is empty, simbol ++ havent at filter

**Desktop (please complete the following information):**
 - Browser all
 - Version all

**Comment by welj** [comment]
Please fix it ;)

**Comment by sni** [comment]
unfortunatly, there is no easy fix.
