### ISSUE TITLE
Recurring Downtime for all services

### ISSUE THREAD

**Issue by alexstaz** [sni/Thruk#868]
Hello,

I need to create recurring downtime for all services of a host. I can schedule a downtime for all services from the server, but from recurring I can only do a host or service(s) downtime.
I am missing something ? Or this need to be implemented ?

Best regards,

**Comment by sni** [comment]
isn't a host downtime what you want then? It suppresses all services automatically.

**Comment by alexstaz** [comment]
A host downtime only work if the host is really down. But when the host is in downtime, still always OK, and some services are not OK, we will be notified.
The cron do a SCHEDULE_HOST_DOWNTIME command.
What I need is a SCHEDULE_HOST_SVC_DOWNTIME to schedule a downtime for all services of the host.

**Comment by alexstaz** [comment]
I will try to explain better :
You reboot a server. On this server, a big application is hosted. This application need time to stop and time to start.
If you schedule a Host downtime, only notification when host is down will be handled by the downtime. When the host is still up but the application is shutdown , I will be notified when I schedule only a host downtime. So I have to also create services downtime to not be notified.
But I have to specify services that will be handled by the downtime. What I want is a downtime with all services without specifying them, and for that I think it will use SCHEDULE_HOST_SVC_DOWNTIME to schedule a downtime for all services.
I hope it's more clear.
