### ISSUE TITLE
Panorama-Custom-Filter-Dropdown has a bug

### ISSUE THREAD

**Issue by lausser** [sni/Thruk#869]
**Describe the bug**
Panorama view: Dropdown-menu of a custom filter Icon does not work properly.

**Thruk Version**
Thruk 2.23-20181017

**To Reproduce**
1. New->Icons&Widgets->Custom Filter
2. Click on "Change Filter"
3. Select something from the left Dropdown menu. The first items are ok. If you click on an item which is shown below the "-----" separator, the item above will be selected.

**Expected behavior**
I click on X and X will be selected

**Comment by sni** [comment]
fixed in aa17ed6
