### ISSUE TITLE
Thruk 2.24 - main.html, Left Panel "General - All Unhandled" appended "no NODESTATUS" 

### ISSUE THREAD

**Issue by Yu6936** [sni/Thruk#870]
Hi,
  
   After yum update to thruk.x86_64 2.24-1, the main.html page, left panel, under General - All Unhandled link appended "no NODESTATUS".   See attached image.

yum update:
Oct 29 03:38:01 Updated: thruk-base.x86_64 2.24-1
Oct 29 03:38:03 Installed: urw-fonts.noarch 2.4-16.el7
Oct 29 03:38:06 Updated: thruk-plugin-reporting.x86_64 2.24-1
Oct 29 03:38:06 Updated: thruk.x86_64 2.24-1 
![screen shot 2018-10-29 at 1 09 13 pm](https://user-images.githubusercontent.com/32713607/47677555-abd39d00-db7c-11e8-9586-b1a558e631a6.png)

**Comment by sni** [comment]
Could you double check your bookmarks or local menu adjustments? This seems to be originated somewhere in your settings i guess.

**Comment by Yu6936** [comment]
Yes, it was bookmarks.  Delete bookmarks and problem was resolved. Thanks!

**Comment by Yu6936** [comment]
Yes, it was bookmarks. Deleted bookmarks and problem was resolved. Thanks!
