### ISSUE TITLE
This page does not exist... if F5

### ISSUE THREAD

**Issue by welj** [sni/Thruk#871]
**Describe the bug**
F5 (refresh) doesn't work at all pages sites

**Thruk Version**
2.24

**To Reproduce**
1. Go to site
2. Click on Problems -> Services (for example)
3. Press F5 -> This page does not exist...
If you believe this is an error, check your configuration and your logfiles.

**Comment by sni** [comment]
Whats in the url address bar when you get the page not found?

**Comment by welj** [comment]
thruk/#undefined like this https://demo.thruk.org/demo/thruk/#undefined

**Comment by sni** [comment]
please try the nightly or the next release. should be better now.
