### ISSUE TITLE
Host display name truncated in minemap in ma

### ISSUE THREAD

**Issue by pattarom** [sni/Thruk#873]
**Describe the bug**
In Panorama view, in minemap the host names (display names) are truncated.

**Thruk Version**
Thruk version 2.24

**To Reproduce**
1. Go to Panorama
2. Create a new dashboard
3. Add a minemap
4. Display name of hosts are truncated

**Expected behavior**
Column must auto-resize to the width of the largest host display name,

**Screenshots**
![dashboard](https://user-images.githubusercontent.com/23275429/47988012-58fc6700-e0e1-11e8-8abb-b6547fd4573d.jpg)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 69.0.3497.100

**Additional context**
I've found a possible solution here: https://groups.google.com/forum/#!searchin/thruk/minemap$20hostnames$20column%7Csort:date/thruk/canRgJwFp7Y/rTFhR6_hBgAJ
But applying the suggested changes to the code, I obtain an error. 
I'm not a perl (it is perl??) developer, so I'm not able to debug the error.

**Comment by sni** [comment]
its not so easy. Even in 2018 its quite complicated to write vertical text across all major browsers and ExtJS is a bit picky when changing those attributes on the fly which might happen if filter returns different hosts lists.
But i will have a look at that patch, seems like the author never created a pull request for this.
