### ISSUE TITLE
Paging on showlog.cgi, config.cgi

### ISSUE THREAD

**Issue by VladimirBilik** [sni/Thruk#874]
**Describe the bug**
After upgrade Thruk from 2.20 to 2.24 i noticed the number of entries shown in _showlog.cgi_ and _config.cgi_ is shortened. Both of these pages shows at most the _default paging steps_ entries (100) selected in _paging_steps_ but not more. The config in _thruk_local.conf_ is:
```
use_pager=1
paging_steps=30,*100,500,1000,all
```

When I switch off the pagging with:
```
use_pager=0
paging_steps=30,*100,500,1000,all
```
the page show all entries. When I switch on the pagging  and select 'all' as the default: 
```
use_pager=1
paging_steps=30,100,500,1000,*all
```
the page show all entries, too. But in both cases there are no paging controls shown.
Settings for pagging is shared with _status.cgi_, where the pages are shown as expected.
I think something similar was reported in   #443 

**Thruk Version**
Thruk 2.24, not using OMD

**To Reproduce**
1. Go to 'Main page'
2. Click on 'Event Log'
3. Scroll down to bottom of page
4. See _100 of 100 Matching Log Entries Displayed_, although there are more lines in a table

**Expected behavior**
Paging similar to _status.cgi_, i.e.:
![image](https://user-images.githubusercontent.com/11392744/48057262-dd1f1f00-e1b3-11e8-8f4b-72f687e99836.png)

**Desktop (please complete the following information):**
 - Browser1: Firefox 60.2.0esr (64-bit)
 - Browser2: Internet Explorer 11.0.96

**Comment by VladimirBilik** [comment]
However, on the Thruk demo page:
https://demo.thruk.org/thruk/#cgi-bin/showlog.cgi
the paging is working correctly.  Is it just a problem with my configuration only?

As a workaround I adjusted the link in _/etc/thruk/menu_local.conf_ to open showlog.cgi with parameter _entries=all_:

```
  add_section('name' => 'Reports');
  add_link('name' => 'Availability',      'href' => '/thruk/cgi-bin/avail.cgi');
  add_link('name' => 'Trends',            'href' => '/thruk/cgi-bin/trends.cgi') if $c->stash->{'use_feature_trends'};
  add_link('name' => 'Alerts',            'href' => '/thruk/cgi-bin/history.cgi?host=all');
    add_sub_link( 'name' => 'Summary',    'href' => '/thruk/cgi-bin/summary.cgi');
  add_link('name' => 'Histogram',         'href' => '/thruk/cgi-bin/histogram.cgi') if $c->stash->{'use_feature_histogram'};
  add_link('name' => 'Notifications',     'href' => '/thruk/cgi-bin/notifications.cgi?contact=all');
  add_link('name' => 'Event Log',         'href' => '/thruk/cgi-bin/showlog.cgi?entries=all');
```

Thank you for your time.

**Comment by VladimirBilik** [comment]
I use just one backend - Naemon 1.0.8. OS= Centos 7.4.1708 (Core), kernel 3.10.0-693.21.1.el7.x86_64.

I have another observation: in URL /thruk/#cgi-bin/showlog.cgi, if I set page=_somenumber_ where somenumber is greater or equal 2, I can see the paging, but with number of entries set to _somenumber_ x _default paging steps_. If I select the page number 1 afterwards, the paging header disappears.

Could you give me a hint what to check please? Should I focus on showlog.cgi and try to debug what data it is processing, or communication with backend and data it is retrieving from it?


![image](https://user-images.githubusercontent.com/11392744/48382620-286c8c80-e6e2-11e8-904a-be803eb4b1ec.png)








At the same time I'm investigating some crashes of Naemon, but I think it is different problem (some issues with libc: kernel: traps: naemon[7494] general protection ip:7fd9ae384036 sp:7fd9af29cae8 error:0 in libc-2.17.so). It occurs with searching in event log with long period covering 8-12 months. What do you think - could it have something in common with this issue?

Thank you.

**Comment by anfoe1111** [comment]
We observe the same issue:
After upgrading thruk to 2.24-2, paging does not work anymore in showlog.cgi, notifications.cgi and history.cgi. We also use naemon 1.08 as a backend, running on  CENTOS 7.5, Kernel 3.10.0-862.14.4

Also, like Vladimir described, we observe some naemon- (livestatus- ?) crashes when reading a huge amount of eventlogs, e.g. several days.

Thanks and Regards,
ANdreas

**Comment by sni** [comment]
both issues should be fixed in nightly already if you want to test that one.

**Comment by VladimirBilik** [comment]
tested - works fine. 
Thank you.

**Comment by anfoe1111** [comment]
Thanks, I’ll test it on Thursday.
