### ISSUE TITLE
Missing timeout for backend/Business Process calculations

### ISSUE THREAD

**Issue by gzalo** [sni/Thruk#878]
Hi
I've found a bug: If a livestatus broker is being slow or stops answering queries, the BP calculation doesn't timeout! It keeps waiting indefinitely for an answer.
Since this calculation runs every minute via cron and there is no check to see if a calculation is already pending, if the system can't keep up, the process counts starts increasing until the system runs out of RAM and swap:

![photo_2018-11-14_13-32-16](https://user-images.githubusercontent.com/538127/48499386-19d3c180-e817-11e8-8b0a-cc986e90bc84.jpg)

Is there a way to configure a broker timeout to avoid this kind of issues? I'd appreciate any help!

My version of Thruk is 2.24-2. I'm using XI 5.5.6 with Core 4.4.2, Livestatus 1.5.0p7.

Thanks,
Gonzalo

**Comment by sni** [comment]
indeed, there should be a timeout, but it seems like it doesn't work.

**Comment by sni** [comment]
should be better with the next release

**Comment by gzalo** [comment]
Awesome, thanks!
