### ISSUE TITLE
Wrong BP status after applying configuration

### ISSUE THREAD

**Issue by gzalo** [sni/Thruk#881]
Hi. 

I think I found a bug that happens if the BP calculation is scheduled right after (or during the time) the Nagios Core is being restarted. Somehow service status are considered as UNKNOWN, so many BPs will return incorrect status for a minute.
I don't know if this is a livestatus bug or if Thruk is parsing incorrectly its output.

For instance:
![err_livestatus](https://user-images.githubusercontent.com/538127/48841361-f907f080-ed6f-11e8-8190-226348d0e2d4.PNG)
(I'm using the spool as a way to send back the results to Nagios, so the time is probably just seconds after the process restarted)

![auditlog](https://user-images.githubusercontent.com/538127/48841403-1d63cd00-ed70-11e8-803b-5ff43b1254a2.PNG)

Livestatus log:
![livestatus_log](https://user-images.githubusercontent.com/538127/48841410-22288100-ed70-11e8-99ef-041ab14eab25.PNG)
It seems as if Livestatus didn't recieve any queries during that minute.

Version: Nagios XI 5.5.7 (Nagios Core 4.4.2), Thruk 2.24-2, Livestatus 1.5.0p7

If its a livestatus bug, could you add a way to cancel the processing of BPs if the Nagios Core run time is less than a certain threshold?

Many Thanks,
Gonzalo

**Comment by sni** [comment]
should be fixed with 5c1b1c835da76d9479c827ce290fc66ce71e9016
