### ISSUE TITLE
custvars works but when trying to export it to excel there is no value for custom var

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#885]
**Describe the bug**
We are trying to export a report to excel. we selected a Hostname, IP Address and some custom variable and we got the error message below: 

**Thruk Version**
Version of Thruk 2.24-2

Please report this issue by mail to: bugs@thruk.org

Please describe what you did:
Make sure the report does not contain confidential information.
---------------
Url:        status.cgi?host=all&view_mode=xls
Browser:    
Version:    2.24-2
Release:    November 06, 2018
LMD:        lmd - version 1.3.6 (Build: )
Backends:   State / Program Version / Data Source Version
0 / 4.3.4 / 1.2.8p27
2 /  / 
0 / 4.3.4 / 1.2.6p15
uname:      Linux dkrdswppthrukt01.vestasext.net 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Sep 18 10:29:08 EDT 2018 x86_64
release:    Red Hat Enterprise Linux Server release 6.10 (Santiago)
Stacktrace:
internal lmd error - /var/cache/thruk/lmd/live.sock: socket error - Post http://172.26.66.71:8080/query: EOF
at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 386
at /usr/share/thruk/lib/Thruk.pm line 350
Thruk::_dispatcher('HASH(0x307c8c8)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
Plack::Util::run_app('CODE(0x2fdb2a0)', 'HASH(0x307c8c8)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 145
Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x25b0d48)', 'CODE(0x2fdb2a0)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24

**Additional context**
we didnt encounter this issue on version 2.20-2. We tried downgrading to version 2.22 but filtering on custvars works but when trying to export it to excel there is no value for custom var..

`
![image](https://user-images.githubusercontent.com/12998432/48936715-b77d6e00-ef46-11e8-8ef5-de5f23643e19.png)

`

**Comment by sni** [comment]
looks like a clustered lmd, right? Is there anything in the lmd.log?

**Comment by jgbuenaventura** [comment]
Hi Sven. 
i cant reproduce the issue now since ive already disabled the LMD and downgraded to version 2.22 but filtering on custom vars works but when trying to export it to excel there is no value for custom var..

![image](https://user-images.githubusercontent.com/12998432/48942519-beae7700-ef5a-11e8-8bb5-9969279c7f79.png)

**Comment by sni** [comment]
should be fixed by #803
