### ISSUE TITLE
custom vars is empty on export to csv

### ISSUE THREAD

**Issue by Delat0918** [sni/Thruk#887]
Hi, Sven.

Good day.

We are exporting an Excel CSV and are using **version 2.22** however there is no output on the   **Duration** column. Also noticed that when selecting/checking all the **_"Columns to export"_** it does not give/download the **_status.xls_** 

Checking from the error logs I have here the following :

[Tue Nov 27 06:38:07 2018] [debug] auth_mellon_util.c(48): [client 10.1.1.100] reconstruct_url: url=="http://xxx.xxx.xxx.net/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&reload_nav=1&scrollTo=320&_=1543297072680", unparsed_uri=="/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&reload_nav=1&scrollTo=320&_=1543297072680", referer: http://xxx.xxx.xxx.net/thruk/side.html
[Tue Nov 27 06:38:07 2018] [debug] auth_mellon_handler.c(253): [client 10.1.1.100] loaded IdP "http://idp.xxx.net" from "/etc/httpd/saml2/wpp_idp_test.xxx.net_metadata.xml"., referer: http://xxx.xxx.xxx.net/thruk/side.html
[Tue Nov 27 06:38:07 2018] [debug] auth_mellon_handler.c(3184): [client 10.1.1.100] Redirecting to login URL: http://xxx.xxx.xxx.net/saml2/login?ReturnTo=http%3A%2F%2Fxxx.xxx.xxx.net%2Fthruk%2Fcgi%2Dbin%2Fstatus.cgi%3Fhostgroup%3Dall%26style%3Dhostdetail%26reload_nav%3D1%26scrollTo%3D320%26_%3D1543297072680&IdP=http%3A%2F%2Fidp.xxx.net, referer: http://xxx.xxx.xxx.net/thruk/side.html
[Tue Nov 27 06:38:07 2018] [debug] auth_mellon_cookie.c(176): cookie_set: mellon-cookie=cookietest; Version=1; Path=/; Domain=xxx.xxx.xxx.net;
[Tue Nov 27 06:38:07 2018] [debug] auth_mellon_handler.c(253): [client 10.1.1.100] loaded IdP "http://idp.xxx.net" from "/etc/httpd/saml2/wpp_idp_test.xxx.net_metadata.xml"., referer: http://xxx.xxx.xxx.net/thruk/side.html

(process:18202): Lasso-WARNING **: 2018-11-27 06:38:07  Encoded a RelayState of more than 80 bytes, see #3.4.3 of saml-bindings-2.0-os
[Tue Nov 27 06:38:15 2018] [debug] auth_mellon_handler.c(253): [client 10.1.1.100] loaded IdP "http://idp.xxx.net" from "/etc/httpd/saml2/wpp_idp_test.xxx.net_metadata.xml"., referer: http://wpp-idp-test.xxx.net/login

(process:25103): Lasso-CRITICAL **: 2018-11-27 06:38:15 (xml.c/:1658) Trying to add to a GList* a non GObject pointer dest=*list src=subnode
[Tue Nov 27 06:38:15 2018] [debug] auth_mellon_util.c(48): [client 10.1.1.100] reconstruct_url: url=="http://xxx.xxx.xxx.net/saml2/postResponse", unparsed_uri=="/saml2/postResponse", referer: http://wpp-idp-test.xxx.net/login
[Tue Nov 27 06:38:15 2018] [debug] auth_mellon_cookie.c(176): cookie_set: mellon-cookie=04ceadaf5592010eab479f2fe929bd51; Version=1; Path=/; Domain=xxx.xxx.xxx.net;
[Tue Nov 27 06:38:15 2018] [debug] auth_mellon_handler.c(509): [client 10.1.1.100] The current LassoProfile object doesn't contain a LassoIdentity object., referer: http://wpp-idp-test.xxx.net/login
ERROR: got signal TERM while handling request, possible timeout in http://xxx.xxx.xxx.net/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&reload_nav=1&scrollTo=80&_=1543297261219
ERROR: User: batman
ERROR: Address: 10.1.1.100
ERROR: Stacktrace:
 at /usr/share/thruk/lib/Thruk.pm line 565
        Thruk::__ANON__('TERM') called at /usr/share/thruk/lib/Thruk/Utils.pm line 2534
        eval {...} called at /usr/share/thruk/lib/Thruk/Utils.pm line 2534
        Thruk::Utils::check_memory_usage('Thruk::Context=HASH(0x4420d40)') called at /usr/share/thruk/lib/Thruk.pm line 875
        Thruk::_after_dispatch('Thruk::Context=HASH(0x4420d40)', 'ARRAY(0x3c95bc8)') called at /usr/share/thruk/lib/Thruk.pm line 356
        Thruk::_dispatcher('HASH(0x3b8d7e8)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
        eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
        Plack::Util::run_app('CODE(0x2a97c48)', 'HASH(0x3b8d7e8)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 145
        Plack::Handler::FCGI::run('[Tue Nov 27 06:41:02 2018] [error] [client 10.1.1.100] Premature end of script headers: fcgid_env.sh, referer: http://xxx.xxx.xxx.net/thruk/cgi-bin/status.cgi?hostgroup=all&style=hostdetail&reload_nav=1
Plack::Handler::FCGI=HASH(0x2099d48)', 'CODE(0x2a97c48)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24

Saw this script in the error log.

**/usr/share/thruk/fcgid_env.sh**

#!/bin/bash
#set thruk environment
#and run fastcgi server

if [ "x$OMD_ROOT" != "x" ]; then
  export THRUK_CONFIG="$OMD_ROOT/etc/thruk"
  THRUK_FCGI_BIN="$OMD_ROOT/share/thruk/script/thruk_fastcgi.pl"
  [ -e $OMD_ROOT/.profile ] && . $OMD_ROOT/.profile
  [ -e $OMD_ROOT/.thruk   ] && . $OMD_ROOT/.thruk
else
  export THRUK_CONFIG="/etc/thruk"
  THRUK_FCGI_BIN="/usr/share/thruk/script/thruk_fastcgi.pl"
  [ -e /etc/sysconfig/thruk ] && . /etc/sysconfig/thruk
  [ -e /etc/default/thruk ]   && . /etc/default/thruk
  [ -e ~/.thruk ]             && . ~/.thruk
fi

exec $THRUK_FCGI_BIN

![duration](https://user-images.githubusercontent.com/38754324/49061818-c9178c00-f24c-11e8-8ad7-db0fdc324423.JPG)

Would like to seek for your advice and help on this

**Comment by jgbuenaventura** [comment]
Hi Sven,

So I tested the thruk nightly build but the exporting the custom Variable to excel produce nothing


thruk-2.25-20181127.x86_64
thruk-plugin-reporting-2.25-20181127.x86_64
libthruk-2.24-0.x86_64
thruk-base-2.25-20181127.x86_64

Red Hat Enterprise Linux Server release 6.10 (Santiago)
httpd-tools-2.2.15-69.el6.x86_64
httpd-2.2.15-69.el6.x86_64


![image](https://user-images.githubusercontent.com/12998432/49074553-da25c480-f26f-11e8-9460-93a35d69d0db.png)

**Comment by sni** [comment]
should be fixed by #803
