### ISSUE TITLE
API Contactgroups no output with name in the URL

### ISSUE THREAD

**Issue by Beatlor** [sni/Thruk#891]
**Describe the bug**
When I try to curl the thruk API and try to GET the contactgroup "**name**" config
like curl -k 'https://apiuser:test@server/site/thruk/r/contactgroup/**oncall**/config'

I get [] as output.

When I curl 
curl -k 'https://apiuser:test@server/site/thruk/r/contactgroup/'

I get a complete list with all contactgroups.

**Thruk Version**
Thruk 2.24 - www.thruk.org - OMD 2.80-labs-edition

**To Reproduce**
Send curl like described

**Expected behavior**
Config only for the contactgroup **name**
[
  {
      "alias" : "Oncall Alerting Group",
      "members" : [
         "member-1"
      ],
      "name" : "oncall",
      "peer_key" : "fd511",
      "peer_name" : "site"
   }
]

**Desktop (please complete the following information):**
Browser Safari/Firefox/Chrome and curl - same result

**Comment by sni** [comment]
Should be better tomorrow: 6fb770a
