### ISSUE TITLE
Thruk as a service 

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#892]
Hi is there a reason why i cant start thruk as a service in thruk version 2.24-2?

btw this is a fresh install of thruk in rhel 7

# systemctl status thruk
Unit thruk.service could not be found.

# ps -ef | grep thruk

root     27646 27645  0 10:30 ?        00:00:00 perl -x /usr/share/thruk/thruk_auth
apache   27658 27647  0 10:30 ?        00:00:00 /usr/bin/perl /usr/share/thruk/script/thruk_fastcgi.pl
apache   27667 27647  0 10:30 ?        00:00:00 /usr/bin/perl /usr/share/thruk/script/thruk_fastcgi.pl
root     28637  9822  0 10:45 pts/1    00:00:00 grep --color=auto thruk

but thruk is started. 

Thanks

**Comment by sni** [comment]
There is no systemd service for Thruk. Thruk is started automatically from the apache webserver upon request.
