### ISSUE TITLE
REST API filter custom variables

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#893]
It seems in REST API you can't query with complex filtering custom variables.

You can filter with limitations with the &. Example: thruk/r/host?&_custom_variable=value.

Greetings,
Jorge.

**Comment by sni** [comment]
i just tried and it works, what exactly did you try?

```
%> thruk r -d 'q=***rta > 0 and _WORKER = "local"***' /hosts?columns=rta,_WORKER
[
   {
      "_WORKER" : "local",
      "rta" : "0.014"
   },
   {
      "_WORKER" : "local",
      "rta" : "0.014"
   }
]
```

**Comment by jevvz** [comment]
Don't know if I'm doing wrong or it's not working with services.

http://127.0.0.1/thruk/r/host?q=(_OFICINA =  0554) -> Works.

http://127.0.0.1/thruk/r/host?&_OFICINA=0554 -> Also works.

http://127.0.0.1/thruk/r/services?q=(_HOSTOFICINA = 0554) -> Doesn't work. And _HOSTOFICINA shows up with http://127.0.0.1/thruk/r/services

http://127.0.0.1/thruk/r/host?q=(_OFICINA >=  "0554") <- Just curious because first I wrote a test like this and it showed up with also values greater than 0554. Isn't there a way to force the logical operator as contains in list context discriminating string and not numerical?

**Comment by sni** [comment]
it gets tricky with url encoding when not using the equal operator. Have a look at: https://thruk.org/documentation/rest.html#_filtering to see some examples. If you use `key>=value` unencoded in the url, it will result in this filter: `"key>" == value`. You can workaround by either using the named operator like:
```
curl -gk 'http://127.0.0.1/thruk/r/services?_OFICINA[gte]=554'
```

or the generic query parameter:
```
curl -d 'q=***_OFICINA >= 554***' 'http://127.0.0.1/thruk/r/services'
```

If OFICINA is a variable from the host object, you can filter by HOSTOFICINA like you already did.
