### ISSUE TITLE
JSON Exporting fails after adding second backend

### ISSUE THREAD

**Issue by dan-m-joh** [sni/Thruk#895]
**Describe the bug**
If I add a second Backend (that does not have the "SLA"-Servicegroup defined) the following JSON-query fails:
https://nagiostest/thruk/cgi-bin/avail.cgi?servicegroup=SLA&timeperiod=24x7&pttimeperiod=thismonth&view_mode=json

If remove the second Backend again it works like it should.

This is what I see in the thruk-log:
```
[2019/01/03 11:49:11][nagiostest][ERROR] Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Avail.pm line 736.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Avail.pm line 736.
Use of uninitialized value in string eq at /usr/share/thruk/lib/Thruk/Utils/Avail.pm line 736.
```
(the last two lines repeats about 40 times)

If I add a (empty) "SLA"-Servicegroup on the second backend, I get the following in the thruk.log instead:
```
[2019/01/03 13:09:45][nagiostest][ERROR] Use of uninitialized value in subroutine entry at /usr/share/thruk/lib/Thruk/Utils.pm line 1112.
Use of uninitialized value in subroutine entry at /usr/share/thruk/lib/Thruk/Utils.pm line 1113.
Use of uninitialized value in subroutine entry at /usr/share/thruk/lib/Thruk/Utils.pm line 1113.
ERROR: perl eval failed:Date::Calc::Mktime(): date out of range at /usr/share/thruk/lib/Thruk/Utils.pm line 1113.
```

**Thruk Version**
Nagios Core 4.3.4
Thruk 2.26-2

**To Reproduce**
1. Add second backend (without a "SLA"-Servicegroup)
2. Open the URL in a Browser
3. This results in: "Background Job Failed background job failed, look at your logfile for details"

**Expected behavior**
I expect to get the same JSON-responce as I get with only one backend (the one that has a "SLA"-Servicegroup) in all three cases:
- Only one backed with SLA group
- No "SLA" group defined on the second backend
- An empty "SLA" group on the second backend

**Desktop (please complete the following information):**
 - Browser Firefox / curl
 - Version 60.4.0esr / 7.29.0

Regards,
-- 
Dan

**Comment by sni** [comment]
i cannot reproduce this with the current development version, so i assume this is fixed already. Could you try the daily by chance? Otherwise, please reopen the issue if it still persists with the next release.
