### ISSUE TITLE
MAP ISSUE

### ISSUE THREAD

**Issue by Plinio16** [sni/Thruk#896]
Panorama VIEW (OSM) dont load in Thruk, even in https://demo.thruk.org/demo/thruk/cgi-bin/panorama.cgi

Please help!!!

**Comment by sni** [comment]
should be fine again.

**Comment by Plinio16** [comment]
Thanks a lot,

what was it?

Also, there are wear lines over the map, could you check?

**Comment by sni** [comment]
i just restarted the mapproxy on maps.thruk.org. I also update mapproxy to latest 1.11 which seem so remove the dark lines as well.
