### ISSUE TITLE
Apache VirtualHost directive showing login pop-up

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#898]
When you configure Thruk Apache as a vhost with the VirtualHost directive it looses the default login form and shows a login pop-up. After logging in Thruk it neither shows a logout option. Anything else is working.

**Comment by sni** [comment]
Rewrite Rules are not inherited into virtualhosts by default, you have to include the cookie auth rules, for example like here:
https://thruk.org/documentation/faq.html#enable-https-tls-ssl-in-apache-webserver-for-thruk
