### ISSUE TITLE
Panorama View Show Details (Filter Backends Not Workig

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#899]
Hi.

We found a little thing which is now not working after upgrading to v2.20-2 to v2.26-2.

From panorama view we could before with “Show Details” on an Icon open the thruk interface with the same filter setting.

![image](https://user-images.githubusercontent.com/12998432/50966506-135c8000-1510-11e9-936b-43f82d359864.png)

now the filter is still there but all Backend Servers are activated and I can’t disable one 

![image](https://user-images.githubusercontent.com/12998432/50966523-22433280-1510-11e9-862f-42342a4de54a.png)

Locks like the system lose the “Backends / Sites” setting from the Icon settings

here's the general setting of our panorama view. we specified 3 backend sites, but when we right click the view and selects show details, it will still show all backends.  

![image](https://user-images.githubusercontent.com/12998432/50966733-e3fa4300-1510-11e9-822a-0e1653c9ab1b.png)

**Comment by sni** [comment]
thanks, should be better with the next release
