### ISSUE TITLE
Config Tool issue ->waiting for core reload failed

### ISSUE THREAD

**Issue by mgadi** [sni/Thruk#900]
Hi,

**Ubuntu 18.04**
**Thruk from 2.20 to 2.26**
**naemon from 1.0.7 to 1.0.9**

i'm getting this error using Thruk ; When i try to reload naemon aftrer create/modify an host/service/command/hostgroup/contact/contactgroup with Config Tool, i obtain the issue (and in thruk.log) :

_config reloaded by external command. Warning: waiting for core reload failed._

There's no error with the command line
/etc/init.d/naemon configtest

Total Warnings: 0
Total Errors: 0

So I have to change the cfg file permissions on the folder located in /etc/naemon/conf.d from 660 to 664. 
Then : 
`sudo systemctl stop npcd` 
`sudo systemctl stop apache2`
`sudo systemctl stop snmpd`
`sudo systemctl stop snmptrapd`

And: 

`sudo systemctl start apache2`
`sudo systemctl start npcd`
`sudo systemctl start naemon`
`sudo systemctl start snmpd`
`systemctl start snmptrapd`

**Comment by sni** [comment]
is `/etc/init.d/naemon configtest` really your reload command? If so, no wonder thruk runs into a timeout when waiting for the core to reload. This command only runs the config check.
