### ISSUE TITLE
Cannot get glob (*) working in show_custom_vars for custom columns

### ISSUE THREAD

**Issue by russoisraeli** [sni/Thruk#903]
1) When either of the following is set (or a combination):

show_custom_vars=_*
show_custom_vars=_HOST*
show_custom_vars=_SOMEVAR*

The custom variables that should be matched by the glob (*) do not appear in the dropdown for column selection (to display on the dashboard) in either host detail or service detail view

2) Setting show_custom_vars to explicit _VARNAME works.

3) Setting a mixture, e.g.

show_custom_vars = _VARNAME, _OTHERVAR*

will allow selecting _VARNAME, but none of the _OTHERVAR

4) glob (*) works when using it as a Custom Variable for a filter, so in case 3) _OTHERVAR's will show up for the filter

-- Thruk 2.26-2, Naemon 1.0.9 installed from the official repo, as an RPM package for RHEL7

Example host definition with custom variables:

define host {
             host_name mon204l
             alias mon204l.domain
             address 10.6.55.54
             _IP_MAC1 10.6.55.54 <=> 0:50:56:93:66:68
             _SUBNET1 some subnet name
             _department Some department, other dept
             _building New South
             _room MR, VM, -
             _date_created 2016-01-27
             _date_changed 2016-02-17
              contacts Name
             _contacts email1@email.com, email2@email.com
             use UNIX Production NS EISFW
}

Example show_custom_vars:
_BUILDING, _CONTACTS, _DEPARTMENT, _ROOM, _SUBNET*, _*

-- It's expected for the glob specified variables to appear for selection of columns, as per documentation.
In the example host above _SUBNET1 is not available in the column selection, while _BUILDING, _CONTACTS, _DEPARTMENT, and _ROOM are. None of the other custom variables are available.

-- Firefox 64.0.2 on Windows 10

**Comment by sni** [comment]
Should be better with the next release, please reopen the issue if its still not working.
