### ISSUE TITLE
Thruk shows empty config

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sni/Thruk#904]
**Describe the bug**

**Thruk Version**
OMD - Open Monitoring Distribution Version 2.90-labs-edition

**To Reproduce**
Migrated to latest OMD version.
I used before Shinken+Thruk.
Now naemon+Thruk as Shinken is unavailable.

1. Use default nagios core: naemon
2. naemon detects lots of services and hosts
3. Thruk shows empty config: no host, no service

**Expected behavior**
See all configured nagios objects
By looking at the naemon logs, all objects are detected.
Thruk shows no meaningful message at `var/log/thruk.log`.

**Screenshots**
![image](https://user-images.githubusercontent.com/6008104/52201109-ccda1700-286a-11e9-82b7-778cf9b69a10.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version latest

**Additional context**
Related [serverfault question](https://serverfault.com/questions/952199/omd-thruk-doesnt-detect-nagios-config)

**Comment by StefThomas** [comment]
On the serverfault post OP replied he had to edit ~/etc/thruk/cgi.cfg to set:

`authorized_for_admin=myuser`

to fix his problem. So this issue should be closed IMHO.

**Comment by DavidPerezIngeniero** [comment]
Thanks!
