### ISSUE TITLE
Backend behind proxy

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#906]
This isn't a bug. It's a question about the settings selecting http as backend.

In the backend configuration for http there is a proxy parameter. Is this parameter valid in a scenario where you have a Thruk site behind the corporate network?

The Thruk site behind the corporate network isn't reachable from inside the corporate network. Want to know if it would be reachable putting in the settings a proxy. And if this could be done beside the destination, ports 80 and 443 need to be allowed in the proxy, are there more ports who need to be allowed?

What about the queries to the REST API from the hosts and services in the Thruk site behind the corporate network? Are the http setting valid also for the REST API?

Thanks in advance.

Jorge.

**Comment by sni** [comment]
The proxy option simply enables using a proxy solely for the connection from the central thruk to the backend thruk. So if your setup looks like
`[central thruk] -> http -> [backend thruk] -> livestatus -> [naemon]`
then enabling the proxy would simply change that to:
`[central thruk] -> http over proxy -> [backend thruk] -> livestatus -> [naemon]`
