### ISSUE TITLE
Invalid requests headers

### ISSUE THREAD

**Issue by StefThomas** [sni/Thruk#907]
**Describe the bug**
Can’t display many pages. I have errors of this kind (on table services or hosts) :

`Core: ERROR: 400: The request contains an invalid header. - Table 'services' has no column 'depends_exec' (/var/cache/naemon/live)`

**Thruk Version**
Thruk Version 2.27~20190222
Nameon-Livestatus : 1.0.9.gd4664e2.20190110

**Expected behavior**
Valid requests

**Additional context**
I did not installed omd but thruk-base, naemon-core, naemon-livestatus and nginx.

I realize I’m using the testing version of both Thruk and Livestatus. I’ll try with stable versions but I let this issue open

OS is Debian Stretch.

**Comment by StefThomas** [comment]
Well, no bug with the stable versions (2.26 & 1.0.9). Guess you may close the issue as it concerns testing versions?

**Comment by sni** [comment]
thanks for your report. There was an issue in yesterdays dev-tree indeed. It is fixed meanwhile with e09da9140.
Reporting issues for testing versions is totally fine. I usually only push working things.
