### ISSUE TITLE
Charset issue

### ISSUE THREAD

**Issue by StefThomas** [sni/Thruk#908]
Hi,

In the tactical overview, there is a charset issue in the date (on the é of the word fév.) :

![capture d ecran_2019-02-23_19-34-22](https://user-images.githubusercontent.com/38944475/53290289-25ce0880-37a2-11e9-85cc-35c884e3cdac.png)

Thruk version 2.26 (packaged stable version)

I don’t have charset issue in the plugin output, only in the date here.

I prefer to report this bug now, at least someone could lead me in the right direction to fix this. This is the kind of problem that has to be fixed before to go further…

My users and I except an UI in french with no charset issue.

I use Debian, Firefox 60.5.1.

I can’t select another charset to use in Firefox because my server specify utf8 as charset (what I find acceptable, I want to use utf8). Thruk is run as a uwsgi application as user www-data which has its locale at fr_FR.UTF-8

If I’m not mistaken, although UTF-8 is a defacto standard nowadays, the standard for HTTP still is ISO-8859-1, so I suspect the content is displayed with this charset (instead of expected UTF-8).

If I login as www-data (the user which runs both the uwsgi/psgi app and the web server) the date command produce UTF-8 :

```
$ date > /tmp/toto
$ file /tmp/toto
/tmp/toto: UTF-8 Unicode text
```

I will also test Thruk on CentOS 7 in parallel with this test on Debian 9. I will be able to tell how it is on this other OS, probably on monday.

**Comment by sni** [comment]
Should be better now. However dates are not localized everywhere, the date picker uses english dates for example.
