### ISSUE TITLE
ConfigTool with two backends

### ISSUE THREAD

**Issue by StefThomas** [sni/Thruk#910]
The configuration tool always write the configuration to the directory specify for the first backend, whatever backend is selected in Thruk.

Thruk 2.26-2

This is how my backends are configured:

```
<Component Thruk::Backend>
    <peer>
        name    = Core
        id      = 7215e
        type    = livestatus
        <options>
            peer          = /var/cache/naemon/live
        </options>
        <configtool>
            core_conf      = /etc/naemon/naemon.cfg
            obj_check_cmd  = /usr/bin/naemon -v /etc/naemon/naemon.cfg
            obj_reload_cmd = /etc/init.d/naemon reload
        </configtool>
    </peer>
</Component>
<Component Thruk::Backend>
    <peer>
        name    = poller1
        id      = 7215e
        type    = livestatus
        <options>
            peer          = tls://192.168.122.114:6557
            cert          = /etc/nginx/ssl/thruk.nanshe.crt
            key           = /etc/nginx/ssl/thruk.nanshe.key
            ca_file       = /etc/nginx/ssl/thruk.nanshe.crt
            verify        = 2
        </options>
        <configtool>
            core_conf      = /etc/naemon-poller1/naemon.cfg
            obj_check_cmd  = /usr/bin/naemon -v /etc/naemon-poller1/naemon.cfg
            obj_reload_cmd = 
        </configtool>
    </peer>
</Component>
```
My initial goal was to have the path for the remote backend’s configuration being a remote FS mounted on my Thruk server. I expected to be able to keep the configuration split across the different backends, while being able to modify it in one place in Thruk… As I didn’t manage it to get it working, I get back to a simple local directory. I could later find a way to push the files onto my remote poller, this is not my problem now.

Now it keeps editing /etc/naemon/ , I cannot manage to write in /etc/naemon-poller1. I thought selecting a backend or another with the upper left buttons would permit me to configure one backend or the other… both having different path.

Firefox/Debian 9 - Nginx

I really like the way Thruk may monitor many remote (TLS) livestatus. It kind of makes using NSCA and passive checks useless to transmit check status… And even if it’s not a load-balanced solution, one can manually spread hosts across different remote pollers. Sadly I guess that with this setup, notifications also are being sent from all the pollers…

What about the graphics ? I configured PNP4Nagios on my central Thruk server and I can see that only the services on the central have a graphic… Services from the second, remote backend have not. Do I have to install PNP4Nagios, with a webserver, for the second backend too ? Do I have to keep one backend with every service configured as passive ones, just to handle perfdata ? What would you do ?

If this setup is not a good idea I guess I have the choice in between :
 - Install Thruk/uwsgi/nginx on every pollers, and use their HTTP Thruk backend ? It seems too much…
 - Use mod_gearman with the job server on the same host than the thruk server, or another host with TLS Livestatus.

**Comment by sni** [comment]
You can simply test if the correctness of the config file location by opening the "Browse filesystem" from the config tool. Thruk simply parses the `/etc/naemon-poller1/naemon.cfg` so if that file also contains a reference to `conf_folder /etc/naemon` then that is used.
Distributed monitoring comes in many flavors and each has its own advantages and disadvantages. From my personal preference i would install `OMD-Labs` on each Poller and the central node and connect them by https. OMD removes the installation burden and you get graphing out of the box on each node.

**Comment by StefThomas** [comment]
OK I get it… thanks.

>From my personal preference i would install OMD-Labs on each Poller and the central node and connect them by https.

I like to understand how it works and I have a preference for Nginx as a webserver. That’s why I first tried “simple” setup with naemon-core alone, then with TLS livestatus, etc…

But I’ll try the omd package for sure! And many thx for the fix of the encoding issue…

The last time I tested Thruk was something like four years back… I just tested it now and I’m very pleasantly surprised by the good quality of the UI. The panorama view and all its customization functionalities are very interesting and it’s particularly responsive for a webapp. Félicitations pour le travail accompli !

**Comment by sni** [comment]
you are welcome. OMD still uses apache and it would be quite some work to get that ported to nginx. However, OMD uses a site-apache for each user (instance) and the system apache on 80/443 just uses mod-proxy to connect to the site apaches. It should be easy to replace the system apache with nginx. But i would keep the site apache.
