### ISSUE TITLE
500: Can't connect to serverA:443 (certificate verify failed) (https://serverA/poller1)

### ISSUE THREAD

**Issue by StefThomas** [sni/Thruk#912]
Can’t add a second (HTTP) backend.

Thruk 2.26-2, installed from the omd-labs package from Consol.

Try to add another http backend and it fails on host key verification. I tried to add _verify = 0_ manually in _etc/thruk/thruck_local.conf_ but it results in the same error. I also tried to specify cert = and key = with the cert and key of the remote backend (etc/apache/site.cert and etc/apache/site.key)… Any help would appreciated.

In the log I have the following error, I don’t know if it’s related:

`[Fri Mar 01 20:57:26.912455 2019] [ssl:warn] [pid 20654] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name`

I, also, do have a question regarding mod_gearman. It requires that the path to the plugins to be the same as the one configured in naemon, on every workers, so they can find them.

I didn’t use the same name for both sites (should I?), one being my job server and the other being the worker. I guess I could simply make a symbolic link on my worker(s) but I wonder if there is any better and advised thing to do.

**Comment by sni** [comment]
the general option is `ssl_verify_hostnames=0` to disable all kind of host verifications. The key/cert options in the backend are only used for tls livestatus connection, not for https. But that might be an
interesting idea for the future.

**Comment by StefThomas** [comment]
>The key/cert options in the backend are only used for tls livestatus connection, not for https

I’m very surprised because when I tested this (and had the bug) I’ve had only configured an https backend, not any livestatus one… The message about the failed verification was visibly about the https backend… I should have screenshoted it.

Sadly I had to remove the test I made installing omd-labs-edition, so I can’t test the option you gave. I’ll remember it for a next test though…Where can I find any documentation where those options are described ?

I went back to a “brick by brick” setup, mostly for educational purpose. It’s working fine with Naemon+Nginx+PNP4Nagios+Thruk+Gearman and a remote Gearman worker. That’s not really a distributed setup, the configuration is centralized and there is only one monitoring engine, but I can add one or more worker if it’s needed, it fills my needs. The only problem I had was about packaging (on Debian 9). I had to temporarily install omd-labs-edition to get the file __libgearman.so.6__ … The gearman module is linked against this library but only __libgearman.so.7__ and __libgearman.so.8__ were available…

I should test to reproduce this setup on CentOS 7 as soon as tomorrow. If I encounter such the same bug I’ll report it. Closing this one as I cannot manage to test proposed workaround.

**Comment by StefThomas** [comment]
I reopen the issue because I have the same error message with a clean install of omd-labs-edition on CentOS 7

![image](https://user-images.githubusercontent.com/38944475/53965923-60b13400-40f2-11e9-8201-e7ff056beb00.png)

I just created one site "test" on a host and another site "test2" on another host, then tried to add the backend test2 on test’s Thruk instance using Thruk GUI.

The generated Thruk config file has no key/cert parameters at all :

```
    <peer>
	name    = test2
        id	= 5eb67
        type    = http
        <options>
            peer          = https://sup37poc3/test2
            auth          = a33bd17a19a29c27791fafcf6acf9983
        </options>
    </peer>
```

I added _ssl_verify_hostnames = 0_ (inside `<options></options>`) but the same error remains with this option.

**Comment by StefThomas** [comment]
The hostname I used is a DNS alias but I also tried with the FQDN or the IP and it gives the same result. I also tried to put the _ssl_verify_hostnames = 0_ outside of `<options></options>`…

**Comment by sni** [comment]
`ssl_verify_hostnames = 0` has to go directly in the thruk_local.conf, not into any block. Also i cannot reproduce this issue. Can you try the latest nightly?

**Comment by StefThomas** [comment]
Tested with omd-labs-edition-daily on both sites. Worked fine.

![image](https://user-images.githubusercontent.com/38944475/55039030-f3bef900-5022-11e9-9e7a-f0018cfe085a.png)

**Comment by sni** [comment]
great, thanks for testing.
