### ISSUE TITLE
REST API: Can't use string as an ARRAY ref

### ISSUE THREAD

**Issue by nmalacarne** [sni/Thruk#913]
**Describe the bug**
Unable to update host configs with any attribute that is an array (contacts, groups, etc) via the API. When using the `POST /hosts/<name>/config` endpoint, I receive a 500 error with the following message:  `"description" : "Can't use string (\"TEST_CONTACT\") as an ARRAY ref while \"strict refs\" in use at /omd/sites/demo/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 137.\n",`.

**Thruk Version**
2.26-2 - OMD 2.90-labs-edition

**To Reproduce**
1. Sent POST request to `thruk/r/config/objects?:FILE=TEST-HOST.cfg&:TYPE=host` with json payload:
```
{
	"host_name": "TEST_HOST",
	"alias": "TESTING",
	"address": "1.1.1.1",
	"max_check_attempts": 5,
	"contacts": "TEST-CONTACT",
	"check_command": "check-host-alive",
	"check_interval": "20",
	"retry_interval": "1",
	"check_period": "24x7",
	"notification_interval": "5",
	"notification_period": "24x7",
	"active_checks_enabled": 0,
	"passive_checks_enabled": 1,
	"process_perf_data": 1
}
```

**Expected behavior**
Expected the host config file to be created with the correct contacts associated

**Screenshots**
![image](https://user-images.githubusercontent.com/2746307/53806568-483af100-3f1b-11e9-9217-403f57b6a4bc.png)
![image](https://user-images.githubusercontent.com/2746307/53806585-52f58600-3f1b-11e9-9dc0-cb3a101444f9.png)

Attempting to 'view diff' of config files:
![image](https://user-images.githubusercontent.com/2746307/53806611-630d6580-3f1b-11e9-8abf-fb4c936794ac.png)

**Desktop (please complete the following information):**

**Additional context**
```
Url:        conf.cgi
Browser:    
Version:    2.26-2 / OMD OMD 2.90-labs-edition
Release:    December 18, 2018Backends:   State / Program Version / Data Source Version
            0 / 1.0.9 / Livestatus 1.0.9-naemon

uname:      Linux staging.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64
release:    CentOS Linux release 7.6.1810 (Core)

Stacktrace:
Can't use string ("TEST-CONTACT") as an ARRAY ref while "strict refs" in use at /omd/sites/demo/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 137.

 at /omd/sites/demo/share/thruk/lib/Thruk.pm line 349.
	Thruk::_dispatcher('HASH(0x503a5a0)') called at /omd/sites/demo/lib/perl5/lib/perl5/Plack/Util.pm line 145
	eval {...} called at /omd/sites/demo/lib/perl5/lib/perl5/Plack/Util.pm line 145
	Plack::Util::run_app('CODE(0x29faed8)', 'HASH(0x503a5a0)') called at /omd/sites/demo/lib/perl5/lib/perl5/Plack/Handler/FCGI.pm line 147
	Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x1fadc90)', 'CODE(0x29faed8)') called at /omd/sites/demo/share/thruk/script/thruk_fastcgi.pl line 27
```

**Comment by nmalacarne** [comment]
Adding the contacts manually in the config and applying configuration seems to work OK. I am not sure what I am doing wrong via the API, however.

**Comment by sni** [comment]
have you tried `"contacts": ["TEST-CONTACT"],`? contacts is a list.

**Comment by nmalacarne** [comment]
Hey @sni, thanks for the response. I did try the `["TEST-CONTACT"]` format, but it still results in the same error. I am not that familiar with Perl .. but from what I can tell its parsing a comma separated string as an array [here](https://github.com/sni/Thruk/blob/master/plugins/plugins-available/conf/lib/Monitoring/Config/Object/Parent.pm#L60), but when it hits [here](https://github.com/sni/Thruk/blob/master/plugins/plugins-available/conf/lib/Monitoring/Config/Object/Parent.pm#L137) `$self->{'conf'}->{$attr}` is still a string and not a list.

Any ideas?

**Comment by sni** [comment]
i tried to reproduce this and it works if you send contacts as a list like this:
`"contacts": ["TEST-CONTACT"]`

Anyway, the rest api now supports strings as well and will split the string automatically if the attribute expects a list.

**Comment by nmalacarne** [comment]
@sni Thanks for your help :+1:

**Comment by loguido** [comment]
Hi, i have the same problem defining new hosts (can't use a string as an array). Is it  possible to have a complete example of an host creation ? thanks
