### ISSUE TITLE
Thruk Config tool: support regexp in object definitions

### ISSUE THREAD

**Issue by M4rotte** [sni/Thruk#914]
Naemon Core, and others, supports using regexp in object definition, if using the option __use_regexp_matching=1__. Thruk doesn’t understand such object definitions and reports a reference error.

![image](https://user-images.githubusercontent.com/6515724/53986385-5a38b180-411e-11e9-842b-945f6475f396.png)

I’d like at least that it’s not reported as an error. Would be nice if it also checks regexp syntax, and even nicer if it gives all the matching hosts that the regexp in the definition matches…

I considered no alternative as just ignoring the warning is fine. The only drawback, except of the bad image it gives of the software to a non technical user, is that it could lead to miss some legit warnings, because of the noise.

Thruk Config tool is very nice and ergonomic globally, I like it a lot! 

Yeah, I have an IP as part of the hostname… My laptop uses a different address according to the network interface it uses, so I created two hosts in Naemon, this is only a test setup…

**Comment by sni** [comment]
Thats not easily possible. The config tool barely supports wildcards so far. Only a single `*` is supported.
