### ISSUE TITLE
host downtime should show all services in downtime on that host

### ISSUE THREAD

**Issue by mcasviper** [sni/Thruk#915]
**Is your feature request related to a problem? Please describe.**
now a host downtime only sets the host in downtime not the services on that host.

**Describe the solution you'd like**
all services on a hosts should be shown as in downtime if the host is in downtime.

**Describe alternatives you've considered**
perhaps the host downtime state is shown at the service. 

**Additional context**

**Comment by sni** [comment]
Thinking about it, at least in Icinga2 this is apparently not the case and host downtimes seems to not affect services. But no idea if this is intentional or a bug.
