### ISSUE TITLE
500 Internal server error Can't use string (\"linux-host\") as an ARRAY ref while \"strict refs\" in use at /omd/sites/QA_test/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 137.\n"

### ISSUE THREAD

**Issue by loguido** [sni/Thruk#920]
**Describe the bug**
Trying to define a new host i receive "Can't use string (\"linux-host\") as an ARRAY ref while \"strict refs\" in use at /omd/sites/QA_test/etc/thruk/plugins-enabled/conf/lib/Monitoring/Config/Object/Parent.pm line 137.\n"" and a 500 server internal error.

**Thruk Version**
omd-2.90-labs-edition-el7-47.x86_64
thruk 2.26-2

**To Reproduce**

POST 
http://omdadmin:xxx@qa-xxxx.qa.xxxx.intra:5001/QA_test/thruk/r/config/objects?:TYPE=host&:FILE=sre_hosts.cfg&host_name=test_host&use=linux-host&contacts=TEST-CONTACT

POST
http://omdadmin:xxxxxx@qa-xxxxxxx.qa.xxxxxx.intra:5001/QA_test/thruk/r/config/objects?:TYPE=host&:FILE=sre_hosts.cfg&host_name=test_host&use=["linux-host"]&contacts=["TEST-CONTACT"]

**Expected behavior**
The craetion of the host object

**Screenshots**
<img width="987" alt="Screen Shot 2019-03-27 at 10 21 57" src="https://user-images.githubusercontent.com/22444213/55064430-424bb200-507a-11e9-9dc9-ffd9852f03fb.png">

**Desktop (please complete the following information):**
--

**Additional context**
--

**Comment by sni** [comment]
see #913 
This has been fixed meanwhile, you can either try the nightly or wait for the next release.
