### ISSUE TITLE
Search field not listing hosts with an underscore in name

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#921]
**Describe the bug**
Search field is not listing hosts with an underscore in the name like "DS_" or "ES_" etc.
Hostgroups are still listed

**Thruk Version**
Thruk 2.27-20190326 
2.91.20190326-labs-edition

**To Reproduce**
1. Go main search field in the navigation
2. Search for any host with an underscore

**Expected behavior**
List of expected hosts :)

**Desktop (please complete the following information):**
 -  Browser: Chrome 73

**Comment by sni** [comment]
i cannot reproduce that. Is there anything else in those hostnames?

**Comment by kafos** [comment]
nothing special, is thruk maybe just able to list max 500 host-items?
we have about 700 hosts starting with DP_, but in the list thruk is saying "500 hosts"

**Comment by sni** [comment]
ah right, there is a new limit. If more than 500 results were found you need to be more specific. Or combine multiple search strings with spaces. However, i will try to make it more visible that there was a limit hit here.

**Comment by kafos** [comment]
problem seems to be, that thruk is only processing the first 500 hosts sorted alphabetically and has nothing to do with an underscore, how mentionend before.

After a couple of tests the search bar is listing for example 171 hosts starting with "CE-" and after removing and typing something like "DP_", I get 329 hosts for that.

Other hosts beginning with "TS" or "LS" are not listed

**Comment by sni** [comment]
right, but if you continue typing, it should be filtered further till you get the host you want
