### ISSUE TITLE
Add  as suggestion a custom variable inside the search box

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#922]
A question or a feature request:

Would it possible inside the configuration (snippet I paste below) to add as a suggestion a custom variable?

I think what's allready in the configuration are the only possible options.

######################################
# use ajax search
use_ajax_search           = 1  # enable ajax search
ajax_search_hosts         = 1  # suggest hosts while typing
ajax_search_hostgroups    = 1  # suggest hostgroups while typing
ajax_search_services      = 1  # suggest services while typing (can be slow which large amount of services)
ajax_search_servicegroups = 1  # suggest servicegroups while typing
ajax_search_timeperiods   = 1  # suggest timeperiods while typing

Thanks,
Jorge.

**Comment by sni** [comment]
that section has been removed with the next release and it will just be enabled. Custom variables should be listed in the search drop down when you have sufficient permissions.
