### ISSUE TITLE
DOM-based Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by mnikhil-git** [sni/Thruk#924]
**Describe the bug**
We ran a quick security scan against thruk served by Apache2/mod_fcgi and found couple of XSS related issues.

**Thruk Version**
Thruk version: 2.28
Apache2: 2.4.18-2ubuntu3.9

**To Reproduce**
1. Download and install Arachni
2. Run Arachni on the installed system
3. XSS scans show there are possible vulnerabilities with login.cgi

When I looked at login.tt there was nothing explicit but I am not an expert in XSS / Web security.

I can provide more context and details upon touch base.

Thanks.

**Comment by sni** [comment]
so what did you find? If you need to send confidential information, use e-mail: bugs@thruk.org

**Comment by sni** [comment]
issues have been addressed.
