### ISSUE TITLE
Config tool breaks multiple hostgroups

### ISSUE THREAD

**Issue by bakercr17** [sni/Thruk#925]
**Describe the bug**
If a host definition requires to be in multiple hostgroups the config tool will quote the comma as such "hostgroup1','hostgroup2','hostgroup3". Prior to 2.28 this did not cause issues however now the config test will fail and the daemon will not reload properly. If I vim the config file and do a global search and replace of ',' with just a comma the daemon will reload properly. However, the config tool will attempt to revert back to ',' whenever another change is attempted and once again the config test will fail.

**Thruk Version**
2.28

**To Reproduce**
1) Have host definitions with multiple hostgroups.
2) Make a change and reload the config.

**Expected behavior**
The reload should finish with no error.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Firefox 60.6.0esr (64-bit)

**Comment by sni** [comment]
I was able to reproduce this with a fresh installation. While still investigating whats the best way to fix this, there is a quick workaround by simply removing the quotes in `/etc/thruk/naglint.conf`:
```
# should list attributes be joined with space or not
list_join_string        = ,
```

**Comment by bakercr17** [comment]
Thank you, indeed that does solve the issue.
