### ISSUE TITLE
view Check Command/Expanded Command

### ISSUE THREAD

**Issue by xeroy** [sni/Thruk#926]
**Describe the bug**
Before the 2.26 version, i was able to see only my hosts and have access to config tool and view " Check Command/Expanded Command" by setting my contact_group to authorized_contactgroup_for_configuration_information variable
Since 2.26, if i let my contact_group in authorized_contactgroup_for_configuration_information, i see all the hosts.
                if i remove my contact group from authorized_contactgroup_for_configuration_information i see only my hosts but i have no access to config tool and don't see "Check Command/Expanded Command"

How can i manage to see only my hosts by having access to config tools and" view Check Command/Expanded Command"

**Thruk Version**
>=2.26

**Comment by sni** [comment]
I don't get it. If you remove the `authorized_for_configuration_information` role, you cannot see configuration information. That's how it should be.
However there is a setting to always show the expanded command, even when you don't have this role, see:
http://thruk.org/documentation/configuration.html#show_full_commandline

**Comment by xeroy** [comment]
Hello,
I agree why you, i need authorized_for_configuration_information  role.
But with this role , i see all the hosts not only the host to my contact

**Comment by sni** [comment]
thing is, `authorized_for_configuration_information` in combination with the `authorized_for_system_commands` role gives you admin permissions and therefor all other roles.
You can get details about your roles and groups in the users profile (top right button or at /thruk/cgi-bin/user.cgi)
