### ISSUE TITLE
schedule_svc_downtime with multiple backends

### ISSUE THREAD

**Issue by bouvs** [sni/Thruk#927]
Hi,

This Thruk instance have multiple backends (livestatus).
When scheduling downtime through API, we obtain an error 500 with the following description:

"Undefined subroutine &Thruk::Controller::cmd::_get_affected_backends called at /usr/share/thruk/lib/Thruk/Controller/Rest/V1/cmd.pm line 123, <DATA> line 1081.\n"

I also tried with CLI and i obtain the same error.

Finally, i've tried on another Thruk instance which have only one backend (livestatus) and i didn't obtain error.

API/CLI seems to not be compatible with multiple backends.

We are using Thruk Version 2.26~2.

**Comment by sni** [comment]
found the issue or does it work with the last release?

**Comment by bouvs** [comment]
Hi,

Finally i've found we have a problem with loading of cmd module. My apologies...

Maybe you could add in HTTP Methods documentation that the backend can be set like this: 

http://your_webserver/thruk/r/services/<host>/<svc>/cmd/schedule_svc_downtime**?backends=<backen id>**.
