### ISSUE TITLE
MobileVersion

### ISSUE THREAD

**Issue by luban8** [sni/Thruk#928]
**Describe the bug**
Brokem mobile version

**Thruk Version**
v3.0

**To Reproduce**
View mobile version (mobile.cgi) either on desktop OS or mobile OS.

**Expected behavior**
functional page of the mobile version

**Screenshots**
http://tinypic.com/r/10qymno/9
![Screenshot_20190405-151156](https://user-images.githubusercontent.com/44843692/55706716-2f25d400-59e2-11e9-9d8b-be08aa9d99c4.png)

**Desktop (please complete the following information):**
Android 9 - Firefox, Chrome
IOS 12.01- Safari
W10 1709 - Firox, Chrome

**Additional context**
N/A

**Comment by sni** [comment]
fixed with https://github.com/sni/Thruk/commit/4e1f59799a026046d99508904c9985ed3ed48b72
thanks
