### ISSUE TITLE
some hosts don't show up in ajax search

### ISSUE THREAD

**Issue by r-lindner** [sni/Thruk#929]
**Describe the bug**
the new ajax search shows only some hosts
**Thruk Version**
2.28 Deb

**To Reproduce**
1. Use a Nagios-Config with >500 hosts
2. Enter a search term in the search input box
3. only some hosts (e.g. starting with A-M) are listed and not all hosts (e.g. starting with A-Z)

**Expected behavior**
All configured hosts should be searchable

**Additional context**
https://github.com/sni/Thruk/blob/master/root/thruk/javascript/thruk-2.28-1.js#L6050

**Comment by sni** [comment]
thanks, should be better with the next release.

**Comment by topinet** [comment]
I have a similar problem when searching for hosts and services.
With the last nightly build, the ajax search shows the error message "error: regex failed: SyntaxError: unterminated character class"

**Comment by sni** [comment]
what did you search for?

**Comment by topinet** [comment]
I've upgraded LMD and restarted Thruk and now all services appear in ajax search (some time after restarting)
