### ISSUE TITLE
Thruk Config tool: single quotes in template-listing

### ISSUE THREAD

**Issue by mgr42** [sni/Thruk#932]
Our env:
thruk 2.28
shinken 2.43
debian jessie (8.11)

Since 2.28, Thruk-Config-Tool changing coma-seperated list of templates to single-quoted coma. So shinken ignore the complete list of templates when restart shinken

config-diff-example:
 `-  use                            type-2, host-pnp, wiki_host_link, generic-host`
 `+  use                            type-2','host-pnp','wiki_host_link','generic-host`

**Comment by sni** [comment]
please see #925
