### ISSUE TITLE
Thruk 2.26-2 - Error when genereting "SLA Host" reports

### ISSUE THREAD

**Issue by antoniofacchi** [sni/Thruk#935]
**Describe the bug**
Hi Team,

I receive the attached error (**no such host**:...) when genereting a SLA Host report either manually or scheduled. What I understood the error is related to the "**groups**" parameter defined in thruk_local.conf configuration files, if I comment-out the "groups" parameter the reports working fine. 
I defined different groups becuase in production we have many backend and each group must see only its own backend.

**Thruk Version**
2.26-2

**To Reproduce**
1. Insert "groups" parameter in thruk_local.conf
2. Generte a SLA Host report
5. See error

**Expected behavior**
I expect to have the report

![thruk_error](https://user-images.githubusercontent.com/43602247/56967025-a7eefa80-6b60-11e9-8e3f-04059fccdc83.PNG)
![thruk_local](https://user-images.githubusercontent.com/43602247/56967026-a7eefa80-6b60-11e9-8b73-f7abb172602d.PNG)

**Comment by marcom29** [comment]
<configtool>
            core_conf      = /usr/local/nagios/etc/nagios.cfg
            obj_check_cmd  = /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
            obj_reload_cmd = service nagios restart
       </configtool>

**Comment by sni** [comment]
Maybe its easier to setup separate Thruk instances for each group. You can still create an "umbrella" Thruk for your admins with all backends.
