### ISSUE TITLE
thruk_fastcgi forks when using multiple backends

### ISSUE THREAD

**Issue by renard** [sni/Thruk#937]
**Describe the bug**

I use 2 monitoring instances in 2 different datacenter. Both of them have the other configured as a backend. Each instance monitors all machines within the local datacenter.

DC1 is my primary instance and DC2 is the fallback instance. A public VIP  (with is totally unrelated to the Thruk setup) is hold on a HAproxy load-balancer which routes the traffic to DC1 by default and DC2 as a fallback. The VIP is managed by BGP from one DC to the other. This is just to explain how the 2 instances work. The monitor interface is  https://monitor.example.com.

In datacenter1 (auth have been changed here for obvious reason but they match their local setting):
```
<Component Thruk::Backend>
    <peer>
        name    =  monitor01-dc1
        id      = c6aff
       type     = livestatus
       <options>
            peer          =  /var/cache/naemon/live
            resource_file = /etc/naemon/resource.cfg
            remote_name   = monitor01-dc1
       </options>
       <configtool>
            core_type = naemon
            core_conf =  /etc/naemon/naemon.cfg
            obj_check_cmd = sudo /etc/init.d/naemon configtest
            obj_reload_cmd = sudo /etc/init.d/naemon reload
       </configtool>
    </peer>
    <peer>
        name    =  monitor01-dc2
        id      = 7aeef
        type     = http
        <options>
            peer          = http://monitor01-dc2.example.com/thruk/
            auth          = 3a4714051e8697238b529a201ed4be6b
            remote_name   = monitor01-dc2
        </options>
    </peer>
</Component>
```
In datacenter2:
```
<Component Thruk::Backend>
  # Disable this peer to prevent from having /usr/share/thruk/script/thruk_fastcgi.pl forks on both nodes.
    <peer>
        name    =  monitor01-dc1
        id      = c6aff
        type     = http
        <options>
            peer          = http://monitor01-dc1.example.com/thruk/
            auth          = c3d086cccde7d644682592c2ad3bae63
            remote_name   = monitor01-dc1
        </options>
   </peer>
    <peer>
        name    =  monitor01-dc2
        id      = 7aeef
       type     = livestatus
       <options>
            peer          =  /var/cache/naemon/live
            resource_file = /etc/naemon/resource.cfg
            remote_name   = monitor01-dc2
       </options>
       <configtool>
            core_type = naemon
            core_conf =  /etc/naemon/naemon.cfg
            obj_check_cmd = sudo /etc/init.d/naemon configtest
            obj_reload_cmd = sudo /etc/init.d/naemon reload
       </configtool>
    </peer>
</Component>
```

With version 2.20 this setup worked like a charm (I just added the `remote_name` in when upgraded to 2.28). Each instance can directly see the other.

After an upgrade to version 2.28 I need to comment the `dc1` section in the datacenter2 otherwise the `/usr/share/thruk/script/thruk_fastcgi.pl` script forks many times and eats up all memory on both monitoring instances. This ends up with OOM killer and leads to the need of a server reboot.

This is behaviour looks like a loop exists DC1 is checking DC2 which also provide DC1 data, which connects to DC2, ... But I have to proof about that.

**Thruk Version**

Installation from Debian packages found on official Thruk repository

* libthruk 2.26
* thruk 2.28
* thruk-base 2.28
* naemon 1.0.10
* naemon-core 1.0.10
* naemon-livestatus 1.0.10
* naemon-thruk 1.0.10

**To Reproduce**
1. Configure 2 instances each one of them has the other as a backend.
2. restart apache2 and thruk
3. Wait
4. See many `/usr/share/thruk/script/thruk_fastcgi.pl` instances

**Expected behavior**
`/usr/share/thruk/script/thruk_fastcgi.pl` should not fork so many times

Did I missed something? Should I add/remove extra configuration parts to make this setup work like in the previous 2.20 version? Should I need to provide extra log information?

Thanks in advance.

**Comment by sni** [comment]
Thruk now shows all connected backends when from each connected http backend, which creates a circular loop here probably. However, this should only happen if no remote_name is set. If so, it should
just behave like before.
I have investigate this more in detail

**Comment by renard** [comment]
Ok.

The documentation is not pretty clear about what should be set as a `remote_name` thus I naively set the same as the `name` on remote side. It turns out that this is what Thruk expects.

On the other hand, `state_host` is not much clear about what should be set either.
 

If you want me to do deeper checks please feel free to ask. 

For the moment I can live with having DC2 not connected to DC1 since DC1 is my primary site which means that if traffic is routed to DC2 there is no chance to get DC1 data.
