### ISSUE TITLE
REST API seems not working

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#938]
Hi Sven,

the URL http://web_server_ip/thruk/r/ seems to be not working. Here are some of the details of my test:

thruk_local.conf
rest_api_enabled = 1

Thruk Version
libthruk-2.26-0.x86_64
thruk-plugin-reporting-2.28-1.x86_64
thruk-2.28-1.x86_64
thruk-base-2.28-1.x86_64

this is working
thruk r '/hosts?name[regex]=^DK-'

THIS IS NOT WORKING

[root@clonethrukp01 thruk]# curl -gk 'http://thrukadmin:password@10.0.102.162/thruk/r/hosts?name[regex]=^DK-'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /thruk/r/hosts was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at 10.0.102.162 Port 80</address>
</body></html>

**Comment by sni** [comment]
depending on how you installed thruk, you need to update the apache config with the .rpmnew file.

**Comment by jgbuenaventura** [comment]
Hi Sven,

Thanks for the prompt reply seems to be working, will make a few more tests, Thank you!
