### ISSUE TITLE
PanoramaView: host alias, hostgroup name/alias as macro for labels

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#941]
**Is your feature request related to a problem? Please describe.**
If we want to use the current host-alias hostgroup-name/alias as a label for the icons, it's currently only possible with host-name.

**Describe the solution you'd like**
be able to use macros for the above mentioned types in the label section like {{alias}}, {{groupname}} and {{groupalias}}

**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by sni** [comment]
fixed with next release.
