### ISSUE TITLE
PNP4Nagios iframe not shown

### ISSUE THREAD

**Issue by riskersen** [sni/Thruk#942]
**Describe the bug**
PNP4Nagios iframe not displayed in Chrome nor in IE

**Thruk Version**
2.30

**To Reproduce**
Open Service with Performance data available

**Expected behavior**
PNP4Nagios iframe should be displayed

**Desktop (please complete the following information):**
 - Chrome version 74.0.3729.131 (Offizieller Build) (64-Bit)
- IE11.2906

**Additional context**
`extinfo.cgi?type=2&host=foobar&service=Stats - HTTP Client Connections&backend=220b8:827 Uncaught SyntaxError: missing ) after argument list`

`<document.write('<iframe name="graph" id="graph" src="https://foobar.corp/pnp4nagios/index.php/graph?host=foobaresx1001&amp;amp;srv=Memory Usage&amp;amp;theme=smoothness' class='tips' rel='http://foobar.corp/pnp4nagios/index.php/popup?host=foobaresx1001&amp;amp;srv=Memory Usage" width="800" height="500" frameborder="0" style="overflow-x: hidden; overflow-y: scroll;"><\/iframe>');`

**Comment by sni** [comment]
could you try the fix from 4b30fa77bd4c52db0419547408dd61ba3f74f130. Besides that, is there a reason why you use the third party graph integration instead of the native pnp integration?

**Comment by riskersen** [comment]
What do you mean? Im using action urls following the documentation.

Regards
Oliver

Sven Nierlein <notifications@github.com> schrieb am Mi., 15. Mai 2019,
16:28:

**Comment by sni** [comment]
it is not neccessary to set the `graph_url` when using pnp with action urls, you just need to set `shown_inline_pnp=1` but i just noticed the documentation tells otherwise :)

**Comment by sni** [comment]
i updated the default config file and https://thruk.org/documentation/graphing.html#pnp4nagios

**Comment by riskersen** [comment]
Okay, so I double-checked the settings. show_inline_pnp was set to 0 for whatever reason in the thruk_local.conf. I've changed that to 1. However, the same issue is still present.

I'm not using graph_url, but action_url parameter.

After injecting the fix from https://github.com/sni/Thruk/commit/4b30fa77bd4c52db0419547408dd61ba3f74f130 the iframe is back and displayed correctly.
