### ISSUE TITLE
Randomly internal server error with URLs from reports with logcache enabled

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#943]
Thruk 2.26-2

With logcache enabled loading an URL like "History (Summary)" or "Event log" the server returns randomly an internal error.

The Apache error.log everytime this happens writes a message like this:

"ERROR: got signal TERM while handling request, possible timeout in http://XXXX.XXXX.XXX/thruk/cgi-bin/showlog.cgi
ERROR: User:       thrukadmin
ERROR: Address:    A.B.C.D
ERROR: Stacktrace:
 at /usr/share/thruk/lib/Thruk.pm line 681.
        Thruk::__ANON__('TERM') called at /usr/share/thruk/lib/Thruk/Utils.pm line 2680
        eval {...} called at /usr/share/thruk/lib/Thruk/Utils.pm line 2680
        Thruk::Utils::check_memory_usage('Thruk::Context=HASH(0x2852e60)') called at /usr/share/thruk/lib/Thruk.pm line 1009
        Thruk::_after_dispatch('Thruk::Context=HASH(0x2852e60)', 'ARRAY(0x2fc3ff8)') called at /usr/share/thruk/lib/Thruk.pm line 366
        Thruk::_dispatcher('HASH(0x2a3d470)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
        eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
        Plack::Util::run_app('CODE(0x1cb5290)', 'HASH(0x2a3d470)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 145
        Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x10e8c48)', 'CODE(0x1cb5290)')[Mon May 27 13:57:03.481689 2019] [core:error] [pid 9385] [client A.B.C.D:58176] End of script output before headers: fcgid_env.sh, referer: http://XXXX.XXXX.XXX/thruk/side.html
 called at /usr/share/thruk/script/thruk_fastcgi.pl line 24"

There's no error written in thruk.log.

The visible output of the error in a browser is: "Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."

**Comment by sni** [comment]
if thruk uses too much memory it kills itself. That should happen after the request while it looks like it happens during the request in this case. This should be fixed meanwhile, could you try the latest release?
