### ISSUE TITLE
Thruk "report from URL" without text content

### ISSUE THREAD

**Issue by WorrenB** [sni/Thruk#945]
**Describe the bug**
We have a scheduled report (generated from a Thruk page) that runs every Tuesday at 00:00 and send a email overview of a service (in this case, Windows update status of some servers) with a PDF attachment.
This ran without any problems until 05/14
From 05/21 on these PDF-Report suddenly sent without content (or showed only shades - not text)
Switching the report to html - did not solve our problem.
A manual simulation (regenerate report) shows that a rendering and converting process is triggered and showed NO error messages at all, but the PDF is still without text content.
Apparently the phenomenon only occurs in "Report From Url - Reports".
Reports such as SLA or Eventlog are not affected by this and display content as usual.
The page on which the report is based can be displayed correctly.
In this timeframe we installed package updates with apt-get which could cause this behavior.

**Thruk version**
Thruk 2.27-20190213 - OMD 2.91 2019-02-14-labs-edition
Thruk 2.31-20190527 - OMD 3.11 2019-05-27-labs-edition (above site integrated / displayed via "livestatus connection")

**To Reproduce**
On a Thruk page / click on the "gear" icon/ create e-mail report for this page / create report.
after generating this report the "view report preview" and "view report" (pdf) are without text content.

**desktop**
Envirionment: Hyper-V VM
```
uname -a
Linux DEHEA0X35G9JC2 4.4.0-17763-Microsoft # 379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU / Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Code name: bionic
```
**Additional context**
We already had had a short e-mail conversation about it.
This is my first GitHub Issue, so I hope it is complete and usable.

THANK YOU!
regards

**Comment by sni** [comment]
i cannot reproduce that. Which page is this report about or does it fail with any page?

**Comment by WorrenB** [comment]
on our system it currently fails on any page I tried so far...

**Comment by sni** [comment]
you might want to have a look in ~/var/thruk/jobs/<id> folder after creating the report. maybe its stdout / stderr files contain some hints.

**Comment by WorrenB** [comment]
logged in as siteuser and took a look in the ~/var/thruk/jobs/ folder.
there seem to be a subfolders for each report I tried. 
Unfortunatly the stderr and stdout files in those folders are empty.
