### ISSUE TITLE
Editing downtime end time changes downtime start time

### ISSUE THREAD

**Issue by rephlex** [sni/Thruk#946]
**Describe the bug**
When setting a downtime end time using the keyboard, the downtime start time field is also changed, although this is not desired.
See video screen capture at https://www.youtube.com/watch?v=sNsBbrtV_qY for illustration

**Thruk Version**
Thruk 2.31-20190516 - OMD 3.01~2019-05-16-labs-edition

**To Reproduce**
see video screen capture: https://www.youtube.com/watch?v=sNsBbrtV_qY

**Expected behavior**
I want the start time to NOT change (stay as-is)

**Screenshots**
https://www.youtube.com/watch?v=sNsBbrtV_qY

**Desktop (please complete the following information):**
Version 75.0.3770.75 (Offizieller Build) beta (64-Bit)
also exists in any older chrome version

**Additional context**
- the bug appears when scheduling downtime using cmd.cgi, not when scheduling downtime using status.cgi.

**Comment by rephlex** [comment]
Suggestion: This could be fixed by opening the calendar control only when the calendar icon is clicked, NOT on clicking the end time input box

**Comment by rephlex** [comment]
Also note: When scheduling the downtime via status.cgi, the behaviour is as expected and the bug does not appear.

**Comment by lamaral** [comment]
I have the exact same problem with Thruk 2.30-2 on Debian Stretch. 

Firefox 67.0.1 64-bit.

**Comment by sni** [comment]
thanks for your report, should be fixed now.
