### ISSUE TITLE
Panorama View: Geo Map min max zoom level setting

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#947]
**Is your feature request related to a problem? Please describe.**
Currently there is only a static posibility to zoom into the geo map of Panorama View. The second problem is, that it's only possible to zoom in until level 15 and in different cases a closer zoom is much better. 

**Describe the solution you'd like**
setting up in the Thruk Panorama View settings-section an min and a max zoom level. Based on that settings, PanoramaView should generate the zoom bar. Max level should be at least 21.

**Describe alternatives you've considered**
The max zoom level could be expanded to 21 without the possibility to set them up in the thruk settings.

**Comment by sni** [comment]
You can change the available zoomlevels here: https://thruk.org/documentation/configuration.html#wms_provider
