### ISSUE TITLE
Custom function for Business Process, type host,hostgroup,service and service group doesn't exist

### ISSUE THREAD

**Issue by malcombecerra** [sni/Thruk#948]
hi

i have a problem with business process, i need to create a node with a custom filter with two or more hostgroups, i see that doesn't exist so i created a custom function, but in type of args doesn't exist hostgroup like an arg, i search on the code and is correct doesn't exist, i search on de documentation and there says this var exist on type of args

if you have another solution for custom filter it could be great, or guide me to add the types of args missing on code.

i attach the part of the code where is missing the search of type args like host or hostgroup and the documentation that say exist this types of arg

![image](https://user-images.githubusercontent.com/20689770/59864695-67884d80-9355-11e9-9f59-7f28a849a2aa.png)

![image](https://user-images.githubusercontent.com/20689770/59864772-93a3ce80-9355-11e9-841f-d21db61dccf5.png)

**Comment by sni** [comment]
without changing too much, you could either use regular expressions on hosts/services if that fits. Or define a hostgroup in naemon which has multiple hostgroup_members.
If you really want to create a custom function, you could use the hostgroup field multiple times.

**Comment by malcombecerra** [comment]
the two options that you gave me doesn't work for my company, cuz we have hostgroup by company and region, so they all have both and its more difficult to separate them.

and if u look on the custom function, not exist a hostgroup field, i attach my custom function with the output on the business process.

tell me if i have something wrong

![image](https://user-images.githubusercontent.com/20689770/59943672-d4bce100-9430-11e9-8b0c-392042bda058.png)

![image](https://user-images.githubusercontent.com/20689770/59943709-e56d5700-9430-11e9-9cc3-e277612e9b3a.png)
