### ISSUE TITLE
Using url_prefix, all pages are not found.

### ISSUE THREAD

**Issue by frisky-gh** [sni/Thruk#949]
**Describe the bug**
I was using Thruk (2.26-1) with url_prefix setting. 
Today, I have upgraded Thruk to 2.30-3, and Thruk cannot output any pages. 

**Thruk Version**
thruk (2.30-3)

**To Reproduce**
1. Setup Apache and Thruk (2.26-1) with a setting "url_prefix = /pub".
2. Upgrade Thruk to 2.30-3.
3. Access http://localhost/pub/thruk/
4. Browser says "This page does not exist..."

**Expected behavior**
I expect to browse Thruk index page.

**Additional context**
I tried to put back following code (commit id: 36f15bfd):

/usr/share/thruk/lib/Thruk/Context.pm:54
`    my $path_info         = translate_request_path($env->{'REQUEST_URI'} || $env->{'PATH_INFO'}, $app->config, $env);
`
to
`    my $path_info         = translate_request_path($env->{'PATH_INFO'} || $env->{'REQUEST_URI'}, $app->config, $env);
`

And the modify is looked work fine.

**Comment by sni** [comment]
how did you install thruk, did you update the apache config? Some systems do not do that automatically, ex.: centos/rhel.

**Comment by frisky-gh** [comment]
I'm using Thruk on Debian. I installed it by APT.

**Comment by sni** [comment]
check if there is a `dpkg.new` apache config or similar and see if there are changes required to your apache config.
