### ISSUE TITLE
Unable to display graphs/popups of hosts/service on remote site

### ISSUE THREAD

**Issue by ykleet** [sni/Thruk#952]
Sorry for unformatted submission previously.

**Describe the bug**
I had setup two sites on one server, say site1 and site2, site1 connected to site2 via livestatus. Everything worked like a charm. Graphs and popups worked as expected. However, if I setup the two sites on different servers, site1 can still retreive data from site2 but graphs and popups didn't work at all. Any idea to fix this. Thx a million in advance.

**Thruk Version**
Thruk 2.30-2 (installed via OMD 3.1 Lab-edition with default settings. i.e. php4nagios enabled)

**To Reproduce**
1. install OMD 3.1 Lab Ed at two servers and create site, add hosts and services at each site.
2. config livestatus connection: site1 as master and site2 as slave. click 'test' button at site1 to make sure the connection is working.
3. at site1 web interface, move mouse to point to local hosts/services action icon, popup will be displayed as expected. if moving mouse to point to site2's hosts/services action icon, no popup will be displayed, new page with no graph will be opened if clicked on the icon. Instead of graph, 'Not Found
The requested URL /CamMon/pnp4nagios/index.php/graph was not found on this server.' will be shown.

**Expected behavior**
popups and graphs of hosts/services of remote site should be displayed.

**Desktop (please complete the following information):**
 - Chrome 
 - 70.0.3538.67

**Comment by sni** [comment]
Try to connect these backends via https. Then Thruk can passthrough the graphs. 
Or use absolute urls for pnp.

**Comment by ykleet** [comment]
Thank you!!! It works once I modified the action url to absolute url.
