### ISSUE TITLE
Wrong release date year (2018 instead of 2019) on homepage

### ISSUE THREAD

**Issue by neuhaus** [sni/Thruk#953]
According to http://www.thruk.org/download.html, Thruk  v2.30-3 was released on Jun 11, 2018.

Looks like it was released in 2019, not 2018.

**Comment by sni** [comment]
thanks, fixed in https://github.com/sni/thruk_org/commit/8255917eecac176984a7618f597ef988c8659e43

**Comment by neuhaus** [comment]
When will the website be updated?

**Comment by sni** [comment]
should be fine now, seems like the automatic update mechanism failed. thanks again
