### ISSUE TITLE
Thruk plugin panorama, the problem with show non-english characters after xdata refresh

### ISSUE THREAD

**Issue by metacoma** [sni/Thruk#954]
**Describe the bug**
After the scripted-dashboard refreshed by xdata timer, non-english characters shows with errors

**Thruk Version**
Version 2.30-3

**To Reproduce**
1. Create a simple dashboard with non-english letters and refresh interval 10s.
```
# title:  OTRS dynamic2
# user:   thrukadmin
# groups: [{"*" : "read-only"}]
use utf8;

my $_show_data = sub {
  my ($x, $y, $message) = @_;
  $dashboard->{'panlet_' . $y} = {
      "xdata" => {
         "appearance" => {
            "type" => "icon"
         },
         "cls" => "TP.TextLabelWidget",
         "general" => {
            "text" => ""
         },
         "groups" => [],
         "label" => {
            "bgcolor" => "",
            "bordercolor" => "",
            "bordersize" => 1,
            "display" => "always",
            "fontbold" => "0",
            "fontcenter" => "",
            "fontcolor" => "#000000",
            "fontfamily" => "",
            "fontitalic" => "",
            "fontsize" => 30,
            "height" => "",
            "labeltext" => $message,
            "offsetx" => 0,
            "offsety" => 0,
            "orientation" => "horizontal",
            "position" => "top-left",
            "roundcorners" => "",
            "width" => ""
         },
         "layout" => {
            "scale" => 100,
            "size_x" => 0,
            "size_y" => 0,
            "x" => $x,
            "y" => $y,
            "zindex" => "0"
         },
         "link" => {}
      }
  };
};

# get actual position
$dashboard = load_data();

&{$_show_data}(10, 30, "Очереди");
$dashboard->{'ts'}                          = time()-time()%10;
$dashboard->{'tab'}->{'xdata'}->{'refresh'} = 10;
```
2. Open dashboard first time, there is no problem.

![panorama-ok](https://user-images.githubusercontent.com/5146707/60832054-1210c500-a1cc-11e9-84cf-e275c35af403.png)

3. Wait about 10-15 seconds, dashboard refreshed by xdata timer
![panorama-fail](https://user-images.githubusercontent.com/5146707/60832122-340a4780-a1cc-11e9-868f-aaacadbfcab4.png)

**Expected behavior**
The dashboard must look without any changes.

**Screenshots**
Browser network console with json answer
![panorama-console](https://user-images.githubusercontent.com/5146707/60832335-a9761800-a1cc-11e9-9d32-60bb00448dd5.png)

**Desktop (please complete the following information):**
Reproduced on:
- Google chrome 75.0.3770.100 (Official build), (32 bit)
- Firefox 67.0.4 (32-bit)

**Comment by sni** [comment]
should be better now, thanks
