### ISSUE TITLE
Thruk fcgid update breaks Stor2rrd on CentOS 6x

### ISSUE THREAD

**Issue by Panther505** [sni/Thruk#955]
With the addition of the line (which apprears to become global)
AddHandler fcgid-script .sh 

in the thruk.conf file, stor2rrd fails to run correct. I get a genjson.sh error (which is #!/bin/sh file). 

**Thruk Version**
Version of Thruk (and OMD if applicable)
>cat /etc/redhat-release
CentOS release 6.10 (Final)
> rpm -qa|grep thruk
thruk-base-2.30-3.x86_64
libthruk-2.30-0.x86_64
thruk-plugin-reporting-2.30-3.x86_64<br>

httpd-2.2-15-69.el6.centos.x86_64

no OMD installed but using the mk_livestatus backend for nagios

**To Reproduce**
1. Install and configure stor2rrd
2. Install thruk and configure
3. restart httpd 
4. stor2rrd no longer loads. Error logs show 
Premature end of script headers: genjson.sh 

**Expected behavior**
Expect that thruk and stor2rrd should be able to co-exist in the same space. 

**Desktop (please complete the following information):**
Browser irrelevant. - Server side issue

**Additional context**
Failure does not occur with apache 2.4 
httpd-2.4.6-89.el7.centos.x86_64

**Comment by sni** [comment]
should be better with the next release.

**Comment by Panther505** [comment]
Dropped the fix in the current release and it now works as expected.   Thanks for the quick response. 

M
