### ISSUE TITLE
Business Process : No such host or no such service

### ISSUE THREAD

**Issue by aurelienjes** [sni/Thruk#956]
After setting up a business process (no problem with host or service choice), plugin output show : "no matching hosts/services found" or "no such host"

My Thruk Version is : 2.30-3

1. Go to Business Process
2. Create a new business process
3. Select an hosts and services
4. See error. Business process is in "Unknown status" and plugin output is : "no matching hosts/services found"

I need to know if it's a new bug or if it's a configuration problem

 - Browser : Chrome
 - Version :  75.0.3770.100 (64 bits)

Thanks a lot

**Comment by sni** [comment]
i tried to reproduce this, but it works as expected.

**Comment by aurelienjes** [comment]
Hi Sven,

Thanks for your reply.
Could you tell me if there is any log or any debug mode in Business Process with Thruk ?
I wonder if all requirements are installed on the machine.
I just see this problem after upgrade to Thruk 2.30-3.
Before, Business process ran like a charm.

Thanks

Aurélien

De : Sven Nierlein <notifications@github.com>
Envoyé : vendredi 12 juillet 2019 15:33
À : sni/Thruk <Thruk@noreply.github.com>
Cc : Aurélien CLAVIER <aclavier@jeslabs.com>; Author <author@noreply.github.com>
Objet : Re: [sni/Thruk] Business Process : No such host or no such service (#956)


i tried to reproduce this, but it works as expected.

**Comment by sni** [comment]
could you try if it works with the latest release?
