### ISSUE TITLE
Custom variable filter and sorting broke during 2.28 -> 2.30-3 upgrade

### ISSUE THREAD

**Issue by sshmanko** [sni/Thruk#957]
**Describe the bug**
Specifying custom variable in filter OR trying to sort list view with custom variable column causes an exception.

Url:        status.cgi?nav=&hidesearch=0&hidetop=&dfl_columns=&style=detail&dfl_s0_type=custom+variable&dfl_s0_val_pre=ROLES&dfl_s0_op=%3D&dfl_s0_value=nagios-backend
Browser:    
Version:    2.30-3
Release:    June 11, 2019
LMD:        lmd - version 1.6.0 (Build: b3e3ddd)
Backends:   State / Program Version / Data Source Version
0 / 4.3.1 / 1.2.8p18
0 / 4.3.1 / 1.2.8p18
uname:      Linux ip-xxx-xxx-xxx-xxx 4.14.114-83.126.amzn1.x86_64 #1 SMP Tue May 7 02:26:58 UTC 2019 x86_64
release:    Amazon Linux AMI release 2018.03
Kernel  on an
Stacktrace:
internal lmd error - /usr/local/thruk/tmp/lmd/live.sock: 
peer                $VAR1 = '/usr/local/thruk/tmp/lmd/live.sock';
statement           $VAR1 = 'GET services
Backends: d46f9 c790b
Columns: accept_passive_checks acknowledged action_url action_url_expanded active_checks_enabled check_command check_interval check_options check_period check_type checks_enabled comments current_attempt current_notification_number description event_handler event_handler_enabled custom_variable_names custom_variable_values execution_time first_notification_delay flap_detection_enabled groups has_been_checked high_flap_threshold host_acknowledged host_action_url_expanded host_active_checks_enabled host_address host_alias host_checks_enabled host_check_type host_latency host_plugin_output host_perf_data host_current_attempt host_check_command host_comments host_groups host_has_been_checked host_icon_image_expanded host_icon_image_alt host_is_executing host_is_flapping host_notes host_name host_notes_url_expanded host_notifications_enabled host_scheduled_downtime_depth host_state host_accept_passive_checks host_last_state_change icon_image icon_image_alt icon_image_expanded is_executing is_flapping last_check last_notification last_state_change latency low_flap_threshold max_check_attempts next_check notes notes_expanded notes_url notes_url_expanded notification_interval notification_period notifications_enabled obsess_over_service percent_state_change perf_data plugin_output process_performance_data retry_interval scheduled_downtime_depth state state_type modified_attributes_list last_time_critical last_time_ok last_time_unknown last_time_warning display_name host_display_name host_custom_variable_names host_custom_variable_values in_check_period in_notification_period host_parents depends_exec depends_notify parents has_long_plugin_output last_state_change_order state_order peer_key
Filter: host_custom_variables = ROLES nagios-backend
Filter: custom_variables = ROLES nagios-backend
Or: 2
Limit: 100
Offset: 0
Sort: host_name asc
Sort: description asc
OutputFormat: wrapped_json
ResponseHeader: fixed16
';
message             $VAR1 = 'reading header from socket failed, check your livestatus logfile: ';
at /usr/local/thruk/share/lib/Monitoring/Livestatus.pm line 1228.
Monitoring::Livestatus::_socket_error('Monitoring::Livestatus=HASH(0x23a8400)', 'GET services\x{a}Backends: d46f9 c790b\x{a}Columns: accept_passive_checks acknowledged action_url action_url_expanded active_checks_enabled check_command check_interval check_options check_period check_type checks_enabled comments current_attempt current_notification_number description event_handler event_handler_enabled custom_variable_names custom_variable_values execution_time first_notification_delay flap_detection_enabled groups has_been_checked high_flap_threshold host_acknowledged host_action_...', 'IO::Socket::UNIX=GLOB(0x3700430)', 'reading header from socket failed, check your livestatus logfile: ') called at /usr/local/thruk/share/lib/Monitoring/Livestatus.pm line 1180
Monitoring::Livestatus::_read_socket_do('Monitoring::Livestatus=HASH(0x23a8400)', 'IO::Socket::UNIX=GLOB(0x3700430)', 'GET services\x{a}Backends: d46f9 c790b\x{a}Columns: accept_passive_checks acknowledged action_url action_url_expanded active_checks_enabled check_command check_interval check_options check_period check_type checks_enabled comments current_attempt current_notification_number description event_handler event_handler_enabled custom_variable_names custom_variable_values execution_time first_notification_delay flap_detection_enabled groups has_been_checked high_flap_threshold host_acknowledged host_action_...') called at /usr/local/thruk/share/lib/Monitoring/Livestatus.pm line 1109
eval {...} called at /usr/local/thruk/share/lib/Monitoring/Livestatus.pm line 1100

Same URL works fine in Thruk 2.28 and LMD 1.5.0

**Comment by sni** [comment]
could you try to upgrade LMD?

**Comment by sshmanko** [comment]
upgrading LMD to 1.6.1 resolved the issue, thanks!
