### ISSUE TITLE
PanoramaView: Browser not responding after adding squares in large env.

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#958]
**Describe the bug**
In large environements browsers are crashing, because the squares window has no filter as default and all available hosts / services are generated for the dashboard.

**Thruk Version**
2.28(OMD 2.91~2019-03-30-labs-edition)

**To Reproduce**
1. Create Dashbaord with multiple backends and large amount of hosts (our env. ~ 20.000)
2. Create squares panel
3. Browser will not respond for a long time

**Expected behavior**
After creating the squares panel, the squares shouldn't be generated directly for all available hosts. 

**Screenshots**
---

**Desktop (please complete the following information):**
 - Chrome 75 
 - Firefox 68

**Comment by sni** [comment]
thats a know issue, the inital set of hosts or services should be limited somehow.
