### ISSUE TITLE
This host/service doesn't exist for the hosts having FQDN

### ISSUE THREAD

**Issue by raghavc-zz** [sni/Thruk#963]
Hi All,

I've installed Thruk(Version 2.30-3) from labs-consol-stable.repo on RHEL 7.4 server. Nagios core 4.4.4 and mk-livestatus-1.5.0p18 installed on the remote server and added on thruk as a back end.  Thruk saying "This host does not exist..." or "This service does not exist..." for those  hosts which are having  FQDN(e.g., vm0012.agf.ecmsvc.com) as host name, it is working fine for those hosts which do not have the FQDN (e.g., vm0012) as host name, kindly let me know how to fix this.

Regards,
RC

**Comment by r-lindner** [comment]
With Naemon + Livestatus 1.0.10 and Thruk 2.30-3 it is working for me (static.domain.de as host_name).
Does the live search dropdown show the host and then it cannot find it or how do you get to the "This host does not exist..." page?

**Comment by raghavc-zz** [comment]
Yes, live search populates all the hosts and services and services on thruk web-console, when I click on a  host(with FQDN), I get "This host does not exist..." page
![image](https://user-images.githubusercontent.com/15325021/62940078-5bb68600-bdf0-11e9-97ac-f5ef01f9a0d9.png)
![image](https://user-images.githubusercontent.com/15325021/62940104-70931980-bdf0-11e9-8b38-5f7dde69169d.png)

**Comment by r-lindner** [comment]
is there something odd in the URL of the "not found" page? Especially the **host=** parameter?

**Comment by sni** [comment]
there had been other strange things with mk-livestatus-1.5.x already. Could you try a 1.4.x version?

**Comment by raghavc-zz** [comment]
Awesome!, it worked with mk-livestatus-1.4.0p37.
![image](https://user-images.githubusercontent.com/15325021/62942343-b30b2500-bdf5-11e9-859f-75b7c6df3d3b.png)

Thank you Sven and Ronny :)

Regards,
RC

**Comment by sni** [comment]
great :-)
