### ISSUE TITLE
Panorama VIEW dont load

### ISSUE THREAD

**Issue by Plinio16** [sni/Thruk#966]
Please help
Panorama VIEW (OSM) dont load in Thruk, even in https://demo.thruk.org/demo/thruk/cgi-bin/panorama.cgi
Someone can restart the mapproxy?

This issue was ready fix:
MAP ISSUE #896

by SNI
i just restarted the mapproxy on maps.thruk.org. I also update mapproxy to latest 1.11 which seem so remove the dark lines as well.

**Comment by sni** [comment]
thanks, should be up and running again. My small vserver had some memory issues.
