### ISSUE TITLE
Config Backend not show in config tool

### ISSUE THREAD

**Issue by jbeaujour** [sni/Thruk#967]
**Config Backend not show in config tool**
When Backend is defined in /etc/thruk/thruk_local.d/thruk.hostname , it is not shown in Config Tool / Backends,  but it works fine.

**Thruk Version**
Thruk 2.30-2

**To Reproduce**
1. vi /etc/thruk/thruk_local.d/thruk.hostname
insert backend definition like :
\<Component Thruk::Backend\>
    \<peer\>
        name   = nagios-rec
        type   = livestatus
        \<options\>
            peer = w.x.y.z:6557
      \</options\>
    \</peer\>
\</Component\>

2. Click on Config Tools
3. Click on Backends / Sites
4. See nothing in Name connection, Connection

**Expected behavior**
Retrieve the backend definition of /etc/thruk/thruk_local.d/thruk.hostname

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [e.g. 76]

**Comment by sni** [comment]
Yes, the config tool cannot handle those files. That might be pretty complicated.
