### ISSUE TITLE
Panorama VIEW

### ISSUE THREAD

**Issue by Plinio16** [sni/Thruk#969]
Please help
Panorama VIEW (OSM) dont load in Thruk, even in https://demo.thruk.org/demo/thruk/cgi-bin/panorama.cgi
Someone can restart the mapproxy?

This issue was ready fix:
MAP ISSUE #896 and #966

by SNI
i just restarted the mapproxy on maps.thruk.org. I also update mapproxy to latest 1.11 which seem so remove the dark lines as well.

**Comment by sni** [comment]
i am migrating this service right now, it should be up and running in 2-3 hours.
