### ISSUE TITLE
Wrong current state when displaying status information

### ISSUE THREAD

**Issue by K-Hoffmann** [sni/Thruk#970]
* Ubuntu 18.04.3
* Naemon Core 1.1.0
* Thruk 2.30-3

```
define command {
    command_name    check_vhost_certificate
    command_line    $USER1$/check_http -H $ARG1$ --ssl --sni -C $ARG27$,$ARG28$ $ARG2$
}
```
For testing purposes: `$ARG27$ = 90, $ARG28$ = 40`
```
define service {
    name                            local-service-1d
    use                             local-service
    check_interval                  1440
    max_check_attempts              1
    notification_interval           1440
    register                        0
}
```
```
define host {
    use                         local-server
    host_name                   server.example.com
    address                     aaa.bbb.ccc.ddd
}

define service {
    use                         local-service-1d
    host_name                   server.example.com
    service_description         vhost-cert [cloud.example.com]
    check_command               check_vhost_certificate!cloud.example.com
}
```
Under `http://SERVER/thruk/#cgi-bin/extinfo.cgi?type=2&host=server.example.com
&service=vhost-cert%20%5Bcloud.example.com%5D&backend=378e7`:

Check Command : `check_vhost_certificate!cloud.example.com`
Expanded Command: `/usr/lib/naemon/plugins/check_http -H cloud.example.com --ssl --sni -C 90,40`

Executing the expanded command on the command line:
``` 
WARNING - Certificate 'cloud.example.com' expires in 88 day(s) (Sun Jan  5 14:59:41 2020 +0000)
```
But in Thruk under `Current Status` i get `OK` state.

Did I do something wrong with the configuration or did I not understand the concept of the service checks correctly?

![Naemon Service Status Certificate](https://user-images.githubusercontent.com/36964418/66495774-1c3bab80-eaba-11e9-8508-c0469aa919b4.png)

Kind regards,
Karsten

**Comment by sni** [comment]
sounds like a configuration issue in naemon. there is nothing thruk can do here except you can have a look at the computed command line and try exactly that one and see if you get the same result.
Nevertheless, not a Thruk issue.
