### ISSUE TITLE
ERROR: Can't use string ("-1") as an ARRAY ref on logcacheclean

### ISSUE THREAD

**Issue by shermanchan** [sni/Thruk#971]
Error on logcacheclean 

[Fri Oct 11 01:00:02 2019][INFO][ServerName] ERROR: Can't use string ("-1") as an ARRAY ref while "strict refs" in use at /usr/share/thruk/lib/Thruk/Backend/Provider/Mysql.pm line 1062.
[Fri Oct 11 01:00:02 2019][INFO][ServerName] ERROR - removed 0 log items from 1 site with 1 errors in 0.03s (0/s)

**Thruk Version**
Version 2.30-3

**To Reproduce**
/usr/bin/thruk -a logcacheclean=730

**Expected behavior**
[Tue Sep 10 01:26:37 2019][INFO][ServerName] OK - removed 56460 log items (and 41006 plugin ouput references) from 1 site successfully in 1594.85s

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
Not Applicable

**Additional context**
OS:  CentOS release 6.5

Thanks in advance

**Comment by sni** [comment]
cannot reproduce that with latest HEAD. Please reopen if this still occurs with the next release. I assume this is fixed already.
