### ISSUE TITLE
To hide a backend from sectional or default view

### ISSUE THREAD

**Issue by Delat0918** [sni/Thruk#972]
**Describe the bug**
We tried to hide a backend from a section or default view but still we could view and only "hidden" appears

**Thruk Version**
[root@clonethrukp01 thruk]# rpm -qa thruk
thruk-2.30-3.x86_64

**To Reproduce**
1. edit the file thruk_local.conf
2. add on the peers config the argument 'display = 0' to the APPL-ChinaHUB
<peer>
        name    = APPL-ChinaHUB
        id      = b86d7
        type    = livestatus
        section = App Monitoring
        display = 0
        <options>
            peer          = 10.78.8.134:6557
        </options>
    </peer>
 
3. Save the file and reload the thruk services and restart the httpd services

**Expected behavior**
The backend APPL-ChinaHUB should be hidden and will not be viewable from the default or section view

**Screenshots**
![Thruk_backend view](https://user-images.githubusercontent.com/38754324/66798416-80d68a80-ef40-11e9-8a89-56d3f9933c4f.JPG)

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by sni** [comment]
`display=0` just sets the default initial value. If you changed the backends selection once, then your selection is used.
