### ISSUE TITLE
Downtime not completly removed from "list view" for hosts on multiple collector

### ISSUE THREAD

**Issue by GuillaumeSigma** [sni/Thruk#973]
**Describe the bug**
We have a random host  simultaneously managed by two collectors (nagios 4+livestatus/Naemon+Livestatus).
If we add a downtime from the "list" vie, two downtime are added : one per collector = normal behaviour.
Downtime logo is present in list view.

If we remove downtime from the "list" view, only one of these two downtime is removed. Downtime icon on list view is not present, even if one donwitime (on collector 2) remains.

**Thruk Version**
2.26-2

**To Reproduce**
1. search a host that is managed by two collectors
2. in tab/list view (status.cgi) : select the host
3. Select the downtime quick command, fill in informations and submit
4. downtime icon appears on host
5. in detail view of this host (extinfo.cgi) there are two downtime
6. in list view, remove downtime by selecting host and using quick action
7. icon is removed
8. In host information view, one dowtime remains (on collector 2).

**Expected behavior**
1. The two downtime should habe been removed with quick action
2. In detail view (list view) : downtime icon sould be displayed if there is active  donwtime on nay collector.

**Screenshots**
- 

**Desktop (please complete the following information):**
 - Firefox 69.0.3

**Additional context**

**Comment by sni** [comment]
I assume this is fixed in the latest release. Please reopen the issue if it still persists in the next release.
