### ISSUE TITLE
Calendar widget stops working when thruk embedded using iframe

### ISSUE THREAD

**Issue by msciciel** [sni/Thruk#974]
**Describe the bug**
When thruk is embedded into html page using iframe then calendar widget is not working when adding downtime. We are using iframes to put together information from many monitoring system on single page. It was working on `1.84` but stop working after upgrade to latest version.

**Thruk Version**
thruk-base-2.32-1.x86_64
thruk-2.32-1.x86_64
thruk-plugin-reporting-2.32-1.x86_64
libthruk-2.32-0.x86_64

**To Reproduce**

1. Use below page with embeded thruk:
```
<html>
<head>
        <title>Info</title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style>
body {
        background: black;
        margin: 0;
        padding: 0;
}
#mon {
        border: 0;
        width: 100%;
        height: 100%;
}
</style>

</head>
<body>
        <iframe id="mon" src="https://thruk/thruk/cgi-bin/status.cgi?minimal=2&svc_s0_servicestatustypes=28&hst_s0_hostprops=262154&hst_s0_servicestatustypes=31&svc_s0_serviceprops=262154&svc_s0_hoststatustypes=3&sorttype_svc=1&hst_s0_hoststatustypes=4&style=combined&svc_s0_hostprops=10&sortoption_svc=6&svc_s0_hostprop=2&svc_s0_hostprop=8&sorttype_hst=1&hst_s0_serviceprops=0&sortoption_hst=6&title=All+Unhandled+Problems"></iframe>

</body>
</html>
```
2. Click on some service
3. Select downtime
4. Try to click calendar icon
5. Calendar widget is not showing up

**Expected behavior**
Calendar widget shows up.

**Desktop (please complete the following information):**
 - Firefox
 - 60.9.0esr
 - CentOS 7

**Comment by sni** [comment]
closing this one, Thruk 3 has been released and a lot has changed. Also for the calendar library. Please open a new issue if this is still relevant.
