### ISSUE TITLE
BP: Input Filters do not work for Hostgroups

### ISSUE THREAD

**Issue by ukaufmach** [sni/Thruk#975]
**Describe the bug**
If I attach a Hostgroup below a node (worst of) and select to Filter ACK event, the status of the node is OK even if there are warning or critical objects in the host group that are not acknowledged. 
If I attach a "Any Filter" containing a Hostgroup, the status will change correctly but the  Filter for the Ackknowledged events does not work. Acknkowleged Events should not get forwarded then, if I understand this function correctly.

**Thruk Version**
2.32-2

**Comment by sni** [comment]
Thats right, the ack filter does not work with host- servicegroups. Simply use the "Any filter" in this case.
