### ISSUE TITLE
In Nagios there is no graphic in the SLA Thruk report

### ISSUE THREAD

**Issue by marcom29** [sni/Thruk#978]
Hi !
My problem is that I don't have graphics in SLA reports
I use Nagios Core 4.4.5, Thruk 2.33 and PNP4Nagios 0.6
I have these frequently asked questions

I wish to be able to visualize the graphs of pnp4nagios in the service reports, which I generate by thruk.

[https://www.thruk.org/images/galleries/reports3-thumb.png](url)

I understand that you have to edit this file, pnp_export.sh

> PNP_WGET="wget -q"

> if [ "$OMD_ROOT" != "" ]; then
> PNP_ETC=~/etc/pnp4nagios
> PNP_INDEX=~/share/pnp4nagios/htdocs/index.php
> fi
> [ -e ~/.thruk   ] && . ~/.thruk
> [ -e ~/.profile ] && . ~/.profile

> HOST=$1
> SERVICE=$2
> WIDTH=$3
> HEIGHT=$4
> START=$5
> END=$6
> PNPURL=$7
> TEMPFILE=$8
> SOURCE=$9

> if [ "$PNPURL" != "" ]; then
> PNPURL="$PNP_URL_PREFIX$PNPURL"
> fi
> export REQUEST_URI="image? host=$HOST&srv=$SERVICE&view=1&source=$SOURCE&graph_width=$WIDTH&graph_height=$HEIGHT&start=$START&end=$END"
> if [ "${PNPURL:0:5}" != "http:" -a "${PNPURL:0:6}" != "https:" ]; then

>  [ "$PNP_ETC"   = "" ] && exit 0
>  [ "$PNP_INDEX" = "" ] && exit 0
>  [ -d "$PNP_ETC/."   ] || exit 0
>  cd $PNP_ETC
>  php $PNP_INDEX "$REQUEST_URI" > $TEMPFILE 2>/dev/null
> else

>  $PNP_WGET -O $TEMPFILE "$PNPURL/$REQUEST_URI"
>fi
> exit 0

But I don't know how the fields are filled, or what parameters to place.

Note: I have followed what they comment here but I have not been able to obtain the graphs of pnp4nagios in the reports.

**Comment by sni** [comment]
well, those fields have to match your PNP installation. Create a ~/.thruk file for your webserver user and add:
```
PNP_ETC=/etc/pnp4nagios
PNP_INDEX=/share/pnp4nagios/htdocs/index.php
```

**Comment by marcom29** [comment]
where do you put the file ~ / .thruk? or in what way? It must go eb the same as pnp_export.sh

**Comment by thowo** [comment]
Hello,
we are currently facing the same issue here. We are trying to migrate our really old thruk Version 2.12 which was included in
OMD 2.20-labs-edition to the current one Thruk 2.38-2, installed as a debian package on debian 10.
We are missing the pnp graphs in our report. We have created the .thruk file in /var/www and also edited the pnp_export.sh to include the correct path. But none of them worked for us. What do we missing?

Any thoughts are highly welcome,

Thanks in advance,
best regards,
cheers,

Tom
