### ISSUE TITLE
Availability Report XLS/CSV wrong values in "known" columns

### ISSUE THREAD

**Issue by kafos** [sni/Thruk#982]
**Describe the bug**
It seems that values from "total" columns are in the "known" columns. The HTML view is showing the correct values

**Thruk Version**
Thruk 2.33-20191129 - OMD 3.21~2019-11-29-labs-edition

**To Reproduce**
1. Create a report for yesterday with a timeperiod smaller than the whole day
2. create the report in XLS/CSV & HTML
3. The "known" columns should show a smaller percent value as the "totals" but the values are in CSV/XLS the same

**Expected behavior**
HTML are showing the correct values

**Comment by sni** [comment]
The report is based on this template:
https://github.com/sni/Thruk/blob/master/templates/excel/availability.tt for the xls file and
https://github.com/sni/Thruk/blob/master/templates/avail_report_services_csv.tt
https://github.com/sni/Thruk/blob/master/templates/avail_report_hosts_csv.tt
Which exact column is wrong? Maybe you could have a look at the templates and see if you spot the error.
