### ISSUE TITLE
Action menu for Service Name with backslash

### ISSUE THREAD

**Issue by zhiltsov-dtln** [sni/Thruk#983]
Hello!
We have multiple services with backslashes in names.
When I try to execute the action from action menu for this service it fails.
I check cfg.service and found that backslash didn't escape - see screenshot.
![2019-12-13_113929](https://user-images.githubusercontent.com/58843861/70786281-59176d80-1d9d-11ea-9d1a-bdd350397c88.png)
![2019-12-13_113842](https://user-images.githubusercontent.com/58843861/70786283-59b00400-1d9d-11ea-8e3d-45ae7487b202.png)

**Comment by sni** [comment]
right, that should be properly escaped

**Comment by zhiltsov-dtln** [comment]
How should I escape backslash in my action menu js code?
I tried  
cfg.service.replace(/\\/g, "\\\\");
but without success.

**Comment by sni** [comment]
i assume there is no literal `\` at that point but a tab character already. It has to be escaped before.

**Comment by zhiltsov-dtln** [comment]
in action menu code or thruk code?
To action menu code service string comes with tab character already I suppose.

**Comment by sni** [comment]
can you post an example of your action menu config?

**Comment by zhiltsov-dtln** [comment]
This is test action menu:
function js_adv_menu(cfg) {
    return({
        "icon": "/thruk/themes/{{theme}}/images/dropdown.png",
       "title": "Service Menu",
       "menu": [
           {
               "icon": "/thruk/themes/{{theme}}/images/action_pnp.png",
               "label": "Create Incident in Service Desk",
               "action":
"server://create_incident/$HOSTNAME$/$SERVICEDESC$/$SERVICESTATE$/$SERVICEDURATION$/$SERVICEOUTPUT$/$REMOTE_USER$/$_SERVICESUPPORT_GROUP$",
               "target": "_blank"
           },
           "-",
        {
          "icon":"../themes/{{theme}}/images/info.png",
          "label":"Show Incident in Service Desk",
          "menu": js_show_incident
        }
      ]
    });
}

function js_show_incident(cfg) {
console.log(action_menu_options.service)
//debugger
str1 = action_menu_options.service;
alert(str1);
}


чт, 20 февр. 2020 г. в 19:28, Sven Nierlein <notifications@github.com>:

**Comment by sni** [comment]
thanks, should be better with the next release.
