### ISSUE TITLE
Thruk Internal Error

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/Thruk#984]
Good Day! We have a large setup of Thruk/Nagios Servers and from time to time we are getting internal error server when one of the Icinga backend goes down. I don’t see any relevant error from the thruk.log except for the reporting error during downtime. (Please see attached). Btw we have setup the icinga using stunnel since we don’t have a direct connection to the icinga servers.

Thruk Version: 2.30-3
Logcache: Enabled
LMD: not enabled
Nagios Backend: 13 
Icinga Backend: 3 using stunnel
[thruk.log](https://github.com/sni/Thruk/files/3987725/thruk.log)

**Comment by jgbuenaventura** [comment]
[capture2.log](https://github.com/sni/Thruk/files/3988167/capture2.log)

i replicated the issue by shutting down one of the icinga backend and the thruk server became inaccessible.

**Comment by sni** [comment]
Thats where LMD usually comes into play. Its a caching daemon especcially designed to handle lots of backends. Go is much better in handling different connections and multiple threads.
