### ISSUE TITLE
String in "Status information" in "Service Status Details" table is not HTML escaped.

### ISSUE THREAD

**Issue by eduault** [sni/Thruk#987]
**Describe the bug**
String in "Status information" in "Service Status Details" table is not HTML escaped.

**Thruk Version**
Thruk Monitoring Webinterface
Version 2.12-3
December 20, 2016

**To Reproduce**
1. A plugin returns HTML code is its response, for example "HTTP CRITICAL: HTTP/1.1 404 Introuvable - string '<title>Page de test des we...' not found - 125 bytes in 0.036 second response time"
2. Display the service status page, including a service using a command using this plugin
3. Errors found :
* "Status information" for this service is truncated to "HTTP CRITICAL: HTTP/1.1 404 Introuvable - string '"
* The Service Status Details table is truncated after this service : following services are not dispalyed

**Expected behavior**
* "Status information" for this service not truncated : it is "HTTP CRITICAL: HTTP/1.1 404 Introuvable - string '<title>Page de test des we...' not found - 125 bytes in 0.036 second response time"
* The Service Status Details table is not truncated

**Screenshots**
![2020-01-16 16_16_30-Thruk](https://user-images.githubusercontent.com/29234693/72545050-aef1a080-3888-11ea-8527-bc1995eaab8d.png)

**Desktop (please complete the following information):**
Firefox Quantum 67.0.2 (64 bits)

**Comment by sni** [comment]
Have you changed `escape_html_tags=1` in your cgi.cfg?

**Comment by eduault** [comment]
No. Thanks for this help.

![image](https://user-images.githubusercontent.com/29234693/72545958-34298500-388a-11ea-9585-8727d5e8661e.png)
