### ISSUE TITLE
Panorama View Isn't Loading Multiple Dashboards Properly

### ISSUE THREAD

**Issue by rgelber** [sni/Thruk#991]
**Describe the bug**
In our current work environment, we have may users using Panorama View with multiple dashboards. If the user switches to a different dashboard by clicking on another "dashboard tab" it will take a few minutes for the graphs to load. If the user manually refreshes the web page it will load instantly but if they change tabs again, the newly selected "dashboard" will have the same issue. 
 
**Thruk Version**
Thruk-2.32
LMD-1.8.0
OMD Backends Connected via Live-status with the following versions. 
- 2.70-labs-edition (Site 1)
- 2.90-labs-edition (Site 2)
- 3.10-labs-edition (Site 3)
- 3.20-labs-edition (Site 4)

**To Reproduce**
1. Go to 'Create two or more dashboards'
2. Click on 'Dashboard 1'
3. Click on 'Dashboard 2'
4. Graphs for dashboard 2 will take forever to load. 

**Expected behhavior was that it would load instantly. 

**Screenshots**
User is on dashboard 1
![tab1](https://user-images.githubusercontent.com/33894087/72939999-dcc06480-3d22-11ea-9cdc-cba6718e0df7.png)
User changes to dashboard 2
![tab2](https://user-images.githubusercontent.com/33894087/72937099-56555400-3d1d-11ea-819c-0b810fb94146.png)
User refreshes web browser while on dashboard 2 
![tab3](https://user-images.githubusercontent.com/33894087/72937541-2fe3e880-3d1e-11ea-9a86-bd393ce49609.png)

**Desktop (please complete the following information):**
 Browsers Used [ Brave, Chrome, Firefox]:
1. Brave Version [Version 1.2.41 Chromium: 79.0.3945.88 (Official Build) unknown (64-bit)]
2. Chrome Version [Version 79.0.3945.130 (Official Build) Arch Linux (64-bit)
3. Firefox Version [Version 72.0.2 (64-bit)]

**Additional context**
This issue wasn't present on thruk-2.30-3.x86_64 and only manifested itself after updating the thruk packages on our Centos 7 server.

**Comment by sni** [comment]
This is hopefully already fixed in the latest nightlies.
