### ISSUE TITLE
autodetection of core does not work with icinga2

### ISSUE THREAD

**Issue by micw** [sni/Thruk#992]
**Describe the bug**
Thruk does not enable icinga features (e.g. expire acks) with icinga2 core.

**Thruk Version**
2.32 + LMD + Icinga2 (same issue without LMD)

**To Reproduce**
Setup icinga2 with livestatus, connect thruk
Setup a failing host or service
Add an ack -> should be possible to set expire time but is not

When enforcing icinga features (enable_icinga_features = 1), it works

**Expected behavior**
Icinga core should be auto-detected and icinga features enabled.

**Comment by sni** [comment]
Thruks core autodetection only works within OMD, but as you already noticed, simply set `enable_icinga_features`. If you have an idea on how to detect Icinga2, let me know.

**Comment by micw** [comment]
Seems that I just understood "autodetection" wrong. I thought it was something that happens over livestatus protocol. I'll close this issue.

**Comment by sni** [comment]
It be detected over livestatus, for example Naemon or Shinken append a `-naemon` or `-shinken` suffix when fetching the version. Icinga 2 doesn't do anything like that.
If you can convince them so send anything uniq for icinga 2, it could be detected.
