### ISSUE TITLE
BP: Notify with recursive informations when add_recursive_output_filter is set

### ISSUE THREAD

**Issue by rverchere** [sni/Thruk#993]
WIth ThrukBP, I use the following bp_filter to have extended/recursive output information when something goes wrong:

```cfg
    default_filter        = add_recursive_output_filter
```

This works fine, as extended information are available:
![image](https://user-images.githubusercontent.com/232433/73307989-92a61a00-421f-11ea-8daf-a131b2e87e12.png)

But when I get notification, only the basic status information are sent:

```
Additional Info:

UNKOWN - kafka-3 unknown
```

This could be great if notifications send same extended infos!

Thanks for your work!

**Comment by sni** [comment]
Seems like you did not include the long plugin output macro in your notification then:
https://www.naemon.org/documentation/usersguide/macrolist.html#longserviceoutput

**Comment by rverchere** [comment]
Thanks, that's fine with this macro !
