### ISSUE TITLE
Problem with drop down menu multiple graphs

### ISSUE THREAD

**Issue by JeromeTeam** [sni/Thruk#994]
My problem is that in the information service view,
when my plugin returns several performance data, for example ram_used and swap_used
I can't get the drop-down menu to be able to access these two graphs in the Performance Graph section.
Thruk will only show me the ram_used graph.
I have however positioned as requested the documentation shown_inline_pnp = 1, perf_bar_pnp_popup = 1, perf_bar_mode = match

In addition I use the default fill in pnp4nagios / templates.dist / default.php.
Do we have to make another configuration in order to see the two graphs?

I use Thruk 2.20-2 
![Thruk](https://user-images.githubusercontent.com/23382494/73542227-83e48080-4434-11ea-85e8-ef455d23d460.png)

Thanks for your help

**Comment by sni** [comment]
Having multiple performance counter does not necessarily mean you have multiple graphs. Can you check a few things:
 - does this work with other services?
 - does this service actually have multiple graphs

**Comment by JeromeTeam** [comment]
Hello sni,
Thank you very much for taking an interest in my problem.
No it does not work on any service. I have nowhere the drop-down menu when I have several graphs
When I connect to pnp4nagios, I see that the service produces two graphs.

**Comment by JeromeTeam** [comment]
Hello sni,
Do you have an idea of the origin of my problem please ?
Thanks

**Comment by sni** [comment]
You could have a look at the developer tools console of your browser. You should see an http request to fetch the list of graphs. The response should contain an array.
