### ISSUE TITLE
REST API filter custom variables from services

### ISSUE THREAD

**Issue by jevvz** [sni/Thruk#995]
This bug is the same as issue 893 (https://github.com/sni/Thruk/issues/893). The last response from issue 893 aint working.

Filtering custom variables with the REST API when you query host is working but when you query services it aint working.

Examples: 

http://127.0.0.1/thruk/r/host?q=(_OFFICE = 0554)  -> Works
http://127.0.0.1/thruk/r/host?_OFFICE=0554 -> Works
http://127.0.0.1/thruk/r/services?q=(_HOSTOFFICE = 0554) -> Doesn't work.
curl -gk 'http://127.0.0.1/thruk/r/services?_OFFICE[gte]=554' -> Doesn't work.
curl -d 'q=***_OFFICE >= 554***' 'http://127.0.0.1/thruk/r/services' -> Doesn't work.

Beside that there something strange when you filter data that works custom variables disappear.

Example:

http://127.0.0.1/thruk/r/services -> shows custom variables like _HOSTOFFICE
http://127.0.0.1/thruk/r/services?description[regex]=(^CPU$|^Disk space$) -> custom variables and host_custom_variables dissapear.

**Comment by sni** [comment]
the host custom variable filter has not been properly converted into a livestatus filter. This is fixed in ba3278480912974c36f7c2c4119864c6392bc7c0.
