### ISSUE TITLE
rest api - acknowledge_svc_problem with special characters

### ISSUE THREAD

**Issue by Kapeluszniik** [sni/Thruk#999]
Trying to execute rest api for ack for service that have "/" in the name:
Endpoint: acknowledge_svc_problem
Host: host1
Service: LINUX--/var/log/messages Errors
Service: LINUX--RAM Used

Doesn't work (in Thruk GUI a not see anything to changes), despite the message is Command successfully submitted
```sh
curl -k -X POST -u user:password -d "comment_data='TEST'&backends=4db88"  -g "https://10.2.10.50/thruk/r/services/host1/LINUX--%252Fvar%252Flog%252Fmessages%2520Errors/cmd/acknowledge_svc_problem"
{
   "commands" : "COMMAND [1582149549] ACKNOWLEDGE_SVC_PROBLEM;host1;LINUX--%2Fvar%2Flog%2Fmessages%20Errors;1;1;1;user;'TEST'",
   "message" : "Command successfully submitted"
}
```

Doesn't work - it ask for backend parameter:
```sh
curl -k -X POST -u user:password -d "comment_data='TEST'"  -g "https://10.2.10.50/thruk/r/services/host1/LINUX--%252Fvar%252Flog%252Fmessages%2520Errors/cmd/acknowledge_svc_problem"
{
   "code" : 400,
   "help" : "Sends the ACKNOWLEDGE_SVC_PROBLEM command.\n\nRequired arguments:\n\n  * comment_data\n\nOptional arguments:\n\n  * sticky_ack\n  * send_notification\n  * persistent_comment\n  * comment_author\n\nSee http://www.naemon.org/documentation/developer/externalcommands/acknowledge_svc_problem.html for details.",
   "message" : "cannot send command, affected backend list is empty."
}
```

Works fine for service that have only space in the name, but not have "/":
```sh
 curl -k -u user:password -d "comment_data='TEST'" https://10.2.10.50/thruk/r/services/host1/LINUX--CPU%20Count/cmd/acknowledge_svc_problem
{
   "commands" : "COMMAND [1582150774] ACKNOWLEDGE_SVC_PROBLEM;host1;LINUX--CPU Count;on;on;off;user;TEST",
   "message" : "Command successfully submitted"
}
```

**Comment by sni** [comment]
You need to url encode the host and service name. `/` must be replace with a `%2F`.

The `affected backend list is empty` does not mean it is asking for a backend, it means the the requested service cannot be found in any connected backend.

**Comment by Kapeluszniik** [comment]
I wish you were right... butI know that I should use %2F and I tested it before open the issue. It doesn't work -  I got that there is no endpoint in REST.
```sh
curl -k -u user:password -d "comment_data=TEST" 'https://10.2.10.50/thruk/r/services/host1/LINUX--%2Fvar%2Flog%2Fmessages%20Errors/cmd/acknowledge_svc_problem'
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /thruk/r/services/host1/LINUX--/var/log/messages Errors/cmd/acknowledge_svc_problem was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at 10.2.10.50 Port 443</address>
</body></html>
```

**Comment by sni** [comment]
This is an apache thing:
http://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes
Apache returns an 404 for every url containing a %2F.

**Comment by sni** [comment]
Anyway, i add a generic `/cmd` endpoint to avoid escaping issues. This endpoint can be used to send host and service name as argument instead of part of the url.

**Comment by Kapeluszniik** [comment]
@sni - thanks a lot for that generic endpoint.
